Azure/azure-cli-extensions

- .travis.yml
- scripts/ci/test_source.sh
> More CI for source tests

- src/index.json
> Update IoT Extension index data for new release.

- src/index.json
> Update IoT Extension v0.3.2

- src/index.json
> IoT Extension with DPS functionality v0.4.0

- src/index.json
> update batch extension hash

- src/eventhubs/azext_eventhub/tests/recordings/test_eh_alias.yaml
- src/eventhubs/azext_eventhub/tests/recordings/test_eh_consumergroup.yaml
- src/eventhubs/azext_eventhub/tests/recordings/test_eh_eventhub.yaml
- src/eventhubs/azext_eventhub/tests/recordings/test_eh_namespace.yaml
- src/eventhubs/azext_eventhub/tests/test_eventhub_commands.py
- src/index.json
> Index.json: updated index.json for Service Bus and Event Hubs extensions

- src/index.json
- [na] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
> update index of aem extension

- src/index.json
> Add subscription extension to index.

- src/aem/setup.py
- src/index.json
- [na] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [na] Have you run `python scripts/ci/test_integration.py -q` locally?
> aem:update index for releasing

- src/index.json
- src/webapp/azext_webapp/create_util.py
- src/webapp/azext_webapp/custom.py
- src/webapp/setup.py
> Sisirap netcore pkg fix

- src/webapp/azext_webapp/create_util.py
* Fixed #72 - Node.js deployments stopped working
* Fixed #73 - Logic for defaulting node version was faulty
* Fixed #70 - Errors when app was empty
> az webapp new - Fix Node.js errors

- src/index.json
> Update webapp hash and version

- src/webapp/setup.py
> updating version on setup

- src/index.json
- src/rdbms/azext_rdbms/_help.py
- src/rdbms/azext_rdbms/_params.py
- src/rdbms/setup.py
> Update MySQL and PostgreSQL help text and sku-name parameter.

- src/aem/azext_aem/__init__.py
---
- [na] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [na] Have you run `python scripts/ci/test_integration.py -q` locally?
> aem: adjust command authoring code per cli core change

- src/aem/setup.py
- src/index.json
---
- [na] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [na] Have you run `python scripts/ci/test_integration.py -q` locally?
> aem: update index

- src/index.json
- src/webapp/azext_webapp/_help.py
- src/webapp/setup.py
> Updating help for az webapp new 

- .github/PULL_REQUEST_TEMPLATE.md
> Change test_integration.py to test_index.py

- src/index.json
> [Subscription RP] Update index.json

- scripts/ci/test_source.sh
- src/aem/azext_aem/custom.py
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure.yaml
- src/dns/azext_dns/tests/latest/recordings/test_dns.yaml
- src/dns/azext_dns/tests/latest/recordings/test_private_dns.yaml
- Fix aem test
Closes https://github.com/Azure/azure-cli-extensions/issues/121
> Fix extension tests

- src/aem/azext_aem/azext_metadata.json
- src/aem/setup.py
- src/index.json
> republish aem due to cli core change

- src/alias/azext_alias/__init__.py
- src/alias/azext_alias/_const.py
- src/alias/azext_alias/_help.py
- src/alias/azext_alias/_validators.py
- src/alias/azext_alias/alias.py
- src/alias/azext_alias/azext_metadata.json
- src/alias/azext_alias/custom.py
- src/alias/azext_alias/hooks.py
- src/alias/azext_alias/telemetry.py
- src/alias/azext_alias/tests/_const.py
- src/alias/azext_alias/tests/test_alias.py
- src/alias/azext_alias/tests/test_alias_commands.py
- src/alias/azext_alias/tests/test_argument.py
- src/alias/azext_alias/tests/test_custom.py
- src/alias/azext_alias/tests/test_util.py
- src/alias/azext_alias/util.py
- src/alias/azext_alias/version.py
- src/index.json
---
Adding @williexu as a reviewer for the interactive portion.
do not merge this PR until azure-cli-2.0.31 is released.
> Tab completion for Alias

- src/alias/azext_alias/_help.py
- src/alias/azext_alias/custom.py
- src/alias/azext_alias/version.py
- src/index.json
> Fix alias default export path

- src/index.json
> adding keyvault-preview extension to index.json

- src/index.json
> updating keyvault-preview version and install location

- src/eventgrid/azext_eventgrid/azext_metadata.json
- src/index.json
---
Added eventgrid preview extension to index.json.
> Added eventgrid preview extension to index.json.

- src/index.json
> updating index with keyvault-preview 0.1.3

- src/index.json
- src/webapp/azext_webapp/custom.py
> Updating #of trials for deployment status before timing out

- src/index.json
> IoT extension release v0.4.4

- src/index.json
> Update new batch cli extension

- src/botservice/azext_bot/custom.py
- src/eventgrid/azext_eventgrid/custom.py
- src/storage-preview/azext_storage_preview/oauth_token_util.py
> Fixes for python 2 env

- src/index.json
>  Updated the whl, filename and the dependency 

- src/index.json
> iotext v0.4.5

- src/dev-spaces-preview/setup.py
- src/index.json
> [Milestone: 5/22] Bumping Dev Spaces version to 0.1.1 and updating the Index

- src/index.json
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_management_policy.yaml
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_storage_blob_incremental_copy.yaml
- src/storage-preview/setup.py
> Management policy recording and new version of wheel

- src/botservice/setup.py
- src/index.json
> update index.json with new botservice package(minor fixes)

- .travis.yml
> extend alotted time for script in travis

- src/storage-preview/README.md
> readme changes

- src/index.json
> Index storage 0.1.3

- scripts/ci/test_index.py
- src/index.json
> Update batch extension to 2.3.0

- .github/PULL_REQUEST_TEMPLATE.md
---
Fixes: https://github.com/Azure/azure-cli-extensions/issues/231
> Fix link for extension summary for PRs

- .travis.yml
> add static check as precheck

- src/index.json
> Update azure batch extension to latest

- src/index.json
---
- [ X] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [ X] Have you run `python scripts/ci/test_index.py -q` locally?
> Update Batch Extension to latest

- src/index.json
> IoT extension release v0.5.1

- scripts/refdoc/conf.py
---
- [ x ] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [ x ] Have you run `python scripts/ci/test_index.py -q` locally?
> fix smartquotes issues

- src/index.json
Follow up to #230. cc/ @karthikananth @gimotwanMSFT
> Publish ExpressRoute Cross Connection extension to Index

- src/index.json
- src/webapp/azext_webapp/create_util.py
- src/webapp/azext_webapp/custom.py
- src/webapp/setup.py
> Updating the default SKU to basic for Linux, Node app & changing to use zipdeployment method from core

- pylintrc
- src/storage-preview/azext_storage_preview/__init__.py
- src/storage-preview/azext_storage_preview/_help.py
- src/storage-preview/azext_storage_preview/_params.py
- src/storage-preview/azext_storage_preview/_validators.py
- src/storage-preview/azext_storage_preview/commands.py
- src/storage-preview/azext_storage_preview/completers.py
- src/storage-preview/azext_storage_preview/operations/account.py
- src/storage-preview/azext_storage_preview/operations/blob.py
- src/storage-preview/azext_storage_preview/operations/file.py
- src/storage-preview/azext_storage_preview/operations/table.py
- src/storage-preview/azext_storage_preview/storage_url_helpers.py
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_create_storage_account.yaml
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_customer_managed_key.yaml
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_show_usage.yaml
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_storage_account_show_exit_codes.yaml
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_storage_blob_upload_midsize_file.yaml
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_storage_blob_upload_small_file.yaml
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_storage_table_main_scenario.yaml
- src/storage-preview/azext_storage_preview/tests/latest/storage_test_util.py
- src/storage-preview/azext_storage_preview/tests/latest/test_storage_account_scenarios.py
- src/storage-preview/azext_storage_preview/tests/latest/test_storage_batch_operations.py
- src/storage-preview/azext_storage_preview/tests/latest/test_storage_blob_live_scenarios.py
- src/storage-preview/azext_storage_preview/tests/latest/test_storage_blob_scenarios.py
- src/storage-preview/azext_storage_preview/tests/latest/test_storage_table_scenarios.py
- src/storage-preview/azext_storage_preview/tests/latest/test_storage_validators.py
> Storage extension updates

- src/storage-preview/azext_storage_preview/oauth_token_util.py
---
MSI token do not undergo the same serialization that adal goes through and will fail in current Oauth implementation.
Raised an issue: https://github.com/Azure/msrestazure-for-python/issues/116 for msrestazure
> [Storage-preview] Address oauth scenario for msi token

- src/index.json
Also as part of this release, most of the superfluous dependencies of the extension are removed (relies on azure CLI core for msrestazure, jmespath and pyyaml).
---
> IoT extension release v0.5.2

- src/index.json
- src/storage-preview/azext_storage_preview/azext_metadata.json
> Set higher min version for storage extension

- scripts/ci/index_changes.py
- scripts/ci/verify_linter.sh
> Add extension using new source instead of currently publicly available one.

- .travis.yml
> move index verification to index

- src/index.json
> Adding SAP Hana extensions to index

- src/storage-preview/azext_storage_preview/__init__.py
- src/storage-preview/azext_storage_preview/_client_factory.py
- src/storage-preview/azext_storage_preview/commands.py
- src/storage-preview/azext_storage_preview/profiles.py
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_create_storage_account_premium_sku.yaml
- src/storage-preview/azext_storage_preview/tests/latest/test_storage_account_scenarios.py
---
Just added testing since new kinds are brought by updated sdk
> [Storage] Premium blobs/files

- scripts/ci/verify_linter.sh
> [automation] skip extension if unable to add

- scripts/ci/index_ref_doc.py
---
-Docs are generated using the latest CLI version. This may cause an extension to not be compatible. 
-Filtering out for now to pass CI
-Will talk to docs team about our plans for these extensions.
> Add filtering for extensions with max version

- src/index.json
> IoT extension release v0.6.0

- src/index.json
> Update to latest batch extension 2.5.0

- src/index.json
- src/storage-preview/README.md
- src/storage-preview/azext_storage_preview/_params.py
- src/storage-preview/setup.py
---
-Contains File-AAD  and Premium Blobs/Files
> [Storage] publish new version for Ignite

- src/azure-firewall/azext_firewall/azext_metadata.json
- src/index.json
- src/virtual-network-tap/azext_vnettap/_params.py
- src/virtual-network-tap/azext_vnettap/azext_metadata.json
> Add VTAP to index

- src/botservice/MANIFEST.in
- src/botservice/azext_bot/_params.py
- src/botservice/azext_bot/commands.py
- src/botservice/azext_bot/custom.py
- src/botservice/azext_bot/webappv4.template.json
- src/botservice/setup.py
- src/index.json
add botbuilder sdk v4 related features (publish, create). Also update index.json
> add botbuilder sdk v4 related features (publish, create). Also update index.json

- src/botservice/azext_bot/commands.py
- src/botservice/azext_bot/custom.py
- src/index.json
removed this method from teh extension so that the command will call the native cli now.
> fix prepare_publish command

- src/index.json
- src/webapp/azext_webapp/__init__.py
- src/webapp/azext_webapp/_help.py
- src/webapp/azext_webapp/azext_metadata.json
- src/webapp/azext_webapp/custom.py
- src/webapp/setup.py
> webapp: Updating to use the latest SDK & adding exception analysis incase of error

- README.md
---
Hopefully this helps developers who have trouble with getting the index verification CI check to pass.
Closes: https://github.com/Azure/azure-cli-extensions/issues/323
> [Documentation] added documentation for extension metadata

- src/index.json
> Update to batch extension 2.5.1

- src/index.json
- src/storage-preview/README.md
- src/storage-preview/azext_storage_preview/__init__.py
- src/storage-preview/setup.py
> Storage doc

- scripts/ci/test_index_ref_doc.sh
> gen refdocs with latest dev

- src/express-route/azext_express_route/_params.py
- src/express-route/azext_express_route/_validators.py
- src/express-route/azext_express_route/custom.py
- src/express-route/setup.py
---
Fixes: https://github.com/Azure/azure-cli-extensions/issues/340
> Express route port bug fix

- src/index.json
> [Express-route] publish new index with bug fix

- src/express-route/setup.py
- src/index.json
> bump version and add to idnex

- src/storage-preview/README.md
> headings for storage extension references in readme

- src/index.json
> [Express-route] add to index

- .travis.yml
> pin flake8 to 3.5.0

- src/interactive/azext_interactive/__init__.py
> [Interactive] removed command from being registered in command table

- src/index.json
---
Has recent changes to decouple itself from interactive.
> [Alias] release alias

- src/alias/azext_alias/azext_metadata.json
- src/index.json
- src/interactive/azext_interactive/azext_metadata.json
> [Alias Interactive] set min cli version to dev to allow cli ci to pass

- src/index.json
> [Alias, Interactive] update extensions for CLI namespace

- src/eventgrid/azext_eventgrid/_help.py
- src/eventgrid/azext_eventgrid/_params.py
- src/eventgrid/azext_eventgrid/custom.py
- src/index.json
---
EventGrid: Updated index.json to reflect latest version.
> EventGrid: Update index.json to reflect latest version.

- src/index.json
- src/webapp/azext_webapp/create_util.py
- src/webapp/setup.py
> Webapp: Make Python detection higher pri over static html

- src/index.json
---
- release 0.1.7, which will use 2018-07-01 for all mgmt-plane calls.
> [Storage] update index

- src/aks-preview/setup.py
- src/index.json
> add aks-preview to index

- src/index.json
- src/webapp/azext_webapp/__init__.py
- src/webapp/azext_webapp/_constants.py
- src/webapp/azext_webapp/custom.py
- src/webapp/setup.py
> fixing an issue where az webapp up is not honoring the location attribute anymore

- src/find/azext_find/__init__.py
- src/find/azext_find/custom.py
- src/find/setup.py
- src/index.json
---
-Reflects https://github.com/Azure/azure-cli-extensions/pull/373
-Cleaned up commits
> [Find] New help and feedback mechanism added.

- scripts/ci/update_index.py
- scripts/update_index.py
- src/azure-firewall/azext_firewall/_validators.py
- src/azure-firewall/setup.py
- src/index.json
Fixes #367.
Also, adds a simple script for updating the index.
`python scripts/ci/update_index.py <URL to extension WHL>` cc/ @yugangw-msft 
---
> Azure Firewall --protocol fix and Index Update script

- src/index.json
- src/webapp/azext_webapp/custom.py
- src/webapp/setup.py
check app service is linux when making a remote connections
fixes https://github.com/Azure/azure-cli-extensions/issues/365
---
> check windows app service for remote connections

- src/index.json
- src/webapp/azext_webapp/__init__.py
- src/webapp/azext_webapp/create_util.py
- src/webapp/azext_webapp/custom.py
- src/webapp/setup.py
> webapp: Adding sku option to az webapp up

- src/index.json
> Iotext new release v0.6.1

- src/dms-preview/azext_dms/_help.py
- src/index.json
> Updating index.json to include new version of dms extension

- src/botservice/azext_bot/azext_metadata.json
- src/index.json
Adds entry to index.json for botservice's latest release.
---
> azext_botservice: update index.json with 0.4.2 botservice entry

- scripts/ci/index_ref_doc.py
> Unsuppress index ref doc ci for botservice

- .github/CODEOWNERS
> add codeowner for mesh

- src/botservice/HISTORY.rst
- src/botservice/azext_bot/custom.py
- src/botservice/setup.py
- src/index.json
> azext_botservice 0.4.3 release

- src/index.json
- src/storage-preview/HISTORY.rst
> [Storage-preview] Release failover

- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_management_policy.yaml
> [Storage] fixed recording for mgmt-policy

- src/index.json
> [botservice] re-add botservice

- src/storage-preview/HISTORY.rst
- src/storage-preview/azext_storage_preview/operations/blob.py
---
Fixes: https://github.com/Azure/azure-cli-extensions/issues/438
> [Storage] raise error for non-storagev2 accounts

- src/index.json
- src/storage-preview/HISTORY.rst
> [Storage] release new extension version

- src/index.json
Non-code change, only updating of index.json.
Fixes: Microsoft/botbuilder-tools#896
---
> botservice: update index.json to new hosting location

- src/index.json
- src/storage-preview/HISTORY.rst
- src/storage-preview/azext_storage_preview/azext_metadata.json
- src/storage-preview/setup.py
> [Storage] update min cli version for storage and release

- src/index.json
- src/rdbms-up/setup.py
> [Rdbms-Up] release rdbms-up

- src/index.json
> new release for azure devops extension

- src/db-up/README.md
> Update Readme.md for MySQL up

- src/db-up/azext_db_up/_transformers.py
- src/db-up/azext_db_up/custom.py
- src/db-up/azext_db_up/mysql_util.py
> [db-up] out hostname/pw/user and small fixes to connection strings

- src/db-up/HISTORY.rst
- src/db-up/setup.py
- src/index.json
> [db-up] bump version, history, and release

- src/db-up/azext_db_up/_validators.py
- src/db-up/azext_db_up/custom.py
- src/db-up/setup.py
- src/index.json
> [db-up] Edits in output and release

- src/db-up/HISTORY.rst
- src/db-up/README.md
- src/db-up/azext_db_up/custom.py
- src/db-up/setup.py
- src/index.json
> [db-up] Release postgres and down commands

- src/index.json
> HanaOnAzure release 0.3.3: update restart command to be asynchronous

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/custom.py
- src/db-up/setup.py
- src/index.json
> [db-up] changes to output and release

- src/index.json
> Update Index file for latest batch extension

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/setup.py
> [AKS]: add network policy support

- src/index.json
> [AKS]: add new version 0.2.2 for aks-preview

- src/storage-preview/README.md
> pstorage] updated readme for failover release

- src/db-up/README.md
> small change

- scripts/ci/verify_modified_index.sh
> remove dep on edge build and build from source code

- src/db-up/HISTORY.rst
- src/db-up/README.md
- src/db-up/azext_db_up/_params.py
- src/db-up/azext_db_up/custom.py
- src/db-up/setup.py
- src/index.json
> [db-up] Release db up with show-connection-string commands

- src/index.json
> Update sap-hana version, add hwRevision field to HANA instance model

- azure-cli-extensions.pyproj
- scripts/run_az.py
Adds a startup file to permit debugging from the extensions solution file in Visual Studio.
---
- [N/A] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).
> Permit debugging from Visual Studio

- src/db-up/HISTORY.rst
- src/db-up/setup.py
- src/index.json
> [db-up] Release

- src/mesh/azext_mesh/_help.py
Adding parameters help text for mesh generate armtemplate.
---
> Update _help.py for mesh extension 

- src/index.json
Fix bug introduced in v2.5 of Batch Extension which disabled core CLI functionality for extended cmdlets.
'az batch pool create' and 'az batch job create'
---
> Batch bug fix

- src/index.json
[Mixed Reality Azure CLI Extension](https://test.pypi.org/project/mixed-reality/)
---
> Add mixed-reality extension to index

- src/index.json
---
- [Yes ] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [ Yes] Have you run `python scripts/ci/test_index.py -q` locally?
> Update index for front-door

- src/index.json
> Iotext release v0.7.0

- src/index.json
> updated mesh

- src/aks-preview/azext_aks_preview/custom.py
Add a special character to service principal secret to satisfy aad requirements
---
> Update service principal secret to include special character

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/_help.py
- src/db-up/azext_db_up/commands.py
- src/db-up/azext_db_up/custom.py
- src/db-up/setup.py
- src/index.json
---
Removing sql commands and pyodbc dependency because the other components and source file are needed for linux.
> [db-up] Revert sql and release db-up with mysql and postgres updates

- src/db-up/HISTORY.rst
- src/index.json
> [db-up] release postgres fix

- src/storage-preview/azext_storage_preview/_help.py
> [Storage] Remove min_profile and max_profile in the example

- src/index.json
- src/storage-preview/HISTORY.rst
- src/storage-preview/README.md
- src/storage-preview/azext_storage_preview/_help.py
- src/storage-preview/azext_storage_preview/_params.py
- src/storage-preview/setup.py
> [storage-preview] Release azcopy

- src/db-up/azext_db_up/_client_factory.py
- src/db-up/azext_db_up/_help.py
- src/db-up/azext_db_up/_validators.py
- src/db-up/azext_db_up/commands.py
- src/db-up/azext_db_up/custom.py
- src/db-up/azext_db_up/tests/latest/recordings/test_mysql_flow.yaml
- src/db-up/azext_db_up/tests/latest/recordings/test_sql_flow.yaml
- src/db-up/azext_db_up/tests/latest/test_db_up_scenarios.py
> [db-up] Sql commands- up/down/show-connection-string

- src/db-up/HISTORY.rst
- src/db-up/README.md
- src/db-up/setup.py
- src/index.json
> [db-up] publish index, docs, history

- src/index.json
---
- [ Yes] Have you run `./scripts/ci/test_static.sh` locally? (`pip install pylint flake8` required)
- [Yes ] Have you run `python scripts/ci/test_index.py -q` locally?
> Update index for front_door

- .github/CODEOWNERS
> Add alias to dev spaces extension

- src/index.json
> 0.4.0 release for Azure DevOps

- src/express-route-cross-connection/azext_expressroutecrossconnection/_help.py
- src/express-route-cross-connection/setup.py
> Remove unnecessary kwarg from ER Cross-Connection extension.

- src/express-route-cross-connection/azext_expressroutecrossconnection/_help.py
- src/express-route-cross-connection/azext_expressroutecrossconnection/_params.py
- src/express-route-cross-connection/setup.py
- src/index.json
> Update index for ER Cross Connection

- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
> fixing az support for agent pools and mc

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/index.json
> update the index file to publish latest aks-preview

- src/front-door/setup.py
> Update version for front-door

- src/front-door/setup.py
- src/index.json
> Update front door index to 0.1.5

- src/index.json
Publish interactive 0.4.2 (compatible with azure CLI 2.0.62 and higher)
---
> Publish interactive 0.4.2

- src/aks-preview/setup.py
- src/index.json
---
This PR adds new aks-preview version in index.json
> Add new version of aks-preview in index.json

- src/index.json
- src/storage-preview/setup.py
> [storage-preview] pulish 0.2.4

- src/index.json
> 0.5.0 release for Azure DevOps

- src/index.json
---
- [ X ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ X ] Have you run `python scripts/ci/test_index.py -q` locally?
- [ X ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).
> onboard Azure Machine Learning Service CLI"

- src/index.json
> [storage-preview] publish 0.2.5

- src/index.json
> 0.6.0 release for Azure DevOps

- src/index.json
> Upgrade AppConfig extension version from 0.4.0 to 0.5.0

- src/aks-preview/azext_aks_preview/custom.py
> Update service principal secret for windows nodes

- src/storage-preview/HISTORY.rst
- src/storage-preview/setup.py
> Release storage-preview 0.2.5

- src/index.json
> 0.7.0 release for Azure DevOps

- src/index.json
> Azure-devops Cli release 0.8.0

- src/interactive/HISTORY.rst
- src/interactive/azext_interactive/azclishell/__init__.py
- src/interactive/azext_interactive/azclishell/app.py
> Fix issue 677: config problem in interactive

- src/index.json
- src/interactive/azext_interactive/azclishell/app.py
> [interactive] Publish interactive 0.4.3

- src/db-up/azext_db_up/custom.py
> Fixed typo on name of SQL server

- src/aks-preview/azext_aks_preview/commands.py
- src/aks-preview/azext_aks_preview/custom.py
---
- [x ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x ] Have you run `python scripts/ci/test_index.py -q` locally?
> Enable/Disable kube-dashboard addon

- src/index.json
> Update index.json for batch extension

- src/eventgrid/azext_eventgrid/azext_metadata.json
- src/eventgrid/setup.py
> [eventgrid] Set the max CLI core version as 2.0.66

- src/dev-spaces/azext_dev_spaces/azext_metadata.json
- src/dev-spaces/setup.py
> [dev-spaces] Set the max CLI core version as 2.0.66

- src/index.json
---
- [ x ] Have you run `python scripts/ci/test_index.py -q` locally?
> update to azure-cli-ml version 1.0.41

- src/front-door/azext_front_door/azext_metadata.json
- src/front-door/setup.py
> [front-door] Set the max CLI core version as 2.0.66

- src/index.json
> Updated hanainstance extension version to include new SKU

- src/index.json
> 0.9.0 release for DevOps Extension

- src/index.json
---
- [Yes ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ Yes] Have you run `python scripts/ci/test_index.py -q` locally?
> Update index for new version of front-door(with max cli core version

- src/netappfiles-preview/azext_netappfiles_preview/azext_metadata.json
- src/netappfiles-preview/setup.py
> [netappfiles] Set the max CLI core version as 2.0.66

- src/signalr/azext_signalr/azext_metadata.json
- src/signalr/setup.py
> [signalr] Set the max CLI core version as 2.0.66

- .github/CODEOWNERS
> Remove botservice from codeowners

- .flake8
- azure-cli-extensions.pyproj
> [botservice] Remove the code of botservice

- src/rdbms_vnet/azext_rdbms_vnet/azext_metadata.json
- src/rdbms_vnet/setup.py
> [rdbms-vnet] Set the max CLI core version as 2.0.66

- src/resource-graph/azext_resourcegraph/azext_metadata.json
- src/resource-graph/setup.py
> [resource-graph] Set the max CLI core version as 2.0.66

- src/index.json
EventGrid: Update the index.json file with the version 0.4.2 to accomodate maxCliCoreVersion 2.0.66 change
---
- [] Have you run `python scripts/ci/test_index.py -q` locally?
> EventGrid: Update the index.json file with the version 0.4.2 to accomodate maxCliCoreVersion 2.0.66 change

- src/index.json
---
- [ X ] Have you run `python scripts/ci/test_index.py -q` locally?
> update AzureML CLI to version 1.0.41.1

- src/index.json
> Updating index.json

- src/db-up/azext_db_up/_validators.py
- src/db-up/azext_db_up/azext_metadata.json
- src/db-up/azext_db_up/util.py
- src/db-up/setup.py
- src/index.json
> [db-up] Set the max CLI core version as 2.0.66

- src/index.json
- src/resource-graph/setup.py
> Update version resource-graph

- src/index.json
> update AzureML CLI version to 1.0.43

- src/index.json
> Publish webapp 0.2.18

- src/index.json
> Remove netappfiles-preview extension form index.json

- src/index.json
- src/subscription/azext_subscription/__init__.py
> Publish subscription 0.1.2

- src/index.json
This reverts commit 43ed33d13552edc7d6b41ee141d9fd361234c28b.
---
> Add azure-cli-iot-ext to index.json

- src/aks-preview/azext_aks_preview/custom.py
Remove the print command used for debugging
Fixed the description sentence 
---
> minor bug fix

- azure-cli-extensions.pyproj
- src/aks-preview/azext_aks_preview/__init__.py
- src/aks-preview/azext_aks_preview/azext_metadata.json
- src/db-up/azext_db_up/__init__.py
- src/db-up/azext_db_up/azext_metadata.json
- src/dev-spaces/azext_dev_spaces/__init__.py
- src/dev-spaces/azext_dev_spaces/azext_metadata.json
- src/dms-preview/azext_dms/__init__.py
- src/dms-preview/azext_dms/azext_metadata.json
- src/eventgrid/azext_eventgrid/__init__.py
- src/eventgrid/azext_eventgrid/azext_metadata.json
- src/front-door/azext_front_door/__init__.py
- src/front-door/azext_front_door/azext_metadata.json
- src/mesh/azext_mesh/__init__.py
- src/mesh/azext_mesh/azext_metadata.json
- src/netappfiles-preview/azext_netappfiles_preview/__init__.py
- src/netappfiles-preview/azext_netappfiles_preview/azext_metadata.json
- src/resource-graph/azext_resourcegraph/__init__.py
- src/resource-graph/azext_resourcegraph/azext_metadata.json
- src/storage-preview/azext_storage_preview/__init__.py
- src/storage-preview/azext_storage_preview/azext_metadata.json
- src/subscription/azext_subscription/azext_metadata.json
- src/webapp/azext_webapp/__init__.py
- src/webapp/azext_webapp/azext_metadata.json
> Remove min_profile

- src/front-door/setup.py
- src/index.json
---
- [ Yes] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [Yes ] Have you run `python scripts/ci/test_index.py -q` locally?
> Update index removing the max cli version

- src/index.json
> Releasing CLI extension version 0.4.1

- src/index.json
> Update index.json with Azure Devops CLI extension version 0.11.0

- src/eventgrid/setup.py
- src/index.json
EventGrid CLI extension: Updating to 0.4.3 version to account for min_profile change.
---
> EventGrid CLI extension: Updating to 0.4.3 version to account for min_profile change.

- src/index.json
- src/netappfiles-preview/azext_netappfiles_preview/__init__.py
- src/netappfiles-preview/azext_netappfiles_preview/azext_metadata.json
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_create_delete_account.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_create_delete_pool.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_create_delete_snapshots.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_create_delete_volumes.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_get_account_by_name_ext.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_get_pool_by_name.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_get_snapshot.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_get_volume_by_name.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_accounts_ext.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_mount_targets.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_pools.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_snapshots.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_volumes.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_set_account_ext.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_update_account_ext.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_update_pool.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_update_volume.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/test_snapshot_commands_ext.py
- src/netappfiles-preview/setup.py
And fix merge issues from previous (closed) PR
https://github.com/Azure/azure-cli-extensions/pull/742/
---
> NFSAAS-2316 Update to R4 RP standard (#49)

- src/aks-preview/azext_aks_preview/custom.py
> fixing network plugin parameter missing error when setting standard load balancer

- src/aks-preview/setup.py
- src/index.json
> publish aks-preview extension 0.4.5

- src/index.json
- src/netappfiles-preview/HISTORY.rst
- src/netappfiles-preview/azext_netappfiles_preview/__init__.py
- src/netappfiles-preview/azext_netappfiles_preview/azext_metadata.json
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_create_delete_account.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_create_delete_pool.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_create_delete_snapshots.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_create_delete_volumes.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_get_account_by_name_ext.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_get_pool_by_name.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_get_snapshot.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_get_volume_by_name.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_accounts_ext.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_mount_targets.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_pools.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_snapshots.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_list_volumes.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_set_account_ext.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_update_account_ext.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_update_pool.yaml
- src/netappfiles-preview/azext_netappfiles_preview/tests/latest/recordings/test_ext_update_volume.yaml
- src/netappfiles-preview/setup.py
> NFSAAS-2316 update versions (#52)

- src/index.json
- src/mesh/HISTORY.rst
- src/mesh/azext_mesh/azext_metadata.json
- src/mesh/setup.py
> mesh update for cli core version 2.0.67

- src/index.json
- src/vm-repair/azext_vm_repair/_help.py
- src/vm-repair/azext_vm_repair/_validators.py
- src/vm-repair/azext_vm_repair/custom.py
- src/vm-repair/setup.py
*New PR due to incorrect branching resulting in conflicting commit history
Minor changes for 0.1.1
1. Region bug fix where 'repair create' failed when the resource group region and disk region was different.
2. Typo fixes
> vm-repair extension: Region copy fix

- src/front-door/setup.py
- src/index.json
---
- [Yes ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [Yes] Have you run `python scripts/ci/test_index.py -q` locally?
> Update index - Enable caching parameter when creating a routing rule

- src/index.json
> update AzureML CLI version to 1.0.45.1

- .travis.yml
- azure-pipelines.yml
Converts the key jobs in the old TravisCI file to use ADO.
TODO:
> Convert Travis pipeline to ADO

- src/index.json
> Updated SAP HANA extension to include new SAP Monitor resource type

- src/index.json
> update azure-cli-ml version to 1.0.48

- src/index.json
> Update hanaInstances CLI Extension

- src/front-door/azext_front_door/custom.py
---
- [Yes ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ Yes] Have you run `python scripts/ci/test_index.py -q` locally?
> Making 'FrontDoor' Default for certificate source

- src/index.json
- src/webapp/azext_webapp/__init__.py
- src/webapp/azext_webapp/_help.py
- src/webapp/azext_webapp/acr_util.py
- src/webapp/azext_webapp/custom.py
- src/webapp/setup.py
> webapp: az webapp container up release as preview on extensions

- src/index.json
> Onboard AzML CLI version 1.0.53.1

- src/resource-graph/azext_resourcegraph/custom.py
> Resource Graph:  show warning when too many subscriptions

- .github/CODEOWNERS
> add aks code owners

- src/aks-preview/azext_aks_preview/_help.py
Fixes https://github.com/Azure/azure-cli/issues/9746
> Fix a help message.

- src/index.json
> New release azure-devops extension version 0.12.0

- src/index.json
> update azure-cli-ml to version 1.0.55

- src/index.json
> Updated Hana CLI Extension

- src/index.json
> Updating the index to reflect the correct build

- src/index.json
> IoT Extension v0.8.0 (Plug & Play public preview)

- src/index.json
---
Update index for  aks-preview 0.4.8
/assign @zikalino
> Update index for aks-preview 0.4.8

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/setup.py
- src/index.json
> Support https port

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
> AKS: add support for 'az aks update --disable-acr --acr <name-or-id>'

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
- src/index.json
> Update index for aks-preview 0.4.10

- src/index.json
> update azure-cli-ml to version 1.0.57

- .github/CODEOWNERS
> refine github code owners

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/setup.py
- src/index.json
> [AKS] Add "--enable-private-cluster" flag for enabling private cluster on creation

- src/index.json
> update azure-cli-ml version to 1.0.60.1

- src/aks-preview/azext_aks_preview/custom.py
> Default AKS CLI extension to SLB+VMSS when possible

- src/index.json
> Updating index for sap-hana CLI extension

- src/index.json
> Update IoT extension to v0.8.1

- src/index.json
> Update AzML CLI to version 1.0.62

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
- src/index.json
> Publish AKS CLI extension 0.4.15

- src/index.json
> iot extension release v0.8.2

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/setup.py
- src/index.json
1. Support namespace delete in `aks kollect` command
2. publish 0.4.16 version
---
> support clean up in az aks kollect command and publish 0.4.16

- src/healthcareapis/HISTORY.rst
- src/healthcareapis/azext_healthcareapis/_help.py
- src/healthcareapis/azext_healthcareapis/custom.py
- src/healthcareapis/setup.py
- src/index.json
New code generated
- fixed examples
- fixed bugs
> Healthcareapis upgrade

- src/index.json
- src/vm-repair/azext_vm_repair/custom.py
- src/vm-repair/azext_vm_repair/repair_utils.py
- src/vm-repair/setup.py
2 small bug fixes.
1) Fix bug where disk_sku is None and returns error when source vm is deallocated
2) Hide vm-user-name for telemetry
* Clear for merge whenever reviews are done.
> vm-repair: fix small bugs

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/custom.py
Adding support for low-pri node pools.
Adding support for initial node taints.
Adding support for node public IP (using the same public-ip-per-vm parameter name as az vmss create)
---
> Add support for low-pri scale sets and node taints

- src/index.json
> Update AzML CLI version to 1.0.65

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
- src/index.json
> publish latest aks-preview extension 0.4.17

- src/index.json
> Release new version 0.13.0 for Azure DevOps Extension

- src/index.json
> iot extension increment to v0.8.3

- src/index.json
> Update AzureML CLI version to 1.0.69

- src/healthcareapis/HISTORY.rst
- src/healthcareapis/azext_healthcareapis/azext_metadata.json
- src/healthcareapis/azext_healthcareapis/vendored_sdks/healthcareapis/_healthcare_apis_management_client.py
- src/healthcareapis/azext_healthcareapis/vendored_sdks/healthcareapis/models/_models.py
- src/healthcareapis/azext_healthcareapis/vendored_sdks/healthcareapis/models/_models_py3.py
- src/healthcareapis/azext_healthcareapis/vendored_sdks/healthcareapis/operations/_operation_results_operations.py
- src/healthcareapis/azext_healthcareapis/vendored_sdks/healthcareapis/operations/_operations.py
- src/healthcareapis/azext_healthcareapis/vendored_sdks/healthcareapis/operations/_services_operations.py
- src/healthcareapis/setup.py
- src/index.json
> Upgrade healthcare SDK and remove preview flag

- src/index.json
> Adding vmware-cs extension to index

- src/index.json
> Release v0.8.4 for IoT extension

- src/index.json
> IoT extension release v0.8.5

- src/index.json
- src/spring-cloud/azext_spring_cloud/_help.py
> update index for spring-cloud

- src/connectedmachine/setup.py
- src/index.json
> adding connectedmachine to index

- src/azure-firewall/setup.py
- src/index.json
> [Network] azure-firewall: Update index

- src/index.json
- src/spring-cloud/azext_spring_cloud/_transformers.py
- src/spring-cloud/azext_spring_cloud/commands.py
- src/spring-cloud/azext_spring_cloud/custom.py
> Spring cloud bug fix

- src/index.json
> upgrade AzureML CLI to 1.0.72

- src/index.json
> Updated index of vmware-cs extension

- src/index.json
> upgrade azure-cli-ml to 1.0.72.1

- src/index.json
> new iteration of spring-cloud extension release

- src/index.json
> IoT extension release v0.8.6

- src/storage-preview/README.md
> [storage-preview] Update README

- src/index.json
> upgrade azure-cli-ml to 1.0.74

- src/index.json
> Release new version for azure-devops 0.15.0

- src/storage-preview/README.md
> [Storage-preview] Fix missing words in README

- src/index.json
- src/virtual-wan/azext_vwan/_params.py
- src/virtual-wan/azext_vwan/azext_metadata.json
- src/virtual-wan/azext_vwan/commands.py
- src/virtual-wan/azext_vwan/custom.py
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vhub_basic_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vwan_vhub_commands.py
- src/virtual-wan/setup.py
> [Network]support sku and type for vhub and vwan respectively

- src/index.json
Update extension version with few new EventGrid features introduced in the new preview API version 2020-01-01-preview:
1). Azure Functions as destination
2). ServiceBus topic as destination.
3). CloudEvents v1.0 support
4). Batching parameters during event subscription creation.
---
> Update extension version with few new EventGrid features introduced in the new preview API version 2020-01-01-preview

- src/storage-preview/README.md
> [storage-preview] Add feedback link in README

- src/hack/HISTORY.rst
- src/hack/README.rst
- src/hack/azext_hack/__init__.py
- src/hack/azext_hack/_database_utils.py
- src/hack/azext_hack/_help.py
- src/hack/azext_hack/_website_utils.py
- src/hack/azext_hack/commands.py
- src/hack/azext_hack/custom.py
- Fixed issues with Node and SQL
- Added command to display current settings
- Made database optional
---
> az hack patches and updates

- src/index.json
> upgrade azure-cli-ml to 1.0.76

- src/index.json
> [Storage-preview] update index

- src/index.json
> Release new version for azure-devops 0.16.0

- src/index.json
> Hotfix bug by publishing another ip-group wheel file for test

- src/dev-spaces/azext_dev_spaces/__init__.py
- src/dev-spaces/setup.py
- src/index.json
Extension code was updated in commit 71658b307d89dfc4aac25e175bab9a58f2fb192c.  We have now published a new .whl file and this change starts referencing it in index.json.
> Posting extension update for dev-spaces

- src/index.json
> update azure-cli-ml to version 1.0.79

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/_validators.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
- src/azure-firewall/setup.py
- src/index.json
> [Network]support multiple ip config

- src/index.json
> Update IoT Extension to v0.8.7

- src/index.json
> upgrade azure-cli-ml to 1.0.81

- src/index.json
> update azure-cli-ml version to 1.0.83

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_help.py
- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/_validators.py
- src/azure-firewall/azext_firewall/commands.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_threat_intel_whitelist.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
- src/azure-firewall/setup.py
- src/index.json
> [Network][Feature]az network firewall create: support threat intel whitelist and private ranges

- pylintrc
> [CI]diable import checks for azure_devtools in pylint

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/setup.py
- src/index.json
---
This PR fixed following aks cluster creationg error:
```
az aks create -g $RG -n $XXX --node-count 1 --generate-ssh-keys
fails with error:
Property id '' at path 'properties.diskEncryptionSetID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
```
> fix: aks cluster creation error

- scripts/ci/test_source.py
> Test to fix CI job

- scripts/ci/test_source.py
> Hotfix ci test source src

- azure-pipelines.yml
> Release pipeline test

- src/application-insights/HISTORY.rst
- src/application-insights/azext_applicationinsights/_client_factory.py
- src/application-insights/setup.py
- src/index.json
> [Monitor][Fix] support app insights in china cloud

- src/hack/HISTORY.rst
- src/hack/azext_hack/_database_utils.py
- src/hack/azext_hack/_website_utils.py
- src/hack/setup.py
- src/index.json
- Fixed small issue with name display for publishing profiles
- Updated code to reflect updates to CosmosDB client
---
> Updates for hack extension

- src/index.json
> Release New Version for azure-devops 0.17.0

- src/image-copy/setup.py
- src/index.json
Includes the fix provided by @qwordy for creating disk snapshots
---
> [image-copy] release version 0.2.3

- src/index.json
> IoT extension release v0.8.8

- src/index.json
> update azure-cli-ml to 1.0.85

- src/index.json
> [Support] Release 0.1.0

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/_validators.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/__init__.py
- src/azure-firewall/azext_firewall/tests/latest/__init__.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_rules.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_virtual_hub.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
- src/azure-firewall/setup.py
- src/index.json
> [Network] firewall with firewall policy

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/setup.py
- src/index.json
> [AKS] add nodepool tag for cli extension

- src/azure-firewall/azext_firewall/_help.py
- src/index.json
> [Network]Update index and release azure firewall 0.3.0

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
- src/index.json
> [AKS] Release for spot and autoscaler profile

- scripts/ci/util.py
- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/setup.py
- src/index.json
Fixed issue https://github.com/Azure/azure-cli/issues/12304
---
> fix bug aks-preview to use float(nan)

- src/index.json
> Update Batch Manifest

- src/index.json
> update AzureML CLI to version 1.1.5

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
- src/index.json
> [AKS] publish uptime-sla

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> [AKS] Publish aks-preview extension.

- src/aks-preview/setup.py
---
This PR https://github.com/Azure/azure-cli-extensions/pull/1417 lost the version update when rebasing on  https://github.com/Azure/azure-cli-extensions/commit/9090ef23485be58233e87dde6ab082c184a00d69
> Update version for aks-preview

- src/aks-preview/setup.cfg
- src/aks-preview/setup.py
> [aks-preview] update setup.py and setup.cfg

- scripts/ci/test_index.py
> [CI] remove limit on wheel name

- src/front-door/azext_front_door/custom.py
- src/front-door/setup.py
> {Network}fix negative index

- src/aks-preview/setup.py
> public aks-preview 0.4.39

- src/front-door/azext_front_door/_params.py
- src/front-door/setup.py
> {Monitor}fix help message

- src/aks-preview/setup.py
> publish aks-preview 0.4.40

- src/aks-preview/azext_aks_preview/_validators.py
> [AKS] use latest api version for autoscaler profile validator

- src/aks-preview/azext_aks_preview/_validators.py
Reverts Azure/azure-cli-extensions#1470
> revert: use latest API for autoscaler validator

- src/aks-preview/setup.py
> aks-preview extension 0.4.41

- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_03_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_03_01/models/_models_py3.py
---
This partially reverts the changes with: https://github.com/Azure/azure-cli-extensions/pull/1430. Adding this field causes some marshaling errors which blocks AKS update/upgrade commands.
> [AKS] partial revert #9f31dd8: vendored sdk

- src/aks-preview/setup.py
> [AKS] Bump aks-preview version

- src/index.json
> Updating the Azure DevOps Extension Version to v0.18.0

- src/databricks/azext_databricks/azext_metadata.json
- src/databricks/azext_databricks/commands.py
- src/databricks/setup.cfg
- src/databricks/setup.py
> [Databricks] Use Experimental Tag

- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_03_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_03_01/models/_models_py3.py
---
updates vendored SDK to 9.0.1 to pickup a bug fix in 202003 API specs
> [AKS] update aks vendored sdk to 9.0.1

- src/index.json
> Update azure-cli-ml version to 1.3.0

- src/image-copy/azext_imagecopy/_help.py
- src/image-copy/azext_imagecopy/cli_utils.py
https://github.com/Azure/azure-cli-extensions/issues/1254
Add "Keep in mind that it requires the source disk to be available."
Long summary is not shown in HTML doc. And Doc team is not willing to fix it.
> This logic did not change for quite a long time, which was designed to hide long summary long time ago(2 years ago) as many long summary was empty or duplicate as short summary at that time.
---
The precondition is to put your code inside this repo and upgrade the version in the PR …
> {image-copy} Update help

- src/index.json
> Updated HanaOnAzure CLI extension to include SapMonitor multi-instance multi-provider feature

- src/index.json
Service is not public right now.
---
> [Monitor] downgrade the version since the service is not ready

- src/portal/azext_portal/generated/commands.py
- src/portal/azext_portal/tests/latest/dashboard.json
- src/portal/azext_portal/tests/latest/recordings/test_portal.yaml
> [Portal] Fix a small error in commands.py and update test sample file

- src/application-insights/azext_applicationinsights/_client_factory.py
- src/application-insights/azext_applicationinsights/custom.py
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_api_key.yaml
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component.yaml
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_storage.yaml
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_workspace.yaml
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_public_network_access.yaml
- src/application-insights/azext_applicationinsights/tests/latest/test_applicationinsights_mgmt.py
> {Monitor} refactor the logic

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/custom.py
---
Unblock updating minCount in both `aks update` and `aks nodepool update` when minCount < actual node count < max Count.
With this, `minCount` can be greater than the actual node count. Later scale operations equal to or greater than minCount, will respect that minCount in operations.
> [AKS] Unblock agentpool min count range check

- src/index.json
> IoT CLI extension release v0.9.2

- src/storage-ors-preview/setup.py
> [storage-ors-preview] fix storage-ors-preview no azext metadata

- src/aks-preview/azext_aks_preview/_help.py
> update help context of "--uptime-sla"

- azure-pipelines.yml
The same as https://github.com/Azure/azure-cli/pull/13388
---
> [CI] Temporary disable CredScan since ADO bug

- src/resource-graph/README.md
Fixing the minor issue reported in #1663.
> [resource-graph] Fix extension name in readme

- src/index.json
See https://github.com/virtustream/azure-vmware-virtustream-cli-extension/releases/tag/0.6.0
---
> bump vmware to 0.6.0

- src/index.json
The repository has moved to https://github.com/Azure/az-csvmware-cli . 
---
> download from az-csvmware-cli

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_consts.py
- src/aks-preview/azext_aks_preview/_helpers.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/test_helpers.py
> Fix issues for az aks kollect on private clusters

- src/aks-preview/azext_aks_preview/custom.py
Change the defaul vm sku to Standard_D2s_v3 for better disk performance
---
> change default vm sku to Standard_D2s_v3

- src/timeseriesinsights/setup.py
> [TimeSeriesInsights] Release #1720

- src/front-door/azext_front_door/_params.py
- src/front-door/azext_front_door/custom.py
- src/front-door/azext_front_door/tests/latest/recordings/test_route_rule_basic.yaml
- src/front-door/azext_front_door/tests/latest/recordings/test_rules_engine_basic.yaml
- src/front-door/azext_front_door/tests/latest/test_route_rule_scenarios.py
- src/front-door/azext_front_door/tests/latest/test_rules_engine_scenarios.py
- src/front-door/setup.py
* Cache duration and query parameters options enabled
* rules-engine conditions can be empty, match values can be empty for 'Any' operator
* routing-rule update can enable Caching
* updated help text
---
> Frontdoor rules-engine and routing-rule bug fixes

- src/index.json
> Updated HanaOnAzure CLI extension

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/setup.py
> AKS support node image upgrade feature

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/_params.py
- src/db-up/azext_db_up/_validators.py
- src/db-up/azext_db_up/tests/latest/recordings/test_mysql_flow.yaml
- src/db-up/azext_db_up/tests/latest/recordings/test_postgres_flow.yaml
- src/db-up/azext_db_up/tests/latest/recordings/test_postgres_up.yaml
- src/db-up/azext_db_up/tests/latest/recordings/test_sql_flow.yaml
- src/db-up/azext_db_up/tests/latest/test_db_up_scenarios.py
- src/db-up/azext_db_up/util.py
- src/db-up/setup.py
---
Fix https://github.com/Azure/azure-cli/issues/11633 , https://github.com/Azure/azure-cli/issues/11635, https://github.com/Azure/azure-cli/issues/12340
The PR will change the behavior for some commands:
1. ssl_enforcement will be enabled by default
2. When resource group name in namespace is different from what in cache, reset it and create new server name
3. Bump psycopg2 in MacOS, refering https://github.com/Azure/azure-cli-extensions/pull/1675/files
The precondition is to put your …
> [db-up] Fix bug for server name and enable ssl enforecement

- src/ai-did-you-mean-this/azext_ai_did_you_mean_this/tests/latest/aladdin_scenario_test_base.py
> {CI} reimport mock in unit test

- src/aks-preview/azext_aks_preview/tests/__init__.py
- src/aks-preview/azext_aks_preview/tests/latest/__init__.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_managed_aad.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
We think we were misisng __init__.py. Lets see if that's true.
> Run aks-preview UTs as part of CI

- .github/CODEOWNERS
- linter_exclusions.yml
> {CI} Fix ci linter for new linter rules in extension

- src/index.json
New Azure IoT extension for Azure CLI release.
---
> IoT extension release v0.9.3

- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_management_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_with_dns_proxy.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
Close https://github.com/Azure/azure-cli/issues/13350
add `--dns-servers`, `--dns-proxy-enabled`, `--dns-require-proxy-for-network-rules` to `network firewall create/update`
---
> [Firewall] Add dns proxy settings for network firewall

- src/aks-preview/azext_aks_preview/custom.py
This reverts commit 1c1052896697b6929ba28ad549fc03312f53d187.
We reverted the same change in official CLI. will revisit the choice of the default VM sku later. 
---
> Revert "change default vm sku to Standard_D2s_v3"

- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/commands.py
- src/aks-preview/azext_aks_preview/custom.py
---
Porting the same change from official CLI to cli extension
> [AKS] support --yes for az aks upgrade

- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
follow up of https://github.com/Azure/azure-cli-extensions/pull/1795
---
> [Firewall] Rename --dns-require-proxy-for-network-rules to --require-dns-proxy-for-network-rules

- src/index.json
> Update sap-hana extension to version 0.6.3

- src/log-analytics/azext_loganalytics/_client_factory.py
- src/log-analytics/azext_loganalytics/tests/latest/test_loganalytics_commands.py
- src/log-analytics/setup.py
Fix https://github.com/Azure/azure-cli-extensions/issues/959
---
> [Log Analytics] Query support cloud awareness

- src/azure-firewall/azext_firewall/custom.py
> [Network] az network firewall network-rule: fix potential bug

- src/aks-preview/setup.py
> [AKS] aks-preview: version bump

- src/aks-preview/HISTORY.md
> [AKS] aks-preview: update HISTORY.md

- src/aks-preview/azext_aks_preview/custom.py
> Support 0 node agent pool and block manual scale CAS enabled pool

- src/ip-group/setup.py
As mentioned in https://github.com/Azure/azure-cli-extensions/issues/1052
---
> [ip-group] fix azext_metadata.json missing error

- src/vm-repair/azext_vm_repair/azext_metadata.json
- src/vm-repair/setup.py
As it's going to on board https://github.com/Azure/azure-cli-extensions/pull/1842, we should fix the extension that miss azext_metadata.json
---
> [vm-repair] add azext_metadata.json

- src/mixed-reality/setup.py
As it's going to on board #1842, we should fix the extension that miss azext_metadata.json
---
> [mixed-reality] Add azext_metadata.json 

- src/managementpartner/azext_managementpartner/azext_metadata.json
- src/managementpartner/setup.py
As it's going to on board #1842, we should fix the extension that miss azext_metadata.json
---
> [managementpartner] Add azext_metadata.json

- src/managementpartner/setup.py
> [managementpartner] bump to 0.1.3

- linter_exclusions.yml
- src/index.json
> IoT extension 0.9.4 release (Digital Twins content release)

- src/log-analytics/azext_loganalytics/azext_metadata.json
- src/log-analytics/setup.py
As it's going to on board #1842, we should fix the extension that miss azext_metadata.json
---
> [log-analytics] complete azext_metadata.json

- src/application-insights/azext_applicationinsights/_help.py
- src/application-insights/azext_applicationinsights/_params.py
- src/application-insights/azext_applicationinsights/custom.py
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component.yaml
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_workspace.yaml
- src/application-insights/azext_applicationinsights/tests/latest/test_applicationinsights_mgmt.py
---
This PR resolves #1638 
- Set retention for legacy AI without workspace connection.
> [Monitor] Set retention for AI

- src/spring-cloud/setup.py
> update version to 0.2.5

- src/ai-did-you-mean-this/HISTORY.rst
- src/ai-did-you-mean-this/azext_ai_did_you_mean_this/custom.py
- src/ai-did-you-mean-this/setup.py
Rename required service parameter "sessionId" to "correlationId". Required by pending changes to the Aladdin prod endpoint.
---
> [ai-did-you-mean-this] Rename Required Service Parameter "sessionId" to "correlationId"

- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy_with_threat_intel_whitelist.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
> [Network] az network firewall policy create: support threat white list arguments

- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
> [Network] az network firewall create/update: support --threat-intel-model argument

- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_policy_with_dns_settings.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
Close https://github.com/Azure/azure-cli/issues/13638
Add `--dns-servers`, `--enable-dns-proxy`, `--require-dns-proxy-for-network-rules` to `firewall policy create/update`
---
> [azure-firewall] Support DNS settings options in firewall policy

- src/virtual-wan/azext_vwan/_help.py
- src/virtual-wan/azext_vwan/_params.py
- src/virtual-wan/azext_vwan/commands.py
- src/virtual-wan/azext_vwan/custom.py
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_route_table_v3.yaml
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vhub_route_table_scenario.py
This PR is to support vhub v3 route table features in https://github.com/Azure/azure-cli/issues/12959
---
> [Network] Support virtual hub v3 route table

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/_validators.py
- src/spring-cloud/setup.py
> [SpringCloud] fix none sku case

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
> [AKS] add uptime-sla for updating

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> update aks-preview version

- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy_with_threat_intel_whitelist.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_rules.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_rules_with_ipgroups.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_threat_intel_whitelist.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_virtual_hub.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_zones.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_policy_with_dns_settings.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_with_dns_proxy.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
The wrong key of DNS proxy settings would fail ip-config create command.
---
> [firewall] wrong key that would crash firewall ip-config

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/setup.py
1. https://github.com/Azure/azure-cli-extensions/pull/1795
2. https://github.com/Azure/azure-cli/issues/13638
---
> [Firewall] bump to 0.4.0

- src/ai-examples/HISTORY.rst
- src/ai-examples/README.md
- src/ai-examples/README.rst
- src/ai-examples/azext_ai_examples/custom.py
- src/ai-examples/azext_ai_examples/tests/latest/test_ai_examples_scenario.py
- src/ai-examples/setup.py
Updating the telemetry to follow our current pattern. Improve README to be more descriptive of the project. Remove pruned responses from the examples.
---
> [ai-examples] Update the telemetry, README, and remove pruned responses 

- src/index.json
> [sap-hana] Updated sap-hana to version 0.6.4

- src/index.json
> [azure-iot] Update for 0.9.5. Still keep 0.9.4 on index.

- src/storage-preview/HISTORY.rst
- src/storage-preview/azext_storage_preview/_help.py
- src/storage-preview/azext_storage_preview/_params.py
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_storage_adls_blob_move.yaml
- src/storage-preview/azext_storage_preview/tests/latest/test_storage_adls_scenarios.py
> [Storage] az storage blob directory list: Fix the problem of `--num-results` (#1257)

- src/blueprint/HISTORY.rst
- src/blueprint/azext_blueprint/custom.py
- src/blueprint/setup.py
> [Blueprint] Bug fix for publish and assignment

- src/index.json
Hot fix for monitor event initialization issue.
---
> [azure-iot] IoT extension v0.9.6

- src/azure-firewall/azext_firewall/_help.py
- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy_rules_with_ip_groups.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
---
Fix Azure/azure-cli#13811
Fix Azure/azure-cli#13631
> [Network] az network firewall policy rule-collection-group rule-collection: support multiple DNAT rules and ip groups settings

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/setup.py
> {Release} bump version and add history for azure firewall

- src/virtual-wan/azext_vwan/custom.py
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_gateway.yaml
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vwan_vhub_commands.py
> [Network] az network vpn-gateway create: add validation to check the existence of an vpn gateway.

- src/virtual-wan/azext_vwan/custom.py
> {Network} refine implementation detail

- src/datashare/azext_datashare/manual/_help.py
> {Datashare} Add reference link in help

- src/storage-preview/HISTORY.rst
- src/storage-preview/azext_storage_preview/_help.py
Issue: https://github.com/Azure/azure-cli/issues/10020
Related to https://github.com/Azure/azure-cli/pull/14062
---
> [Storage] Fix the storage account name in examples 

- src/ai-did-you-mean-this/setup.py
> [ai-did-you-mean-this] Change URL in setup.py

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/_stream_utils.py
- src/spring-cloud/setup.py
> {spring cloud} change dependency

- src/virtual-wan/azext_vwan/_help.py
- src/virtual-wan/azext_vwan/_params.py
- src/virtual-wan/azext_vwan/_util.py
- src/virtual-wan/azext_vwan/commands.py
- src/virtual-wan/azext_vwan/custom.py
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_p2s_gateway_routing_configuration.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_route_table.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_route_table_v3.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_gateway_connection.yaml
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vhub_route_table_scenario.py
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vwan_vhub_commands.py
This PR adds routing configuration for vpn connection and p2s connection which is requested in https://github.com/Azure/azure-cli/issues/12959
---
> [Network] Support routing configuration for vpn connection and p2s connection

- src/index.json
IoT extension release which includes PnP summer refresh content as well as new Central commands.
---
> IoT extension release 0.9.7

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_nonaad_and_update_with_managed_aad.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/setup.py
> [aks-preview] Support migrating a non-AAD cluster to a AKS-managed AAD cluster

- src/application-insights/HISTORY.rst
- src/application-insights/azext_applicationinsights/_params.py
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component.yaml
- src/application-insights/azext_applicationinsights/tests/latest/test_applicationinsights_mgmt.py
- src/application-insights/setup.py
> [Monitor] az monitor app-insights component billing: support `--cap` with float value

- src/application-insights/HISTORY.rst
- src/application-insights/azext_applicationinsights/_help.py
- src/application-insights/azext_applicationinsights/custom.py
- src/application-insights/setup.py
> [Monitor] az monitor app-insights api-key: Add warning to remove permission and example

- src/synapse/azext_synapse/_validators.py
> [Synapse] Fixed a typo in validator

- src/synapse/setup.py
> [Synapse]Update Synapse version

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/_exception_handler.py
- src/db-up/azext_db_up/_params.py
- src/db-up/azext_db_up/commands.py
- src/db-up/setup.py
---
Fix https://github.com/Azure/azure-cli/issues/14407
> {db-up} Fix issue to refine error message

- src/virtual-wan/azext_vwan/_help.py
- src/virtual-wan/azext_vwan/commands.py
- src/virtual-wan/azext_vwan/custom.py
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vhub_route_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vwan_vhub_commands.py
> [Network] az network vhub route reset: reset this route when the routingState is set to Failed.

- src/virtual-wan/azext_vwan/_help.py
- src/virtual-wan/azext_vwan/_params.py
- src/virtual-wan/azext_vwan/commands.py
- src/virtual-wan/azext_vwan/custom.py
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_p2s_vpn_gateway_basic_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vpn_server_config_basic_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vhub_connection_routing_configuration.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vhub_get_effective_routes.yaml
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vhub_route_table_scenario.py
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vwan_vhub_commands.py
This PR includes the following features requested in https://github.com/Azure/azure-cli/issues/12959:
- Get the effective routes configured for the Virtual Hub resource or the specified resource.
- Manage routing configuration for virtual hub vnet connection.
---
> [Network] Support vhub get effective routes and vhub connection routing configuration

- src/storage-preview/azext_storage_preview/azcopy/util.py
* storage-preview/azext_storage_preview/azcopy/util.py changed subprocess.call() param to array
---
> Fix Executable File Not Found Error

- src/synapse/HISTORY.rst
> [Synapse] Update synapse's release history

- src/ai-examples/HISTORY.rst
- src/ai-examples/azext_ai_examples/custom.py
- src/ai-examples/setup.py
Now if the service provides no values or the client is unable to connect to the service, it falls back to using the built in examples.
---
> [ai-examples] Add fallback to use built-in values if there is an issue with the service

- src/virtual-wan/HISTORY.rst
- src/virtual-wan/setup.py
> [Network] Release vwan extension with new version 0.2.0

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> Add release information for aks-preview 0.4.59

- linter_exclusions.yml
Add two kinds of suppression for existing commands
- option_length_too_long
- option_should_not_contain_under_score
Remove one kind of suppression since the severity become medium
- parameter_should_not_end_in_resource_group
> {CI} add suppression for two incoming linter rules.

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> bump AKS extension to 0.4.60

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_help.py
- src/azure-firewall/setup.py
> {Network} Refine help message

- src/kusto/azext_kusto/manual/tests/latest/recordings/test_kusto.yaml
- src/kusto/azext_kusto/manual/tests/latest/test_kusto_scenario.py
> kusto test: create dependency in setup

- src/application-insights/azext_applicationinsights/commands.py
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_api_key.yaml
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component.yaml
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_storage.yaml
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_workspace.yaml
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_public_network_access.yaml
- src/azure-firewall/azext_firewall/commands.py
- src/connectedmachine/azext_connectedmachine/commands.py
- src/front-door/azext_front_door/commands.py
- src/hpc-cache/azext_hpc_cache/commands.py
- src/internet-analyzer/azext_internet_analyzer/commands.py
- src/maintenance/azext_maintenance/commands.py
- src/maintenance/azext_maintenance/tests/latest/recordings/test_signalr_commands.yaml
- src/managementpartner/azext_managementpartner/commands.py
- src/mesh/azext_mesh/commands.py
- src/spring-cloud/azext_spring_cloud/commands.py
- src/stream-analytics/azext_stream_analytics/commands.py
- src/support/azext_support/commands.py
> [CI] Fix show command and custom show command

- src/index.json
Content for this release https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.9.8
---
> [azure-iot] IoT extension version 0.9.8

- src/db-up/azext_db_up/_params.py
This PR is to add local context support for `az postgres up`.
---
> [Postgres] az postgres up: support local context

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_help.py
- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/_validators.py
- src/azure-firewall/azext_firewall/commands.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy_with_threat_intel_allowlist.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_rules.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_rules_with_ipgroups.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_threat_intel_allowlist.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
- src/azure-firewall/setup.py
> [Network] Breaking Change: rename whitelist to allow list

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/_constants.py
- src/connectedk8s/azext_connectedk8s/_utils.py
- src/connectedk8s/azext_connectedk8s/custom.py
- src/connectedk8s/setup.py
> [connectedk8s] Adding support for passing extra helm parameters through file

- src/index.json
Content for this release https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.9.9
---
> [azure-iot] IoT extension version 0.9.9

- src/index.json
> {ImageCopy} update 0.2.6 checksum

- src/image-copy/HISTORY.rst
- src/image-copy/setup.py
- src/index.json
> [ImageCopy] Release image-copy-extension 0.2.7

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> Release aks-preview 0.4.62

- src/spring-cloud/HISTORY.md
- src/spring-cloud/setup.py
> Bump Spring Cloud version to 1.0.1

- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
---
There are few corner case in python that a float number time 100000 and remain 1 will result in a large number. In this PR, we convert the float to string and directly check the decimal number count.
**Python 3.8.2**
print(0.061 * 100000 % 1) => 0.0
print(0.062 * 100000 % 1) => 0.0
print(0.063 * 100000 % 1) => 0.0
print(0.064 * 100000 % 1) => 0.0
print(0.065 * 100000 % 1) => 0.0
print(0.066 * 100000 % 1) => 0.0
print(0.067 * 100000 % 1) => 0.0
print(0.068 * 100000 % 1) => 9.094947017729282e-13
print(0.069 * 100000 % 1) => 9.094947017729282e-13
print(0.070 * 100000 % 1) => 9.094947017729282e-13
print(0.071 * 100000 % 1) => 0.9999999999990905
print(0.072 * 100000 % 1) => 0.9999999999990905
print(0.073 * 100000 % 1) => 0.9999999999990905
print(0.074 * 100000 % 1) => 0.0
print(0.075 * …
> Use string length to cover corner case for decimal number count

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_help.py
> [AKS] Remove preview from azure policy addon for cli extension

- src/aks-preview/azext_aks_preview/_consts.py
- src/aks-preview/azext_aks_preview/custom.py
Sibling PR in azure-cli: https://github.com/Azure/azure-cli/pull/15123/files
---
> [AKS] Fixed case sensitive issue for AKS dashboard addon

- src/application-insights/HISTORY.rst
- src/application-insights/azext_applicationinsights/custom.py
- src/application-insights/setup.py
> [Application Insights] `az monitor app-insights component update`: Update consent message.

- src/storage-blob-preview/azext_storage_blob_preview/_validators.py
> {storage-blob-preview} add check

- src/storage-blob-preview/azext_storage_blob_preview/vendored_sdks/__init__.py
- src/storage-blob-preview/azext_storage_blob_preview/vendored_sdks/azure_storage_blob/__init__.py
> {storage-blob-preview} package vendored sdk

- src/index.json
Content for this release: https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.0
---
- [] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [] Have you run `python scripts/ci/test_index.py -q` locally?
> IoT Extension version 0.10.0

- src/ssh/HISTORY.md
- src/ssh/setup.py
> [SSH] upgrade version to 0.1.1

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> [AKS] Release aks-preview 0.4.63

- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_management_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_firewall_policy.yaml
- src/azure-firewall/setup.py
Fix https://github.com/Azure/azure-cli/issues/15028
---
> [Firewall] Network.DNS.EnableProxy shoule be lowercase

- src/aks-preview/azext_aks_preview/custom.py
> [AKS] Fixed indentation

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/commands.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_get_upgrades.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Official CLI has already supported it. Add the same support to CLI-Extension https://github.com/Azure/azure-cli/pull/14516
> [AKS] Add az aks nodepool get-upgrades command

- src/aks-preview/azext_aks_preview/custom.py
Sibling PR in azure-cli: https://github.com/Azure/azure-cli/pull/15267
---
> [AKS] Expect kube-dashboard addon be disabled by default

- src/databricks/HISTORY.rst
- src/databricks/azext_databricks/_params.py
- src/databricks/azext_databricks/_validators.py
- src/databricks/setup.py
> [Databricks] GA CMK feature

- src/index.json
Release notes can be found here: https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.1
---
> [azure-iot] IoT Extension version 0.10.1

- src/index.json
Release information can be found here: https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.2
---
> [azure-iot] IoT Extension version 0.10.2

- src/codespaces/README.rst
- src/codespaces/azext_codespaces/tests/latest/recordings/test_codespaces_plan.yaml
- src/codespaces/azext_codespaces/tests/latest/test_codespaces_scenario.py
---
Fix docker image in codespaces extension doc, to pull from mcr.microsoft.com/azure-cli
> fix docker image in doc

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
AKS requires the Open Service Mesh addon to be available
as a part of the AKS cli extensions.
---
> aks-preview: release version 0.4.64

- src/databricks/azext_databricks/azext_metadata.json
---
databricks service is ready for GA, they request Azure CLI extension GA also.
> mark databricks extension ga since service ga

- src/databricks/HISTORY.rst
- src/databricks/setup.py
> release GA databricks extension

- src/index.json
> [baremetal] Adding the baremetal extension to the overall cli extension repo

- src/application-insights/HISTORY.rst
- src/application-insights/azext_applicationinsights/_help.py
- src/application-insights/azext_applicationinsights/_params.py
- src/application-insights/azext_applicationinsights/commands.py
- src/application-insights/azext_applicationinsights/custom.py
- src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_webapp.yaml
- src/application-insights/azext_applicationinsights/tests/latest/test_applicationinsights_mgmt.py
Details in https://github.com/Azure/azure-cli/issues/14789
Commands:
`az monitor app-insights component connect-webapp –ids resource-id-for-webapp --enable-profiler false --enable-snapshot-debugger`
`az monitor app-insights component connect-webapp -g rg -n myApp --enable-profiler --enable-snapshot-debugger`
---
> [Monitor] Enable AI for web app

- src/application-insights/setup.py
> [Monitor] Upgrade extension version for application insights

- src/aks-preview/azext_aks_preview/_consts.py
- src/aks-preview/azext_aks_preview/custom.py
Sibling PR in azure-cli: https://github.com/Azure/azure-cli/pull/15376
---
> [AKS] Honor addon names defined in Azure CLI

- src/index.json
Notes for this release can be found here: 
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.4
---
> [azure-iot] IoT Extension Version 0.10.4

- src/image-copy/HISTORY.rst
- src/image-copy/azext_imagecopy/__init__.py
- src/image-copy/setup.py
Resolve https://github.com/Azure/azure-cli-extensions/issues/2083
---
> [ImageCopy] Remove unused --subscription parameter

- src/cli-translator/README.md
> {CLI Translator} Update CLI Translator README.md

- src/cli-translator/HISTORY.md
- src/cli-translator/azext_cli_translator/azext_metadata.json
- src/cli-translator/setup.py
> {CLI Translator} update minCliCoreVersion to 2.13.0

- src/index.json
Release notes available here: https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.5
---
> [azure-iot] IoT Extension Version 0.10.5

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ahub.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_windows.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_aks/models/container_service_windows_profile.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_aks/models/container_service_windows_profile_py3.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2019_04_01/models/managed_cluster_windows_profile.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2019_04_01/models/managed_cluster_windows_profile_py3.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2019_08_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2019_08_01/models/_models_py3.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2019_10_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2019_10_01/models/_models_py3.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_01_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_01_01/models/_models_py3.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_02_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_02_01/models/_models_py3.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_03_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_03_01/models/_models_py3.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_04_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_04_01/models/_models_py3.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_06_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_06_01/models/_models_py3.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_09_01/models/_models.py
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_09_01/models/_models_py3.py
> [AKS] remove patterns for adminUsername and adminPassword in WindowsProfile

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
---
* Honor addon names defined in Azure CLI
* Add LicenseType support for Windows
* Remove patterns for adminUsername and adminPassword in WindowsProfile
> aks-preview: release version 0.4.65

- src/vmware/README.md
> update vmware readme

- src/front-door/azext_front_door/_help.py
- src/front-door/azext_front_door/_params.py
- src/front-door/azext_front_door/commands.py
- src/front-door/azext_front_door/custom.py
- src/front-door/azext_front_door/tests/latest/recordings/test_backend_pool_basic.yaml
- src/front-door/azext_front_door/tests/latest/recordings/test_frontend_endpoint_basic.yaml
- src/front-door/azext_front_door/tests/latest/recordings/test_load_balancing_basic.yaml
- src/front-door/azext_front_door/tests/latest/recordings/test_probe_basic.yaml
- src/front-door/azext_front_door/tests/latest/recordings/test_route_rule_basic.yaml
- src/front-door/azext_front_door/tests/latest/test_backend_pool_scenarios.py
- src/front-door/azext_front_door/tests/latest/test_frontend_endpoint_scenarios.py
- src/front-door/azext_front_door/tests/latest/test_load_balancing_scenarios.py
- src/front-door/azext_front_door/tests/latest/test_probe_scenarios.py
- src/front-door/azext_front_door/tests/latest/test_route_rule_scenarios.py
- src/front-door/setup.py
- Add command: network front-door load-balancing update
- Add test scenarios for backend-pool, frontend-endpoint, load-balancing, probe and route-rule
---
> [Network] Add front-door load-balancing update

- src/ai-examples/HISTORY.rst
- src/ai-examples/azext_ai_examples/custom.py
- src/ai-examples/setup.py
@fengzhou-msft let me know that the User ID we were sending was not the intended one, so this PR switches it to the pseudo ID we wanted.
---
> [ai-examples] Update to use appropriate User ID hash

- src/stack-hci/HISTORY.rst
- src/stack-hci/setup.py
> Update setup.py for Stack HCI

- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_policy_with_dns_settings.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_with_dns_proxy.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
- src/azure-firewall/setup.py
[firewall] Remove DNSProxyRequiredForNetworkRule in Azure Firewall and Azure Firewall Policy
---
> [Firewall] Remove DNSProxyRequiredForNetworkRule in Azure Firewall and Azure Firewall Policy

- src/index.json
Revert the release per service team's request.
---
> {k8sconfiguration} Revert release of version 0.2.0

- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
Fix 1st stage of https://github.com/Azure/azure-cli/issues/15377, adding --sku to `firewall policy`
---
> [Firewall] Support to configure policy sku with --sku

- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
---
Close: https://github.com/Azure/azure-cli/issues/15481
> [Firewall]  Add a new parameter named translated-fqdn to the command az network firewall policy rule-collection-group collection add-nat-collection

- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
Revert https://github.com/Azure/azure-cli-extensions/pull/2645 as service Team requested
---
> {Firewall} Revert SKU feature 

- src/datadog/azext_datadog/manual/_help.py
- src/datadog/azext_datadog/manual/commands.py
- src/datadog/azext_datadog/manual/custom.py
> [Datadog] Add link command

- src/dev-spaces/azext_dev_spaces/custom.py
- src/dev-spaces/setup.py
> [dev-spaces] Add deprecation info to dev-spaces extension

- src/index.json
> [Baremetal] fix a bug with the delete operation

- src/logic/HISTORY.rst
- src/logic/azext_logic/generated/_params.py
- src/logic/azext_logic/generated/action.py
- src/logic/setup.py
---
- [ * ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ * ] Have you run `python scripts/ci/test_index.py -q` locally?
- [ n/a ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).
> [logic] Fix parsing argument --integration-service-environment

- src/communication/README.md
> [Communication] Fix Readme

- src/cli-translator/HISTORY.md
- src/cli-translator/azext_cli_translator/custom.py
- src/cli-translator/setup.py
> [cli-translator] Fix can't recognize ~ in path problem

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> aks-preview: release version 0.4.66

- src/index.json
> Release k8sconfiguration 0.2.0

- src/index.json
Notes for this release are available here:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.7
---
> [azure-iot] IoT Extension Version 0.10.7

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> aks-preview: Release aks-preview 0.4.67

- linter_exclusions.yml
- src/healthcareapis/HISTORY.rst
- src/healthcareapis/azext_healthcareapis/__init__.py
- src/healthcareapis/azext_healthcareapis/azext_metadata.json
- src/healthcareapis/azext_healthcareapis/generated/_client_factory.py
- src/healthcareapis/azext_healthcareapis/generated/_help.py
- src/healthcareapis/azext_healthcareapis/generated/_params.py
- src/healthcareapis/azext_healthcareapis/generated/_validators.py
- src/healthcareapis/azext_healthcareapis/generated/action.py
- src/healthcareapis/azext_healthcareapis/generated/commands.py
- src/healthcareapis/azext_healthcareapis/generated/custom.py
- src/healthcareapis/azext_healthcareapis/tests/__init__.py
- src/healthcareapis/azext_healthcareapis/tests/latest/test_healthcareapis_scenario.py
- src/healthcareapis/azext_healthcareapis/vendored_sdks/healthcareapis/_healthcare_apis_management_client.py
- src/healthcareapis/azext_healthcareapis/vendored_sdks/healthcareapis/_version.py
- src/healthcareapis/azext_healthcareapis/vendored_sdks/healthcareapis/setup.py
- src/healthcareapis/report.md
- src/healthcareapis/setup.py
> [healthcareapis] Private Link and BYOK updates

- src/spring-cloud/HISTORY.md
- src/spring-cloud/setup.py
> [Spring-Cloud] Boom up version for mooncake support

- src/virtual-wan/azext_vwan/_params.py
---
Deprecate RTv2, please see details in: https://github.com/Azure/azure-cli/issues/15927 
> [Network] Deprecate route table V2

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> aks-preview: Release aks-preview 0.4.68

- src/k8sconfiguration/HISTORY.rst
- src/k8sconfiguration/azext_k8sconfiguration/_validators.py
- src/k8sconfiguration/azext_k8sconfiguration/custom.py
- src/k8sconfiguration/setup.py
> [k8sconfiguration] Fix bug in known_hosts property and add support for other key types

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/custom.py
---
I haven't updated the version in setup.py as akash will be updating in a later PR this week
> Added some checks for proxy

- src/attestation/README.md
> {Attestation} Update readme.md

- src/connectedk8s/setup.py
> Increase version of connecectedk8s cli

- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_management_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
Close https://github.com/Azure/azure-cli/issues/15377
---
> [Firewall] az network firewall policy: Add --sku option

- src/hack/HISTORY.rst
- src/hack/azext_hack/_database_utils.py
- src/hack/azext_hack/_website_utils.py
- src/hack/setup.py
---
@GeekTrainer this change for Az Hack Create uses the Serverless mode for Cosmos DB Mongo by default.
> {Hack} `az hack create`: Use Serverless mode for Cosmos DB

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.8
---
> [azure-iot] IoT Extension Version 0.10.8

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_byo_appgw_with_ingress_appgw_addon.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_byo_subnet_with_ingress_appgw_addon.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ingress_appgw_addon.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
This PR updates the network api version in the AGIC addon tests.
---
> aks: update AGIC addon recordings

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> [AKS] bump to 0.4.71 for private dns zone feature

- src/azure-firewall/azext_firewall/_help.py
- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/commands.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy_intrusion_detection.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
Support to configure intrusion detection policy and transport security for premium tier firewall policy
It's part 3/3 of Azure/azure-cli#15377
Close https://github.com/Azure/azure-cli/issues/15377
---
> [Firewall] Support to configure intrusion detection policy and transport security for premium tier firewall policy

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/azext_metadata.json
- src/azure-firewall/setup.py
It's a sumamry of:
1. https://github.com/Azure/azure-cli-extensions/pull/2797
2. https://github.com/Azure/azure-cli-extensions/pull/2805
2. https://github.com/Azure/azure-cli-extensions/pull/2822
Close https://github.com/Azure/azure-cli/issues/15377
---
> [Firewall] Upgrade to 0.8.0 to enable premium firewall policy featue

- src/index.json
> {index} Remove rdbms-connect due to installation issue

- src/aks-preview/README.md
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/custom.py
---
Support updating tags by az aks update --tags
> [AKS] Support updating tags by az aks update --tags

- src/cosmosdb-preview/azext_cosmosdb_preview/azext_metadata.json
> [cosmosdb-preview] Updating the minCliCoreVersion

- scripts/ci/index_ref_doc.py
> {CI} fix trackback print exc bug

- src/cosmosdb-preview/azext_cosmosdb_preview/vendored_sdks/__init__.py
> {cosmosdb-preview} add init file for vendored sdk

- src/ssh/HISTORY.md
- src/ssh/azext_ssh/_help.py
- src/ssh/azext_ssh/_params.py
- src/ssh/azext_ssh/custom.py
- src/ssh/azext_ssh/ip_utils.py
- src/ssh/azext_ssh/ssh_utils.py
- src/ssh/azext_ssh/tests/latest/test_custom.py
- src/ssh/azext_ssh/tests/latest/test_ssh_utils.py
- src/ssh/setup.py
* Add support for using private IPs
* Force lowercase username
* Add support for --name instead of --vm-name
* Fix various typos
---
> [SSH] Add support for private IPs and force lowercase usernames

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/tests/latest/recordings/test_mysql_flow.yaml
- src/db-up/setup.py
Fix [CVE-2019-2435](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-2435)
---
> [db-up] Bump mysql-connector-python

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/_params.py
- src/spring-cloud/azext_spring_cloud/_validators.py
- src/spring-cloud/azext_spring_cloud/custom.py
- src/spring-cloud/setup.py
> [Spring-Cloud]remove preview parameter and fix warning message

- src/aem/azext_aem/__init__.py
- src/aem/azext_aem/custom.py
- src/aem/azext_aem/tests/latest/recordings/test_ExtensionDowngrade.yaml
- src/aem/azext_aem/tests/latest/recordings/test_ExtensionReinstall.yaml
- src/aem/azext_aem/tests/latest/recordings/test_ExtensionUpgrade.yaml
- src/aem/azext_aem/tests/latest/recordings/test_NewExtensionDiskAdd.yaml
- src/aem/azext_aem/tests/latest/recordings/test_NewExtensionMultiNic.yaml
- src/aem/azext_aem/tests/latest/recordings/test_OldExtensionReinstall.yaml
- src/aem/azext_aem/tests/latest/recordings/test_WithSystemAssignedIdentity.yaml
- src/aem/azext_aem/tests/latest/recordings/test_WithUserAssignedIdentity.yaml
- src/aem/azext_aem/tests/latest/recordings/test_WithoutIdentity.yaml
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure.yaml
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure_v2.yaml
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure_v2_individual.yaml
- src/aem/azext_aem/tests/latest/test_aem_commands.py
> add support for new VM Extension for SAP

- src/aem/azext_aem/tests/latest/recordings/test_ExtensionDowngrade.yaml
- src/aem/azext_aem/tests/latest/recordings/test_ExtensionReinstall.yaml
- src/aem/azext_aem/tests/latest/recordings/test_ExtensionUpgrade.yaml
- src/aem/azext_aem/tests/latest/recordings/test_NewExtensionDiskAdd.yaml
- src/aem/azext_aem/tests/latest/recordings/test_NewExtensionMultiNic.yaml
- src/aem/azext_aem/tests/latest/recordings/test_OldExtensionReinstall.yaml
- src/aem/azext_aem/tests/latest/recordings/test_WithSystemAssignedIdentity.yaml
- src/aem/azext_aem/tests/latest/recordings/test_WithUserAssignedIdentity.yaml
- src/aem/azext_aem/tests/latest/recordings/test_WithoutIdentity.yaml
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure.yaml
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure_v2.yaml
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure_v2_individual.yaml
- src/aem/setup.py
> Update AEM version after adding support for new Azure Extension for SAP

- src/databricks/HISTORY.rst
- src/databricks/azext_databricks/_params.py
- src/databricks/azext_databricks/_validators.py
- src/databricks/azext_databricks/commands.py
- src/databricks/azext_databricks/tests/latest/recordings/test_databricks.yaml
- src/databricks/azext_databricks/tests/latest/recordings/test_databricks_vnet_peering.yaml
- src/databricks/azext_databricks/tests/latest/test_databricks_scenario.py
- src/databricks/setup.py
Resolve #2578 
The root cause is that the `validate_workspace_values` validator in `az databricks workspace create` command overwrites the validator for `tags_type` parameter. This PR removes the `validate_workspace_values` command validator and moves the logic into different validators for parameters.
---
> [Databricks] Fix issue when creating a workspace with --tags

- src/confluent/azext_confluent/manual/_help.py
> [Confluent] Add examples for using --ids

- src/index.json
Release notes can be found here: https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.9
---
> IoT Extension Release 0.10.9

- CONTRIBUTING.rst
Align with https://github.com/Azure/azure-cli/pull/16704
---
> {Doc} Fix broken link in CONTRIBUTING.rst

- src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query.yaml
- src/scheduled-query/azext_scheduled_query/tests/latest/test_scheduled_query_scenario.py
> {Scheduled Query} Record tests.

- src/stack-hci/HISTORY.rst
- src/stack-hci/azext_stack_hci/azext_metadata.json
- src/stack-hci/azext_stack_hci/generated/commands.py
- src/stack-hci/setup.py
> [Stack HCI] GA stack-hci version

- src/storage-blob-preview/HISTORY.rst
- src/storage-blob-preview/azext_storage_blob_preview/_client_factory.py
- src/storage-blob-preview/azext_storage_blob_preview/_params.py
- src/storage-blob-preview/azext_storage_blob_preview/_transformers.py
- src/storage-blob-preview/azext_storage_blob_preview/_validators.py
- src/storage-blob-preview/azext_storage_blob_preview/azext_metadata.json
- src/storage-blob-preview/azext_storage_blob_preview/commands.py
- src/storage-blob-preview/azext_storage_blob_preview/operations/blob.py
- src/storage-blob-preview/azext_storage_blob_preview/tests/latest/recordings/test_storage_blob_soft_delete.yaml
- src/storage-blob-preview/azext_storage_blob_preview/tests/latest/recordings/test_storage_blob_update_service_properties.yaml
- src/storage-blob-preview/azext_storage_blob_preview/tests/latest/test_storage_blob_scenarios.py
- src/storage-blob-preview/setup.py
> {storage-blob-preview} Support blob service properties with track 2 SDK

- src/aks-preview/azext_aks_preview/custom.py
the required permission is correctly assigned when `create`ing a new AKS cluster, but still missed in `eanble-addons` subcommand. This PR is to fill that gap.
> [AKS]Assign required permission for virtual-node MSI

- src/databricks/azext_databricks/_params.py
- src/databricks/azext_databricks/custom.py
- src/databricks/azext_databricks/tests/latest/recordings/test_databricks.yaml
- src/databricks/azext_databricks/tests/latest/recordings/test_databricks_vnet_peering.yaml
- src/databricks/azext_databricks/tests/latest/test_databricks_scenario.py
`az databricks workspace create`: Add `--enable-no-public-ip` to allow creating workspace with no public ip
---
> [Databricks] Add --enable-no-public-ip

- .github/CODEOWNERS
- src/powerbidedicated/HISTORY.rst
- src/powerbidedicated/azext_powerbidedicated/_params.py
- src/powerbidedicated/setup.py
> [powerbidedicated] Fix #2613: The parameter for --administration-members is incorrectly stated as optional

- src/rdbms-connect/azext_rdbms_connect/azext_metadata.json
- src/rdbms-connect/setup.py
> [RDBMS] Updating versions for package and minCliCore for rdbms-connect extension

- src/virtual-wan/azext_vwan/_help.py
- src/virtual-wan/azext_vwan/commands.py
> [Netowrk] az network vhub route: Add deprecation message

- src/vmware/CHANGELOG.md
- src/vmware/azext_vmware/azext_metadata.json
- src/vmware/setup.py
> Update the minimum az cli version to 2.11.0 for vmware

- src/aem/azext_aem/azext_metadata.json
- src/aem/azext_aem/tests/latest/recordings/test_ExtensionDowngrade.yaml
- src/aem/azext_aem/tests/latest/recordings/test_ExtensionReinstall.yaml
- src/aem/azext_aem/tests/latest/recordings/test_ExtensionUpgrade.yaml
- src/aem/azext_aem/tests/latest/recordings/test_NewExtensionDiskAdd.yaml
- src/aem/azext_aem/tests/latest/recordings/test_NewExtensionMultiNic.yaml
- src/aem/azext_aem/tests/latest/recordings/test_OldExtensionReinstall.yaml
- src/aem/azext_aem/tests/latest/recordings/test_WithSystemAssignedIdentity.yaml
- src/aem/azext_aem/tests/latest/recordings/test_WithUserAssignedIdentity.yaml
- src/aem/azext_aem/tests/latest/recordings/test_WithoutIdentity.yaml
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure.yaml
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure_v2.yaml
- src/aem/azext_aem/tests/latest/recordings/test_vm_aem_configure_v2_individual.yaml
- src/aem/setup.py
> AEM: update required Python and CLI versions

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_fqdn_subdomain.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
> AKS: add --fqdn-subdomain for private cluster with custom private dns zone

- src/scheduled-query/HISTORY.rst
- src/scheduled-query/azext_scheduled_query/_help.py
- src/scheduled-query/azext_scheduled_query/grammar/scheduled_query/ScheduleQueryConditionValidator.py
- src/scheduled-query/azext_scheduled_query/tests/latest/test_scheduled_query_scenario.py
- src/scheduled-query/setup.py
> {scheduled-query} Fix parse bug for --condition with " and ' in query

- src/log-analytics/azext_loganalytics/_help.py
- src/log-analytics/azext_loganalytics/tests/latest/recordings/test_query.yaml
- src/scheduled-query/setup.py
---
closed https://github.com/Azure/azure-cli-extensions/issues/3003
> {LogAnalytics} Fix 'az monitor log-analytics query' examples

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/_validators.py
- src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_validator.py
- src/spring-cloud/setup.py
---
- When one of subnets associate route table while the other not, error
- When two subnets associate with the same route table, error
- Subnets with different route tables should be validate now
> Add bring your own route table support

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.10
---
> IoT Extension v0.10.10

- src/hpc-cache/HISTORY.rst
- src/hpc-cache/azext_hpc_cache/azext_metadata.json
- src/hpc-cache/azext_hpc_cache/commands.py
- src/hpc-cache/setup.py
> [HPC Cache] GA hpc-cache version

- src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query.yaml
> [Monitor] Fix test failure due to compute SDK version bump

- src/spring-cloud/azext_spring_cloud/commands.py
- src/spring-cloud/azext_spring_cloud/custom.py
- src/spring-cloud/setup.cfg
> [Spring Cloud] fix check active deployment

- src/costmanagement/HISTORY.rst
- src/costmanagement/azext_costmanagement/azext_metadata.json
- src/costmanagement/azext_costmanagement/manual/commands.py
- src/costmanagement/setup.py
> [CostManagement] `az costmanagement`: GA

- src/timeseriesinsights/HISTORY.rst
- src/timeseriesinsights/azext_timeseriesinsights/azext_metadata.json
- src/timeseriesinsights/azext_timeseriesinsights/commands.py
- src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_environment_gen2.yaml
- src/timeseriesinsights/setup.py
---
Closed https://github.com/Azure/azure-cli-extensions/issues/3092
> [timeseriesinsights] `az tsi`: GA

- src/logic/HISTORY.rst
- src/logic/azext_logic/azext_metadata.json
- src/logic/azext_logic/generated/commands.py
- src/logic/setup.py
---
https://github.com/Azure/azure-cli-extensions/issues/3087
> [Logic] Preview logic version

- src/index.json
> Update index.json for Arc Appliance CLI Extensions 0.1.2

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/custom.py
> aks-preview: support specifying custom http headers in aks upgrade

- src/index.json
> [New Extension] Adding customlocation 0.1.0 to src/index.json

- src/index.json
> Updated SapHana extension

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/custom.py
- src/db-up/azext_db_up/tests/latest/recordings/test_mysql_flow.yaml
- src/db-up/azext_db_up/tests/latest/recordings/test_postgres_flow.yaml
- src/db-up/azext_db_up/tests/latest/recordings/test_sql_flow.yaml
- src/db-up/setup.py
> {db-up} Fix #3143: db-up does not return correct PostgreSQL host for Azure Government

- src/index.json
> Add Arc Appliance CLI Extension 0.1.3

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_addon_with_azurekeyvaultsecretsprovider_with_secret_rotation.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_fqdn_subdomain.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_none_private_dns_zone.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_using_azurecni_with_pod_identity_enabled.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ahub.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_auto_upgrade_channel.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_azurekeyvaultsecretsprovider_addon.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_pod_identity_enabled.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_virtual_node_addon.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_windows.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_enable_addon_with_azurekeyvaultsecretsprovider.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_get_upgrades.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_pod_identity_usage.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_azurekeyvaultsecretsprovider_with_secret_rotation.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_to_msi_cluster.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_to_msi_cluster_with_addons.yaml
> AKS: remove preview description for private dns zone and fqdnsubdomain features

- src/index.json
> Adding CLI version 0.1.1 for CustomLocation

- src/virtual-wan/azext_vwan/_params.py
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vhub_connection_basic_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vpn_server_config_multi_auth.yaml
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vwan_vhub_commands.py
---
https://github.com/Azure/azure-cli/issues/17158
> [virtual-wan]`az network vpn-server-config`: `--auth-types` allow multi value

- src/hpc-cache/HISTORY.rst
- src/hpc-cache/azext_hpc_cache/_params.py
- src/hpc-cache/setup.py
> [hpc-cache] Improve help for nfs3_usage_model

- src/vmware/CHANGELOG.md
- src/vmware/azext_vmware/_help.py
- src/vmware/azext_vmware/commands.py
- src/vmware/azext_vmware/custom.py
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware.yaml
- src/vmware/azext_vmware/tests/latest/test_vmware_scenario.py
> add az vmware rotate passwords

- src/quantum/HISTORY.rst
- src/quantum/setup.py
> Update version and history info for az quantum extension 0.3.0

- src/service_name.json
> {Core} Add entry of cloudservice to service_name.json

- src/index.json
> Adding New Customlocation CLI Version 0.1.2

- src/index.json
> Update Arc Appliance CLI Extension to 0.1.4

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/_params.py
- src/spring-cloud/azext_spring_cloud/custom.py
- src/spring-cloud/setup.py
> [Azure Spring Cloud] Fix cannot enable/disable-ssl in redis service binding

- src/aks-preview/azext_aks_preview/custom.py
> AKS: better run-command result display

- .github/CODEOWNERS
> add myself into the aks-preview owner.

- src/ssh/azext_ssh/_help.py
> [SSH] Update config related help for clarity

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> [Release][AKS] Bump aks-preview version

- src/service_name.json
> updated az graph service name

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/commands.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
> Add get OS options support.

- src/ssh/HISTORY.md
- src/ssh/azext_ssh/_help.py
- src/ssh/azext_ssh/custom.py
- src/ssh/setup.py
> [SSH] Add public key error message, add docs, v0.1.5 rev

- src/index.json
Updating index.json to have a new URL for the fzf extension wheel. Fixes #3321. A second PR will follow to merge the code into this repository to prevent this happening again.
---
> Update index.json for fzf extension url

- azure-pipelines.yml
> {CI} Update pip before installing azdev

- src/index.json
- src/service_name.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.11
---
> IoT Extension Release v0.10.11

- src/aks-preview/azext_aks_preview/custom.py
In previous implementation, we always wipe out pod identity profile when user tries to enable this addon. This PR fixed this wrong behavior by checking the addon enablement before mutating cluster properties.
---
> aks: rebuild pod identity profile only if addon has been disabled before

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> [AKS] Bump aks-preview version to 0.5.11

- scripts/ci/avail-ext-doc/list-template.md
> fixed anchor link

- .flake8
- pylintrc
Migrated from https://github.com/Azure/azure-cli/pull/18003
Require https://github.com/Azure/azure-cli-dev-tools/pull/301
> {Pylint} Ignore `tests` folders

- src/kusto/HISTORY.rst
- src/kusto/setup.py
> Kusto: update setup and HISTORY files

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_disable_local_accounts.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/setup.py
> [AKS] Support disable local accounts

- src/mixed-reality/HISTORY.rst
- src/mixed-reality/azext_mixed_reality/tests/latest/recordings/test_remote_rendering_account_scenario.yaml
- src/mixed-reality/azext_mixed_reality/tests/latest/recordings/test_spatial_anchors_account_scenario.yaml
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/_mixed_reality_client.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/_version.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/aio/_mixed_reality_client.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/aio/operations/_mixed_reality_client_operations.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/aio/operations/_operations.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/aio/operations/_remote_rendering_accounts_operations.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/aio/operations/_spatial_anchors_accounts_operations.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/models/_mixed_reality_client_enums.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/operations/_mixed_reality_client_operations.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/operations/_operations.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/operations/_remote_rendering_accounts_operations.py
- src/mixed-reality/azext_mixed_reality/vendored_sdks/mixedreality/operations/_spatial_anchors_accounts_operations.py
- src/mixed-reality/setup.py
- src/service_name.json
> [MixedReality] Migrate to track2

- scripts/ci/avail-ext-doc/requirements.txt
---
https://github.com/Azure/azure-cli-extensions/pull/3311
> {pipeline} Update requirements.txt

- src/index.json
---
dev-spaces-preview download url is not accessible and block extension pipeline, changed it to backup url.
> remove download url for dev-spaces-preview

- src/webpubsub/HISTORY.rst
- src/webpubsub/setup.py
> Update version and history for Web Pubsub

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/_params.py
- src/connectedk8s/azext_connectedk8s/custom.py
- src/connectedk8s/setup.py
> [Connectedk8s] Added OID param for custom-locations feature

- src/scheduled-query/HISTORY.rst
- src/scheduled-query/azext_scheduled_query/_actions.py
- src/scheduled-query/azext_scheduled_query/_help.py
- src/scheduled-query/azext_scheduled_query/_params.py
- src/scheduled-query/azext_scheduled_query/azext_metadata.json
- src/scheduled-query/azext_scheduled_query/custom.py
- src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query.yaml
- src/scheduled-query/azext_scheduled_query/tests/latest/test_scheduled_query_scenario.py
- src/scheduled-query/setup.py
- src/service_name.json
---
Closed https://github.com/Azure/azure-cli-extensions/issues/3182
Closed https://github.com/Azure/azure-cli/issues/17848
Closed https://github.com/Azure/azure-cli/issues/17847
> [Scheduled-query] support query placeholder for `--condition` argument.

- src/quantum/HISTORY.rst
- src/quantum/setup.py
> Update version and history info for az quantum extension 0.5.0

- src/index.json
Updates to IoT Extension minimum supported core CLI version
---
> [IoT] IoT Extension release v0.10.13

- src/service_name.json
> modified az confluent Azure service node name

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/_params.py
- src/spring-cloud/azext_spring_cloud/custom.py
- src/spring-cloud/setup.py
---
For the newly added code only.
> Add support to format log streaming of structured JSON output

- src/service_name.json
> TOC: az datadog mapping update

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_run_command.py
- src/aks-preview/setup.py
> aks: add 'enable-ultra-ssd' parameter

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/commands.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_to_msi_cluster_with_addons.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Support aks egress-endpoints list operation
---
> [AKS]Support aks egress-endpoints list operation

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/data/kubeletconfig.json
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_node_config.yaml
- src/aks-preview/setup.py
> Add logging settings to node config

- src/cosmosdb-preview/README.md
> Fix installation command in README

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_util.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/setup.py
Closed https://github.com/Azure/azure-cli/issues/18442
---
> [Azure Firewall] Fix not found create_or_update in azure-firewall

- src/service_name.json
> [Reference TOC] fixed Azure service names

- src/monitor-control-service/HISTORY.rst
- src/monitor-control-service/setup.py
> [AMCS] Release new version

- src/service_name.json
> [Redis Enterprise] az redisenterprise: Add entry to service_name.json

- src/aks-preview/azcli_aks_live_test/transcribe_env.sh
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml
* fix trigger branch (from master to main)
* update pipeline agent/pool to 'ubuntu-latest'
* update scripts
> [AKS] Fix AKS PR check-in pipeline

- src/index.json
> Release ML version 2.0.1a2

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_addon_with_azurekeyvaultsecretsprovider_with_secret_rotation.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_none_private_dns_zone.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_private_cluster_public_fqdn.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_using_azurecni_with_pod_identity_enabled.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ahub.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_auto_upgrade_channel.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_azurekeyvaultsecretsprovider_addon.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_fips.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ingress_appgw_addon_with_deprecated_subet_prefix.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_node_config.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_openservicemesh_addon.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ossku.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_pod_identity_enabled.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_windows.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_disable_addon_openservicemesh.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_enable_addon_with_azurekeyvaultsecretsprovider.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_enable_addon_with_openservicemesh.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_add_with_ossku.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_get_upgrades.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_azurekeyvaultsecretsprovider_with_secret_rotation.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Fix recording tests in aks-preview. Update some recording files due to api version update in azure-cli ([PR#18593](https://github.com/Azure/azure-cli/pull/18593)).
> {AKS} Fix recording tests in aks-preview

- src/index.json
> Update ml to version 2.0.1a3

- src/aks-preview/azcli_aks_live_test/scripts/clean_up.sh
- src/aks-preview/azcli_aks_live_test/scripts/clone_repo.sh
- src/aks-preview/azcli_aks_live_test/scripts/prepare_image.sh
- src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
- src/aks-preview/azcli_aks_live_test/scripts/start_container.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_cli_live.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_ext_live.sh
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml
Polish scripts in aks live test pipeline.
* polish scripts according to shellcheck
* update pipeline name
> {AKS} Polish scripts in aks live test pipeline

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.14
---
> IoT Extension Release v0.10.14

- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml
In this PR, we added support for uploading recording files as artifacts on the live test pipeline.
> {AKS} Update AKS pipeline

- src/confluent/azext_confluent/manual/custom.py
- src/confluent/azext_confluent/tests/latest/test_confluent_scenario.py
- src/confluent/azext_confluent/tests/latest/test_confluent_scenario_coverage.md
---
Remove isRIRequired and msrp in price of `az confluent offer-detail show`
> [Confluent] Remove isRIRequired and msrp in price of `az confluent offer-detail show`

- azure-pipelines.yml
> [Pipeline] unping azdev version

- src/connectedk8s/azext_connectedk8s/custom.py
> [Connectedk8s] Added release namespace fix

- src/front-door/HISTORY.rst
- src/front-door/azext_front_door/custom.py
- src/front-door/azext_front_door/tests/latest/recordings/test_route_rule_basic.yaml
- src/front-door/azext_front_door/tests/latest/test_route_rule_scenarios.py
- src/front-door/setup.py
Fix unexpected configuration override when updating routing rule
This PR aims to fix https://github.com/Azure/azure-cli-extensions/issues/3314
---
> [FrontDoor] az network front-door routing-rule update: Fix unexpected configuration override when updating routing rule

- src/storage-preview/azext_storage_preview/azcopy/util.py
- src/storage-preview/azext_storage_preview/azext_metadata.json
- src/storage-preview/setup.py
> {storage-preview} Fix issue 3618: Fix jwt issue

- src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_cli_live.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_ext_live.sh
- src/aks-preview/azcli_aks_live_test/scripts/transcribe_env.sh
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_aadv1_and_update_with_managed_aad.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_managed_aad.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_nonaad_and_update_with_managed_aad.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_enable_utlra_ssd.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_stop_and_start.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_to_msi_cluster.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
* Add re-recording mode.
* Fix (ext/cli) live test options.
* Complete missing `--generate-ssh-keys` options in create cmds.
* Remove unnecessary `@live_only` tag from the following test cases:
* test_aks_create_and_update_with_managed_aad
* test_aks_create_aadv1_and_update_with_managed_aad
* test_aks_create_nonaad_and_update_with_managed_aad
* test_aks_create_and_update_with_managed_aad_enable_azure_rbac
* test_aks_stop_and_start
* test_aks_update_to_msi_cluster
* test_aks_enable_utlra_ssd
* Found potential conflicts in [generating ssh keys](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/keys.py#L37) during concurrent test mode. Opened an [issue](https://github.com/Azure/azure-cli/issues/18854). Would fix this in other PR.
There is a …
> {AKS} Fix AKS live test pipeline

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/custom.py
- src/db-up/azext_db_up/tests/latest/recordings/test_postgres_up.yaml
> [db-up] Fix issue #3301: az postgres up fails unpleasantly when database name contains dash

- src/storage-blob-preview/HISTORY.rst
- src/storage-blob-preview/azext_storage_blob_preview/_client_factory.py
- src/storage-blob-preview/azext_storage_blob_preview/azext_metadata.json
- src/storage-blob-preview/azext_storage_blob_preview/commands.py
- src/storage-blob-preview/setup.py
> [storage-blob-preview ] Fix issue and remove commands

- src/quantum/azext_quantum/_help.py
- src/quantum/azext_quantum/_params.py
This change adds a parameter to the examples of two commands to prevent a confusion by users that might not be aware that a default has to be set first, before using the command without that parameter.
No functionality change as part of this change.
---
> Improve help on `az quantum commands`.

- src/storage-blob-preview/setup.py
> [storage-blob-preview] upgrade version

- src/dnc/HISTORY.rst
> update version in history

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
Release PR for az quantum extension, version 0.6.0.
---
> Update version and history info for az quantum extension 0.6.0

- scripts/ci/avail-ext-doc/list-template.md
> Available extensions | updated metadata and intro paragraph for SEO

- src/aks-preview/azcli_aks_live_test/scripts/test_cli_live.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_cli_unit.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_ext_live.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_ext_unit.sh
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml
Upload the acs and aks-preview recording files to different directories.
> {AKS} Update AKS check-in pipeline

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy_rules_with_fqdns.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
- src/azure-firewall/setup.py
Closed https://github.com/Azure/azure-cli/issues/18932
---
* `az network firewall policy rule-collection-group collection add-filter-collection`: Add parameter `--destination-fqdns`
* `az network firewall policy rule-collection-group collection rule add`: Add parameters `--destination-fqdns` and `--translated-fqdn`
* `az network firewall policy rule-collection-group collection rule update`: Add parameters `--destination-fqdns` and `--translated-fqdn`
The precondition is to put your code …
> [Firewall] create a Firewall Policy Network Rule with FQDNs

- src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
Exclude the test case `test_aks_create_edge_zone` which always fails for acs.
> {AKS} Exclude case `test_aks_create_edge_zone` for acs

- src/cosmosdb-preview/HISTORY.rst
- src/cosmosdb-preview/azext_cosmosdb_preview/custom.py
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_managed_cassandra_cluster_without_datacenters.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_managed_cassandra_verify_lists.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/test_cosmosdb-cassandrami_scenario.py
- src/cosmosdb-preview/setup.py
cli extension module version 0.8.0 introduced regression because of python sdk update. It is being fixed in this PR.
> [CosmosDB] Managed Cassandra Hotfix

- src/index.json
> IoT Extension release v0.10.15

- src/index.json
> Updating azure-ml-cli version (1.33.0)

- src/service_name.json
> fixed TOC entries to consolidate into Azure services

- src/virtual-wan/HISTORY.rst
- src/virtual-wan/azext_vwan/custom.py
- src/virtual-wan/setup.py
Closed https://github.com/Azure/azure-cli-extensions/issues/2982
Closed https://github.com/Azure/azure-cli-extensions/issues/3775
---
> [VirtualWan] Fix ipsec_polices is NoneType

- src/vmware/setup.py
> publish vmware 3.1.0

- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml
Update recording files source location.
> {AKS} Update recording files source location

- src/virtual-wan/HISTORY.rst
- src/virtual-wan/azext_vwan/custom.py
- src/virtual-wan/setup.py
Closed https://github.com/Azure/azure-cli-extensions/issues/3837
---
> [Virtual Wan] Fix some command don't migrate to track2

- src/service_name.json
> [Reference TOC] removed ml(v1) entry

- src/webpubsub/HISTORY.rst
- src/webpubsub/azext_webpubsub/_params.py
- src/webpubsub/azext_webpubsub/client.py
- src/webpubsub/setup.py
> az webpubsub: Add argument `--user-id` to command: `az webpubsub client start`

- src/aks-preview/HISTORY.md
- src/aks-preview/setup.py
> release aks-preview 0.5.30

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/_utils.py
- src/connectedk8s/azext_connectedk8s/custom.py
- src/connectedk8s/setup.py
> Increase helm install and upgrade timeout

- src/index.json
Release notes for this version can be found here:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.16
Also removes v0.10.13 from the index.
---
> [IoT] IoT Extension Release v0.10.16

- src/index.json
Release notes here:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.17
---
> [IoT] IoT Extension Release v0.10.17

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
> Update version and history info for 'az quantum' extension 0.8.0

- src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
> {AKS} Exclude several test cases which need feature registration

- src/aks-preview/azext_aks_preview/custom.py
Current:
This node image upgrade operation will run across every node pool in the clusterand might take a while, do you wish to continue
Proposed:
This node image upgrade operation will run across every node pool in the cluster and might take a while. Do you wish to continue
---
> Missing space when concat the msg lines, sentence too long

- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/deploymentyaml/aks-periscope.yaml
This PR fixes this open workitem for `cli` details under #3766 
Previously the code use to form `containerName` after the `kubectl` command was run, now it is formed earlier and then supplied through.
Thanks,
cc: @rzhang628 and @qpetraroia 
---
> [AKS] Handle containerName passing and edge case for containerName.

- src/index.json
---
chore(arcdata): version bump to 1.1.1
> chore(arcdata): version bump to 1.1.1

- src/webpubsub/HISTORY.rst
- src/webpubsub/azext_webpubsub/_client_factory.py
- src/webpubsub/azext_webpubsub/_exception_handler.py
- src/webpubsub/azext_webpubsub/_help.py
- src/webpubsub/azext_webpubsub/_params.py
- src/webpubsub/azext_webpubsub/_validator.py
- src/webpubsub/azext_webpubsub/client.py
- src/webpubsub/azext_webpubsub/commands.py
- src/webpubsub/azext_webpubsub/custom.py
- src/webpubsub/azext_webpubsub/service.py
- src/webpubsub/azext_webpubsub/tests/latest/recordings/test_webpubsub.yaml
- src/webpubsub/azext_webpubsub/tests/latest/test_webpubsub_scenario.py
- src/webpubsub/setup.py
* Add `az webpubsub list-usage`
* Add `az webpubsub list-skus`
* Sending event in `az webpubsub client start` returns result.
* Follow the return value guidance that returns a dictionary rather than bool in check existence operation like `webpubsub service connection exist`
* Some description and help update
---
> [WebPubSub] Some update on az webpubsub

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/_params.py
- src/spring-cloud/azext_spring_cloud/custom.py
- src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/v2021_09_01_preview/models/__init__.py
- src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/v2021_09_01_preview/models/_models.py
- src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/v2021_09_01_preview/models/_models_py3.py
- src/spring-cloud/setup.py
…eployment_create in spring-cloud
---
> Support new argument --disable-probe for app_create, app_update, and deployment_create in spring-cloud

- src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
---
Fix env setup in test pipelines.
> {AKS} Fix env setup in test pipelines

- src/aks-preview/azext_aks_preview/decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
- Refactor the implementation of option --snapshot-id in `aks create`
> "covered_lines": 448,
> "num_statements": 474,
> "percent_covered": 94.51476793248945,
> "missing_lines": 26,
> "excluded_lines": 0
> Refactor the implementation of option --snapshot-id in `aks create`

- src/rdbms-connect/HISTORY.rst
- src/rdbms-connect/azext_rdbms_connect/commands.py
- src/rdbms-connect/setup.py
---
following up with https://github.com/Azure/azure-cli-extensions/pull/4008
Need to GA and release new version. 
> [rdbms-connect] GA Mysql commands 

- src/aks-preview/azext_aks_preview/azext_metadata.json
- src/aks-preview/azext_aks_preview/commands.py
- src/aks-preview/azext_aks_preview/custom.py
---
Align the following commands with azure-cli.
- `aks browse`: take the implementation from azure-cli, and update the min cli version (azext_metadata.json).
- `aks show`: already implemented in aks-preview.
- `aks list`: already omitted in aks-preview, would fall back to the implementation in azure-cli.
- `aks get-versions`: remove the duplicated implementation in aks-preview, which would fall back to the implementation in azure-cli.
The precondition is to put your code inside this …
> {AKS} Align the implementation of several commands with azure-cli

- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
- Add unit tests for aks create in decorator pattern
- Clean up import in custom.py
- "covered_lines": 447,
- "num_statements": 453,
- "percent_covered": 98.67549668874172,
- "missing_lines": 6,
- "excluded_lines": 0
> {AKS} Add unit tests for aks create in decorator pattern

- src/index.json
- src/service_name.json
> Add azurestackhci cli extension

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/custom.py
- src/spring-cloud/setup.py
> [spring cloud] fix list service by subscription

- src/acrtransfer/HISTORY.rst
- src/acrtransfer/azext_acrtransfer/__init__.py
- src/acrtransfer/azext_acrtransfer/_format.py
- src/acrtransfer/azext_acrtransfer/_help.py
- src/acrtransfer/azext_acrtransfer/_params.py
- src/acrtransfer/azext_acrtransfer/_validators.py
- src/acrtransfer/azext_acrtransfer/commands.py
- src/acrtransfer/azext_acrtransfer/custom.py
- src/acrtransfer/azext_acrtransfer/exportpipeline.py
- src/acrtransfer/azext_acrtransfer/importpipeline.py
- src/acrtransfer/azext_acrtransfer/pipelinerun.py
- src/acrtransfer/setup.py
- src/service_name.json
Change log:
- Add: New command acr pipeline-run clean - Bulk deletes failed pipeline-runs.
- Add: New parameter to acr pipeline-run list --top - Displays only the n most recent pipeline-runs.
- Bug fix:  ResourceNotFoundError will now be thrown if the resource does not exist when calling import-pipeline delete and export-pipeline delete.
- Bug fix: Help text typos fixed.
- Style change: Changed from distutils logger to knock.log logger.
- Style change: General style fixes to conform to latest azdev style output.
---
Once your PR is merged into master branch, a new PR will be created to update …
> [acrtransfer] acrtransfer extension v1.1 release

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/addonconfiguration.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/setup.py
> change dcr resource naming convention used in aks monitoring addon

- src/index.json
chore(arcdata): version bump v1.1.2
> chore(arcdata): version bump v1.1.2

- src/index.json
> [Release] ml 2.0.3 public preview release

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_management_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_policy_update_premiumonlyproperty_issue.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
- src/azure-firewall/setup.py
closed https://github.com/Azure/azure-cli-extensions/issues/4096
---
> [Azure Firewall] Fix a bug that will raise an error due to updating premium only property on standard policy

- src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
---
Update default test matrix for acs module in azure-cli to remove several previously excluded test cases.
> {AKS} Update default test matrix for acs module in azure-cli

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
> Update version and history info for 'az quantum' extension 0.10.0

- src/connectedvmware/HISTORY.rst
- src/connectedvmware/azext_connectedvmware/vmware_utils.py
- src/connectedvmware/setup.py
> Fixed inventory item issue in connectedvmware az cli extension.

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_snapshot.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/setup.py
Remove snapshot name trimming in 'az aks snapshot create' command
> {AKS} Remove snapshot name trimming in 'az aks snapshot create' command

- src/rdbms-connect/azext_rdbms_connect/commands.py
> [rdbms-connect] remove preview tag for postgresql

- src/aks-preview/azcli_aks_live_test/scripts/test_cli_live.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_cli_unit.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_ext_live.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_ext_unit.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_raw_cases.sh
- src/aks-preview/azcli_aks_live_test/scripts/transcribe_env.sh
---
Update live test pipeline.
> {AKS} Update live test pipeline

- src/index.json
> Arc Appliance Public Preview Extension Version 0.2.11

- src/index.json
> [Release] Update index.json and fix conflicts for azclibot-release-20211203 072122

- src/index.json
- src/service_name.json
> [Release] Update index.json for extension [ azurestackhci ] 

- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
- Refactor updating enable/disable pod security policy.
- "covered_lines": 501,
- "num_statements": 503,
- "percent_covered": 99.6023856858847,
- "missing_lines": 2,
- "excluded_lines": 21
> {AKS} Refactor 1st part of the update sub-command in aks-preview module

- src/rdbms-connect/HISTORY.rst
- src/rdbms-connect/azext_rdbms_connect/commands.py
- src/rdbms-connect/setup.py
> [rdbms-connect] Updated version for commands GA

- src/index.json
> ML v1 extension support for MSAL

- linter_exclusions.yml
- src/index.json
chore(arcdata): version bump to 1.1.3
> chore(arcdata): version bump to 1.1.3

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/_validators.py
- src/vm-repair/setup.py
> [vm-repair] Bug fix 

- src/aks-preview/azext_aks_preview/_loadbalancer.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py
---
- Refactor updating nat-gateway profile.
- Refactor the getter functions of dual stack related load balancer parameters.
- Sort out load balancer related test cases.
> "covered_lines": 578,
> "num_statements": 580,
> "percent_covered": 99.65517241379311,
> "missing_lines": 2,
> "excluded_lines": 21
> {AKS} Refactor 3rd part of the update sub-command in aks-preview module

- src/spring-cloud/HISTORY.md
- src/spring-cloud/README_CONTAINER.md
- src/spring-cloud/azext_spring_cloud/_help.py
- src/spring-cloud/azext_spring_cloud/_params.py
- src/spring-cloud/azext_spring_cloud/_utils.py
- src/spring-cloud/azext_spring_cloud/custom.py
- src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_app_deploy_container.yaml
- src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_scenario.py
- src/spring-cloud/setup.py
> feat: Support the customized container

- src/aks-preview/azext_aks_preview/_podidentity.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_pod_identity_helpers.py
---
- Refactor updating pod identity profile.
- Move pod identity related internal functions to a separate `_podidentity.py` file.
- Sort out imports in `custom.py`.
> "covered_lines": 600,
> "num_statements": 602,
> "percent_covered": 99.66777408637874,
> "missing_lines": 2,
> "excluded_lines": 21
---
Changes after code review:
- Add mutual exclusion check for `enable_pod_identity` and `disable_pod_identity`.
- Extract the verification pod identity with kubenet as an independent function.
- Use `SimpleNamespace` to store pod identity models and use the `@property` decorator to avoid overwriting.
There is a pipeline to automatically build, upload and publish …
> {AKS} Refactor 4th part of the update sub-command in aks-preview module

- src/aks-preview/azext_aks_preview/decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/mocks.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
- Complete the update decorator.
- Overwrite `check_raw_parameters` to replace hard-coded error message.
- Fix validation between `enable_pod_identity` and `enable_managed_identity`.
- Update mocks.
> "covered_lines": 636,
> "num_statements": 638,
> "percent_covered": 99.68652037617555,
> "missing_lines": 2,
> "excluded_lines": 21
> {AKS} Refactor 5th part of the update sub-command in aks-preview module

- src/spring-cloud/azext_spring_cloud/api_portal.py
---
Add implementation of API portal update, show, clear, API portal custom-domain show, list, update, unbind.
> [Spring Cloud] Add API portal related commands implementation

- src/aks-preview/azext_aks_preview/azext_metadata.json
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/decorator.py
---
Update the implementation of `aks update` to adopt the decorator pattern.
> {AKS} Update the implementation of `aks update` to adopt the decorator pattern

- src/index.json
---
Update the hotfix release for this #4273 manually. 
It's built and uploaded separately since the latest changes on the main branch aren't expected to publish this time.
> [Spring Cloud] Update index manually for a hotfix.

- src/aks-preview/azext_aks_preview/_completers.py
- src/aks-preview/azext_aks_preview/_helpers.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/addonconfiguration.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_helpers.py
---
- Remove most hard-coded api versions.
- Remove unused code and related test cases.
> {AKS} Remove most hard-coded api versions

- linter_exclusions.yml
- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.12.1
---
> [IoT] IoT Extension release v0.12.1

- src/storage-preview/HISTORY.rst
- src/storage-preview/setup.py
> {storage-preview} Update version

- src/spring-cloud/azext_spring_cloud/custom.py
> Make cli zone redundant property in patch be none

- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Fix regex used to check node image version, which used to only check for 2021.
> {AKS} Fix regex used to check node image version

- src/spring-cloud/azext_spring_cloud/_transformers.py
> Fix certificate list output error

- src/logic/HISTORY.rst
- src/logic/azext_logic/tests/latest/recordings/test_logic.yaml
- src/logic/azext_logic/tests/latest/test_logic_scenario.py
- src/logic/azext_logic/vendored_sdks/logic/models/__init__.py
- src/logic/setup.py
Fix the deserialization errors for the commands `az logic workflow show` and `az logic workflow list`.
Related issues are reported as below:
https://github.com/Azure/azure-cli/issues/21034
https://github.com/Azure/azure-cli/issues/21035
https://github.com/Azure/azure-cli/issues/21036
https://github.com/Azure/azure-cli/issues/21037
https://github.com/Azure/azure-cli/issues/19230
https://github.com/Azure/azure-cli/issues/18302
Root cause: The SDK is incomplete due to missing some model import.
---
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` …
> [Logic] Upgrade SDK to fix deserialization errors

- src/datamigration/setup.py
> [link]Change link in datamigration setup file

- src/rdbms-connect/HISTORY.rst
- src/rdbms-connect/azext_rdbms_connect/azext_metadata.json
- src/rdbms-connect/setup.py
> [rdbm-connect] Add rdbms-connect to cloud shell

- src/spring-cloud/azext_spring_cloud/_validators_enterprise.py
> fix: fix builder validator

- linter_exclusions.yml
- src/index.json
---
chore(arcdata): arcdata version bump to 1.2.0
> chore(arcdata): arcdata version bump to 1.2.0

- src/image-copy/HISTORY.rst
- src/image-copy/azext_imagecopy/create_target.py
- src/image-copy/azext_imagecopy/custom.py
- src/image-copy/azext_imagecopy/tests/latest/recordings/test_image_copy.yaml
- src/image-copy/azext_imagecopy/tests/latest/test_image_copy_commands.py
- src/image-copy/setup.py
- src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query.yaml
Fix the issue that the hyper_v_generation is always V1 when copying the image.
---
> [Image Copy] Fix the hyper_v_generation of image copy

- src/index.json
> Update ml extension to version 2.0.7
