- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_snapshot.yaml
> [AKS] Remove is_preview from snapshot related commands

- src/index.json
> Release 0.23.0 for azure dev ops

- src/aks-preview/setup.py
---
- Add yaml file to package data.
- Format `setup.py`.
This should fix issue [#148](https://github.com/Azure/aks-periscope/issues/148).
> {AKS} Add yaml file to package data

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_outbound_ips.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_update_taints_msi.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
> Fix test: change to use soft taint on system pool in test

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_ipv6_count.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Remove hardcoded k8s version in test case `test_aks_create_and_update_ipv6_count`.
> {AKS} Remove hardcoded k8s version in test case `test_aks_create_and_update_ipv6_count`

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/custom.py
- src/vm-repair/setup.py
> [Vm-repair] preview script bug fix

- src/spring-cloud/azext_spring_cloud/_validators_enterprise.py
- src/spring-cloud/azext_spring_cloud/gateway.py
---
We need to clear the value of parameters like --scope '""' --client-id '""', just check if string is empty will not clear those properties.
> [Spring Cloud] Add clear for sso & cors  properties

- src/alertsmanagement/HISTORY.rst
- src/alertsmanagement/azext_alertsmanagement/_help.py
- src/alertsmanagement/azext_alertsmanagement/_params.py
- src/alertsmanagement/setup.py
1. help file fix
2. removed redundant import from typing_extension
---
> AlertsManagement-CLI-GA-Fixes

- src/aks-preview/azext_aks_preview/_natgateway.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/_podidentity.py
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/azext_metadata.json
- src/aks-preview/azext_aks_preview/decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_dualstack_with_default_network.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_natgateway.py
- src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
---
- Remove `validate_cluster_autoscaler_profile` and its related test cases
-  We validate this parameter in the getter function now. Depends on **core cli version >= 2.32.0**.
- Use `SimpleNamespace` to wrap nat gateway related models instead of dictionary.
- Remove useless `**kwargs` in getter functions.
- Remove hardcoded k8s version in test case `test_aks_create_dualstack_with_default_network`.
The precondition is to put your code inside this repo and upgrade the version in the PR …
> {AKS} Clean up some deprecated code

- src/spring-cloud/azext_spring_cloud/_buildservices_factory.py
- src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app.py
> fix: add runtime version in build

- src/index.json
---
WI: https://msazure.visualstudio.com/AzureArcPlatform/_queries/query/22f18f13-1727-4d68-9c62-3b225db7e791/
> [Release] Add Arc Appliance Extension 0.2.15

- src/service_name.json
> TOC - fixed Azure service names

- src/aks-preview/azcli_aks_live_test/configs/cli_coverage_config.json
- src/aks-preview/azcli_aks_live_test/configs/ext_coverage_config.json
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
- Format unit tests.
- Add test case for `host_group_id`.
- Remove read only property setting for oidc issuer.
- Update unit test coverage configuration.
> {AKS} Update unit test coverage configuration

- src/index.json
> AzureML CLI patch release 2.1.2

- src/aks-preview/HISTORY.md
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/data/motd.txt
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_add_nodepool_with_motd.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
- src/aks-preview/setup.py
> add message of the day for aks agentpools

- src/index.json
---
Resolve conflicts from #4453
> Resolve conflicts for appservice-kube index.json

- src/index.json
---
chore(arcdata): arcdata version bump to 1.2.2
> chore(arcdata): arcdata version bump to 1.2.2

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
> Update version and history info for 'az quantum' extension 0.13.0

- src/index.json
> [Release] Add Arc Appliance Extension 0.2.16

- src/index.json
Reverts Azure/azure-cli-extensions#4501
> Revert "chore(arcdata): arcdata version bump to 1.2.3"

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ingress_appgw_addon.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ingress_appgw_addon_with_deprecated_subet_prefix.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_update_taints_msi.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
Fix several test cases.
- `test_aks_nodepool_update_taints_msi`, the model conversion error has been fixed in rp and released.
- `test_aks_create_with_ingress_appgw_addon`, the default vnet/subnet cidr has been changed in rp v20220303.
- `test_aks_create_with_ingress_appgw_addon_with_deprecated_subet_prefix`, same as above.
> {AKS} Fix several test cases

- src/ssh/azext_ssh/ip_utils.py
> [SSH] Bug Fix: Using Private IP when --prefer-private-ip is not provided fails

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/azext_metadata.json
- src/connectedk8s/setup.py
> Min cli core versions update

- src/datamigration/azext_datamigration/manual/_help.py
- src/datamigration/azext_datamigration/manual/_params.py
- src/datamigration/azext_datamigration/manual/custom.py
> DataMigration: Fixing typo in Performance Data collection command

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/_utils.py
- src/connectedk8s/azext_connectedk8s/azext_metadata.json
- src/connectedk8s/azext_connectedk8s/custom.py
- src/connectedk8s/setup.py
> Remove "packaging" module since 2.16.0 doesn't support it

- src/alertsmanagement/HISTORY.rst
- src/alertsmanagement/azext_alertsmanagement/_validators.py
- src/alertsmanagement/setup.py
> Alerts management contains operator support for resource type condition

- src/index.json
> Release 0.24.0

- .github/CODEOWNERS
---
Update owners of aks-preview.
> {AKS} Update owners of aks-preview

- src/aks-preview/azext_aks_preview/decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
Fix validation for kms options.
> {AKS} Fix validation for kms options

- src/index.json
Release notes for this extension version can be found here:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.14.0
---
> [IoT] IoT Extension Release v0.14.0

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
> Update version and history info for 'az quantum' extension 0.14.0

- src/index.json
> Release ArcAppliance 0.2.18

- .github/CODEOWNERS
Add @necusjz for some extensions' owner
---
> {Code Owner} Add @necusjz for some extensions' owner

- src/index.json
> Add az ml version 2.2.1

- src/index.json
---
chore(arcdata): arcdata version bump to 1.3.0
> chore(arcdata): arcdata version bump to 1.3.0

- src/index.json
> Azure ML CLI v2 extension patch release 2.2.2

- src/securityinsight/HISTORY.rst
- src/securityinsight/azext_sentinel/manual/_help.py
- src/securityinsight/azext_sentinel/tests/latest/recordings/test_sentinel.yaml
- src/securityinsight/setup.py
> [Sentinel] Rebrand the terms in help for Sentinel

- src/aks-preview/setup.py
> update setup.py for aks-extension

- src/index.json
> Support for python 3.10 in ML extension

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/api_portal.py
- src/spring-cloud/azext_spring_cloud/application_configuration_service.py
- src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_persistent_storage.yaml
- src/spring-cloud/setup.py
> [Spring Cloud]fix api portal sso clear and acs update

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
Release PR for az quantum extension, version 0.15.0.
---
> [Quantum] Update version and history info for az quantum extension 0.15.0

- src/aks-preview/azext_aks_preview/_consts.py
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
- Fix test `test_aks_update_with_workload_identity` with custom header.
- Sort out parameter declaration.
> {AKS} Fix test with custom header and sort out parameter declaration

- src/account/HISTORY.rst
- src/account/azext_account/azext_metadata.json
- src/account/azext_account/generated/commands.py
- src/account/setup.py
---
GA of "az account alias" https://github.com/Azure/azure-cli/issues/21937
close https://github.com/Azure/azure-cli/issues/21937
> [Account] `az account alias`: GA release

- src/scvmm/setup.md
Since git.io is deprecated https://github.blog/changelog/2022-04-25-git-io-deprecation/
updating the reference to it :
Old link: curl -L https://git.io/n-install | bash -s -- -y lts
New Link: curl -L https://bit.ly/n-install | bash -s -- -y lts
---
Fixes #4749
> {scvmm} Fixes Azure/azure-cli-extensions#4749

- linter_exclusions.yml
- src/index.json
chore(arcdata): arcdata version bump to 1.4.0
> chore(arcdata): arcdata version bump to 1.4.0

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.14.1
---
> [IoT] IoT Extension Release v0.14.1

- .github/PULL_REQUEST_TEMPLATE.md
> [Template] Change master branch to main branch in pr template

- src/logic/HISTORY.rst
> {Logic} Fix syntax error in HISTORY.rst

- src/cosmosdb-preview/HISTORY.rst
> [CosmosDB] Modify latest version description

- src/index.json
> [Release] ArcAppliance 0.2.21

- src/index.json
---
- [] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).
> Update ML CLI v1 extension to allow setting v1LegacyMode values

- src/subscription/HISTORY.rst
- src/subscription/setup.py
> [Subscription] Release new version and add HISTORY.rst file

- src/spring/setup.py
> Update spring initial version in setup.py

- src/aks-preview/HISTORY.rst
---
Update history.rst to fix syntax errors.
> {AKS} Update history.rst to fix syntax errors

- src/cosmosdb-preview/azext_cosmosdb_preview/_help.py
> Add cosmos DB sample links to long-summary

- src/index.json
> Updating ML extension to use latest public preview for SDKv2

- linter_exclusions.yml
- src/index.json
chore(arcdata): version bump to 1.4.1
> chore(arcdata): version bump to 1.4.1

- src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_standard_csi_drivers.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
- Filter cli test cases
- test_aks_create_with_defender
- test_aks_update_with_defender
- Fix test case `test_aks_create_with_standard_csi_drivers`
> {AKS} Update test cases

- src/aks-preview/setup.py
---
Update `setup.py` to release aks-preview 0.5.72
> {AKS} Release aks-preview 0.5.72

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/setup.py
---
Fix import issues for aks draft commands.
> {AKS} Fix import issues for aks draft commands

- src/index.json
> Hotfix ML extension for addressing endpoint issues

- src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
---
Filter out the app gateway case `test_aks_byo_appgw_with_ingress_appgw_addon` from both azure-cli/acs and azure-cli-extensions/aks-preview.
> A few days ago, the network module in azure-cli updated the SDK and the default API version to 2021-08-01. Some changes (by PR [[Network] Update application gateway by ZengTaoxu · Pull Request #22489 · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/pull/22489)) caused the failure of the following test case test_aks_byo_appgw_with_ingress_appgw_addon([azure-cli/test_aks_commands.py at dev · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/tests/latest/test_aks_commands.py …
> {AKS} Filter app gateway case

- src/spring/azext_spring/_buildservices_factory.py
- src/spring/azext_spring/tests/latest/test_asa_app.py
> [Spring] update the app name used in build to app name and deployment name

- src/spring/setup.py
> [Spring] GA Enterprise tier

- src/scheduled-query/azext_scheduled_query/_help.py
- src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query.yaml
---
Fix: https://github.com/Azure/azure-cli/issues/22718
> [monitor] Fix: #22718 `az monitor scheduled-query create` incorrect column reference in the example

- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
> {AKS} Update v2 managed cluster decorator - part 4

- src/aks-preview/azext_aks_preview/_helpers.py
- src/aks-preview/azext_aks_preview/aks_diagnostics.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_diagnostics.py
- src/aks-preview/azext_aks_preview/tests/latest/test_helpers.py
@FumingZhang - we discussed shuffling some code around to make it more amenable to unit testing, using the `draft` folder structure as an example.
~~Opening this as a draft so you can tell me if it's roughly what you were thinking, before I spend more time adding tests for it.~~
**EDIT**: Moved out of draft state after discussion with @zhoxing-ms and @FumingZhang.
Suggestions about where to place test file would be most welcome!
cc: @zhoxing-ms 
---
The precondition is …
> Move AKS diagnostics commands to their own folder

- src/index.json
> ML extension release 2.5.0

- src/containerapp/azext_containerapp/_params.py
Fixes https://github.com/Azure/azure-cli/issues/22914
---
> {containerapp} Fixed logs-workspace-id description

- src/spring/HISTORY.md
- src/spring/azext_spring/_params.py
- src/spring/azext_spring/commands.py
> [Spring Cloud] Remove preview tag for Spring Cloud Gateway and API portal

- src/aks-preview/HISTORY.rst
- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
- src/aks-preview/setup.py
---
- Update default test case matrix.
- Add `test_aks_create_with_azurekeyvaultkms` and `test_aks_update_with_azurekeyvaultkms` back.
- Filter out `test_aks_create_with_azurekeyvaultkms_private_key_vault` and `test_aks_update_with_azurekeyvaultkms_private_key_vault` by default.
- Fix test case `test_aks_create_web_application_routing_dns_zone_not_exist`.
- Fix KMS properties missing in update scenario.
The precondition is to put your code inside this …
> {AKS} Fix KMS properties missing in update scenario

- src/index.json
> ArcAppliance June Release 0.2.24

- src/aks-preview/HISTORY.rst
- src/aks-preview/setup.py
---
Release aks-preview 0.5.85.
> {AKS} Release aks-preview 0.5.85

- src/quantum/azext_quantum/tests/latest/source_for_build_test/NuGet.config
---
Fix pipeline task `Secure Supply Chain Analysis`
> {quantum} add clear in NuGet.config

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.15.0
---
> [IoT] IoT Extension Release v0.15.0

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
Release PR for az quantum extension, version 0.16.0.
---
> [Quantum] Update version and history info for az quantum extension 0.16.0

- .github/fabricbot.json
Please merge this PR after we switch to milestone Jul 2022 (2022-08-02).
> {CI} Update milestone from Jun 2022 (2022-07-05) to Jul 2022 (2022-08-02)

- src/spring/azext_spring/_help.py
> [spring] Fix source-code and jar deploy examples in help.py

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_overlay_network_plugin_mode.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Signed-off-by: Tyler Lloyd <tyler.lloyd@microsoft.com>
---
> {AKS} add live test for azure cni overlay

- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Add test for virtual node addon in `aks addon list`. Also fix the issue again. Patch PR [#5099](https://github.com/Azure/azure-cli-extensions/pull/5099).
`az aks addon list`
> {AKS} Add test for virtual node addon in `aks addon list`

- src/index.json
> {AKS} Resolve release conflict for aks-preview

- src/aks-preview/HISTORY.rst
- src/aks-preview/setup.py
> {AKS} Release new version 0.5.91 for aks-preview

- src/index.json
> 2.6.1 v2 CLI Release

- src/index.json
chore(arcdata): version bump to 1.4.4
---
> chore(arcdata): version bump to 1.4.4

- src/scheduled-query/HISTORY.rst
- src/scheduled-query/azext_scheduled_query/azext_metadata.json
- src/scheduled-query/azext_scheduled_query/grammar/scheduled_query/ScheduleQueryConditionLexer.py
- src/scheduled-query/azext_scheduled_query/grammar/scheduled_query/ScheduleQueryConditionListener.py
- src/scheduled-query/azext_scheduled_query/grammar/scheduled_query/ScheduleQueryConditionParser.py
- src/scheduled-query/azext_scheduled_query/grammar/scheduled_query/build_python.bat
- src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query.yaml
- src/scheduled-query/setup.py
> [Scheduled-query] Suppress warning from antlr 4.9.3

- src/functionapp/azext_functionapp/_params.py
Fixes https://github.com/Azure/azure-cli/issues/16323
---
> {FunctionApp} Fix #16323: Fix minor typo

- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
* Add test to rotate key for public cluster + public/private key vault
* Add test to create private cluster with private key vault, and rotate key
> {AKS} Refine tests for azurekeyvaultkms

- .github/fabricbot.json
> {CI} Update milestone from Jul 2022 (2022-08-02) to Aug 2022 (2022-09-06)

- text.txt
> {CI} Test auto merge

- src/index.json
> Add new ML Extension version 2.7.0

- text.txt
> {CI} Test auto commit

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/custom.py
- src/vm-repair/setup.py
- Small improvement to use Networking's latest get available ips from subnet command
---
- [V] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [V] Have you run `python scripts/ci/test_index.py -q` locally?
> VM Repair: Improve vm reset nic command

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_help.py
- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_basic_sku.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
- src/azure-firewall/setup.py
Resolves: https://github.com/Azure/azure-cli/issues/23429
"Basically, attaching a management IP configuration should only be possible one time, at firewall creation time, and it requires both types of ip-config in one PUT call."
"Azure Firewall has a management IP configuration set but no public IP configurations for data traffic."
---
az network firewall create
The precondition is to put your code inside this repository and upgrade the version in the pull request but …
> [Network] `az network firewall create`: Support Basic SKU creation with management IP configuration

- src/index.json
> [ML] Update index for v2.7.1

- linter_exclusions.yml
- src/index.json
Version release to add ADU dataplane support.
Notes for this release:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.17.0
---
> [IoT] IoT Extension Release v0.17.0

- src/index.json
> Release ArcAppliance 0.2.26 [August Release]

- src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
- src/aks-preview/azext_aks_preview/_help.py
---
- Filter out one gpu test case `test_aks_nodepool_add_with_gpu_instance_profile`.
- Fix help message.
> {AKS} Filter out one gpu test case

- src/aks-preview/HISTORY.rst
- src/aks-preview/README.rst
- src/aks-preview/azext_aks_preview/azext_metadata.json
---
Update min cli core version to `2.38.0` due to latest SDK requires a newer version `azure.core`.
> {AKS} Update min cli core version to 2.38.0

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/azext_metadata.json
- src/connectedk8s/azext_connectedk8s/custom.py
- src/connectedk8s/setup.py
> Update minimum az cli core version

- .github/fabricbot.json
> {CI} Update milestone from Aug 2022 (2022-09-06) to Sep 2022 (2022-10-12) - For Ignite

- src/aks-preview/HISTORY.rst
- src/aks-preview/setup.py
> {AKS} Release aks-preview

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_helpers.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_apiserver_vnet_integration_public.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
- src/aks-preview/linter_exclusions.yml
- src/aks-preview/setup.py
> AKS: support apiserver-vnet-integration for public cluster

- src/aks-preview/HISTORY.rst
> {AKS} Update release history

- src/index.json
Release notes for this extension version can be found here:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.17.1
---
> [IoT] IoT Extension Release v0.17.1

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/setup.py
---
Remove unused import to avoid failure in Python3.6, see issue [#5303](https://github.com/Azure/azure-cli-extensions/issues/5303).
> {AKS} Remove unused import to avoid failure in Python3.6

- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_image_cleaner_enabled_with_default_interval_hours.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_image_cleaner_enabled_with_interval_hours.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_image_cleaner.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
> {AKS} remove image cleaner testing exceptions

- src/spring/HISTORY.md
- src/spring/azext_spring/_build_service.py
- src/spring/azext_spring/_client_factory.py
- src/spring/azext_spring/_help.py
- src/spring/azext_spring/commands.py
- src/spring/azext_spring/tests/latest/recordings/test_Builder.yaml
- src/spring/azext_spring/tests/latest/test_asa_build_service_builder_scenario.py
- src/spring/setup.py
> add new command to list deployments under the builder

- src/communication/HISTORY.rst
- src/communication/azext_communication/manual/custom.py
- src/communication/azext_communication/tests/latest/recordings/test_chat_delete_message.yaml
- src/communication/azext_communication/tests/latest/test_communication_chat_scenario.py
- src/communication/setup.py
> [Communication] fix 'chat message delete' bug

- src/index.json
> Added ArcAppliance Sept Release

- src/spring/azext_spring/gateway.py
---
Not to upgrade version since we have several PRs for this version. In the last PR, will upgrade the version.
az spring gateway route-config update
> [Spring Apps] Fix spring cloud gateway route config

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_params.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_management_ip_config.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_firewall_policy.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_firewall_policy_premium.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_basic_sku.yaml
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_with_additional_log.yaml
- src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
- src/azure-firewall/setup.py
Resolves: https://github.com/Azure/azure-cli/issues/23758
---
az network firewall create
az network firewall update
> [Azure Firewall]  `az network firewall`: Add parameter `--udp-log-optimization`

- src/init/azext_init/_help.py
---
Issue: https://github.com/Azure/azure-cli/issues/23283
> [init] Refine long-summary for `az init`

- src/cosmosdb-preview/azext_cosmosdb_preview/custom.py
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_dts.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_gremlin_account_restore_command.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_gremlin_account_restore_using_create.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_gremlin_graph_backupinfo.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_gremlin_restorable_commands.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_mongo_role.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_mongodb_collection_adaptiveru.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_mongodb_collection_backupinfo.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_mongodb_collection_merge.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_sql_container_adaptiveru.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_sql_container_backupinfo.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_sql_container_merge.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_sql_continuous30days.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_sql_continuous7days.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_sql_migrate_periodic_to_continuous7days.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_sql_oldestRestorableTime.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_table_account_restore_command.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_table_account_restore_using_create.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_table_backupinfo.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_table_restorable_commands.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_managed_cassandra_cluster_without_datacenters.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_managed_cassandra_verify_lists.yaml
- src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/test_cosmosdb_sql_adaptiveru_scenario.py
> Update extension for managed identity

- src/account/HISTORY.rst
- src/account/azext_account/azext_metadata.json
- src/account/setup.py
> {Account} Update min cli core version from `2.3.1` to `2.38.0`

- src/index.json
> ML extension:2.8.0 for azure-ai-ml 0.1.0b7

- src/spring/HISTORY.md
- src/spring/azext_spring/_params.py
- src/spring/azext_spring/commands.py
- src/spring/setup.py
> feat(App MI GA): Remove Preview tag for commands related to user-assigned identities

- .github/fabricbot.json
> {CI} Update milestone from Sep 2022 (2022-10-12) - For Ignite to Oct 2022 (2022-11-01)

- src/cosmosdb-preview/azext_cosmosdb_preview/_params.py
> [CosmosDB] GA mongo server version

- src/index.json
> Add ml extension version 2.9.0

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_vpa.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_or_update_with_load_balancer_backend_pool_type.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
> {AKS} Fix 2 preview features test cases

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_outbound_ips.yaml
> {AKS} Update recording to fix nrp API version bump

- src/index.json
> Add ml extension 2.10.0

- linter_exclusions.yml
- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.17.3
---
> [IoT] IoT Extension Release v0.17.3

- src/index.json
---
chore(arcdata): version bump to 1.4.7
> chore(arcdata): version bump to 1.4.7

- src/index.json
> [Scenario Guide] Delete index of scenario-guide

- src/scenario-guide/HISTORY.rst
- src/scenario-guide/setup.py
> [Scenario Guide] Fix package name in setup.py

- src/index.json
> Remove reservation

- src/reservation/HISTORY.rst
- src/reservation/setup.py
> release version 0.2.0

- .github/fabricbot.json
> {CI} Add extension Serial-Console to fabric bot

- src/index.json
- src/service_name.json
> Added hybridaks whl file in index.json for public preview

- src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml
---
{AKS} Update pipeline settings
> {AKS} Update pipeline settings

- .github/fabricbot.json
> {CI} Update milestone from Oct 2022 (2022-11-01) to Nov 2022 (2022-12-06)

- src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
---
{AKS} Update venv setup for aks live test pipelines.
> {AKS} Update venv setup for aks live test pipelines

- src/aks-preview/HISTORY.rst
- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
- src/aks-preview/azext_aks_preview/_consts.py
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_loadbalancer.py
- src/aks-preview/azext_aks_preview/_natgateway.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_outbound_from_slb_to_natgateway.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
- src/aks-preview/setup.py
Signed-off-by: MartinForReal <fanshangxiang@gmail.com>
---
> {AKS} add --outbound-type option in update command

- src/spring/HISTORY.md
- src/spring/azext_spring/spring_instance.py
- src/spring/setup.py
When waiting for the async operations, should throw exception when operation status is `Failed`.
---
az spring create 
> [Spring] fix(async operation status): Throw exception when operation status is Failed.

- linter_exclusions.yml
- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/download/v0.18.0/azure_iot-0.18.0-py3-none-any.whl
---
> [IoT] IoT Extension Release v0.18.0

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
`az aks update --enable-workload-identity`
> {AKS} Fix workload identity update error after oidc issure GA in azure-cli

- src/index.json
- src/service_name.json
Revert #5402 first as PM has some concerns about having a third party extension in az cli.
-	How do we know what the package is doing? How can we guarantee that it does not expose tokens since their PR is only adding a link to a download of a binary file?
-	How will this behave in other environments? What about the distribution in airgap clouds? 
-	For 1st party extensions we have IcM path, github contacts to handle issues, how do we handle issues related this extension? 
-	How does it fit under Cyber EO ? 
-	What about Terraform and PowerShell? 
---
Once your pull request is merged into main …
> [qbs] Revert pr-5402

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_outbound_from_slb_to_natgateway.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
- src/aks-preview/setup.py
---
Fix [#24430](https://github.com/Azure/azure-cli/issues/24430). Previously, in update code path, If the nodes in the nodepool of the existing cluster span multiple availability zones, the outbound type conversion related code will be touched unexpectedly.
- `az aks update`
> {AKS} `az aks update`: Fix command failure on changes not related to outbound type conversion

- src/spring/HISTORY.md
- src/spring/azext_spring/_params.py
- src/spring/azext_spring/_validators.py
- src/spring/azext_spring/_validators_enterprise.py
- src/spring/setup.py
Add warn when update Config Server or Application Configuration Service with SSH auth
---
- Config Server
- az spring config-server git repo add
- az spring config-server git repo update
- az spring config-server git  set
- az spring config-server set
- Application Configuration Service
- az spring application-configuration-service git repo add
- az spring application-configuration-service git repo update
The precondition is to put your code inside this repository and …
> Add warn when update Config Server or Application Configuration Service with SSH auth

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/agentpool_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
- src/aks-preview/setup.py
> [AKS] Fix NSG Control flags when creating agentpool

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_ssh_utils.py
- src/containerapp/azext_containerapp/custom.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_logs_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_eventstream.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_logstream.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_env_commands.py
- src/containerapp/setup.py
> [containerapp] `az containerapp logs/exec`: Fix "KeyError" Bug 

- src/index.json
chore(arcdata): version bump to v1.4.8
> chore(arcdata): version bump to v1.4.8

- src/index.json
Reverts Azure/azure-cli-extensions#5516
Need to revert due to an issue we hit with CCOA
> Revert "chore(arcdata): version bump to v1.4.8"

- linter_exclusions.yml
- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/agentpool_decorator.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_node_public_ip_tags.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/setup.py
---
az aks create --node-public-ip-tags
az aks nodepool add --node-public-ip-tags
> feat: support node public IP tags

- src/index.json
chore(arcdata): version bump to 1.4.8
> chore(arcdata): version bump to 1.4.8

- src/index.json
Release notes for this extension can be found here:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.18.1
---
> [IoT] Adds IoT Extension v0.18.1

- src/spring/azext_spring/_validators.py
- src/spring/azext_spring/spring_instance.py
> fix: update service name validation failure message

- azure-pipelines.yml
[Policy Check](https://policheck.microsoft.com/)
PoliCheck contains sensitive terms in over 100 languages and provides guidance to determine the appropriate action depending on context. 
The term data also provides explanations of why certain terms are sensitive or unacceptable.
> {CI} Add policy check to Security Tools

- src/aks-preview/azext_aks_preview/custom.py
> [AKS] remove a warning message

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_snapshot.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Reorder one step of aks_nodepool_snapshot recording test in order that it won't be affected by 22.04 switch over at k8s 1.25.2
---
> {AKS} Reorder one step of aks_nodepool_snapshot recording test in order that it won't be affected by 22.04 switch over at k8s 1.25.2

- src/index.json
> ArcAppliance November Release

- .github/fabricbot.json
> {CI} Update milestone from Nov 2022 (2022-12-06) to Dec 2022 (2023-01-03)

- src/keyvault-preview/HISTORY.rst
- src/keyvault-preview/azext_keyvault_preview/azext_metadata.json
- src/keyvault-preview/setup.py
> [keyvault-preview] Add min cli core version

- src/index.json
> Release for ml extension 2.12.0

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.18.2
---
> [IoT] Adds IoT Extension v0.18.2

- src/aks-preview/HISTORY.rst
- src/aks-preview/README.rst
- src/aks-preview/azext_aks_preview/azext_metadata.json
---
Bump dependency on azure-cli-core to 2.43.0 for aks-preview.
> {AKS} Bump dependency on azure-cli-core to 2.43.0

- src/spring/HISTORY.md
- src/spring/azext_spring/_help.py
- src/spring/azext_spring/_validators_enterprise.py
- src/spring/setup.py
> Add the validator for --build-env

- src/index.json
Notes for this release can be found here;
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.18.3
---
> [IoT] Adds IoT Extension v0.18.3

- src/cosmosdb-preview/HISTORY.rst
- src/cosmosdb-preview/azext_cosmosdb_preview/custom.py
- src/cosmosdb-preview/setup.py
> Fix restorable resources APIs

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
---
- Remove defender related code after GA, reuse the implementation in azure-cli/acs.
- May refer to PR [#23291](https://github.com/Azure/azure-cli/pull/23291) in azure-cli.
> {AKS} Remove defender related code after GA

- src/index.json
chore(arcdata): version bump 1.4.9
- [ x ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ x ] Have you run `python scripts/ci/test_index.py -q` locally?
> chore(arcdata): version bump 1.4.9

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
---
- Remove oidc issuer related code after GA, reuse the implementation in azure-cli/acs.
- May refer to PR [#24070](https://github.com/Azure/azure-cli/pull/24070) in azure-cli.
> {AKS} Remove OIDC Issuer related code after GA

- .github/fabricbot.json
> {CI} Update route rules: add `az dt` to azure-iot

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/agentpool_decorator.py
---
- Remove gpu instance profile related code after GA, reuse the implementation in azure-cli/acs.
- May refer to PR [#23501](https://github.com/Azure/azure-cli/pull/23501) in azure-cli.
> {AKS} Remove GPU instance profile related code after GA

- .github/fabricbot.json
1. Monitor issue assign to AllyW
2. Monitor PR add reviewer AllyW
> {CI} Adjust monitor rules

- src/connectedvmware/HISTORY.rst
- src/connectedvmware/azext_connectedvmware/custom.py
- src/connectedvmware/setup.py
Wait for SystemAssigned Identity PATCH to complete before enabling Guest management on VM
---
> Bug Fix: Wait for LRO before enabling GuestManagement

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/_params.py
- src/vm-repair/azext_vm_repair/_validators.py
- src/vm-repair/azext_vm_repair/custom.py
- src/vm-repair/azext_vm_repair/repair_utils.py
- src/vm-repair/setup.py
This PR:
1. Changes logic to check if resource group already exists in subscription
2. Adds support for hosting repair VM in existing resource group
3. Introduces prompt when cleaning up existing resource group 
> [vm-repair] Changes for hosting repair VM in existing resource group

- src/serial-console/HISTORY.rst
- src/serial-console/azext_serialconsole/custom.py
- src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VM.yaml
- src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VMSS.yaml
- src/serial-console/azext_serialconsole/tests/latest/recordings/test_enable_disable.yaml
- src/serial-console/setup.py
Also, align websocket-client version with azure-cli. Fixes #5533.
---
> [Serial-Console] Fix repeating loading message

- src/aks-preview/azext_aks_preview/commands.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_trustedaccess_rolebinding.yaml
---
Align aks commands.
- declare `aks list` in aks-preview, one test case `test_aks_trustedaccess_rolebinding` uses this command, which was only declared in azure-cli/acs before, so that updating the API version of acs will invalidate the test recording of aks-preview.
> {AKS} Align aks commands

- src/image-copy/azext_imagecopy/custom.py
- src/image-copy/azext_imagecopy/tests/latest/recordings/test_image_copy.yaml
- src/image-copy/azext_imagecopy/tests/latest/test_image_copy_commands.py
---
`az image copy`
Fix subscription id input by user being override
Issue - close: #5663
> [Compute] Fix #5663: `az image copy`: Fix subscription id input by user being override

- src/image-copy/HISTORY.rst
- src/image-copy/setup.py
---
`az image copy`
Issue: #5663
> [Compute] `az image copy`: Update HISTORY.rst and setup.py for upgrading

- .github/fabricbot.json
> {CI} Update milestone from Dec 2022 (2023-01-03) to Jan 2023 (2023-02-07)

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
---
{AKS} Fix test `test_aks_create_and_update_with_http_proxy_config`, previous recording broken by PR [#24673](https://github.com/Azure/azure-cli/pull/24673).
> {AKS} Fix test `test_aks_create_and_update_with_http_proxy_config`

- src/amg/azext_amg/_help.py
- src/amg/azext_amg/azext_metadata.json
- src/amg/azext_amg/commands.py
- src/amg/setup.py
> amg: remove preview flag

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_utils.py
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
- src/containerapp/setup.py
> Fix null custom domain issue for container app

- src/spring/HISTORY.md
- src/spring/azext_spring/commands.py
- src/spring/setup.py
> [Spring] Deprecate the command 'spring app binding'.

- src/spring/HISTORY.md
- src/spring/azext_spring/_help.py
- src/spring/azext_spring/_params.py
- src/spring/azext_spring/api_portal.py
- src/spring/azext_spring/application_configuration_service.py
- src/spring/azext_spring/commands.py
- src/spring/azext_spring/gateway.py
- src/spring/azext_spring/service_registry.py
- src/spring/azext_spring/tests/latest/files/gateway_routes_v2.json
- src/spring/azext_spring/tests/latest/recordings/test_api_portal.yaml
- src/spring/azext_spring/tests/latest/recordings/test_application_configuration_service.yaml
- src/spring/azext_spring/tests/latest/recordings/test_gateway.yaml
- src/spring/azext_spring/tests/latest/recordings/test_service_registry.yaml
- src/spring/azext_spring/tests/latest/test_asa_api_portal.py
- src/spring/azext_spring/tests/latest/test_asa_application_configuration_service.py
- src/spring/azext_spring/tests/latest/test_asa_gateway.py
- src/spring/azext_spring/tests/latest/test_asa_service_registry.py
- src/spring/setup.py
---
az spring application-configuration-service create/delete
az spring service-registry create/delete
az spring gateway create/delete
az spring api-portal create/delete
> [spring] Add delete command for tanzu components

- src/index.json
chore(arcdata): version bump 1.4.10
---
> chore(arcdata): version bump 1.4.10

- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
> [AKS] Add validator for update outbound type operation

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/azext_metadata.json
---
{AKS} Update minimum required cli core version to `2.44.0`.
> {AKS} Update minimum required cli core version to `2.44.0`

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
Raise InvalidArgumentValueError for azure cni + pod_cidr without overlay. Sync changes in PR [#25113](https://github.com/Azure/azure-cli/pull/25113).
> {AKS} Raise InvalidArgumentValueError for azure cni + pod_cidr without overlay

- src/webpubsub/HISTORY.rst
- src/webpubsub/azext_webpubsub/azext_metadata.json
- src/webpubsub/setup.py
---
Some updates before but haven't updated the package version. This PR update the version and prepare to release
> [wps] Update version for new release

- src/index.json
> Add ml extension 2.13.0

- src/aks-preview/HISTORY.rst
- src/aks-preview/README.rst
---
{AKS} Update readme to include latest changes about dependency on azure-cli
> {AKS} Update readme

- linter_exclusions.yml
- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.19.0
---
> [IoT] Adds IoT Extension v0.19.0

- .github/CODEOWNERS
> {containerapp} Add new containerapp codeowners and remove old codeowners

- src/index.json
> Release 0.26.0 for azure dev ops

- .github/fabricbot.json
> {CI} Update milestone from Jan 2023 (2023-02-07) to Feb 2023 (2023-03-07)

- src/nginx/HISTORY.rst
- src/nginx/setup.py
> [Nginx] Release a new version

- src/load/HISTORY.rst
- src/load/azext_load/azext_metadata.json
- src/load/azext_load/tests/latest/recordings/test_load_scenarios.yaml
- src/load/setup.py
> [AzureLoadTesting] Remove Preview tag for Azure Load Testing

- src/bastion/setup.py
> [Bastion] Changes for releasse 0.2.0

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.19.1
---
> [IoT] Adds IoT Extension v0.19.1

- src/automanage/HISTORY.rst
- src/automanage/setup.py
> [Automanage] `az automanage configuration-profile create/update`: Update doc

- src/index.json
> ML Extension for 2.14.0

- src/spring/HISTORY.md
- src/spring/azext_spring/_help.py
- src/spring/azext_spring/_params.py
- src/spring/setup.py
> [Spring] modify help text of creating service and app

- src/index.json
> [serviceconnector-passwordless] remove from index.json

- src/amg/HISTORY.rst
- src/amg/setup.py
> AMG: release 1.1 for SMTP

- src/automanage/HISTORY.rst
- src/automanage/azext_automanage/aaz/latest/automanage/configuration_profile/_create.py
- src/automanage/setup.py
> [Automanage] `az automanage configuration-profile create`: Add example

- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/azext_metadata.json
- src/serviceconnector-passwordless/setup.py
> [serviceconnector-passwordless]fix issue

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_node_restriction.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
{AKS} Fix test case `test_aks_create_and_update_with_node_restriction`. The default version cannot meet the testing requirements (>1.22.0, <1.24.0). Select the appropriate k8s version for testing, if there is no suitable version, skip the test.
- previously failed [test run](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=68642143&view=logs&j=b162b355-d59d-5864-ce0f-0a70f12dd28b&t=a26fe913-e2be-5062-b08e-d15f1acc7ea2)
- passed [test run](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=68643535&view=results)
Once your pull request is merged into …
> {AKS} Fix test case `test_aks_create_and_update_with_node_restriction`

- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
{AKS} Update default live test matrix.
> {AKS} Update default live test matrix

- src/aks-preview/azext_aks_preview/_consts.py
- src/aks-preview/azext_aks_preview/_help.py
update AKV secrets provider help description
---
> {AKS} update AKV secrets provider help description

- src/index.json
---
Reverting #5843
A regression reported [here](https://github.com/microsoft/azure-container-apps/issues/631) as the new API version is not widely available.
containerapp
> Revert containerapp 0.3.22 release

- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/custom.py
> {Service Connector} Refactor for Azure CLI forward compatibility

- src/aks-preview/HISTORY.rst
- src/aks-preview/setup.py
> {AKS} publish new release 0.5.130

- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
{AKS} `az aks nodepool upgrade`: Align command implementation.
`az aks nodepool upgrade`
> {AKS} `az aks nodepool upgrade`: Align command implementation

- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
{AKS} Update node os upgrade channel related test cases
> {AKS} Update node os upgrade channel related test cases

- src/index.json
This reverts commit fe927f586837c0a4d923e382b0858e44231e4286.
---
> Revert "[Release] Update index.json for extension [ aks-preview ]"

- src/storage-mover/HISTORY.rst
- src/storage-mover/azext_storage_mover/commands.py
- src/storage-mover/setup.py
> [StorageMover] `az storage-mover endpoint create/update`: Remove preview tag

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
Release PR for az quantum extension, version 0.19.0.
---
> [Quantum] Update version and history info for az quantum extension 0.19.0

- .github/fabricbot.json
> {CI} Update milestone from Feb 2023 (2023-03-07) to March 2023 (2023-04-04)

- linter_exclusions.yml
- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.20.0
---
> [IoT] Adds IoT Extension v0.20.0

- src/index.json
> Users/singankit/release 2.14.1

- src/spring/HISTORY.md
- src/spring/azext_spring/_params.py
- src/spring/azext_spring/_utils.py
- src/spring/azext_spring/_validators.py
- src/spring/azext_spring/app.py
- src/spring/setup.py
1. Bypass jar check for enterprise tier
2. Check jar java version and asa java version
3. Add disable-app-log to disable app logs when create/deployment
---
> Add java runtime check when create/update deployment

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_up_utils.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_identity_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_identity_user.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_msi.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
- src/containerapp/setup.py
Fixes #5893 
Looks like bug was introduced in #5749. File can't be deleted until `acr_task_run` is complete.
/cc @torosent @vinisoto 
---
az containerapp up
> containerapp – fix error when running `az containerapp up` with no Dockerfile

- src/serviceconnector-passwordless/HISTORY.rst
- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_params.py
- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/custom.py
- src/serviceconnector-passwordless/setup.py
> [Service Connector]remove firewall rule after creation

- src/containerapp/azext_containerapp/_clients.py
- src/containerapp/azext_containerapp/_models.py
> Containerapp: fix Unknown properties internalLoadBalancerEnabled

- .github/fabricbot.json
> {CI} Update container app reviewers

- .github/fabricbot.json
> {Fabric Bot} Updating notification for Compute

- src/serviceconnector-passwordless/HISTORY.rst
- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
- src/serviceconnector-passwordless/setup.py
> [Service Connector] Use client ip in connection message to update sql firewall

- src/aks-preview/azext_aks_preview/_params.py
---
For the system nodepool created when creating the AKS cluster, it must be a linux nodepool. Could add a windows nodepool after the cluster is created via `az aks nodepool add`. See doc [Create a Windows Server container on an AKS cluster by using Azure CLI - Azure Kubernetes Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/aks/learn/quick-windows-container-deploy-cli#add-a-windows-node-pool).
`az aks create`
You only need to update the version …
> {AKS} `az aks create`: Correct help message for option `--os-sku`

- src/index.json
Notes for this [release](https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.21.0).
---
> [IoT] Adds IoT Extension v0.21.0

- src/index.json
---
Will release a new version 0.3.23 https://github.com/Azure/azure-cli-extensions/pull/5955
containerapp
> Remove 0.3.22 from index.json

- src/index.json
chore(arcdata): version bump to 1.4.12
> chore(arcdata): version bump to 1.4.12

- src/serial-console/setup.py
> Fix incorrect URL

- src/spring/HISTORY.md
- src/spring/azext_spring/_validators.py
- src/spring/setup.py
> fix subscription id type

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/custom.py
- src/vm-repair/setup.py
- Private IpAddress error under Reset-Nic was because of the breaking change from CLI team. [Breaking Change](https://github.com/Azure/azure-cli/pull/25498)
- Updated the field `privateIpAddres` to `privateIPAddress`.
- Re run Reset-Nic for TestVM and validate the change.
> Updated PrivateIPAddress var

- src/serviceconnector-passwordless/HISTORY.rst
- src/serviceconnector-passwordless/setup.py
> serviceconnector-passwordless update dependency

- src/storage-blob-preview/HISTORY.rst
- src/storage-blob-preview/azext_storage_blob_preview/operations/blob.py
- src/storage-blob-preview/setup.py
Sync with https://github.com/Azure/azure-cli/pull/25592, https://github.com/Azure/azure-cli/pull/25880
---
> [storage-blob-preview] `az storage blob copy start`: Fix auth issue

- .github/azure-client-tools-bot/config.yml
- .github/fabricbot.json
---
* Auto choose milestone for issue or pull request
* If the current milestone time is more than expected days (7 days), auto set in current milestone.
* If the current milestone time is less than expected days (7 days):
1. If next milestone exist, auto set in next milestone and reminder user.
2. If next milestone not exist, auto set in current milestone and reminder user.
You only need to update the version information in file setup.py and historical information in …
> {CI} Auto manage milestone

- src/managedccfs/HISTORY.rst
- src/managedccfs/azext_managedccfs/aaz/latest/confidentialledger/managedccfs/_create.py
- src/managedccfs/azext_managedccfs/tests/latest/recordings/test_managedccfs_create_custom_3nodes.yaml
- src/managedccfs/azext_managedccfs/tests/latest/recordings/test_managedccfs_create_custom_3nodes_defaultlocation.yaml
- src/managedccfs/azext_managedccfs/tests/latest/recordings/test_managedccfs_create_custom_3nodes_nogroup.yaml
- src/managedccfs/azext_managedccfs/tests/latest/recordings/test_managedccfs_create_sample_3nodes.yaml
- src/managedccfs/azext_managedccfs/tests/latest/test_managedccfs_scenario.py
- src/managedccfs/setup.py
This PR contains fixes to the help documentation and a new test case to validate that the location argument is set to the default value if not supplied by the user.
> Updated help documentation and added a test case

- src/resource-graph/README.md
"_az extension add --name resource-graph_" is missing a character
---
Readme of _az extension add --name resource-graph_
Only update on readme.md
> Corrected misspelled install command

- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_enable_cilium_dataplane.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_get_upgrades.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
- `test_aks_nodepool_get_upgrades`, node image version has a new naming pattern, update the test check.
- `test_aks_create_with_enable_cilium_dataplane`, property name breaking change, may refer to [#11389](https://github.com/Azure/azure-rest-api-specs-pr/pull/11389).
> {AKS} Fix test several test cases

- src/connectedk8s/azext_connectedk8s/custom.py
The release history of this PR will be added with next PR - https://github.com/Azure/azure-cli-extensions/pull/5961 for a single release
> Adding back Heuristics Detection in CLI

- .github/azure-client-tools-bot/config.yml
- .github/fabricbot.json
---
1. Auto manage milestone for pull request
2. Revert auto manage milestone for issue
> {CI} Auto manage milestone for pull request

- src/mobile-network/HISTORY.rst
- src/mobile-network/azext_mobile_network/aaz/latest/mobile_network/site/_create.py
- src/mobile-network/azext_mobile_network/azext_metadata.json
- src/mobile-network/azext_mobile_network/tests/latest/recordings/test_mobile_network.yaml
- src/mobile-network/azext_mobile_network/tests/latest/recordings/test_mobile_network_attached_data_network.yaml
- src/mobile-network/azext_mobile_network/tests/latest/recordings/test_mobile_network_data_network.yaml
- src/mobile-network/azext_mobile_network/tests/latest/recordings/test_mobile_network_pccp.yaml
- src/mobile-network/azext_mobile_network/tests/latest/recordings/test_mobile_network_pcdp.yaml
- src/mobile-network/azext_mobile_network/tests/latest/recordings/test_mobile_network_service.yaml
- src/mobile-network/azext_mobile_network/tests/latest/recordings/test_mobile_network_sim.yaml
- src/mobile-network/azext_mobile_network/tests/latest/recordings/test_mobile_network_site.yaml
- src/mobile-network/azext_mobile_network/tests/latest/recordings/test_mobile_network_slice.yaml
- src/mobile-network/setup.py
---
`az mobile-network site` Fix example error
update aaz model: https://github.com/Azure/aaz/pull/159
close https://github.com/Azure/azure-cli/issues/25919
> {mobile-network} `az mobile-network site`: Fix example error

- .github/azure-client-tools-bot/config.yml
---
support branch check for pull request
> {CI} Support check pull request branch

- src/index.json
> [ML] CLI version 2.15.0 release

- .github/workflows/AddPRComment.yml
---
Add permission `pull-requests: write` to avoid error:
**Error: Parameter token or opts.auth is required**
> {CI} Add auto reply for pull request

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.21.1
---
> [IoT] Adds IoT Extension Release v0.21.1

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_cni_overlay_migration.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
`az aks update`: a cluster can be updated from Azure CNI to Azure CNI Overlay. The full command is `az aks update -n $CLUSTER_NAME -g $CLUSTER_RG --pod-cidr $POD_CIDR --network-plugin-mode overlay`
> [AKS] allow setting `--pod-cidr` and `--network-plugin-mode` in `az aks update` command

- .github/fabricbot.json
---
1. `az account` assign to @zhoxing-ms 
2. `az login` assign to @jiasli
> {CI} Update fabricbot.json for `az login` and `az account`

- .github/fabricbot.json
---
The following modules are involved:
1. Compute
2. Monitor
3. Network
4. KeyVault
5. Account
6. Storage
> {CI} Update fabricbot.json to add `Azure CLI Team` and `question` label

- src/index.json
> ArcAppliance CLI March Release

- src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Update default test matrix,
for azure-cli/acs
- \+ test_aks_azure_cni_overlay_migration
- \- test_aks_nodepool_add_with_ossku
for azure-cli-extensions/aks-preview
- \+ test_aks_nodepool_add_with_workload_runtime
- \- test_aks_update_outbound_from_slb_to_natgateway
- \- test_aks_nodepool_abort
- \- test_aks_nodepool_add_with_ossku
- \- test_aks_create_with_ossku
You only need to update the version information in file setup.py and historical information in file …
> {AKS} Update default test matrix

- src/spring/HISTORY.md
- src/spring/azext_spring/_app_factory.py
- src/spring/azext_spring/_params.py
- src/spring/azext_spring/custom.py
- src/spring/setup.py
> [Spring]Add support for byos subPath

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/azuremonitorprofile.py
- src/aks-preview/setup.py
---
```
az aks update -n kaveeshcli -g kaveeshcli --enable-azuremonitormetrics
```
I'm removing a check that's not needed anymore which was causing issues for customer in this PR.
> {AKS} fix: remove uneeded check for dcr, dcra support

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_up_utils.py
- src/containerapp/azext_containerapp/_utils.py
- src/containerapp/azext_containerapp/custom.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_up_image_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_update_containers.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_up.py
---
az containerapp up
az containerapp update
> containerapp fix up --location and update --max-replicas

- src/index.json
> ml extension 2.15.1

- src/spring/HISTORY.md
- src/spring/azext_spring/_validators.py
- src/spring/azext_spring/tests/latest/recordings/test_app_crud.yaml
- src/spring/azext_spring/tests/latest/test_asa_app_scenario.py
- src/spring/setup.py
> Fix ingress_read_timeout and session_max_age validation error

- .github/azure-client-tools-bot/config.yml
> {CI} Support check HISTORY.rst and setup.py in extension pull request

- src/spring/HISTORY.md
- src/spring/azext_spring/_params.py
- src/spring/azext_spring/_validators.py
- src/spring/azext_spring/custom.py
- src/spring/azext_spring/spring_instance.py
- src/spring/azext_spring/tests/latest/test_asa_create.py
- src/spring/setup.py
---
Update parameter for updating/creating asa instance
> Update parameter for updating/creating asa instance

- .github/fabricbot.json
> {CI} Fabric bot support routing `az fleet`

- src/fleet/HISTORY.rst
- src/fleet/azext_fleet/_help.py
- src/fleet/azext_fleet/_params.py
- src/fleet/azext_fleet/commands.py
- src/fleet/azext_fleet/custom.py
- src/fleet/azext_fleet/tests/latest/recordings/test_fleet.yaml
- src/fleet/azext_fleet/tests/latest/test_fleet_scenario.py
- src/fleet/setup.py
---
az fleet member create
az fleet member update
> [fleet] update fleet member commands

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_clients.py
- src/containerapp/azext_containerapp/_utils.py
- src/containerapp/azext_containerapp/custom.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_with_yaml.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_logs_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_scale_update.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_env_commands.py
---
az containerapp update --no-wait --yaml
az containerapp env update --no-wait
> containerapp fix update --no-wait and --yaml

- src/spring/HISTORY.md
- src/spring/azext_spring/_build_service.py
- src/spring/azext_spring/_params.py
- src/spring/setup.py
> spring: fix some errors when creating service

- src/bastion/HISTORY.rst
- src/bastion/README.md
- src/bastion/azext_bastion/custom.py
- src/bastion/azext_bastion/tunnel.py
- src/bastion/setup.py
> [Bastion] fixing azure cli experience for ip connect

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_params.py
- src/containerapp/azext_containerapp/custom.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py
---
az containerapp auth update
> containerapp remove unsupported --enable-token-store

- src/virtual-wan/HISTORY.rst
- src/virtual-wan/azext_vwan/aaz/latest/network/vhub/_create.py
- src/virtual-wan/azext_vwan/aaz/latest/network/vhub/_delete.py
- src/virtual-wan/azext_vwan/aaz/latest/network/vhub/_list.py
- src/virtual-wan/azext_vwan/aaz/latest/network/vhub/_show.py
- src/virtual-wan/azext_vwan/aaz/latest/network/vhub/_update.py
- src/virtual-wan/azext_vwan/aaz/latest/network/vhub/_wait.py
- src/virtual-wan/azext_vwan/aaz/latest/network/vhub/routing_intent/__cmd_group.py
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_p2s_vpn_gateway_basic_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vhub_connection_basic_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vpn_server_config_basic_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vpn_server_config_multi_auth.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vhub_basic_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vhub_bgpconnection.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vhub_route_scenario.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_gateway.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_gateway_connection.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_gateway_connection_vpn_site_link.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_gateway_connection_vpn_site_link_conn.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_site_link_conn_ipsec_policy.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_p2s_vpn_client_generate.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_p2s_vpn_gateway_inbound_outbound_routemap.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_vhub_connection_inbound_outbound_routemap.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_vhub_route_map.yaml
- src/virtual-wan/azext_vwan/tests/latest/recordings/test_vpn_gateway_connection_inbound_outbound_routemap.yaml
- src/virtual-wan/azext_vwan/tests/latest/test_azure_vwan_vhub_commands.py
- src/virtual-wan/setup.py
---
* `az network vhub create`
* `az network vhub update`
Related AAZ PR: https://github.com/Azure/aaz/pull/175
> [Network] `az network vhub create/update`: Add parameters `--allow-b2b-traffic` and `--auto-scale-config`

- .github/fabricbot.json
---
1. Support adding reviewers and assignees for `vm-repair` PR.
2. Add [yanzhudd](https://github.com/yanzhudd) as reviewer to connectedk8s PR.
3. Support routing `az azurestackhci`
> {CI} Update fabricbot.json

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.21.2
---
> [IoT] Adds IoT Extension Release v0.21.2

- src/vmware/HISTORY.md
- src/vmware/azext_vmware/_help.py
- src/vmware/setup.py
Updating cluster command descriptions as it was causing confusion to customers:
---
> Update Clusters Descriptions

- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-clean-up.yaml
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml
---
Change the pool used by AKS test pipelines to `1ES-AKS-DevInfra-Auto-TearDown-Pool-EastUS`.
N/A
> {AKS} Replace default pool used by test pipelines

- .github/fabricbot.json
> {CI} App Services add yanzhudd as reviewer

- src/index.json
> Release ML 2.17.0

- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Fix test case `test_aks_byo_appgw_with_ingress_appgw_addon`.
> {AKS} Fix test case `test_aks_byo_appgw_with_ingress_appgw_addon`

- src/index.json
> Release ML 2.17.1

- src/index.json
> Release ML 2.17.2

- src/databricks/HISTORY.rst
- src/databricks/azext_databricks/aaz/latest/databricks/workspace/_update.py
- src/databricks/azext_databricks/tests/latest/recordings/test_databricks_v3.yaml
- src/databricks/azext_databricks/tests/latest/test_databricks_scenario.py
- src/databricks/setup.py
> {Databricks} `az databricks workspace update`: add params

- src/index.json
---
The `pydash` dependence is not compatible with typing_extensions==4.6.0, it causes CI issues when generate docs.
> [Release] Revert `confcom` 0.2.14

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/repair_utils.py
- src/vm-repair/setup.py
---
https://github.com/Azure/azure-cli-extensions/issues/6325
> [Vm-repair] VM-repair removing unnecessary check

- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dev_service_binding_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Closes https://github.com/Azure/azure-cli-extensions/issues/6302
---
> Include test coverage for "containerapp service redis/postgres delete"

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/custom.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_identity_system.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_identity_user.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
az containerapp create --registry-identity --revision-suffix
> containerapp fix az containerapp create with --registry-identity system and --revision-suffix

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.21.3
> [IoT] Adds IoT Extension Release v0.21.3

- src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
---
Fix the version of a lib vcrpy (used by testsdk) to 4.2.1 to fix live test execution. There're some compatibility issues between vcrpy>=4.3.0 and urllib3 (v1).
> {AKS} Fix live test execution by fixing version of vcrpy

- src/index.json
> ml extension 2.18.0

- src/load/README.md
> Update README for Azure Load Testing

- src/index.json
---
Fix: 
```
======================================================================
FAIL: test_checksums (__main__.TestIndex)
----------------------------------------------------------------------
File "/mnt/vss/_work/1/s/./scripts/ci/test_index.py", line 138, in test_checksums
self.assertEqual(computed_hash, item['sha256Digest'],
AssertionError: '1d5d6d3ff7c18a7ce6ccdc5ac3dd4fc38b7b028fa9cf2e03ab58a05e6b733081' != '4c9a4ce36b23f6c6fc4bd1e3250c25cacef4f4db215309164bf82724d5f71218'
- 1d5d6d3ff7c18a7ce6ccdc5ac3dd4fc38b7b028fa9cf2e03ab58a05e6b733081
+ 4c9a4ce36b23f6c6fc4bd1e3250c25cacef4f4db215309164bf82724d5f71218
: Computed 1d5d6d3ff7c18a7ce6ccdc5ac3dd4fc38b7b028fa9cf2e03ab58a05e6b733081 but found …
```
> {CI} Update index.json

- .github/azure-client-tools-bot/config.yml
---
Adjust the content of the automatic reply.
> {CI} Update config.yml

- src/load/setup.py
> Update description for Azure Load Testing extension

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_utils.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_private_registry_port.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
---
az containerapp create
az containerapp up
> containerapp --registry-server support custom port

- src/index.json
> Added Arc Resource Bridge 0.2.32 CLI extension

- src/index.json
> delete the traffic controller extension from index.json

- src/index.json
chore(arcdata): version bump to 1.5.2
> chore(arcdata): version bump to 1.5.2

- src/containerapp/azext_containerapp/_clients.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_job_executionstest_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerappjob_executions.py
> fix stop execution call without execution name

- .azure-pipelines/breaking-change-tests.yml
- .azure-pipelines/templates/variables.yml
- .github/azure-client-tools-bot/config.yml
- .github/azure-client-tools-bot/templates/BreakingChangeTest.handlebars
- scripts/ci/breaking_change_test.py
- scripts/ci/util.py
---
Support comparing the current PR with the latest dev branch, and display the breaking change report to the github page.
> {CI} Breaking change tool integration

- src/networkcloud/HISTORY.rst
- src/networkcloud/azext_networkcloud/operations/kubernetescluster/_create.py
- src/networkcloud/azext_networkcloud/operations/kubernetescluster/agentpool/_create.py
- src/networkcloud/azext_networkcloud/tests/latest/recordings/test_bmm_replace_scenario1.yaml
- src/networkcloud/azext_networkcloud/tests/latest/recordings/test_cluster_scenario1.yaml
- src/networkcloud/azext_networkcloud/tests/unit/test_kubernetescluster.py
- src/networkcloud/azext_networkcloud/tests/unit/test_kubernetesclusteragentpool.py
- src/networkcloud/setup.py
NetworkCloud 2023-05-01 Update to kubernetesCluster and Agentpool
> NetworkCloud 2023-05-01 Update to kubernetesCluster and Agentpool

- src/index.json
Fixing 
- dependency on pydantic, explicit version < 2
> Partner Center Extension - v0.2.4-alpha

- scripts/ci/breaking_change_test.py
---
If the extension is release for the first time, skip the breaking change test to aviod `ERROR: extension(s) not found`.
> {CI} Fix breaking change test

- src/index.json
chore(arcdata): version bump to 1.5.3
> chore(arcdata): version bump to 1.5.3

- src/containerapp/azext_containerapp/custom.py
---
`az containerapp hostname bind --hostname something.test.net -g MY-GROUP -n my-container-app -e my-container-app-env`
> Add check if validation_method and raise exception before using it

- scripts/ci/index_ref_doc.py
Reverts Azure/azure-cli-extensions#6474
> {CI} Revert `Temporarily skip the detection of the partnercenter extension in IndexRefDocVerify`

- src/containerapp-preview/azext_containerapp_preview/containerapp_decorator.py
- src/containerapp-preview/azext_containerapp_preview/custom.py
- src/containerapp-preview/azext_containerapp_preview/tests/latest/test_containerapp_preview_scenario.py
- src/containerapp/azext_containerapp/containerapp_decorator.py
- src/containerapp/azext_containerapp/custom.py
> containerapp refactor decorator

- scripts/ci/index_ref_doc.py
- scripts/refdoc/generate.py
> {CI} Update the `--dependent-file` parameter to be an optional argument to avoid introducing a breaking change.

- src/amg/azext_amg/_help.py
- src/amg/setup.py
> amg: add more examples based on user inputs

- src/index.json
> CLI version 2.19.0 release

- .github/policies/resourceManagement.yml
> {CI} Add description to Resource Management Policy

- .github/policies/resourceManagement.yml
> {CI} Update policy config

- src/index.json
> New cli wheel hotfix

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_outbound_ips.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_trustedaccess_rolebinding.yaml
---
{AKS} Fix test recordings broken by vmss/pip API version bump.
- [#26882](https://github.com/Azure/azure-cli/pull/26882)
- [#26961](https://github.com/Azure/azure-cli/pull/26961)
> {AKS} Fix test recordings broken by vmss/pip API version bump

- src/index.json
- src/service_name.json
The azure-sphere extension is ready to be released as Public Preview.
We would like to add our extension in the index.json file.
---
=> It's planned to update description/summary in the new version and follow the Extension Summary Guidelines.
> [azure-sphere] Update index.json for extension

- src/index.json
Release notes:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.21.5
---
> [IoT] IoT extension release v0.21.5

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_consts.py
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/agentpool_decorator.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_vms_agentpool_type.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/setup.py
---
az aks --vm-set-type "VirtualMachines"
> AKS: Add vms agentpool type

- src/index.json
chore(arcdata): version bump to 1.5.4
> chore(arcdata): version bump to 1.5.4

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_up_utils.py
- src/containerapp/azext_containerapp/containerapp_decorator.py
- src/containerapp/azext_containerapp/containerapp_job_decorator.py
- src/containerapp/azext_containerapp/custom.py
- src/containerapp/azext_containerapp/tests/latest/test_containerappjob_crud.py
- src/containerapp/azext_containerapp/tests/latest/test_containerappjob_with_yaml.py
---
`az containerapp job create`
`az containerapp logs show`
> containerapp `containerapp job` add tests

- src/containerapp/azext_containerapp/containerapp_job_decorator.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_manualjob_private_registry_port.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_manualjob_registry_acr_look_up_credentical.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_acr_look_up_credentical.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
- src/containerapp/azext_containerapp/tests/latest/test_containerappjob_crud.py
---
az containerapp job create
> containeraapp add tests for ACR look up credential

- src/index.json
> Remove containerapp-preview from index.json

- src/serviceconnector-passwordless/HISTORY.rst
- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_help.py
- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_params.py
- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_resource_config.py
- src/serviceconnector-passwordless/setup.py
---
Fix issue https://github.com/Azure/azure-cli/issues/27134
> {Service Connector}: Fix auth type issue and check db existence

- src/reservation/setup.py
> [Az.Reservation] Bump up version

- src/amg/azext_amg/_help.py
- src/amg/setup.py
> amg: fix a typo

- src/scheduled-query/HISTORY.rst
- src/scheduled-query/azext_scheduled_query/grammar/scheduled_query/ScheduleQueryConditionValidator.py
- src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query_condition_operator.yaml
- src/scheduled-query/azext_scheduled_query/tests/latest/test_scheduled_query_scenario.py
- src/scheduled-query/setup.py
---
closed https://github.com/Azure/azure-cli/issues/27138
> fixed scheduled query condition operator mapping

- src/stack-hci/HISTORY.rst
- src/stack-hci/azext_stack_hci/aaz/latest/stack_hci/extension/_create.py
- src/stack-hci/azext_stack_hci/aaz/latest/stack_hci/extension/_list.py
- src/stack-hci/azext_stack_hci/aaz/latest/stack_hci/extension/_show.py
- src/stack-hci/azext_stack_hci/aaz/latest/stack_hci/extension/_wait.py
- src/stack-hci/azext_stack_hci/azext_metadata.json
- src/stack-hci/azext_stack_hci/tests/latest/recordings/test_stack_hci_extension_crud.yaml
- src/stack-hci/azext_stack_hci/tests/latest/test_stack_hci_commands.py
- src/stack-hci/setup.py
---
`az stack-hci extension create`
AAZ model: https://github.com/Azure/aaz/pull/296
> [Stack-hci] `az stack-hci extension create`: Change `--settings/--protected-settings` as custom properties

- src/index.json
> [k8s-extension] Roll back k8s-extension to 1.4.3 

- src/containerapp/setup.py
> {containerapp} fix extension url

- src/index.json
> Added hybridaks whl file for 0.2.2 version in index.json

- src/spring/HISTORY.md
- src/spring/azext_spring/custom.py
- src/spring/setup.py
---
Make error message for `az spring app logs` more readable.
`az spring app logs`
> Make error message for `az spring app logs` more readable.

- src/index.json
> [Arc Appliance] Releasing ArcAppliance 0.2.33 August Release

- .github/policies/resourceManagement.yml
> {CI} Update bot policy

- src/index.json
Updating index to include new CLI version
n/a
> Update index to point at new CLI version.

- src/index.json
chore(arcdata): version bump to 1.5.5
> chore(arcdata): version bump to 1.5.5

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
- src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2023_07_02_preview/models/_models_py3.py
---
- {AKS} Refresh vendored SDK to include changes by [PR #25494](https://github.com/Azure/azure-rest-api-specs/pull/25494).
- Fix recording file `test_aks_create_and_update_with_http_proxy_config.yaml` broken by [network API version bump](https://github.com/Azure/azure-cli/pull/27334).
> {AKS} Refresh vendored SDK

- src/palo-alto-networks/HISTORY.rst
- src/palo-alto-networks/setup.py
> [palo-alto-networks] Revert the GA version, use Beta version instead.

- src/index.json
---
`palo-alto-networks` is not ready for GA. Removed the GA version 1.1.0
> [palo-alto-networks] Remove version 1.1.0

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_loadbalancer.py
- src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py
- src/aks-preview/setup.py
---
az aks update -g MyResourceGroup -n MyManagedCluster --load-balancer-outbound-ips "outboundip ids"  --load-balancer-managed-outbound-ip-count 3
> [AKS] Custom ips and managed ips can be assigned to aks cluster outbound resources

- src/scvmm/HISTORY.rst
- src/scvmm/azext_scvmm/tests/latest/recordings/test_scvmm.yaml
- src/scvmm/azext_scvmm/tests/latest/test_scvmm_scenario.py
- src/scvmm/setup.py
Release scvmm 0.2.0
1. Update `setup.py` and `History.rst`
2. Add tests
---
`az scvmm`
> [scvmm] release 0.2.0

- src/spring/HISTORY.md
- src/spring/azext_spring/_marketplace.py
- src/spring/setup.py
> Fix `az spring list-marketplace-plan` command unexpected error

- src/fleet/azext_fleet/_params.py
> fleet argument documentation update

- src/index.json
Notes for this release can be found here: 
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.22.0
---
> [IoT] IoT Extension Release v0.22.0

- .github/policies/resourceManagement.yml
> {CI} Take over all CXP Attention issues

- .github/policies/resourceManagement.yml
> {CI} Update policy configuration according to Service-Contact-List wiki

- src/index.json
> revert connectedk8s cli version from 1.5.0 to 1.4.2

- src/fleet/azext_fleet/custom.py
> [AKS Fleet] Fix broken --node-image-selection

- src/fleet/HISTORY.rst
- src/fleet/setup.py
> [AKS Fleet] Version bump

- src/index.json
> chore: `ml` extension 2.21.0 release 

- src/index.json
> revert connectedk8s 1.5.1

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/_utils.py
- src/connectedk8s/azext_connectedk8s/custom.py
- src/connectedk8s/azext_connectedk8s/tests/latest/README.md
- src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py
- src/connectedk8s/setup.py
revert 8ace62a472ee763e319f3e09964472f9427be0f2, except test changes
---
> revert 8ace62a472ee763e319f3e09964472f9427be0f2, except test changes

- src/index.json
> Added hybridaks az cli 0.2.3 version

- src/redisenterprise/HISTORY.rst
- src/redisenterprise/azext_redisenterprise/_params.py
- src/redisenterprise/azext_redisenterprise/aaz/latest/redisenterprise/_create.py
- src/redisenterprise/azext_redisenterprise/aaz/latest/redisenterprise/_update.py
- src/redisenterprise/setup.py
> Add support to new enterprise skus

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
- src/aks-preview/setup.py
```
az aks create --subscription $SUB_ID \
-n $CLUSTER_NAME \
-g $RG_NAME \
--enable-image-cleaner \
--image-cleaner-interval-hours 48
az aks update --subscription $SUB_ID \
-n $CLUSTER_NAME \
-g $RG_NAME \
--disable-image-cleaner
```
> {AKS} Replace Image Cleaner related functions in aks-preview with azure-cli ones

- src/traffic-collector/HISTORY.rst
- src/traffic-collector/azext_traffic_collector/azext_metadata.json
- src/traffic-collector/setup.py
Hi, we are moving to GA in September. This PR will be in draft state until then. Please don't approve this PR yet.
> remove preview tag

- src/containerapp/HISTORY.rst
> {containerapp} Fix history

- src/index.json
> Add 2.21.1 ml extension release

- src/k8s-extension/HISTORY.rst
- src/k8s-extension/azext_k8s_extension/partner_extensions/AzureDefender.py
- src/k8s-extension/setup.py
> MDC k8s extension - force fetching LA workspace key

- .github/CODEOWNERS
- src/fleet/HISTORY.rst
- src/fleet/azext_fleet/_params.py
- src/fleet/azext_fleet/_validators.py
- src/fleet/azext_fleet/azext_metadata.json
- src/fleet/azext_fleet/commands.py
- src/fleet/azext_fleet/custom.py
- src/fleet/azext_fleet/tests/latest/test_fleet_hubful_scenario.py
- src/fleet/azext_fleet/tests/latest/test_fleet_hubless_scenario.py
- src/fleet/azext_fleet/tests/latest/test_validators.py
- src/fleet/setup.py
---
-Updates the `az fleet` extension to GA (non-preview) status.
- Removed preview flags from GA support capabilities.
- Added support for preview flag '--vm-size'.
> [az fleet] GA Update & --vm-size

- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_cronjob_defaults_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_eventjob_crudoperations_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_eventjob_defaults_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_manualjob_crudoperations_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_manualjob_private_registry_port.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_manualjob_registry_acr_look_up_credentical.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerappjob_crud.py
> {Containerapp} `az containerapp job`: Fix test for event job default

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.23.0
---
> [IoT] IoT Extension Release v0.23.0

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_transformers.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_container_acr.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_eventjob_crudoperations_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_scale_update_azure_queue.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
---
az containerapp create/update
Fix issue: https://github.com/Azure/azure-cli/issues/27696
> [containerapp] `az containerapp create/update`: Fix issue for transform sensitive info when scale rule metadata is none

- src/dataprotection/HISTORY.rst
- src/dataprotection/azext_dataprotection/manual/custom.py
- src/dataprotection/setup.py
---
`az dataprotection backup-instance update-msi-permissions`
> [dataprotection] Added UAMI support while setting permissions for AKS backup/restore

- .github/CODEOWNERS
- src/alb/HISTORY.rst
- src/alb/azext_alb/aaz/latest/network/alb/_create.py
- src/alb/azext_alb/aaz/latest/network/alb/_delete.py
- src/alb/azext_alb/aaz/latest/network/alb/_list.py
- src/alb/azext_alb/aaz/latest/network/alb/_show.py
- src/alb/azext_alb/aaz/latest/network/alb/_update.py
- src/alb/azext_alb/aaz/latest/network/alb/_wait.py
- src/alb/azext_alb/aaz/latest/network/alb/association/_create.py
- src/alb/azext_alb/aaz/latest/network/alb/association/_delete.py
- src/alb/azext_alb/aaz/latest/network/alb/association/_list.py
- src/alb/azext_alb/aaz/latest/network/alb/association/_show.py
- src/alb/azext_alb/aaz/latest/network/alb/association/_update.py
- src/alb/azext_alb/aaz/latest/network/alb/association/_wait.py
- src/alb/azext_alb/aaz/latest/network/alb/frontend/_create.py
- src/alb/azext_alb/aaz/latest/network/alb/frontend/_delete.py
- src/alb/azext_alb/aaz/latest/network/alb/frontend/_list.py
- src/alb/azext_alb/aaz/latest/network/alb/frontend/_show.py
- src/alb/azext_alb/aaz/latest/network/alb/frontend/_update.py
- src/alb/azext_alb/aaz/latest/network/alb/frontend/_wait.py
- src/alb/azext_alb/azext_metadata.json
- src/alb/azext_alb/tests/latest/recordings/test_alb_resources.yaml
- src/alb/azext_alb/tests/latest/test_alb_commands.py
- src/alb/setup.py
> ALB extension GA version. Only API change

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/agentpool_decorator.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_agentpool_os_sku.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/setup.py
---
{AKS} `az aks nodepool update`: Add option `--os-sku` to support updating os sku in place.
- `az aks nodepool update`
> {AKS} `az aks nodepool update`: Add option `--os-sku` to support updating os sku in place

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/agentpool_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_agentpool_os_sku.yaml
- src/aks-preview/setup.py
---
{AKS}: Fix the issue that the value passed by option `--os-sku` in command `az aks nodepool update` is not processed.
Bug fix for PR #6944.
`az aks nodepool update`
> {AKS}: Fix the issue that the value passed by option `--os-sku` in command `az aks nodepool update` is not processed

- src/index.json
- src/service_name.json
> Added the 0.1.1 version of akshybrid cli

- src/scvmm/HISTORY.rst
- src/scvmm/setup.py
Release scvmm 1.0.0
Updated setup.py and History.rst
---
az scvmm
> [SCVMM] Stable GA release 1.0.0

- src/index.json
Release notes for this extension can be found here:
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.1.0b1
---
> [IoT] IoT Operations Extension v0.1.0b1

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/containerapp_env_decorator.py
> [ContainerApp] Update history for container app

- src/index.json
chore(arcdata): version bump to 1.5.7
---
> chore(arcdata): version bump to 1.5.7

- src/index.json
> Arc Appliance CLI: 1.0.1 [November Release]

- src/index.json
> Arc Appliance CLI: 1.0.1 [November Release] [with package bump]

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.1.0b2
---
> [IoT] Adds IoT Operations extension v0.1.0b2

- src/index.json
> revert connectedk8s 1.5.5

- src/index.json
- src/service_name.json
> Added the whl file for 1.0.0 version of aksarc cli (renamed from akshybrid)

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.2.0b1
---
> [IoT] Adds IoT Ops extension v0.2.0b1

- src/index.json
chore(arcdata): version bump to 1.5.8
> chore(arcdata): version bump to 1.5.8

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.23.1
---
> [IoT] Add IoT Extension v0.23.1

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
Release PR for az quantum extension, version 0.20.0
---
> [Quantum] Update version and history info for az quantum extension 0.20.0

- src/index.json
> Added 1.0.2 version of aksarc CLI extension

- azure-pipelines.yml
> {CI} Add statement for azdev style

- src/devcenter/HISTORY.rst
- src/devcenter/azext_devcenter/_help.py
- src/devcenter/azext_devcenter/_params.py
- src/devcenter/azext_devcenter/action.py
- src/devcenter/azext_devcenter/custom.py
- src/devcenter/azext_devcenter/tests/latest/test_devcenter_scenario.py
- src/devcenter/setup.py
> [devcenter] Update project environment type parameters to be required

- src/spring/HISTORY.md
- src/spring/azext_spring/_help.py
- src/spring/azext_spring/_params.py
- src/spring/azext_spring/app.py
- src/spring/azext_spring/commands.py
- src/spring/azext_spring/custom.py
- src/spring/azext_spring/log_stream/__init__.py
- src/spring/azext_spring/log_stream/log_stream_operations.py
- src/spring/azext_spring/log_stream/writer.py
- src/spring/azext_spring/managed_components/__init__.py
- src/spring/azext_spring/managed_components/managed_component.py
- src/spring/azext_spring/managed_components/managed_component_operations.py
- src/spring/azext_spring/managed_components/validators_managed_component.py
- src/spring/azext_spring/tests/latest/managed_component/__init__.py
- src/spring/azext_spring/tests/latest/managed_component/test_managed_component_scenarios.py
- src/spring/azext_spring/tests/latest/managed_component/test_managed_component_validators.py
- src/spring/azext_spring/tests/latest/managed_component/test_writer.py
- src/spring/setup.py
> [Spring] Support managed component log stream

- src/monitor-control-service/HISTORY.rst
- src/monitor-control-service/setup.py
> {Monitor-control-service} Use extension module name to avoid index test failure

- src/index.json
> {Monitor-control-service} Remove fatal package

- src/aks-preview/azext_aks_preview/__init__.py
- src/aks-preview/azext_aks_preview/_client_factory.py
- src/aks-preview/azext_aks_preview/_completers.py
- src/aks-preview/azext_aks_preview/_consts.py
- src/aks-preview/azext_aks_preview/_format.py
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_helpers.py
- src/aks-preview/azext_aks_preview/_loadbalancer.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/_podidentity.py
- src/aks-preview/azext_aks_preview/_roleassignments.py
- src/aks-preview/azext_aks_preview/_validators.py
---
- Fix azdev style issues for internal files (may refer to PR #7112).
> {AKS} Fix azdev style issues for internal files

- src/aks-preview/azext_aks_preview/commands.py
- src/aks-preview/azext_aks_preview/custom.py
---
- Fix azdev style issues for command & custom (may refer to PR #7112).
> {AKS} Fix azdev style issues for command & custom

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/custom.py
- src/vm-repair/azext_vm_repair/scripts/win-run-driver.ps1
- src/vm-repair/azext_vm_repair/tests/latest/test_repair_commands.py
- src/vm-repair/setup.py
---
az vm repair run
Bug fix for invoking az vm repair run on windows
> [az vm repair] version 1.0.0b1

- src/index.json
> Added 1.0.3 version of aksarc CLI extension

- .github/pull_request_template.md
> {CI} Add extension versioning doc in pr template

- .github/workflows/AddIssueComment.yml
- .github/workflows/AddPRComment.yml
---
Starting February 1, 2024 the default permission for the GITHUB_TOKEN will change from Read/Write to Read-only for all Open Source GitHub orgs. 
Add permissions block to avoid breaking change to our workflows.
Learn more [here](https://docs.opensource.microsoft.com/github/apps/permission-changes/)
> {CI} Add permissions block for `Github Action Permission Changes`

- linter_exclusions.yml
- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.2.0b2
---
> [IoT] Add IoT Ops Extension v0.2.0b2

- src/quantum/HISTORY.rst
- src/quantum/azext_quantum/__init__.py
- src/quantum/setup.py
> Az Quantum release to 0.21.0

- src/aks-preview/azext_aks_preview/_help.py
---
{AKS} Update help message of option `--node-osdisk-type`. The change is to correct the help information and align it with the information in the official azure-cli ([p1](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py#L82-L84), [p2](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py#L1451-L1453)). …
> {AKS} Update help message of option `--node-osdisk-type`

- src/load/HISTORY.rst
- src/load/azext_load/data_plane/utils/utils.py
- src/load/setup.py
---
Changes made in this PR -
- Adding support for "az load test" in AzureUSGovernment cloud by setting the ARM endpoint and scope based on the cloud.
> [Azure Load Testing] Updating ARM endpoint based on cloud

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_premium_sku.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_premium_sku.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_vms_agentpool_type.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Fix the k8s version used in the following 3 test cases
- test_vms_agentpool_type
- test_aks_create_with_premium_sku
- test_aks_update_with_premium_sku
> {AKS} Fix some test cases

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_trustedaccess_rolebinding.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
az aks trustedaccess rolebinding create
> {AKS} deprecate TA command --source-resource-id alias -r

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.2.0b4
---
> [IoT] Add IoT Operations CLI extension v0.2.0b4 

- src/index.json
---
azdev style stack-hci-vm doesn't work
> Added new stack-hci-vm cli version 0.1.11

- src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
- src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
---
- {AKS} Update AKS live test matrix to exclude some test cases that always fail from the default test matrix.
> {AKS} Update AKS live test matrix

- src/index.json
chore(arcdata): version bump to 1.5.9
> chore(arcdata): version bump to 1.5.9

- src/index.json
---
az extension add --name baremetal-infrastructure should install the 2.0.1 version instead of 2.0.0.
> Update baremetalinstance version

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_params.py
- src/containerapp/azext_containerapp/containerapp_decorator.py
- src/containerapp/azext_containerapp/custom.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_with_yaml.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_max_inactive_revisions.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
> [Containerapp] 'az containerapp create/update': Support --max-inactive-revisions

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.3.0b1
---
> [IoT] Adds IoT Operations extension v0.3.0b1

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/_client_factory.py
- src/connectedk8s/azext_connectedk8s/custom.py
- src/connectedk8s/setup.py
> upgrade connectedk8s to use Microsoft Graph

- .github/workflows/VersionCalPRComment.yml
- scripts/ci/release_version_cal.py
- src/monitor-control-service/azext_amcs/_client_factory.py
> {CI} Add cli bot token

- scripts/ci/sync_extensions.py
> {CI} Fix sync_extensions.py

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.3.0b2
---
> [IoT] Add IoT Operations extension v0.3.0b2

- src/index.json
> Added the 1.0.4 and 1.1.0 version of askarc CLI

- src/index.json
chore(arcdata): version bump to 1.5.10
> chore(arcdata): version bump to 1.5.10

- src/index.json
> New ML release

- src/spring/HISTORY.md
- src/spring/azext_spring/managed_components/managed_component_operations.py
- src/spring/azext_spring/tests/latest/managed_component/test_managed_component_scenarios.py
- src/spring/setup.py
Enhance managed component log stream when -i/--instance or --all-instances are not specified
---
> [Spring] Enhance managed component log stream

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.3.0b3
---
> [IoT] Add IoT Operations extension v0.3.0b3

- src/load/HISTORY.rst
- src/load/azext_load/data_plane/utils/utils.py
- src/load/azext_load/tests/latest/recordings/test_load_app_component.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_app_component.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_create.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_create_with_args.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_delete.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_download_files.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_file.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_list.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_run_create.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_run_delete.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_run_download_files.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_run_list.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_run_metrics.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_run_server_metric.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_run_show.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_run_stop.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_run_update.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_server_metric.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_show.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_update.yaml
- src/load/azext_load/tests/latest/recordings/test_load_test_update_with_config.yaml
- src/load/setup.py
---
Fix for sending correct failureCriteria request payload when using `az load test create` and `az load test update` commands with `--load-test-config-file` option and config file having failureCriteria.
> Fixing payload for failureCriteria and updated test recordings

- src/index.json
> Added 1.1.1 version of askarc CLI

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.4.0b1
---
> [IoT] Adds IoT Operations Extension v0.4.0b1

- .github/workflows/VersionCalPRComment.yml
- scripts/ci/release_version_cal.py
> [CI] Add version cal workflow

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_approuting_enable_with_keyvault_secrets_provider_addon_and_keyvault_id.yaml
---
{AKS} Fix recording file for case `test_aks_approuting_enable_with_keyvault_secrets_provider_addon_and_keyvault_id`.
> {AKS} Fix recording file for case `test_aks_approuting_enable_with_keyvault_secrets_provider_addon_and_keyvault_id`

- src/index.json
chore(arcdata): version bump to 1.5.11
> chore(arcdata): version bump to 1.5.11

- .github/workflows/VersionCalPRComment.yml
> [CI] Add upstream branch name prefix to avoid conflict in version cal

- src/index.json
> adding stack-hci-vm 1.0.0 version

- scripts/ci/release_version_cal.py
> [CI] Add init module version

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
- src/aks-preview/setup.py
> AKS: Fix the resource allocated after disabling Azure Container Storage for "all" option in ephemeralDisk storagepool type.

- src/spring/HISTORY.md
- src/spring/azext_spring/_help.py
- src/spring/azext_spring/_params.py
- src/spring/azext_spring/_utils.py
- src/spring/azext_spring/_validators_enterprise.py
- src/spring/azext_spring/application_configuration_service.py
- src/spring/azext_spring/commands.py
- src/spring/azext_spring/tests/latest/application_configuration_service/__init__.py
- src/spring/azext_spring/tests/latest/application_configuration_service/test_acs_validators.py
- src/spring/setup.py
> [Spring] Show ACS configs

- src/index.json
> {CI} Fix index.json

- src/index.json
> adding version 1.1.2

- src/index.json
chore(arcdata): version bump to 1.5.12
> chore(arcdata): version bump to 1.5.12

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.4.0b3
---
> [IoT] Adds IoT Operations Extension v0.4.0b3

- scripts/ci/release_version_cal.py
> [CI] Fix label quote caused tag parsing bug

- src/index.json
This pull request adds version 2.25.0 of the ml extension
---
> [ML] chore: Add ml extension 2.25.0

- src/index.json
> Updating batch cli extensions

- src/containerapp/HISTORY.rst
- src/containerapp/setup.py
> [Container app] Release version 0.3.50

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/_cloud_build_utils.py
---
We will schedule build job to legion later, it need more time to running a container in legion, so wait longer time for build container logstream
az containerapp create/update/up --source/--artifact xxx
> wait longer for build log stream

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/scripts/win-run-driver.ps1
- src/vm-repair/setup.py
> 1.0.0b1 patch 1

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_premium_sku.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_premium_sku.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Fix the following 2 cases
- test_aks_create_with_premium_sku
- test_aks_update_with_premium_sku
> {AKS} Fix test cases related premium sku

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/repair_utils.py
- src/vm-repair/setup.py
> Fix for nested command for specific SKU

- scripts/ci/avail-ext-doc/update_extension_list.py
> {CI} Modify the structure and put azure-cli-extensions and azure-docs-cli at the same level

- src/fleet/HISTORY.rst
- src/fleet/azext_fleet/custom.py
- src/fleet/setup.py
> [az fleet] RP now defaults dns_name_prefix, remove az defaulting

- .github/workflows/AddPRComment.yml
- .github/workflows/BlockPRMerge.yml
- .github/workflows/VersionCalPRComment.yml
> [CI] Limit workflow target branches

- src/spring/azext_spring/_params.py
- src/spring/azext_spring/_validators.py
- src/spring/azext_spring/log_stream/log_stream_validators.py
- src/spring/azext_spring/managed_components/managed_component_operations.py
- src/spring/azext_spring/managed_components/validators_managed_component.py
- src/spring/azext_spring/tests/latest/log_stream/__init__.py
- src/spring/azext_spring/tests/latest/log_stream/test_log_stream_validators.py
- src/spring/azext_spring/tests/latest/managed_component/test_managed_component_validators.py
> Refactor for log streaming validators.

- .github/workflows/BlockPRMerge.yml
blockedLabels = ["do-not-merge", "needs-author-feedback"];
---
> {CI} Block PR merge on blocked labels

- src/containerapp/azext_containerapp/_cloud_build_utils.py
---
Remove comment about "legion"
> remove comment

- src/index.json
chore(arcdata): version bump to 1.5.13
> chore(arcdata): version bump to 1.5.13

- src/spring/azext_spring/log_stream/log_stream_operations.py
- src/spring/azext_spring/log_stream/writer.py
- src/spring/azext_spring/managed_components/managed_component.py
- src/spring/azext_spring/managed_components/managed_component_operations.py
> Fix W0611 and R0903 for log streaming

- src/service_name.json
> doc: update service name of API Center

- src/spring/azext_spring/tests/latest/common/__init__.py
- src/spring/azext_spring/tests/latest/common/test_utils.py
- src/spring/azext_spring/tests/latest/managed_component/test_managed_component_validators.py
- src/spring/azext_spring/tests/latest/test_asa_api_portal.py
- src/spring/azext_spring/tests/latest/test_asa_app.py
- src/spring/azext_spring/tests/latest/test_asa_app_insights_validator.py
- src/spring/azext_spring/tests/latest/test_asa_app_validator.py
- src/spring/azext_spring/tests/latest/test_asa_application_accelerator.py
- src/spring/azext_spring/tests/latest/test_asa_application_configuration_service.py
- src/spring/azext_spring/tests/latest/test_asa_application_live_view.py
- src/spring/azext_spring/tests/latest/test_asa_certificate.py
- src/spring/azext_spring/tests/latest/test_asa_create.py
- src/spring/azext_spring/tests/latest/test_asa_update.py
- src/spring/azext_spring/tests/latest/test_asa_validator.py
> Extract get_test_cmd

- scripts/ci/release_version_cal.py
> [CI] Adjust tag operations in release suggestion

- .github/workflows/VersionCalPRComment.yml
> {CI} Change version cal trigger condition

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_automatic_sku.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
AZURE_CLI_TEST_MODULES=acs azdev test azext_aks_preview.test_aks_automatic_sku --discover --live
> {AKS} Add required custom feature headers that automatic cluster needs to improve the recording success rate

- src/index.json
> Release AKSArc CLI 1.1.2 .

- src/index.json
> Arc Appliance CLI 1.1.0 April Release

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.4.0b4
---
> [IoT] Adds IoT Operations extension v0.4.0b4

- src/fleet/HISTORY.rst
- src/fleet/azext_fleet/_params.py
- src/fleet/setup.py
> [az fleet] remove preview markings for fleet hub-related parameters

- .github/policies/resourceManagement.yml
> [CI] Config pr and issue assignee

- src/index.json
> [ML] Release Extension 2.25.1

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_artifact_source.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/linter_exclusions.yml
- src/aks-preview/setup.py
> [AKS] Add a new command to enable bootstrap artifact source when updating cluster

- .github/policies/resourceManagement.yml
> Assign AOSM pull request to Xing and Yan

- src/index.json
> Added the 1.2.20 version of aksarc CLI extension

- src/connectedvmware/HISTORY.rst
- src/connectedvmware/azext_connectedvmware/_help.py
- src/connectedvmware/azext_connectedvmware/_params.py
- src/connectedvmware/azext_connectedvmware/azext_metadata.json
- src/connectedvmware/azext_connectedvmware/custom.py
- src/connectedvmware/setup.py
* Fix bug in `az connectedvmware create` command when RG of machine is different from RG of vCenter.
* Update help command for vm create to remove non-required parameters.
* Bug fix in sample resource id format for vcenter
* Add --private-link-scope flag to `az connectedvmware vm guest-agent enable` command.
---
`az connectedvmware`
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not …
> Connectedvmware v1.0.1

- src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/_create.py
- src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/_show.py
- src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/certificate_profile/_list.py
- src/trustedsigning/setup.py
> Trusted signing: updated examples

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_pod_ip_allocation_mode_static_block.yaml
---
{AKS} Fix several test cases broken by API version bump in network module
- test_aks_create_and_update_with_http_proxy_config
- test_aks_create_with_pod_ip_allocation_mode_static_block
> {AKS} Fix several test cases broken by API version bump in network module

- src/spring/HISTORY.md
- src/spring/azext_spring/application_configuration_service.py
- src/spring/azext_spring/tests/latest/test_asa_application_configuration_service.py
- src/spring/setup.py
> [Spring] Show ACS revision (include commit id)

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.5.0b1
---
> [IoT] Adds IoT Operations extension v0.5.0b1

- .github/workflows/AddPRComment.yml
- .github/workflows/TriggerExtensionRelease.yml
- .github/workflows/VersionCalPRComment.yml
> {CI} Use direct env var reference in version cal workflow

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/containerapp_decorator.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_scale_type_tcp.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
> [Container app] `az containerapp update`: Fix `--scale-rule-tcp-concurrency` for TCP scale rule

- .github/workflows/AddPRComment.yml
- .github/workflows/TriggerExtensionRelease.yml
- .github/workflows/VersionCalPRComment.yml
> {CI} Use env for ado job

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/custom.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_environment_to_target_location.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_basic.py
---
Fix issue: https://github.com/Azure/azure-cli-extensions/issues/7542
> [Container app] `az containerapp compose create`: Fix issue #7542 where the environment's location is not resolved from --location

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_check_network.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
- src/aks-preview/setup.py
---
- {AKS} BREAKING CHANGE: `az aks create`: Updates to option `--enable-managed-identity`, sync change from azure-cli [#28906](https://github.com/Azure/azure-cli/pull/28906).
- {AKS} Fix several recording files broken by dependency bump (compute [#28847](https://github.com/Azure/azure-cli/pull/28847))
- test_aks_check_network
- test_aks_create_and_update_with_http_proxy_config
You only need to update the version information in file setup.py and historical information …
> {AKS} BREAKING CHANGE: `az aks create`: Updates to option `--enable-managed-identity`

- src/aks-preview/azcli_aks_live_test/scripts/clean_up.sh
- src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
- src/aks-preview/azcli_aks_live_test/scripts/start_container.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_cli_live.sh
- src/aks-preview/azcli_aks_live_test/scripts/test_ext_live.sh
- src/aks-preview/azcli_aks_live_test/scripts/transcribe_env.sh
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-clean-up.yaml
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml
---
{AKS} Update CI configs. Change to use identity to run live test instead of service principal.
> {AKS} Update CI configs

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/setup.py
> Leave only one default role for automatic sku

- src/index.json
> Release 1.0.1

- src/rdbms-connect/HISTORY.rst
- src/rdbms-connect/setup.py
---
- [X ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ X] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your …
> {rdbms-connect} Add support for Python 3.11

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_client_factory.py
- src/aks-preview/azext_aks_preview/_format.py
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/commands.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_operations_cmds.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
> operationstatusresult api cli

- src/containerapp/HISTORY.rst
- src/containerapp/setup.py
> [Container app] Release version `0.3.51`

- .github/workflows/BlockPRMerge.yml
> {CI} Add merge-block trigger cond on pr open and sync

- src/monitor-control-service/HISTORY.rst
- src/monitor-control-service/azext_amcs/aaz/latest/monitor/__cmd_group.py
- src/monitor-control-service/azext_amcs/aaz/latest/monitor/data_collection/endpoint/_create.py
- src/monitor-control-service/azext_amcs/aaz/latest/monitor/data_collection/endpoint/_update.py
- src/monitor-control-service/azext_amcs/aaz/latest/monitor/data_collection/rule/_create.py
- src/monitor-control-service/azext_amcs/aaz/latest/monitor/data_collection/rule/_list.py
- src/monitor-control-service/azext_amcs/aaz/latest/monitor/data_collection/rule/_show.py
- src/monitor-control-service/azext_amcs/aaz/latest/monitor/data_collection/rule/_update.py
- src/monitor-control-service/azext_amcs/azext_metadata.json
- src/monitor-control-service/azext_amcs/tests/latest/recordings/test_monitor_control_service_commands.yaml
- src/monitor-control-service/setup.py
> `az monitor data-collection rule/endpoint`: Removed the enum limitation for the `--kind` parameter.

- src/spring/setup.py
> Update Spring version

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/custom.py
- src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py
- src/connectedk8s/setup.py
`azdev style` failures are not caused by my changes.
> skip helm download if helm is already installed

- src/containerapp/azext_containerapp/_models.py
> {Containerapp} Remove redeclared `ManagedServiceIdentity` and `CustomDomainCOnfiguration`

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.5.0b2
---
> [IoT] Adds IoT Operations extension v0.5.0b2

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_canary_upgrade.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_enable_disable.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_get_revisions.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_get_upgrades.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_egress_gateway.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_ingress_gateway.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_pluginca.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
- src/aks-preview/setup.py
> [AKS]: Add warnings to `az aks mesh` commands for out of support asm revision in use

- src/aks-preview/azext_aks_preview/_help.py
---
{AKS} `az aks create`: Update help message of option `--enable-managed-identity`
> {AKS} `az aks create`: Update help message of option `--enable-managed-identity`

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
add missing help command for advanced networking enablement 
update description to note to users that enabling this feature will incur additional costs
---
`--enable-advanced-network-observability`
> update(acns): add missing help for adv networking in aks create, and add note for additional costs for feature enablement

- src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml
- src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml
---
{AKS} Update AKS live test pipeline
> {AKS} Update AKS live test pipeline

- src/index.json
> Update ML extension for hotfix 2.26.1

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/containerapp_auth_decorator.py
- src/containerapp/azext_containerapp/custom.py
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_auth_e2e.yaml
---
az containerapp auth update
When set_secrets during update settings, need to wait until finish, otherwise it will throw error about secret not found in containerapp , for example:
```
src\azure-cli\azure\cli\command_modules\containerapp\custom.py:4214: in update_aad_settings
handle_raw_exception(e)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  
e = HTTPError('Bad Request({"error":{"code":"AuthConfigSecretRefNotFound","message":"Secret …
```
> [Containerapp] `az containerapp auth update`: Fix AuthConfigSecretRefNotFound

- src/connectedvmware/HISTORY.rst
- src/connectedvmware/azext_connectedvmware/custom.py
- src/connectedvmware/setup.py
Changes:
* Prompt credentials if not provided for Guest Agent.
---
`az connectedvmware`
> connectedvmware 1.1.0

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/agentpool_decorator.py
- src/aks-preview/azext_aks_preview/custom.py
---
az aks create --vm-set-type --vm-sizes
az aks nodepool add --vm-set-type --vm-sizes
az aks nodepool manual-scale
> {AKS} Set default vm-set-type and ignore spaces for Mixed SKU

- src/index.json
> Release new cli version for Aksarc

- src/index.json
https://github.com/Azure/azure-iot-ops-cli-extension/releases/tag/v0.5.1b1
---
> [IoT] Adds IoT Operations Extension v0.5.1b1

- src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/v0.24.0
---
> [IoT] Adds IoT CLI Extension v0.24.0

- linter_exclusions.yml
- src/index.json
> [stack-hci-vm] Bring v1.1.11 to the index

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_canary_upgrade.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_enable_disable.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_get_revisions.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_get_upgrades.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_egress_gateway.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_ingress_gateway.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_pluginca.yaml
---
{AKS} Remove tokens from recordings
> {AKS} Remove tokens from recordings

- linter_exclusions.yml
- src/index.json
chore(arcdata): version bump to 1.5.15
> chore(arcdata): version bump to 1.5.15

- src/containerapp/HISTORY.rst
- src/containerapp/setup.py
> [Containerapp] Release version 0.3.53

- src/index.json
> [stack-hci-vm] Bring v1.1.12 to the index

- src/index.json
> update index to include CLI 2.27.0

- .github/workflows/ProcessCodeReview.yml
> {CI} Set scripts from base branch

- .github/CODEOWNERS
> Update CODEOWNERS of the AOSM extension

- src/aks-preview/azext_aks_preview/_format.py
- src/aks-preview/azext_aks_preview/azext_metadata.json
---
{AKS} Fix several linter & style issues
> {AKS} Fix several linter & style issues

- .github/policies/resourceManagement.yml
---
1. Add Bernard Pan as reviewer for CI related PRs.
2. Add Qin Kai as owner for k8s-runtime related PRs. 
> {CI} Update resourceManagement.yml

- src/index.json
> {CI} Update index.json for workloads extension

- scripts/ci/release_version_cal.py
---
refer to this https://github.com/Azure/azure-cli-extensions/pull/7684
> {CI} Update parse gh label json string

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_pod_ip_allocation_mode_static_block.yaml
---
{AKS} Fix several cases broken by network module bumping API.
> {AKS} Fix several cases broken by network module bumping API

- src/aks-preview/azext_aks_preview/_help.py
> [aks] Change aks draft up Summary

- src/index.json
chore(arcdata): version bump to 1.5.16
> chore(arcdata): version bump to 1.5.16

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/_validators.py
- src/vm-repair/azext_vm_repair/custom.py
- src/vm-repair/setup.py
> VM repair 1.0.7

- src/storage-preview/HISTORY.rst
- src/storage-preview/azext_storage_preview/_help.py
- src/storage-preview/azext_storage_preview/_params.py
- src/storage-preview/azext_storage_preview/_validators.py
- src/storage-preview/azext_storage_preview/commands.py
- src/storage-preview/azext_storage_preview/operations/account.py
- src/storage-preview/azext_storage_preview/tests/latest/recordings/test_storage_account_local_user.yaml
- src/storage-preview/azext_storage_preview/tests/latest/test_storage_account_scenarios.py
> [Storage-Preview] `az storage account local-user`: Add ACL support, and list paging/filtering

- src/aks-preview/azext_aks_preview/custom.py
---
az aks nodepool manual-scale update
> {AKS} fix error message of `az aks nodepool manual-scale update`

- src/aks-preview/HISTORY.rst
- src/aks-preview/README.rst
- src/aks-preview/azext_aks_preview/azext_metadata.json
---
{AKS} Update the minimum required cli core version to `2.61.0`.
> {AKS} Update the minimum required cli core version to `2.61.0`.

- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Fix aks command test only, no customer facing change
az aks upgrade --cluster-snapshot-id
> Speficy network plugin in test

- .github/template/non-security-comment.md
- .github/workflows/AddIssueCommentWithLabel.yml
> {CI} Add non-security issue label check

- src/providerhub/azext_providerhub/aaz/latest/providerhub/provider_registration/_create.py
- src/providerhub/azext_providerhub/aaz/latest/providerhub/resource_type_registration/_create.py
> Update providerhub cli to use string instead of enum

- .github/workflows/VersionCalPRComment.yml
- scripts/ci/release_version_cal.py
> {CI} Adjust version cal job structure

- .github/workflows/VersionCalPRComment.yml
> {CI} Fix path exclude for version cal

- src/vm-repair/HISTORY.rst
- src/vm-repair/azext_vm_repair/custom.py
- src/vm-repair/setup.py
> 1.0.8 SELFHELP telemetry added

- .github/workflows/VersionCalPRComment.yml
- scripts/ci/release_version_cal.py
> {CI} Fix shell and version extract scripts

- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
> Remove costanalysis preview, it is GA now

- .github/workflows/VersionCalPRComment.yml
- scripts/ci/release_version_cal.py
> {CI} Add skip job config and exit error for version cal

- src/aks-preview/azext_aks_preview/_params.py
> remove preview for GA

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_e2e.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_update.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py
- src/containerapp/setup.py
> [Containerapp] Release version `0.3.55`

- src/oracle-database/HISTORY.rst
- src/oracle-database/azext_oracle_database/azext_metadata.json
- src/oracle-database/setup.py
> Stable oracle-database for Azure CLI support

- .github/workflows/BlockPRMerge.yml
- scripts/ci/release_version_cal.py
> {CI} Adjust comment hint and remove label check

- .github/workflows/VersionCalPRComment.yml
---
refer to this: https://github.com/Azure/azure-cli-extensions/actions/runs/10520708013/job/29150103995?pr=7902
> {CI} Bypass intermediate changed files grep failure

- scripts/ci/release_version_cal.py
> {CI} Block illegal extension version

- src/aks-preview/README.rst
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
---
- Fix test case `test_aks_create_and_update_with_http_proxy_config`.
- Update readme, involving the deprecation of some old API versions.
> {AKS} Fix test case `test_aks_create_and_update_with_http_proxy_config`

- src/connectedk8s/HISTORY.rst
- src/connectedk8s/azext_connectedk8s/_precheckutils.py
- src/connectedk8s/setup.py
> [connectedk8s] change to support breaking change introduced in k8s version 1.31.0

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_format.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_check_network.yaml
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
---
- {AKS} `az aks get-versions`:  Add a new column `supportPlan` when the command output is in table format. Based on PR #7308.
- Update recording files of the following 2 test cases
- test_aks_check_network
- test_aks_create_and_update_with_http_proxy_config
`az aks get-versions`
> {AKS} `az aks get-versions`:  Add a new column `supportPlan` when the command output is in table format

- src/containerapp/HISTORY.rst
---
Updated the description of release `1.0.0b1`. Removed the `update` word from the description, as `update` is not applicable for `container-type`
> Update description of release 1.0.0b1

- src/costmanagement/HISTORY.rst
- src/costmanagement/azext_costmanagement/generated/_validators.py
- src/costmanagement/azext_costmanagement/tests/latest/recordings/test_show_operation_result_in_subscription_scope.yaml
- src/costmanagement/setup.py
Remove ADAL dependencies,
replace functions/models in msrestazure library with parity functions in azure.mgmt.core library or azure.core library
Can't pass these testcases:
`test_export_create_in_subscription_scope`
`test_export_create_with_schedule_in_subscription_scope`
`test_update_with_timeperiod_in_subscription_scope`
--- …
> {costmanagement} Remove ADAL dependencies

- src/log-analytics-solution/HISTORY.rst
- src/log-analytics-solution/azext_log_analytics_solution/custom.py
- src/log-analytics-solution/azext_log_analytics_solution/tests/latest/recordings/test_log_analytics_solution.yaml
- src/log-analytics-solution/setup.py
Remove ADAL dependencies,
replace functions/models in msrestazure library with parity functions in azure.mgmt.core library or azure.core library
---
> {log-analytics-solution} Remove ADAL dependencies

- src/alertsmanagement/HISTORY.rst
- src/alertsmanagement/azext_alertsmanagement/_params.py
- src/alertsmanagement/azext_alertsmanagement/_validators.py
- src/alertsmanagement/azext_alertsmanagement/custom.py
- src/alertsmanagement/azext_alertsmanagement/tests/latest/recordings/test_alertsmanagement_processing_rule.yaml
- src/alertsmanagement/setup.py
Remove ADAL dependencies, 
replace functions/models in msrestazure library with parity functions in azure.mgmt.core library or azure.core library 
---
> {alertsmanagement} Remove ADAL dependencies

- src/k8s-runtime/HISTORY.rst
- src/k8s-runtime/azext_k8s_runtime/custom_commands/common.py
- src/k8s-runtime/setup.py
Replace soon-to-be-removed `azure-graphrbac` SDK to MS Graph SDK. 
---
> [k8s-runtime] Migrate graphrbac to MS Graph sdk

- src/vmware/HISTORY.md
- src/vmware/azext_vmware/operations/addon.py
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_addon.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_vr_addon.yaml
- src/vmware/azext_vmware/tests/latest/test_addon_scenario.py
- src/vmware/setup.py
> Bugfix for `az vmware addon srm` and `az vmware addon arc` create and update

- src/azurelargeinstance/HISTORY.rst
- src/azurelargeinstance/README.md
- src/azurelargeinstance/azext_azurelargeinstance/aaz/latest/large_instance/_create.py
- src/azurelargeinstance/azext_azurelargeinstance/aaz/latest/large_instance/_delete.py
- src/azurelargeinstance/azext_azurelargeinstance/aaz/latest/large_storage_instance/_create.py
- src/azurelargeinstance/azext_azurelargeinstance/aaz/latest/large_storage_instance/_delete.py
- src/azurelargeinstance/azext_azurelargeinstance/tests/latest/recordings/test_list_azurelargeinstances_in_resourcegroup.yaml
- src/azurelargeinstance/azext_azurelargeinstance/tests/latest/recordings/test_list_azurelargeinstances_in_subscription.yaml
- src/azurelargeinstance/azext_azurelargeinstance/tests/latest/recordings/test_list_azurelargestorageinstances_in_resourcegroup.yaml
- src/azurelargeinstance/azext_azurelargeinstance/tests/latest/recordings/test_list_azurelargestorageinstances_in_subscription.yaml
- src/azurelargeinstance/azext_azurelargeinstance/tests/latest/test_azurelargeinstance.py
- src/azurelargeinstance/setup.py
> Flatten the parent arguments that contain sku / azure-large-instance-size in the create methods for 2024-08-01-preview

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_completers.py
- src/aks-preview/azext_aks_preview/_roleassignments.py
- src/aks-preview/azext_aks_preview/_validators.py
- src/aks-preview/azext_aks_preview/addonconfiguration.py
- src/aks-preview/azext_aks_preview/aks_diagnostics.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
{AKS} Remove dependency on `msrestazure.azure_exceptions` and `msrestazure.tools`. Use the alternatives provided by `azure.core.exceptions` and `azure.mgmt.core.tools` instead.
> {AKS} Remove dependency on `msrestazure.azure_exceptions` and `msrestazure.tools`

- src/aks-preview/HISTORY.rst
- src/aks-preview/azext_aks_preview/_help.py
- src/aks-preview/azext_aks_preview/_params.py
- src/aks-preview/azext_aks_preview/custom.py
- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_disable_ssh.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
- src/aks-preview/setup.py
Remove syntax sugar for az aks update --ssh-access and update help message
---
> [AKS] Remove syntax sugar for az aks update --ssh-access and update help message

- src/datamigration/HISTORY.rst
- src/datamigration/azext_datamigration/manual/_help.py
- src/datamigration/azext_datamigration/manual/custom.py
- src/datamigration/azext_datamigration/manual/helper.py
- src/datamigration/setup.py
---
Adding these changes to fix a security bug in datamigration extension. 
> Adding changes to sanities auth-key in datamigration register-integration-runtime

- src/connectedvmware/HISTORY.rst
- src/connectedvmware/azext_connectedvmware/_help.py
- src/connectedvmware/azext_connectedvmware/_params.py
- src/connectedvmware/azext_connectedvmware/_validators.py
- src/connectedvmware/azext_connectedvmware/custom.py
- src/connectedvmware/azext_connectedvmware/vmware_utils.py
- src/connectedvmware/setup.py
---
```yaml
$ az connectedvmware vm create -g contoso-rg -v contoso-vc --mo-name contoso-vm -n test-mo
2024-09-16T00:56:31 WARNING  [1] /subscriptions/12345678-1234-1234-1234-123456789012/resourceGroups/contoso-rg/providers/Microsoft.ConnectedVMwarevSphere/VCenters/contoso-vc/InventoryItems/vm-123456 
{
"inventoryType": "VirtualMachine",
"provisioningState": "Succeeded",
"managedResourceId": "",
"moName": "contoso-vm",
"toolsVersionStatus": "guestToolsSupportedOld",
"toolsRunningStatus": "guestToolsRunning",
"toolsVersion": "11297",
"instanceUuid": "12345678-1234-1234-1234-123456789012",
"resourcePool": {
"inventoryType": "ResourcePool",
"inventoryItemId": …
```
> [connectedvmware] Enable VM using moName

- scripts/ci/release_version_cal.py
> {CI} Fix minor tag return

- src/containerapp/HISTORY.rst
- src/containerapp/setup.py
> [Containerapp] Release version `1.0.0b3`

- src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
---
Fix live test pipeline. [#37491](https://github.com/Azure/azure-sdk-for-python/issues/37491)
> {AKS} Fix live test pipeline

- src/front-door/azext_front_door/_validators.py
- src/front-door/azext_front_door/custom.py
Replace all msrestazure with azure.mgmt.core in Font Door extensions
> {Font-Door}Replace all msrestazure with azure.mgmt.core

- src/fleet/HISTORY.rst
- src/fleet/azext_fleet/commands.py
- src/fleet/setup.py
---
`az fleet autoupgradeprofile ...`
> [fleet] set autoupgradeprofile commands to preview mode

- src/microsoft-fabric/README.md
Extension installation doc is wrong. It should be `microsoft-fabric`.
It's published under available extensions as mentioned above.
CC: @badeamarjieh
---
N/A for below.
> fix(microsoft-fabric): typos in the readme

- src/vmware/azext_vmware/tests/latest/recordings/test_vmware.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_addon.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_cloud_link.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_datastores.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_global_reach_connection.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_hcx.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_iscsi_path.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_placement_policy.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_script.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_virtual_machines.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_vr_addon.yaml
- src/vmware/azext_vmware/tests/latest/recordings/test_vmware_workload_network.yaml
> VMware Extension Python 3.12.6 Upgrade

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_gpu_driver_type.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
> {AKS} Add live test scenario for Windows GPU driver selection feature

- scripts/ci/credscan/CredScanSuppressions.json
> {CI} Update CredScanSuppressions.json

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/commands.py
- src/db-up/setup.py
As requested by PM, the deprecation message needs to be updated
---
> {db-up} Update db-up deprecation warning message

- src/monitor-pipeline-group/HISTORY.rst
- src/monitor-pipeline-group/azext_monitor_pipeline_group/aaz/latest/monitor/pipeline_group/_create.py
- src/monitor-pipeline-group/azext_monitor_pipeline_group/aaz/latest/monitor/pipeline_group/_delete.py
- src/monitor-pipeline-group/azext_monitor_pipeline_group/aaz/latest/monitor/pipeline_group/_list.py
- src/monitor-pipeline-group/azext_monitor_pipeline_group/aaz/latest/monitor/pipeline_group/_show.py
- src/monitor-pipeline-group/azext_monitor_pipeline_group/aaz/latest/monitor/pipeline_group/_update.py
- src/monitor-pipeline-group/azext_monitor_pipeline_group/aaz/latest/monitor/pipeline_group/_wait.py
- src/monitor-pipeline-group/azext_monitor_pipeline_group/tests/latest/data_files/extendedLocation.json
- src/monitor-pipeline-group/azext_monitor_pipeline_group/tests/latest/recordings/test_monitor_pipeline_group.yaml
- src/monitor-pipeline-group/azext_monitor_pipeline_group/tests/latest/test_monitor_pipeline_group.py
- src/monitor-pipeline-group/setup.py
> Update pipeline group extension to 2024-10-01-preview API spec

- src/acat/HISTORY.rst
- src/acat/azext_acat/_help.py
- src/acat/azext_acat/aaz/latest/acat/_onboard.py
- src/acat/azext_acat/aaz/latest/acat/_trigger_evaluation.py
- src/acat/azext_acat/aaz/latest/acat/report/_create.py
- src/acat/azext_acat/aaz/latest/acat/report/_delete.py
- src/acat/azext_acat/aaz/latest/acat/report/_list.py
- src/acat/azext_acat/aaz/latest/acat/report/_show.py
- src/acat/azext_acat/aaz/latest/acat/report/_update.py
- src/acat/azext_acat/aaz/latest/acat/report/snapshot/_download.py
- src/acat/azext_acat/aaz/latest/acat/report/webhook/_create.py
- src/acat/azext_acat/aaz/latest/acat/report/webhook/_delete.py
- src/acat/azext_acat/aaz/latest/acat/report/webhook/_list.py
- src/acat/azext_acat/aaz/latest/acat/report/webhook/_show.py
- src/acat/azext_acat/aaz/latest/acat/report/webhook/_update.py
- src/acat/azext_acat/custom.py
> add examples for acat

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/commands.py
- src/db-up/setup.py
Reverts Azure/azure-cli-extensions#8127 to retrigger release pipeline
> Revert "{db-up} Update db-up deprecation warning message"

- src/db-up/HISTORY.rst
- src/db-up/azext_db_up/commands.py
- src/db-up/setup.py
Create PR again to re-trigger release pipeline
---
> {db-up} Update deprecation msg

- src/staticwebapp/HISTORY.rst
- src/staticwebapp/azext_staticwebapp/_params.py
- src/staticwebapp/azext_staticwebapp/_utils.py
- src/staticwebapp/azext_staticwebapp/custom.py
- src/staticwebapp/azext_staticwebapp/tests/latest/recordings/test_staticwebapp_dbconnection_azure_sql.yaml
- src/staticwebapp/azext_staticwebapp/tests/latest/recordings/test_staticwebapp_dbconnection_cosmosdb.yaml
- src/staticwebapp/azext_staticwebapp/tests/latest/recordings/test_staticwebapp_dbconnection_mysql_flex.yaml
- src/staticwebapp/azext_staticwebapp/tests/latest/recordings/test_staticwebapp_dbconnection_pgsql_flex.yaml
- src/staticwebapp/azext_staticwebapp/tests/latest/recordings/test_staticwebapp_dbconnection_pgsql_single.yaml
- src/staticwebapp/azext_staticwebapp/tests/latest/test_staticwebapp_scenario.py
- src/staticwebapp/setup.py
> [staticwebapp] Replace msrestazure with azure.core

- src/dataprotection/HISTORY.rst
- src/dataprotection/azext_dataprotection/manual/custom.py
- src/dataprotection/azext_dataprotection/manual/helpers.py
- src/dataprotection/setup.py
---
We used `is_valid_resource_id` and `parse_resource_id` from `msrestazure.tools`. Using drop-in replacements from `azure.mgmt.core.tools instead`. There was no dependency on `msrestazure.azure_exceptions`, so no action needs to be taken there.
> {dataprotection} Remove dependency on `msrestazure.tools` 

- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_up_private_registry_port.yaml
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_up_registry_acr_look_up_credentical.yaml
> {Containerapp} Remove secrets

- CodeQL.yml
> {Misc.} Add codeql exclusion list

- src/traffic-collector/HISTORY.rst
- src/traffic-collector/azext_traffic_collector/custom.py
- src/traffic-collector/setup.py
> Removing msrestazure dependency and using azure.mgmt.core for traffic-collector

- src/nexusidentity/HISTORY.rst
- src/nexusidentity/azext_nexusidentity/azext_metadata.json
- src/nexusidentity/azext_nexusidentity/custom.py
- src/nexusidentity/setup.py
---
`az nexusidentity gen-keys`
> {NexusIdentity} Pinning version for azure-identity and file error handling

- azure-pipelines.yml
> Add Secret Scan to PR CI

- src/neon/README.md
> [Update] Readme for Neon Extension

- src/ssh/HISTORY.md
- src/ssh/azext_ssh/ip_utils.py
- src/ssh/azext_ssh/target_os_utils.py
- src/ssh/setup.py
> [SSH] Remove dependency to msrestazure

- src/durabletask/azext_durabletask/aaz/latest/durabletask/namespace/_list.py
- src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_create.py
- src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_list.py
- src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_show.py
- src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_update.py
---
- [x ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ x] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)
Associated aaz PR: https://github.com/Azure/aaz/pull/596
> Updating durabletask extension to include new fields for url

- src/redisenterprise/HISTORY.rst
- src/redisenterprise/azext_redisenterprise/azext_metadata.json
- src/redisenterprise/setup.py
making latest version as preview
---
> Release redisenterprise 1.2.1b1

- src/cloudservice/HISTORY.rst
- src/cloudservice/azext_cloudservice/manual/custom.py
- src/cloudservice/setup.py
> {Cloudservice} Remove direct call to `msrestazure`

- src/support/HISTORY.md
- src/support/azext_support/_validators.py
- src/support/setup.py
---
Remove dependency on msrestazure
> [Support RP] - Remove msrestazure dependency

- src/elastic-san/scripts/connect_for_documentation.py
- src/elastic-san/scripts/connect_for_portal.py
- src/elastic-san/scripts/connect_multiple.py
> [ElasticSAN] connect script node automatic startup

- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Fix test by updating preview flag name
> {AKS} Update preview flag name in test

- src/nexusidentity/HISTORY.rst
- src/nexusidentity/azext_nexusidentity/custom.py
- src/nexusidentity/setup.py
> {NexusIdentity} Adding print statements

- src/amg/HISTORY.rst
- src/amg/azext_amg/custom.py
- src/amg/setup.py
``az grafana dashboard import``
> AMG: validate dashboard json prior to import

- src/containerapp/HISTORY.rst
- src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_preview_create_with_yaml.yaml
- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
> [Containerapp] `az containerapp create/update`: `--yaml` support property pollingInterval and cooldownPeriod

- src/azure-firewall/HISTORY.rst
- src/azure-firewall/azext_firewall/_exception_handler.py
- src/azure-firewall/azext_firewall/_validators.py
- src/azure-firewall/azext_firewall/custom.py
- src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
- src/azure-firewall/setup.py
> {azure-firewall} Remove ADAL dependencies

- src/multicloud-connector/HISTORY.rst
- src/multicloud-connector/setup.py
> [arc-multicloud] Bump up extension version

- .azure-pipelines/breaking-change-tests.yml
---
`persistCredentials: true` leave the OAuth token in the Git config after the initial fetch. The default is not to leave it., which may lead to security risks.
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelineshttps://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines
You only need to update the version information in file setup.py and historical information in file …
> {CI} Disable persist credentials

- src/azure-firewall/azext_firewall/aaz/latest/network/firewall/policy/rule_collection_group/draft/_create.py
- src/azure-firewall/azext_firewall/aaz/latest/network/firewall/policy/rule_collection_group/draft/collection/_list.py
> API mismatch fix

- src/dataprotection/HISTORY.rst
- src/dataprotection/azext_dataprotection/manual/custom.py
- src/dataprotection/azext_dataprotection/manual/helpers.py
- src/dataprotection/setup.py
---
`az dataprotection backup-vault initialize-restoreconfig`: Based on the existence of new parameters `staging_resource_group_id` and `staging_storage_account_id`, we correctly set the object type of the output JSON.
> [dataprotection] Minor bugfix for AKS Vaulted Backups and support for new paired region

- src/confcom/HISTORY.rst
- src/confcom/azext_confcom/data/internal_config.json
- src/confcom/setup.py
There was a [bug in one of the dependencies](https://github.com/microsoft/integrity-vhd/pull/15). This update will pull their newest release to resolve it
---
az confcom
> [confcom] updating version to 1.1.1

- src/containerapp/HISTORY.rst
- src/containerapp/setup.py
> [Containerapp] Release `1.1.0b1` version

- src/service_name.json
> Updating healthcareapis information to Health Data Services.

- src/networkcloud/HISTORY.rst
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/baremetalmachine/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/cloudservicesnetwork/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/cluster/_create.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/cluster/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/cluster/_show.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/cluster/_update.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/cluster/_wait.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/clustermanager/_create.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/clustermanager/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/clustermanager/_show.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/clustermanager/_update.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/clustermanager/_wait.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/kubernetescluster/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/l2network/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/l3network/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/rack/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/storageappliance/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/trunkednetwork/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/virtualmachine/_list.py
- src/networkcloud/azext_networkcloud/aaz/latest/networkcloud/volume/_list.py
- src/networkcloud/azext_networkcloud/azext_metadata.json
- src/networkcloud/azext_networkcloud/operations/cluster/_create.py
- src/networkcloud/azext_networkcloud/operations/cluster/_update.py
- src/networkcloud/azext_networkcloud/operations/common_commandoutputsettings.py
- src/networkcloud/azext_networkcloud/operations/custom_properties.py
- src/networkcloud/azext_networkcloud/tests/unit/test_custom_commandoutputsettings.py
- src/networkcloud/setup.py
---
Coresponding aaz PR https://github.com/Azure/aaz/pull/628
> Networkcloud 20240701preview version updated

- .devcontainer/devcontainer.json
- .devcontainer/login.sh
- .devcontainer/setup.sh
---
what does `repo scope` mean? ref: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes
> {Misc.} Enable devcontainer

- .devcontainer/setup.sh
> {Misc.} Refine devcontainer

- scripts/ci/azdev_linter_style.py
---
main repo: https://github.com/Azure/azure-cli/blob/66037865c63debe1c6e1bc9c1a0242fe1a68041e/azure-pipelines.yml#L1121
```
if [[ "$(System.PullRequest.TargetBranch)" != "" ]]; then
git fetch origin --depth=1 $(System.PullRequest.TargetBranch)
azdev linter --ci-exclusions --min-severity medium --repo=./ --src=HEAD --tgt=origin/$(System.PullRequest.TargetBranch)
else
azdev linter --ci-exclusions --min-severity medium
fi
```
You only need to update the version …
> {CI} Add `--min-severity medium` to `azdev linter` to align with the main repository

- .github/workflows/VersionCalPRComment.yml
---
closed https://github.com/Azure/azure-cli-dev-tools/issues/485
> {CI} Update index.json from pr base branch

- src/internet-analyzer/azext_internet_analyzer/_params.py
> {internet-analyzer} Fix disallowed html tag

- src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_help.py
> {serviceconnector-passwordless} Fix disallowed html tag

- src/storage-preview/azext_storage_preview/_params.py
> {storage-preview} Fix disallowed html tag

- src/spring-cloud/azext_spring_cloud/_help.py
- src/spring-cloud/azext_spring_cloud/_params.py
- src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_persistent_storage.yaml
- src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_stop_and_start_service.yaml
> {spring-cloud} Fix disallowed html tag

- src/connectedvmware/azext_connectedvmware/_params.py
> {connectedvmware} Fix html tag lint

- src/load/azext_load/aaz/latest/load/_create.py
- src/load/azext_load/aaz/latest/load/_delete.py
- src/load/azext_load/aaz/latest/load/_list.py
- src/load/azext_load/aaz/latest/load/_show.py
- src/load/azext_load/aaz/latest/load/_update.py
- src/load/azext_load/aaz/latest/load/_wait.py
> {load} Fix disallowed html tag

- src/devcenter/azext_devcenter/_params.py
> {devcenter } Fix disallowed html tag

- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_bulk_remove.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_commit.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_create.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_delete.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_discard.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_initiate_move.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_list.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_list_required_for.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_list_unresolved_dependency.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_prepare.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_resolve_dependency.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_show.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_update.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_collection/_wait.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_resource/_add.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_resource/_delete.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_resource/_list.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_resource/_show.py
- src/resource-mover/azext_resource_mover/aaz/latest/resource_mover/move_resource/_wait.py
- src/resource-mover/azext_resource_mover/tests/latest/recordings/test_resourcemover_movecollection_e2e.yaml
- src/resource-mover/azext_resource_mover/tests/latest/recordings/test_resourcemover_moveresource_basic.yaml
- src/resource-mover/setup.py
> {resource-mover} Fix disallowed html tag

- src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_list_sku.py
- src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_list.py
- src/elastic-san/azext_elastic_san/azext_metadata.json
https://github.com/Azure/aaz/pull/635
---
> {elastic-san} Fix disallowed html tag

- src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/device/_update.py
> {managednetworkfabric} Fix disallowed html tag

- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_create.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_delete.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_get_billing_info.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_get_metric_rule.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_get_metric_statu.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_list.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_list_app_service.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_list_connected_partner_resource.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_list_host.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_list_linked_resource.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_monitored_resource.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_show.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_switch_billing.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_vm_host_payload.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/_wait.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/monitored_subscription/_create.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/monitored_subscription/_delete.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/monitored_subscription/_show.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/monitored_subscription/_update.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/monitored_subscription/_wait.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/tag_rule/_create.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/tag_rule/_delete.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/tag_rule/_list.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/tag_rule/_show.py
- src/new-relic/azext_new_relic/aaz/latest/new_relic/monitor/tag_rule/_wait.py
> {new-relic} Fix disallowed html tag

- src/spring/azext_spring/tests/latest/recordings/test_api_portal.yaml
- src/stack-hci/azext_stack_hci/tests/latest/recordings/test_stack_hci_arc_setting_crud.yaml
- src/stack-hci/setup.py
- src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_environment_gen2.yaml
- src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_event_source_eventhub.yaml
- src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_event_source_iothub.yaml
> Mask secrets from test recordings

- src/image-gallery/azext_image_gallery/_params.py
- src/image-gallery/azext_image_gallery/tests/latest/recordings/test_shared_gallery_community.yaml
- src/image-gallery/setup.py
> {image-gallery} Fix html tag lint

- src/datamigration/azext_datamigration/manual/_params.py
> {datamigration} Fix disallowed html tag

- .githooks/pre-commit.ps1
- .githooks/pre-commit.sh
> {githooks} Improve pre-commit message

- src/containerapp/azext_containerapp/_params.py
> {containerapp} Fix disallowed html tags

- src/redisenterprise/azext_redisenterprise/_params.py
- src/redisenterprise/azext_redisenterprise/aaz/latest/redisenterprise/_create.py
- src/redisenterprise/azext_redisenterprise/aaz/latest/redisenterprise/_update.py
https://github.com/Azure/aaz/pull/641
---
> {redisenterprise} Fix disallowed html tag

- .githooks/pre-push.ps1
- .githooks/pre-push.sh
---
Optimize the pre-push Git hook to support interactive mode.
> {CI} Optimize azure-cli-extensions githook

- src/load/README.md
> [load] add project structure to README

- .github/workflows/VersionCalPRComment.yml
> {CI} Discard local data changes when checkout branch

- src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
> {Containerapp} Fix integration test

- src/subscription/HISTORY.rst
- src/subscription/azext_subscription/custom.py
- src/subscription/setup.py
---
`az account create`
close https://github.com/Azure/azure-cli/issues/30390
> [Subscription]`az account create`: Fix `--owner-upn` and ` --owner-spn ` not working

- src/confcom/HISTORY.rst
- src/confcom/azext_confcom/data/internal_config.json
- src/confcom/azext_confcom/tests/latest/test_confcom_scenario.py
- src/confcom/setup.py
Updating genpolicy version to the latest
---
az confcom
> [confcom] updating genpolicy version

- src/amg/HISTORY.rst
- src/amg/azext_amg/custom.py
- src/amg/setup.py
---
az grafana
Fixes deserialize issue in AMG notification channel test
> Fix deserialize issue in AMG notification channel test

- src/containerapp/HISTORY.rst
- src/containerapp/setup.py
> [Containerapp] Release version `1.1.0b2`

- src/cosmosdb-preview/HISTORY.rst
- src/cosmosdb-preview/setup.py
> [CosmosDB] 2024-12-01-preview release package versioning.

- linter_exclusions.yml
chore(arcdata): version bump to 1.5.20
> chore(arcdata): version bump to 1.5.20

- src/containerapp/HISTORY.rst
- src/containerapp/setup.py
> [Containerapp] Release a new extension version `1.1.0b3`

- src/durabletask/HISTORY.rst
- src/durabletask/setup.py
> Incrementing version in DTS extension

- linter_exclusions.yml
chore(arcdata): version bump to 1.5.21
> chore(arcdata): version bump to 1.5.21

- .github/workflows/AddIssueComment.yml
- .github/workflows/AddIssueCommentWithLabel.yml
Update GitHub workflows to use ubuntu-latest as ubuntu-20.04 will be removed on 2025-04-01. For more details, see https://github.com/actions/runner-images/issues/11101, for ADO pipelines I will create another PR.
---
> {CI} Update GitHub workflows to use ubuntu-latest

- src/acrquery/HISTORY.rst
- src/acrquery/azext_acrquery/__init__.py
- src/acrquery/azext_acrquery/_help.py
- src/acrquery/azext_acrquery/_params.py
- src/acrquery/azext_acrquery/custom.py
- src/acrquery/azext_acrquery/query.py
- src/acrquery/setup.py
---
This checklist is used to make sure that common guidelines for a pull request  #are followed.
> az acr query 
In response to issue: #8523 
> Remove acr help command from acr query extension

- src/ip-group/HISTORY.rst
- src/ip-group/setup.py
---
close https://github.com/Azure/azure-cli-extensions/issues/8563
> {Ip-group} Release a new package

- .azure-pipelines/sync-alias.yml
> {CI} Update sync-alias.yml to push branch to azclibot/azure-cli-extensions repo

- CodeQL.yml
Inefficient regular expression was scanned by codeql for aks-preview
https://github.com/Azure/azure-cli-extensions/blob/d6c3a73f168ebf5b33725f51bce36c356e19149f/src/aks-preview/azext_aks_preview/_validators.py#L863
Ref: https://liquid.microsoft.com/codeql/issues/2248f600-9483-47aa-802e-ae452487d076
---
> {aks-preview} Add codeql exclusion for aks-preview

- src/internet-analyzer/HISTORY.rst
- src/internet-analyzer/setup.py
> {internet-analyzer} Patch version for updated doc

- src/front-door/HISTORY.rst
- src/front-door/setup.py
> {front-door} Patch version for updated doc

- src/new-relic/HISTORY.rst
- src/new-relic/setup.py
> {new-relic} Patch version for updated doc

- src/spring-cloud/HISTORY.md
- src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_persistent_storage.yaml
- src/spring-cloud/setup.py
> {spring-cloud} Patch version for updated doc

- src/elastic-san/HISTORY.rst
- src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_snapshot_scenarios.yaml
- src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_volume_group_and_volume_scenarios.yaml
- src/elastic-san/setup.py
---
https://github.com/Azure/azure-cli-extensions/pull/8338/files previous fix
> {elastic-san} patch version for documentation

- src/spring/azext_spring/migration/converter/base_converter.py
> [Spring] [CodeQL] Use sha256 instead of md5

- src/image-gallery/HISTORY.rst
- src/image-gallery/azext_image_gallery/_help.py
- src/image-gallery/azext_image_gallery/azext_metadata.json
- src/image-gallery/setup.py
> {image-gallery} Patch version for updated doc

- .github/actions/env-setup/action.yml
- .github/workflows/AzdevLinter.yml
- .github/workflows/AzdevStyle.yml
---
azdev linter rule `missing_command_example` needs git commit history to get the modified cmds, if not provided, this rule is not functional, therefore add another azdev linter check for this specific rule.
> {CI} Add linter example validate rule

- scripts/ci/release_version_cal.py
> {CI} Fix version cal for initial module

- src/network-manager/azext_network_manager/aaz/latest/network/manager/_post_commit.py
---
fix https://github.com/Azure/azure-cli/issues/31022
> Fix issues with Post commit in Routing

- src/ssh/_breaking_change.py
- src/ssh/azext_ssh/_breaking_change.py
> Added breaking change announcement for az ssh arc commands

- src/durabletask/setup.py
> [Durabletask] Updating version in setup.py for durabletask

- src/aks-preview/HISTORY.rst
> fix: update release note for aks-preview 14.0.0b6

- src/spring/HISTORY.md
- src/spring/azext_spring/_deployment_factory.py
- src/spring/setup.py
> [Spring] Fix clear config file pattern with empty string

- src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
- src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
{AKS} Fix API server access profile related test cases. Change in official azure-cli/acs would set additional properties to api_server_access_profile, remove them in aks-preview.
https://github.com/Azure/azure-cli/pull/31318
> {AKS} Fix API server access profile related test cases

- .github/policies/resourceManagement.yml
---
issue and prs from [a-m] to AllyW
issue and prs from [n-z] to necusjz
> {CI} Update issue and pr assignee

- src/neon/setup.py
> updated the Neon version

- src/service_name.json
> remove the preview cmd - k8sconfiguration

- src/containerapp/HISTORY.rst
- src/containerapp/setup.py
> [Containerapp] Release version `1.0.0b5`

- src/cosmosdb-preview/setup.py
> [cosmosdb-preview] Upgraded version in Setup.py for API release 2025-05-01-preview

- .github/azure-client-tools-bot/config.yml
> {CI} Disable milestone comments from the bot.

- src/service_name.json
---
`az pinecone` and `az weights-and-biases` needs to be revoked in doc. Ref list needs to be updated as well.
related pr: 
https://github.com/Azure/azure-cli-extensions/pull/8764
https://github.com/Azure/azure-cli-extensions/pull/8763
> {doc} Remove unpublished module `pinecone` and `weights-and-biases` entry in `service_name.json`

- src/aks-preview/azext_aks_preview/_help.py
> [aks-preview] Add command example

- src/providerhub/setup.py
> Update setup.py version

- src/vmware/azext_vmware/tests/latest/test_addon_scenario.py
- src/vmware/azext_vmware/tests/latest/test_datastores_scenario.py
To support https://github.com/Azure/azure-cli/pull/31066
---
> {vmware} Remove msrestazure for vmware

- src/aosm/HISTORY.rst
- src/aosm/azext_aosm/_validators.py
- src/aosm/azext_aosm/tests/latest/integration_tests/scenario_tests/recordings/test_cnf_nfd_build_and_publish.yaml
- src/aosm/setup.py
To support https://github.com/Azure/azure-cli/pull/31066
---
> {aosm} Remove msrestazure for aosm

- src/appservice-kube/setup.py
> {appservice-kube} Release appservice-kube 0.1.11

- src/service_name.json
Customers should use stack-hci-vm extension instead
---
> {azurestackhci}Remove azurestackhci since it's been deprecated for long time

- src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/load_balancer/_update.py
> add examples about updating load balancer IPs

- src/elastic/HISTORY.rst
- src/elastic/setup.py
> Changing the version in history and setup for Microsoft.Elastic

- src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_enable_imds_restriction.yaml
- src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
> {aks} Update IMDS restriction test suite to enable OIDC issuer

- src/machinelearningservices/CHANGELOG.rst
- src/machinelearningservices/azext_mlv2/manual/custom/_ssh_command.py
- src/machinelearningservices/azext_mlv2/manual/custom/_ssh_connector.py
- src/machinelearningservices/azext_mlv2/manual/custom/compute.py
> Compute connect port 22 path fix

- src/spring/HISTORY.md
- src/spring/azext_spring/_breaking_change.py
- src/spring/setup.py
---
Fix the issue in https://github.com/Azure/azure-cli-extensions/pull/8652. The reference doc is still public available even the service is retiring.
- [* ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [* ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [* ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)
Once your pull request is merged into main branch, a new pull request will be created to update …
> Show the extension reference doc
