azure-pipelines.yml
Migrate Azure.azure-cli-extensions pipeline to azclitools org.
[Azure.azure-cli-extensions](https://dev.azure.com/azclitools/public/_build?definitionId=59)
[Azure CLI Extensions Release](https://dev.azure.com/azclitools/internal/_build?definitionId=197)
[Azure CLI Extensions Sync After Release](https://dev.azure.com/azclitools/internal/_build?definitionId=198)
[Azure CLI Extensions Sync to MicrosoftDocs](https://dev.azure.com/azclitools/internal/_build?definitionId=196)
=> {CI} Migrate azure cli extensions pipelines

src/connectedvmware/HISTORY.rst, src/connectedvmware/azext_connectedvmware/custom.py, src/connectedvmware/setup.py, src/scvmm/HISTORY.rst, src/scvmm/azext_scvmm/custom.py, src/scvmm/setup.py
---
Changes:
- Remove redundant empty checks
- Display asterisk(***) in place of password input for the following commands:
+ az connectedvmware vcenter connect
+ az scvmm vmmserver connect
az connectedvmware vcenter connect
az scvmm vmmserver connect
=> Display Asterisk in place of password

src/aks-preview/HISTORY.rst, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_podidentity.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/data/kubeproxyconfig.json, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_kube_proxy_config.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
---
`az aks create --kube-proxy-config file.json`
=> {AKS} add support to create cluster with kube-proxy configuration

src/connectedk8s/azext_connectedk8s/_params.py
=> Adding an alias(custom-ca-cert) for proxy-cert param for connectedK8s

src/quantum/azext_quantum/_params.py, src/quantum/azext_quantum/commands.py, src/quantum/azext_quantum/operations/job.py
PR for az quantum extension, providing updates for resource estimation.
---
=> [Quantum] Updates to enable resource estimation in the CLI

src/quantum/HISTORY.rst, src/quantum/azext_quantum/__init__.py, src/quantum/azext_quantum/_params.py, src/quantum/setup.py
Release PR for az quantum extension, version 0.17.0.
---
=> [Quantum] Update version and history info for az quantum extension 0.17.0

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/agentpool_decorator.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_add_with_disable_windows_outbound_nat.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_validators.py, src/aks-preview/linter_exclusions.yml, src/aks-preview/setup.py
[AKS] Add ```--disable-windows-outbound-nat``` for ```az aks nodepool add``` to add a Windows agent pool which the Windows OutboundNAT is disabled
---
```
az aks nodepool add --name npwin --os-type Windows --disable-windows-outbound-nat
```
=> [AKS] Add ```--disable-windows-outbound-nat``` for ```az aks nodepool add``` to add a Windows agent pool which the Windows OutboundNAT is disabled

src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/_create.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/_delete.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/_list.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/_show.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/_update.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/_wait.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/collector_policy/_create.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/collector_policy/_delete.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/collector_policy/_list.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/collector_policy/_show.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/collector_policy/_update.py, src/traffic-collector/azext_traffic_collector/aaz/latest/network_function/traffic_collector/collector_policy/_wait.py, src/traffic-collector/azext_traffic_collector/azext_metadata.json, src/traffic-collector/azext_traffic_collector/tests/latest/recordings/test_azure_traffic_scenario.yaml
=> update API version for az network-function traffic-collector

src/ssh/azext_ssh/rdp_utils.py, src/ssh/azext_ssh/ssh_info.py, src/ssh/azext_ssh/ssh_utils.py, src/ssh/azext_ssh/tests/latest/test_rdp_utils.py, src/ssh/azext_ssh/tests/latest/test_ssh_info.py, src/ssh/azext_ssh/tests/latest/test_ssh_utils.py
This will fix issue for usernames whose first character is a dash
---
=> [ssh] Change ssh command format to take user with -l argument

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_ssh_public_key.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
=> {AKS} Support updating SSH public key with `az aks update --ssh-key-value`

src/spring/HISTORY.md, src/spring/azext_spring/_help.py, src/spring/azext_spring/_params.py, src/spring/azext_spring/_validators.py, src/spring/azext_spring/commands.py, src/spring/azext_spring/custom.py, src/spring/azext_spring/tests/latest/recordings/test_remote_debugging.yaml, src/spring/azext_spring/tests/latest/test_asa_app_scenario.py, src/spring/azext_spring/tests/latest/test_asa_scenario.py, src/spring/setup.py
=> Add remote debugging support for spring

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
---
Fix issue [#5488](https://github.com/Azure/azure-cli-extensions/issues/5488). Previously, in update code path, for an SP-based cluster, command would fail on the validation of AzureMonitorMetrics Addon.
- `az aks update`
=> {AKS} `az aks update`: Fix command failure in validation of AzureMonitorMetrics Addon for SP-based cluster

scripts/ci/avail-ext-doc/list-template.md
This PR is a metadata update to replace https://github.com/MicrosoftDocs/azure-docs-cli/pull/3367.  This update is being requested by ...
"
This Pull Request was generated automatically as part of a global effort to improve metadata quality. Please review and merge this Pull Request within 5 days. If you have any questions or concerns about these metadata updates, please contact [docs-allowlist-mgmt@microsoft.com](mailto:docs-allowlist-mgmt@microsoft.com). If you are not the correct contact for this content and repository, please notify [Metadata-Management@microsoft.com](mailto:Metadata-Management@microsoft.com).
Fixing[#559143 Remove ms.technology value azure-cli](https://dev.azure.com/ceapex/Content%20Learning%20Content%20Architecture/_workitems/edit/559143)
"
=> metadata update

.github/fabricbot.json
Add [automated workflows](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/490/Resolving-Issues) to align with the .NET SDK repo：
1. When work on an issue is believed to be complete, the Azure SDK team member responsible for communicating that status may apply the issue-addressed label.
2. When the bot that monitors the repository detects the issue-addressed label, it will respond with the message:
“Hi @issue-author. Thank you for opening this issue and giving us the opportunity to assist. We believe that this has been resolved. If you believe that further discussion is needed, please add a comment with the text “/unresolve” to remove the "issue-addressed” label and continue the conversation.”
3. For issues where the issue-addressed label was applied:
a. If no action is …
=> {CI} Add resolve issues logic

src/vm-repair/HISTORY.rst, src/vm-repair/azext_vm_repair/scripts/linux-mount-encrypted-disk.sh, src/vm-repair/setup.py
=> fixing OS partition detection

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/azext_connectedk8s/tests/latest/recordings/test_connectedk8s.yaml, src/connectedk8s/azext_connectedk8s/tests/latest/recordings/test_forcedelete.yaml, src/connectedk8s/setup.py
=> updated patch behaviour for azureHybridBenefit property in connectedk8s

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
Fix the NoneType error of updating the ssh key value if cluster was created without ssh key. This is not supported, would return an InvalidArgumentValueError.
Fix issue [#5559](https://github.com/Azure/azure-cli-extensions/issues/5559).
=> {AKS} `az aks update`: Fix command failing on updating the ssh key value if cluster was created without ssh key

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_constants.py, src/containerapp/azext_containerapp/_up_utils.py, src/containerapp/azext_containerapp/_utils.py, src/containerapp/setup.py
=> [Container App]: Remove quota check for 'az containerapps env create'

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/aks_diagnostics.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Previously the `kollect` and `kanalyze` commands attempted to gain cluster access by listing admin credentials. This does not work if the cluster has local accounts disabled.
These changes make use of normal non-admin user credentials. However, if a cluster is AAD-enabled, these credentials will initially require interactive login. We can make use of `kubelogin` to convert the credentials to allow non-interactive use. The bulk of the code changes here are to check whether this binary is accessible to the user and either downloading or failing with an appropriate error.
cc: @Tatsinnit 
---
Once …
=> Update diagnostics commands to work with clusters with local accounts disabled

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/commands.py
---
Add custom transform function to handle type conversion for custom CA. Currently this feature is only in preview API. Before feature GA, also need to add this transform to azure-cli/acs.
`aks xxx`
=> {AKS} Add transform function for custom CA

src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py
---
[AKS] `az aks nodepool`: Unify the option names used to specify the nodepool name and cluster name. For nodepool name, option names are `--nodepool-name`, `--name` and `-n`. For cluster name, option name is `--cluster-name`
=> {AKS} `az aks nodepool`: Update nodepool command option names

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/data/kubeproxyconfig.json, src/aks-preview/azext_aks_preview/tests/latest/data/kubeproxyconfig_update.json, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_kube_proxy_config.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_kube_proxy_config.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Support updating kube-proxy configuration with 'az aks update --kube-proxy-config file.json'
---
=> {AKS} add support for updating kube-proxy configuration

scripts/ci/test_index.py, src/keyvault-preview/azext_keyvault_preview/azext_metadata.json
Now we download the wheel package from downloadUrl provided by index.json, then check whether the cli core min version is included in the azext_metadata.json file.
This PR will first search for the latest azext_metadata.json file in local git, and if it can't be found in local git, then search from the downloaded azext_metadata.json file.
=> {CI} Check cli core min version both remote and local

src/vm-repair/azext_vm_repair/custom.py, src/vm-repair/setup.py
---
- Updated logic for Reset Nic "ResourceNotFound" bug.
- Reset Nic Script now correctly picks `VNet ResourceGroup` for fetching `IpAddress` instead of using `ResourceGroup of VM`.
- Tested logic on several Test VM's.
` az vm repair reset-nic -RgName $rgname  -VMName $name --subscription $SubId --verbose`
=> Updated logic for Vm Repair Reset Nic cmd(ResourceNotFound)

azure-pipelines.yml, scripts/ci/test_init.py
Check if the vendored_sdks directory contains `__init__.py` in all extensions.
Will exclude empty vendored_sdks dir, for example:
`azure-cli-extensions\src\containerapp-preview\azext_containerapp_preview\vendored_sdks` is a empty dir that didn't contain any files.
=> {CI} Add check __init__.py file in all extensions

src/index.json
This reverts commit bb4907f17b74365f35f975460699f6b589f230c3 to remove vmware 5.0.0 from the index. It is a bad build. See https://github.com/Azure/azure-cli-extensions/pull/5619 for the fix to make 5.0.1.
---
=> remove vmware 5.0.0 from index

src/scvmm/HISTORY.rst, src/scvmm/azext_scvmm/custom.py, src/scvmm/setup.py
Az cli version 2.42.0 on Windows installed using MSI is not able to install the dependency pwinput.
Issue opened and being tracked : https://github.com/Azure/azure-cli/issues/24781 
As a hotfix, disabling the dependency for now.
---
=> Disabling pwinput till the azure-cli 2.42 issue gets fixed

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/agentpool_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
---
Remove implementation of Azure Dedicated Host, moved to official CLI in PR [#23324](https://github.com/Azure/azure-cli/pull/23324).
=> {AKS} Remove implementation of Azure Dedicated Host

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
- Remove check_raw_parameters in update code path, reuse the implementation in azure-cli/acs.
- May refer to PR [#23682](https://github.com/Azure/azure-cli/pull/23682) in azure-cli. 
=> {AKS} Remove parameter check when update after GA

src/aks-preview/azext_aks_preview/addonconfiguration.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
The new option is added to aks-preview via PR [#5594](https://github.com/Azure/azure-cli-extensions/pull/5594) and azure-cli/acs via PR [#24320](https://github.com/Azure/azure-cli/pull/24320).
The newly added option is not well supported in the aks-preview unique command `aks addon enable`. Fixed and added some tests in this PR.
=> {AKS} Fix monitoring addon option `--enable-syslog` for `aks addon enable`

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
---
- Remove http proxy config related code after GA, reuse the implementation in azure-cli/acs.
- May refer to PR [#23352](https://github.com/Azure/azure-cli/pull/23352) in azure-cli.
=> {AKS} Remove HTTP Proxy Config related code after GA

src/front-door/azext_front_door/_params.py
fixes Azure/azure-cli-extensions#5625 Update the help message for PolicyName
Giving "-" 'hyphen' in the policy name fails. The help message should include that the " Name must begin with a letter and contain only letters and numbers."
---
=> {Front Door} Fix #5625: `az network front-door waf-policy create`: Update help message for `--policy-name`

src/virtual-wan/HISTORY.rst, src/virtual-wan/azext_vwan/_help.py, src/virtual-wan/azext_vwan/_params.py, src/virtual-wan/azext_vwan/custom.py, src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_route_table.yaml, src/virtual-wan/azext_vwan/tests/latest/test_azure_vhub_route_table_scenario.py, src/virtual-wan/setup.py
Resolves: https://github.com/Azure/azure-cli/issues/24629
---
az network vhub route-table
=> [Network] `az network vhub route-table`: Deprecate route table v2 parameters

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_utils.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/setup.py
See title. Also fixes #5642
---
=> [containerapp] Fix 'NoneType object has no attribute get' error in `az containerapp up` with no ingress arguments

src/connectedvmware/HISTORY.rst, src/connectedvmware/azext_connectedvmware/custom.py, src/connectedvmware/azext_connectedvmware/pwinput.py, src/connectedvmware/setup.py
Adding pwinput to source code to workaround the issue with azure cli version >= 2.42.0 in windows installed using MSI.
Links:
- [azure cli Issue][az_issue]
- [pwinput code][pwinput]
[az_issue]: https://github.com/Azure/azure-cli/issues/24781
[pwinput]: https://github.com/asweigart/pwinput/blob/48c7e04c1152e2090ff95d8483cbe4faf970e15d/src/pwinput/__init__.py
---
The precondition is to put your code inside this repository and upgrade the version in the pull request but do …
=> [connectedvmware] Hotfix: Adding pwinput to source code

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/custom.py, src/containerapp/setup.py
fixes Azure/azure-cli-extensions#5673 
fix for hostname bind command to avoid throwing the below exception:
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
File …
```
=> {AzureContainerapp} fixes Azure/azure-cli-extensions#5673 fix for hostname bind

src/spring/HISTORY.md, src/spring/azext_spring/_params.py, src/spring/azext_spring/_validators_enterprise.py, src/spring/azext_spring/commands.py, src/spring/azext_spring/gateway.py, src/spring/azext_spring/tests/latest/recordings/test_gateway.yaml, src/spring/azext_spring/tests/latest/test_asa_gateway.py, src/spring/azext_spring/vendored_sdks/appplatform/v2022_11_01_preview/models/_app_platform_management_client_enums.py, src/spring/setup.py
---
Add new arguments `--apm-types`, `--properties` and `--secrets` for `az spring gateway update`
=> Add gateway APM support

src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Sync changes in PR [#25050](https://github.com/Azure/azure-cli/pull/25050).
=> {AKS} Sync monitorning addon test changes

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_constants.py, src/connectedk8s/azext_connectedk8s/_utils.py, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py
=> Helm release NS change to azure-arc-release

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_up_utils.py, src/containerapp/setup.py
fixes Azure/azure-cli-extensions#5743 PermissionError for temp file
We get the below error When executing az containerapp up without Dockerfile on Windows OS, PermissionError occurs at the ACR task creation step. It seems that temporary files cannot be accessed. This issue can be reproduced on Windows Sandbox also. And it was succeeded to deploy this app from WSL(Ubuntu 22.04) by executing the same command.
```
File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\containerapp\azext_containerapp\_up_utils.py", line 407, in run_acr_build
self.build_container_from_source(image_name, source)
File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\containerapp\azext_containerapp\_up_utils.py", line 375, in build_container_from_source
acr_task_create(self.cmd, task_client, task_name, …
```
=> {AzureContainerApp} fixes Azure/azure-cli-extensions#5743 PermissionError for temp file

.github/fabricbot.json
Update fabricbot.json to support extension regression test pipeline:
1. Assign to `evelyn-ys`
2. Add lable `Auto-Assign`
3. Add reviewer `evelyn`
4. Add milestone `Backlog`
=> {CI} Update fabricbot.json to support extension regression test pipeline

src/bastion/HISTORY.rst, src/bastion/README.md, src/bastion/azext_bastion/BastionServiceConstants.py, src/bastion/azext_bastion/_help.py, src/bastion/azext_bastion/_params.py, src/bastion/azext_bastion/_validators.py, src/bastion/azext_bastion/custom.py, src/bastion/azext_bastion/developer_sku_helper.py, src/bastion/azext_bastion/tunnel.py
=> Adding support for IP Connect and partial for Quick connect.

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/maintenanceconfiguration.py, src/aks-preview/azext_aks_preview/tests/latest/test_maintenanceconfiguration.py, src/aks-preview/setup.py
---
`az aks maintenanceconfiguration add` and `az aks maintenanceconfiguration update`.
Fix error message for validation error - should be '--duration' instead of '--duration-hours'
=> [AKS] Fx maintenanceconfiguration option name for error msg

src/vm-repair/HISTORY.rst, src/vm-repair/azext_vm_repair/custom.py, src/vm-repair/azext_vm_repair/repair_utils.py, src/vm-repair/azext_vm_repair/scripts/win-enable-nested-hyperv.ps1, src/vm-repair/setup.py
---
[vm-repair] Adding hyperv gen to az vm repair create
az vm repair create
=> [vm-repair] Adding hyperv gen to az vm repair create

src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_env_commands.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py, src/containerapp/azext_containerapp/tests/latest/utils.py
=> Hard code region for test

src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_up_dapr_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py, src/index.json
This fixes https://github.com/Azure/azure-cli-extensions/issues/5781
Needs some guidance on how to add tests for this 🙏 
---
az containerapp dapr enable
=> Container app may return null in the dapr object, which cli should handle gracefully

src/automanage/README.md, src/automanage/azext_automanage/aaz/latest/automanage/configuration_profile/_create.py, src/automanage/azext_automanage/aaz/latest/automanage/configuration_profile/_update.py, src/automanage/azext_automanage/aaz/latest/automanage/configuration_profile/version/_create.py, src/automanage/azext_automanage/aaz/latest/automanage/configuration_profile/version/_update.py, src/automanage/azext_automanage/tests/latest/recordings/test_automanage_configuration_profile_assignment_vm_scenarios.yaml, src/automanage/azext_automanage/tests/latest/recordings/test_automanage_configuration_profile_scenarios.yaml, src/automanage/azext_automanage/tests/latest/recordings/test_automanage_scenarios.yaml, src/automanage/azext_automanage/tests/latest/test_automanage.py
=> [Automanage] `az automanage configuration-profile (version)`: Fix documentation to add '' around FreeFormDict

src/quantum/HISTORY.rst, src/quantum/azext_quantum/__init__.py, src/quantum/setup.py
Release PR for az quantum extension, version 0.18.0.
---
=> [Quantum] Update version and history info for az quantum extension 0.18.0

src/containerapp/azext_containerapp/tests/latest/common.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_basic.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_command.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_environment.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_ingress.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_registries.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_resources.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_scale.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_secrets.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_transport_overrides.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_env_commands.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_up.py
=> Refine location config in test for container apps

src/storage-preview/azext_storage_preview/__init__.py
**Description**
The inline help for the argument --access-tier is out of date. This PR updates help for --access-tier to sync what's in the SDK.
---
`az storage account create`
`az storage account update`
=> {storage-preview} `az storage account`: Update help for `--access-tier`

src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
---
{AKS} Fix live test pipeline, fix dependency version.
=> {AKS} Fix live test pipeline

src/spring/azext_spring/_params.py
=> [Spring] More Options For build agent pools:  S6, S7, S8, S9

src/connectedvmware/HISTORY.rst, src/connectedvmware/azext_connectedvmware/_params.py, src/connectedvmware/azext_connectedvmware/custom.py, src/connectedvmware/azext_connectedvmware/tests/latest/recordings/test_connectedvmware.yaml, src/connectedvmware/azext_connectedvmware/tests/latest/test_connectedvmware_scenario.py, src/connectedvmware/azext_connectedvmware/vmware_constants.py, src/connectedvmware/azext_connectedvmware/vmware_utils.py, src/connectedvmware/setup.py
=> Enable automatic upgrade supports for connectedvmware VM extension.

src/spring/HISTORY.md, src/spring/azext_spring/_params.py, src/spring/azext_spring/vendored_sdks/appplatform/v2022_09_01_preview/models/_models_py3.py, src/spring/azext_spring/vendored_sdks/appplatform/v2022_11_01_preview/models/_models_py3.py, src/spring/setup.py
=> Add detail description to Default for argument --backend-protocol

src/quantum/azext_quantum/_params.py, src/quantum/azext_quantum/commands.py, src/quantum/azext_quantum/operations/job.py
Adding batching job support to `az quantum`.
---
=> RE batching

src/containerapp/HISTORY.rst
---
Remove history notes of the reverted version 0.3.22 
Previous PR to revert 0.3.22: #5896 
Original PR for 0.3.22: #5843 
containerapp
=> Remove history notes of the reverted version 0.3.22

src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
=> {AKS} az aks update: enable outbound migration from/to udr in BYO vnet scenario

src/bastion/HISTORY.rst, src/bastion/README.md, src/bastion/azext_bastion/_validators.py, src/bastion/azext_bastion/custom.py, src/bastion/azext_bastion/tunnel.py, src/bastion/setup.py
=> [Azure Bastion] Bug fixes in IP connect

.github/PULL_REQUEST_TEMPLATE.md
=> Add more description for release precondition in pull request template

src/quantum/azext_quantum/operations/job.py
Found and fixed a bug where `job_params is not None` was needed in a logical expression in the `--job-params` parsing code for submitting QIR jobs.
```
az quantum run
az quantum execute
az quanrum job submit
```
---
=> [Quantum] Fix "NoneType is not iterable" error

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_no_ssh_key_and_update_ssh_public_key.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
If the cluster was created with `az aks create --name $CLUSTER_NAME --resource-group $RG_NAME --no-ssh-key`, this PR allows the customer to update ssh public key with `az aks update --name $CLUSTER_NAME --resource-group $RG_NAME --ssh-key-value $YOUR_SSH_KEY_VAULE`.
=> [AKS] Allow updating the ssh key value if cluster was created without ssh key

src/serial-console/HISTORY.rst, src/serial-console/azext_serialconsole/custom.py, src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VM.yaml, src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VMSS.yaml, src/serial-console/azext_serialconsole/tests/latest/recordings/test_enable_disable.yaml, src/serial-console/setup.py
The changes in the pull request are to address a problem found in the azure cli serial-console extension where the wrong resource group was being found if the storage account belong to a different resource group.  The code fixes this issue by using the correct resource group based on where the storage account gets created.
---
az serial-console connect -g MyResourceGroup -n MyVmName
You only need to update the version information in file setup.py and historical …
=> Retrieve the correct resource group based on the storage account

src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
{AKS} Fix UT for setting up network profile. Test failure caused by PR [#25256](https://github.com/Azure/azure-cli/pull/25256). Would remove this temp fix once aks-preview's dependency on core azure-cli is updated to `2.26.0`.
=> {AKS} Fix UT for setting up network profile

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py
---
Change the short name of option `--source-resource-id` in command `az aks trustedaccess rolebinding create` from `-s` to `-r`.
The deprecated short name `-s` is hidden by default and will be completely removed when aks-preview's dependency on the cli core version is updated to [2.47.0](https://github.com/Azure/azure-cli/milestone/128). For current dependency, see [doc](https://github.com/Azure/azure-cli-extensions/tree/main/src/aks-preview#dependency-between-aks-preview-and-azure-cliacs-azure-cli-core).
- `az aks trustedaccess rolebinding create`
Once your pull request is merged into main …
=> {AKS} `az aks trustedaccess rolebinding create`: Change the short name of option `--source-resource-id` to `-r`

src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Current cli tests which involves node image upgrades are not meaningful. These tests is relying on a buggish behavior in upgradeNodeImageVersion API to function. If we are upgrading the node image of an agent pool which is already on the latest node image version, upgradeNodeImageVersion API will exit silently after very long validation on the async side.
Existing nodeimageupgrade related cli tests are all trying to upgrade the node image of clusters which is already on the latest image version. And it only checks if the agent pool goes into UpgradingNodeImageVersion provisioningState. It never verifies whether the upgrade succeeded or not, which make these tests meaningless. 
After changing upgradeNodeImageVersion API to return 304 when agent pool is already on the latest version. …
=> {AKS} Update cli tests disable upgrade node image related tests

src/ssh/HISTORY.md, src/ssh/azext_ssh/ip_utils.py, src/ssh/setup.py
---
az ssh vm
closed https://github.com/Azure/azure-cli-extensions/issues/5984
=> fix public ip address ref

src/spring/azext_spring/tests/latest/custom_preparers.py, src/spring/azext_spring/tests/latest/recordings/test_app_deploy_container.yaml, src/spring/azext_spring/tests/latest/recordings/test_application_accelerator.yaml, src/spring/azext_spring/tests/latest/recordings/test_live_view.yaml, src/spring/azext_spring/tests/latest/recordings/test_persistent_storage.yaml, src/spring/azext_spring/tests/latest/recordings/test_predefined_accelerator.yaml, src/spring/azext_spring/tests/latest/recordings/test_stop_and_start_service.yaml, src/spring/azext_spring/tests/latest/test_asa_application_accelerator.py, src/spring/azext_spring/tests/latest/test_asa_application_live_view.py, src/spring/azext_spring/tests/latest/test_asa_predefined_accelerator.py, src/spring/azext_spring/tests/latest/test_asa_scenario.py
=> [Spring] Add `@SpringPreparer` for scenario test

src/automation/azext_automation/tests/latest/recordings/test_automation.yaml, src/automation/azext_automation/tests/latest/recordings/test_automation_schedule.yaml, src/automation/azext_automation/tests/latest/recordings/test_automation_software_update_configuration.yaml, src/automation/azext_automation/tests/latest/test_automation_scenario_manual.py
---
```
az automation runbook show
az automation runbook list
az automation runbook delete
```
=> {CI} Add test for the automation extension.

src/aks-preview/azext_aks_preview/_roleassignments.py
---
> In version 2.46.0 of azure-cli, due to the [update of the API](https://github.com/Azure/azure-cli/pull/25452) used by the role assignment-related operations, when the role assignment already exists, the returned error message is changed, and the code that previously performed this type of error checking can no longer handle such error, so that the command finally raise an error similar to `Cannot create a role assignment for xxx...`.
> 
> The error message of adding exiting role assignment is (sending request with API version `2022-04-01`)
> ```
> (RoleAssignmentExists) The role assignment already exists.
> Code: RoleAssignmentExists
> Message: The role assignment already exists.
> ```
> 
> …
=> {AKS} `az aks update`: Remove the error that could not create a role assignment error when the role assignment already exists

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/commands.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_ingress_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
```
az containerapp ingress update
```
Today, the `az containerapp ingress enable` command is the same on that can be used to update an ingress as well. But this is not a patch operation which leads to unintended updates to the other properties of the ingress.
This command allows users to update single properties without affecting others. Also, the verb used here is more intuitive about it being to update an ingress.
resolves #6050
=> [ContainerApp] Fix #6050: `az containerapp ingress update`: Add Command to Update Container App Ingress

src/aks-preview/HISTORY.rst, src/aks-preview/setup.py
---
Update history and release a new version of aks-preview.
=> {AKS} Release aks-preview

src/datamigration/HISTORY.rst, src/datamigration/azext_datamigration/manual/custom.py, src/datamigration/setup.py
The PR is to fix a bug for the new CLI commands "az datamigration login-migration".
Local Test:
with this fix, it can migrate logins of source database to the target database.
Below image is the logins of target MI server, the new logins are from the source database by running this CLI command:
---
=> fix bug for a parameter as a list

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
add checks for decorator mode to better match the
logic in the acs (GA CLI) and avoid reading any values from mc unless doing CREATE
---
=> {AKS} `az aks update`: refactor pod_cidr and network_plugin_mode getters to check decorator mode

src/aks-preview/HISTORY.rst, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_podidentity.py, src/aks-preview/azext_aks_preview/_roleassignments.py, src/aks-preview/azext_aks_preview/addonconfiguration.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
---
- Fix the breaking change caused by default API version bump of the auth SDK, [PR #25452](https://github.com/Azure/azure-cli/pull/25452).
- Update pod identity related test cases and enable these cases by default in the cli runner.
- Remove some unused role assignment related code (previously used for attach/detach acr).
`az aks pod-identity`
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR …
=> {AKS} Fix role assignment failure caused by the breaking change of default API version bump of the auth SDK

src/ssh/HISTORY.md, src/ssh/azext_ssh/ip_utils.py, src/ssh/setup.py
---
Without the fix:
```bash
$ az ssh vm -n <myvm> -g <mygroup>
The command failed with an unexpected error. Here is the traceback:
'publicIPAddress'
File "/Users/dion/.virtualenvs/tempenv-5ea7193651842/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
cmd_result = self.invocation.execute(args)
File "/Users/dion/.virtualenvs/tempenv-5ea7193651842/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
raise ex
File "/Users/dion/.virtualenvs/tempenv-5ea7193651842/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
results.append(self._run_job(expanded_arg, cmd_copy))
File …
```
=> Fix SSH into VMs without public IP

.github/workflows/AddPRComment.yml
---
If pr title contains single quotes, bash will report an error when reading `github.event.pull_request.title`.
According to [github doc](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable)：
We should stored expression in memory and used as a variable, and doesn't interact with the script generation process.
In addition, consider using double quote shell variables to avoid word splitting.
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically. …
=> {CI} Update AddPRComment.yml

src/index.json
=> Release ML 2.16.0

src/containerapp/azext_containerapp/_params.py
---
`az container app`
Add documentation link for scale rule type parameter.  Fixes [GitHub Issue 25014](https://github.com/Azure/azure-cli/issues/25014)
=> {containerapp} Add scale rule type parameter

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_kube_proxy_config.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
=> {AKS} `az aks update`: don't always use the current kube-proxy config when updating cluster

src/monitor-control-service/HISTORY.rst, src/monitor-control-service/azext_amcs/manual/_help.py, src/monitor-control-service/azext_amcs/tests/latest/recordings/test_amcs_data_collection_endpoint.yaml, src/monitor-control-service/azext_amcs/tests/latest/recordings/test_monitor_control_service_commands.yaml, src/monitor-control-service/azext_amcs/tests/latest/rule_files/rule_file.json, src/monitor-control-service/setup.py
---
closed https://github.com/Azure/azure-cli/issues/26348
=> add monitor data-collection rule file json file example

src/aks-preview/HISTORY.rst, src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_azuremonitormetrics.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
- Patch release history to add when the default API version was updated to 2021-11-01-preview.
- Update default test matrix to exclude case `test_aks_create_with_azuremonitormetrics` and `test_aks_update_with_azuremonitormetrics` as the resource provider namespace is not registered in the test sub used by cli runner.
- Fix recording file `test_aks_update_with_azuremonitormetrics.yaml`.
N/A …
=> {AKS} Patch release history

src/containerapp/azext_containerapp/_constants.py, src/containerapp/azext_containerapp/_dev_service_utils.py, src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/_managed_service_utils.py, src/containerapp/azext_containerapp/_models.py, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/_sdk_models.py, src/containerapp/azext_containerapp/_utils.py, src/containerapp/azext_containerapp/commands.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dev_service_binding_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Add CLI command for binding a service to an app
---
=> Add CLI command for binding a service to a container app

src/vm-repair/HISTORY.rst, src/vm-repair/azext_vm_repair/repair_utils.py, src/vm-repair/azext_vm_repair/tests/latest/test_repair_commands.py, src/vm-repair/setup.py
=> [Vm-repair] Fix bug in encryption checks

src/containerapp/azext_containerapp/tests/latest/recordings/test_container_app_mount_secret_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_mount_secret_volume.py
---
We used to return a payload of each individual secret mounted when mounting all secrets. However, we recently changed the behavior to return no secret if all secrets are mounted as secrets can change in the future if user adds/removes secrets.
fixing CLI test to reflect this change.
az containerapp create --secret-volume-mount …
=> update mount secret volume test

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/addonconfiguration.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
=> [AKS PREVIEW]aks create: Change the default value of --enable-msi-auth-for-monitoring to true and add check for airgap clouds

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_helpers.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
---
Align the implementation with official azure-cli. Fix issue [#26444](https://github.com/Azure/azure-cli/issues/26444).
`az aks get-credentials`
=> {AKS} Fix #26444: `az aks get-credentials`: Fix command not using the value set by environment variable `KUBECONFIG`

src/scvmm/azext_scvmm/_help.py, src/scvmm/azext_scvmm/_params.py, src/scvmm/azext_scvmm/commands.py, src/scvmm/azext_scvmm/custom.py, src/scvmm/azext_scvmm/tests/latest/recordings/test_scvmm.yaml, src/scvmm/azext_scvmm/tests/latest/test_scvmm_scenario.py, src/scvmm/azext_scvmm/vendored_sdks/aio/operations/_virtual_machines_operations.py, src/scvmm/azext_scvmm/vendored_sdks/operations/_virtual_machines_operations.py
---
az scvmm vm create-checkpoint --subscription contoso-sub \
--resource-group contoso-rg --name contoso-vm --checkpoint-name contoso-chkpt-name \
--checkpoint-description contoso-chkpt-description
az scvmm vm delete-checkpoint --subscription contoso-sub \
--resource-group contoso-rg --name contoso-vm --checkpoint-id checkpoint-guid
az scvmm vm restore-checkpoint --subscription contoso-sub \
--resource-group contoso-rg --name contoso-vm --checkpoint-id checkpoint-guid
az scvmm vm delete --subscription contoso-sub \
--resource-group contoso-rg --name contoso-avset --deleteFromHost
Once your pull …
=> AzCli support for checkpoint operations and added deleteFromHost flag for VM delete

src/interactive/HISTORY.rst, src/interactive/azext_interactive/azclishell/__init__.py, src/interactive/azext_interactive/azclishell/app.py
---
Prevent users from exiting the entire az interactive by using Ctrl+C during command execution
az interactive
=> {interactive} Fix bugs of CTRL+C to cease the whole interactive mode

src/datamigration/HISTORY.rst, src/datamigration/README.md, src/datamigration/azext_datamigration/manual/_help.py, src/datamigration/azext_datamigration/manual/_params.py, src/datamigration/azext_datamigration/manual/commands.py, src/datamigration/azext_datamigration/manual/custom.py, src/datamigration/azext_datamigration/manual/helper.py, src/datamigration/setup.py
The PR is to add new CLI commands "az datamigration sql-server-schema". The same command for Powershell has been published. The new CLI commands has passed local tests.
The local test commands:
az datamigration sql-server-schema --action "MigrateSchema" --src-sql-connection-str "Server=;Initial Catalog=;User ID=;Password=" --tgt-sql-connection-str "Server=;Initial Catalog=;User ID=;Password="
az datamigration sql-server-schema --action "GenerateScript" --src-sql-connection-str "Server=;Initial Catalog=;User ID=;Password=" --tgt-sql-connection-str "Server=;Initial Catalog=;User ID=;Password=" --output-folder "C:\OutputFolder"
az datamigration sql-server-schema --action "GenerateScript" --src-sql-connection-str "Server=;Initial Catalog=;User ID=;Password=" --tgt-sql-connection-str …
=> Add sqlServerSchema command in data migration

src/azure-firewall/HISTORY.rst, src/azure-firewall/azext_firewall/custom.py, src/azure-firewall/setup.py
---
Fix: https://github.com/Azure/azure-cli/issues/26592
=> [Firewall] Fix #26592: `az network firewall policy`: Unhashable `--identity`

linter_exclusions.yml, src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_enable_network_observability.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_enable_network_observability.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
The `--enable-network-observability` flag is used to enable network observability on an aks cluster. This adds the cli command to enable or disable this extension.
---
`az aks create`
=> Add the network observability cli extension

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_models.py, src/containerapp/azext_containerapp/_sdk_models.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_container_app_mount_azurefile_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_azurefile.py, src/containerapp/azext_containerapp/tests/latest/test_containerappjob_with_yaml.py
---
az containerapp create --yaml
az containerapp update --yaml
=> Support subPath and mountOptions for AzureContainerApps

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_constants.py, src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/_utils.py, src/containerapp/azext_containerapp/commands.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dev_service_binding_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Closes https://github.com/Azure/azure-cli-extensions/issues/6330
=> Add support for creation/deletion of kafka

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_up_utils.py, src/containerapp/azext_containerapp/_utils.py, src/containerapp/azext_containerapp/custom.py
=> Fix validation for containerapp name

src/spring/HISTORY.md, src/spring/azext_spring/_help.py, src/spring/azext_spring/_params.py, src/spring/azext_spring/commands.py, src/spring/azext_spring/gateway.py, src/spring/azext_spring/tests/latest/files/gateway_addon_configs.json, src/spring/azext_spring/tests/latest/recordings/test_gateway.yaml, src/spring/azext_spring/tests/latest/test_asa_gateway.py, src/spring/setup.py
=> [Spring] Add addon configs & allowedOriginPatterns & restart for Spring Cloud Gateway

src/index.json, src/service_name.json
CLI extension for the Partner Center
version: v0.2.3-alpha
Currently, experimental support for Microsoft Partner Center Marketplace management commands, commissioned by Global Partner Services (GPS) division.
- @kevinhillinger 
- @bobjac 
- Type: External repository
- URL: https://github.com/Azure/partnercenter-cli-extension
- updating index to point to 0.2.3 version of the extension
- updating service name to align to current naming conventions, e.g. "Microsoft Partner Center"
=> Partner Center Extension - v0.2.3-alpha

src/amg/azext_amg/_help.py
=> amg: add more datasource examples

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_eventstream.yaml
---
az containerapp env logs show
=> containerapp fix env logs show error

src/amg/azext_amg/_help.py, src/amg/setup.py
=> amg: add examples for manage Prometheus 

scripts/ci/index_ref_doc.py
=> {CI} Temporarily skip the detection of the partnercenter extension in IndexRefDocVerify

src/service_name.json
In aligning with the Azure PowerShell reference TOC, _Account_ should be plural _Accounts_, and _App Services_ should be singular _App Service_.
=> {all services] TOC | fixed incorrect plural product names

scripts/ci/breaking_change_test.py
---
The `--repo` parameter of `azdev command-change meta-export` should use the path of the cli-extension repo instead of the path of the cli repo.
=> {CI} Fix breaking change test

scripts/ci/index_ref_doc.py, scripts/refdoc/generate.py
---
Add a new parameter `dep_url (dependent url)`. 
If a extensionA is depend on another extensionB, will install extensionB first.
In this case, will install containerapp extension before verify ref docs for containerapp-preview extension.
=> {CI} Fix verify ref docs

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
---
Fix unexpected error 'Addon "web_application_routing" is not enabled in this cluster' when trying to update the web app routing addon for an managed cluster that already has it enabled. PR forked from #6429, thanks to the contribution by @tg123. Fix issue [#3761](https://github.com/Azure/AKS/issues/3761).
`az aks addon update` …
=> {AKS} `az aks addon update`: Fix unexpected error 'Addon "web_application_routing" is not enabled in this cluster'

src/bastion/HISTORY.rst, src/bastion/azext_bastion/tunnel.py, src/bastion/setup.py
fixes Azure/azure-cli-extensions#6478
`az network bastion rdp --name "" --resource-group "" --target-resource-id "" --disable-gateway` fails with below error:
```
Exception in thread Thread-1 (_start_tunnel):
File "threading.py", line 1016, in _bootstrap_inner
File "threading.py", line 953, in run
File "C:\Users\francisco.nabas.azure\cliextensions\bastion\azext_bastion\custom.py", line 335, in _start_tunnel
tunnel_server.start_server()
File "C:\Users\francisco.nabas.azure\cliextensions\bastion\azext_bastion\tunnel.py", line 194, in start_server
self._listen()
File "C:\Users\francisco.nabas.azure\cliextensions\bastion\azext_bastion\tunnel.py", line 123, in _listen
auth_token = self._get_auth_token()
File …
```
=> {Bastion} az network bastion rdp fails with NullPointerException

src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
{AKS} Fix test case `test_aks_create_and_update_web_application_routing_dns_zone`. Follow-up of PR #6512.
=> {AKS} Fix test case `test_aks_create_and_update_web_application_routing_dns_zone`

linter_exclusions.yml, src/index.json
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.21.4
---
=> [IoT] IoT extension release v0.21.4

src/ssh/HISTORY.md, src/ssh/azext_ssh/connectivity_utils.py, src/ssh/setup.py
- Small bug fix. Function that checked that target port matched allowed port for arc connections now returns true if user has no permission to read service config.
- Error when user tries to connect to arc from arm64 machine
---
=> [SSH][Bug Fix] Error when user tries to download proxy for unsupported arm64 and not attempt to update service conf when user has no permission

src/containerapp-preview/HISTORY.rst, src/containerapp-preview/azext_containerapp_preview/__init__.py, src/containerapp-preview/azext_containerapp_preview/_utils.py
=> containerapp-preview auto install containerapp extension

src/elastic-san/HISTORY.rst, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_create.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_delete.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_list.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_list_sku.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_show.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_update.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_wait.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_create.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_delete.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_list.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_show.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_update.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_create.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_delete.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_list.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_show.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_update.py, src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_wait.py, src/elastic-san/azext_elastic_san/azext_metadata.json, src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_scenarios.yaml, src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_volume_group_and_volume_scenarios.yaml, src/elastic-san/azext_elastic_san/tests/latest/test_elastic_san.py, src/elastic-san/setup.py
---
Support 2022-12-01-preview regen and rerun tests, --tags were removed by volume and volume-group
=> [Elastic-SAN] BREAKING CHANGE `az elastic-san`: Support private endpoint, remove `--tags` from volume-group and volume

src/service_name.json
We have dropped "Azure" and "Microsoft" prefixes from our reference TOC.  This PR changes ....
**az dms**
**az amlfs**
- https://learn.microsoft.com/en-us/azure/templates/microsoft.storagecache/amlfilesystems
- https://learn.microsoft.com/en-us/rest/api/storagecache/aml-filesystems
**az graph-services**
- https://learn.microsoft.com/en-us/rest/api/graphservices/
**Reference TOC guidelines**
1.	Placement in the reference TOC should reflect customer search terms and patterns.  
2.	The reference TOC is organized by Azure service or product without the “Azure” or “Microsoft” prefix.
3.	The reference TOC organization is intended to help our customers answer the question: “What Azure CLI commands are available to me when working with [an Azure product]?”
=> {all services} service name mapping updates

src/containerapp/azext_containerapp/containerapp_auth_decorator.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_auth_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_auth_commands.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py
---
az containerapp auth show/update
=> containerapp refactor containerapp auth show/update

src/containerapp/azext_containerapp/base_resource.py, src/containerapp/azext_containerapp/containerapp_job_decorator.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_eventjob_crudoperations_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_manualjob_crudoperations_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_manualjob_withidentity_crudoperations_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_manualjob_withsecret_crudoperations_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerappjob_create_with_yaml.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerappjob_eventtriggered_create_with_yaml.yaml
---
Refactor `az containerapp job show/list/delete/create` for containerapp-preview extension.
Similar to commands `az containerapp create/show/list/delete` refactor.
az containerapp job show/list/delete/create
=> containerapp refactor job create

scripts/ci/build_ext_cmd_tree.sh, scripts/ci/update_ext_cmd_tree.py
---
When two extensions have the same command, the following error will be reported:
`Exception: Key: show already exists in containerapp. 2 extensions cannot have the same command!`
Temporarily skip the containerapp-preview extension to aviod this error.
Which will cause the containerapp-preview extension to be unable to use the dynamic load function.
That is, when using the unique command of containerapp-preview, the extension cannot be automatically prompted to install.
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` …
=> {CI} Fix command tree broken issue

src/interactive/HISTORY.rst, src/interactive/azext_interactive/azclishell/app.py, src/interactive/azext_interactive/azclishell/recommendation.py
see https://dev.azure.com/devrel/Cloud%20Advocacy/_workitems/edit/101759
---
az interactive
=> [Interactive] Add command skipped message in Scenario Execution Mode

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_migrate_cluster_to_cilium_dataplane.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
Add the `--network-dataplane` flag to the `az aks update` command. This will allow customers to update an existing cluster to enable [Azure CNI Powered by Cilium](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium)
---
`az aks update --network-dataplane=cilium`
=> [AKS] Add --network-dataplane to az aks update command

src/db-up/HISTORY.rst, src/db-up/azext_db_up/custom.py, src/db-up/setup.py
Pin `pymssql==2.2.7` to avoid `2.2.8` issue https://github.com/pymssql/pymssql/issues/832
---
=> [db-up] Pin `pymssql==2.2.7`

azure-pipelines.yml
---
[Change Verify Ref Docs from full test to incremental test](https://github.com/Azure/azure-cli-extensions/pull/6581) is not a good solution.
Because if the extension is not in the azure-cli-extensions repo, it will never be tested.
But all extensions are independent of each other, we should not let an issue with one extension block other extensions.
So mark ref doc test as continueOnError so it will not block pull request from being merged.
You only need to update …
=> {CI} Mark ref doc test as continueOnError

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_utils.py, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py
This PR adds ability to fetch new properties from 2022-09-01 ARM metadata in an on-premises environment that is currently in preview.
**IMPORTANT:** I ran "azdev style azext_connectedk8s", but there are preexisting formatting errors unrelated to my change. I assumption is the project never followed the style guides to begin with. If the style guide should be followed, I am not going to fix those issues in this PR as there are many of them and likely not related to my changes. …
=> update connectedk8s for ARM metadata 2022-09-01

src/databox/HISTORY.rst, src/databox/azext_databox/custom.py, src/databox/azext_databox/tests/latest/recordings/test_databox_transfer_all_details.yaml, src/databox/azext_databox/tests/latest/test_databox_scenario.py, src/databox/setup.py
=> [Databox] `az databox job create`: Add new parameters `--transfer-all-blobs` and `--transfer-all-files` to support setting transfer all details

scripts/ci/build_ext_cmd_tree.sh, scripts/ci/index_ref_doc.py, scripts/ci/verify_linter.py, scripts/refdoc/generate.py
=> {CI} Revert hack code for containerapp-preview

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_image_integrity.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/linter_exclusions.yml, src/aks-preview/setup.py
---
`az aks update --disable-image-integrity`
=> [image integrity] add image integrity disable

src/aks-preview/HISTORY.rst, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_enable_disable.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_pluginca.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
Add pluginca parameters for az aks mesh command
- az aks mesh enable -g rg-name -n mc-name \
--key-vault-id akv-id \
--ca-cert-object-name ca-cert-name \
--ca-key-object-name ca-key-name \
--root-cert-object-name root-cert-name \
--cert-chain-object-name cert-chain-name
`az aks mesh enable `
=> Add pluginca parameters for az aks mesh command

src/interactive/HISTORY.rst, src/interactive/azext_interactive/azclishell/__init__.py, src/interactive/azext_interactive/azclishell/app.py, src/interactive/azext_interactive/azclishell/configuration.py
Before:
After:
---
`az interactive`
=> [Interactive] Optimize the visualization of help text when the window is reduced horizontally

src/datamigration/azext_datamigration/generated/_help.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_database_migrations_sql_db_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_database_migrations_sql_db_operations.py
---
datamigration sql-db create
Add description in "help". 
If the customer does not have table in the target database, suggest them to use "az datamigration sql-server-schema" command to do schema migration firstly.
Checklist
=> update description of datamigration sql-db create

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/commands.py
---
az containerapp job
az containerapp env storage
az containerapp env workload-profile
az containerapp hostname add
az containerapp update/create
az containerapp revision copy
az containerapp hostname bind
=> containerapp remove preview tag for some commands

.github/policies/resourceManagement.yml
---
There is a breaking change happening during the automated migration.
The `action: Opened` condition is added by [this PR](https://github.com/Azure/azure-cli/pull/26925) during the automated migration, so policy will not act when someone add labels.
Possible solution: use `action: Labeled`.
=> {CI} Fix policy migration issue

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_enable_workload_profiles_three_state_flag.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_with_workloadprofile_yaml.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_workload_profiles_delete.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_workload_profiles_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_workload_profiles_e2e_no_waits.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_workload_profile_commands.py
---
az containerapp env create
=> containerapp add three type for enable workload profiles

src/containerapp/azext_containerapp/_utils.py
fixes https://github.com/Azure/azure-cli-extensions/issues/6524
Container Apps lets me create a container with dashes ("-") in the name, but then I can't reference that container in the --bind parameter.
```
cli.azure.cli.core.azclierror: Traceback (most recent call last):
File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job …
```
=> {Container App} az containerapp create --bind "my-app" throws error when service has dashes in the name "-"

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_constants.py, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/containerapp_auth_decorator.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_auth_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_auth_commands.py
… for az cotnainerapp auth
---
=> Support --token-store, --sas-url-secret, --sas-url-secret-name, --yes for container app auth

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/containerapp_decorator.py, src/containerapp/azext_containerapp/containerapp_job_decorator.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_preview_create_with_environment_id.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerappjob_create_with_environment_id.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_create_update_with_yaml.py, src/containerapp/azext_containerapp/tests/latest/test_containerappjob_with_yaml.py
---
When --environment is provided and the environmentId value does not exist in --yaml, the value in --environment is used.
When the environmentId value existed in --yaml, use the environmentId in --yaml.
```
az containerapp create --yaml --environment
az containerapp job create --yaml --environment
```
=> containerapp allow yaml without environment

src/dnc/HISTORY.rst, src/dnc/azext_dnc/aaz/latest/dnc/delegated_subnet_service/_create.py, src/dnc/azext_dnc/aaz/latest/dnc/delegated_subnet_service/_delete.py, src/dnc/azext_dnc/aaz/latest/dnc/delegated_subnet_service/_show.py, src/dnc/azext_dnc/aaz/latest/dnc/delegated_subnet_service/_wait.py, src/dnc/azext_dnc/azext_metadata.json, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_controller_create.yaml, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_controller_create_test_purpose.yaml, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_controller_delete.yaml, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_controller_show.yaml, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_delegated_subnet_service_create.yaml, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_delegated_subnet_service_delete.yaml, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_delegated_subnet_service_show.yaml, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_orchestrator_instance_service_create.yaml, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_orchestrator_instance_service_delete.yaml, src/dnc/azext_dnc/tests/latest/recordings/test_dnc_orchestrator_instance_service_show.yaml, src/dnc/setup.py
=> Add allocationBlockPrefixSize to support vnetBlock

src/mobile-network/HISTORY.rst, src/mobile-network/azext_mobile_network/aaz/latest/mobile_network/sim/group/_bulk_upload_sims.py, src/mobile-network/setup.py
---
az mobile-network
Enriches the documentation for sim bulk-upload.
=> Richer example for bulk-sim-upload

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_clients.py, src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/_transformers.py, src/containerapp/azext_containerapp/commands.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_usages.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_env_commands.py
=> Add list-usages command for container app

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_loadbalancer.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
=> {AKS} Outbound ip/ outbound ipprefix and managed outbound ip should be mutually exclusive

src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/commands.py, src/containerapp/azext_containerapp/containerapp_env_decorator.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_managed_service_binding_e2e.yaml
---
az containerapp env create
az containerapp auth update
=> {containerapp} add --enable-wordload-profiles helps and add preview tag

src/vm-repair/HISTORY.rst, src/vm-repair/azext_vm_repair/command_helper_class.py, src/vm-repair/azext_vm_repair/custom.py, src/vm-repair/azext_vm_repair/repair_utils.py, src/vm-repair/azext_vm_repair/scripts/win-enable-nested-hyperv.ps1, src/vm-repair/azext_vm_repair/telemetry.py, src/vm-repair/azext_vm_repair/tests/latest/test_repair_commands.py, src/vm-repair/setup.py
This PR contains:
ARM64 VM's support for vm repair creation
Telemetry Fix for repair-and-restore command
Repair VM fix for gen1 VM attaching disk on SCSI controller, preventing nested VM from booting (by Ryan McCallum)
---
az vm repair create -g {rg} -n {vm}
=> [vm-repair] arm64 support And Bug Fix for telemetry

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_enable_cost_analysis.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_enable_cost_analysis.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
=> Add cost-analysis preview CLI flag

src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
The PR updates AKS tests to allow enable AAD legacy when creating cluster. Picked from #6670.
=> {AKS} Update AKS tests to allow enable AAD legacy when creating cluster

src/spring/azext_spring/_constant.py, src/spring/azext_spring/_utils.py, src/spring/azext_spring/spring_instance.py
help customers register AKS RP when creating VNET instance
=> [Spring] help customers register AKS RP when creating VNET instance

.github/CODEOWNERS, src/appservice-kube/HISTORY.rst, src/appservice-kube/azext_appservice_kube/_help.py, src/appservice-kube/azext_appservice_kube/custom.py, src/appservice-kube/setup.py
=> Add validation for `az webapp scale`

src/automation/HISTORY.rst, src/automation/azext_automation/manual/_params.py, src/automation/setup.py
=> Removing validation for classification

src/spring/azext_spring/_log_stream.py
Previously, we get log stream url by modifying test endpoint. Just refactor it to use service fqdn directly in this PR.
---
=> [Spring] Use service fqdn to call logstream

src/aks-preview/azext_aks_preview/_openai_wrapper.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
This PR enhance run script to capture error output, which we can feed to chatgpt to suggest corrections, etc
az aks copilot
=> capture az error output and auto-fix the script

src/spring/HISTORY.md, src/spring/azext_spring/_help.py, src/spring/azext_spring/_params.py, src/spring/azext_spring/_transformers.py, src/spring/azext_spring/commands.py, src/spring/azext_spring/spring_instance.py, src/spring/azext_spring/tests/latest/recordings/test_list_support_server_versions.yaml, src/spring/azext_spring/tests/latest/test_asa_server_version.py
Add new command `az spring list-support-server-versions` to list all supported server versions.
=>  Add new command `az spring list-support-server-versions` 

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_egress_gateway.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
=> Add enable ASM egress gateway commands for az aks mesh

src/index.json, src/palo-alto-networks/HISTORY.rst, src/palo-alto-networks/azext_palo_alto_networks/aaz/latest/palo_alto/cloudngfw/local_rulestack/_commit.py, src/palo-alto-networks/azext_palo_alto_networks/azext_metadata.json, src/palo-alto-networks/azext_palo_alto_networks/tests/latest/recordings/test_palo_alto_cloudngfw_local_rulestack_commit.yaml, src/palo-alto-networks/azext_palo_alto_networks/tests/latest/recordings/test_palo_alto_networks_cloudngfw_firewall.yaml, src/palo-alto-networks/azext_palo_alto_networks/tests/latest/test_palo_alto_networks.py, src/palo-alto-networks/setup.py
---
fixed: https://github.com/Azure/azure-cli/issues/27401
=> {PaloAltoNetworks} Fix `az palo-alto cloudngfw local-rulestack commit` command failing

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py, src/index.json
In this PR, I check if the infrastructure and distribution is AKS-HCI. If its AKS-HCI, I am skipping the Pre-onboarding checks to accommodate the low bandwidth networks they run on. This PR will be an immediate fix for multiple customer issues. We keep the pre-onboarding checks intact for all the other infra and distros. 
---
az connectedk8s connect 
- Performed the azdev style, test and lint locally. 
- Also performed the azdev build to build a local .whl file.
=> Skip onboarding prechecks for AKS-HCI

src/service_name.json
`az stack-hci-vm` is in private preview and will not be published until end of October / early November.  Although this should never have been a top-level node, it was entered this way and therefore causes an empty node as seen here:
=> removed az stack-hci-fm

src/ssh/HISTORY.md, src/ssh/azext_ssh/target_os_utils.py, src/ssh/azext_ssh/tests/latest/test_target_os_utils.py, src/ssh/setup.py
Fix: https://github.com/Azure/azure-cli-extensions/issues/6655
---
=> [Bug Fix] Fix "cannot unpack non-iterable NoneType object" error in OS check

src/connectedk8s/.gitignore, src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_utils.py, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/azext_connectedk8s/tests/latest/README.md, src/connectedk8s/azext_connectedk8s/tests/latest/config.json.dist, src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py, src/connectedk8s/setup.py
enforce valid custom locations SP app object id
add .gitignore and test configuration file
---
Style errors from the command were already there. Didn't seem style guide was previously enforced, so won't fix these errors here.
=> enforce valid custom locations SP app object id

src/vmware/HISTORY.md, src/vmware/setup.py
=> Publish vmware extension version 6.0.0

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/containerapp_decorator.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_container_app_mount_secret_update_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_mount_secret_volume.py
---
az containerapp update
fixes bug for using the update command to mount a secret volume, checks for if volume is null since volume is now a NoneType object and mounts volumeMount as an array 
=> [containerapp] Fix `az containerapp update --secret-volume-mount` appending to NoneType object bug

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/containerapp_env_decorator.py, src/containerapp/azext_containerapp/containerapp_job_decorator.py
---
`az containerapp job create`
=> [containerapp] `az containerapp job create`: Fix AttributeError when `--trigger-type` is None

.github/pull_request_template.md, scripts/ci/test_index.py
=> {CI} Add new comment to explain the reason that pin the wheel to 0.30.0

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py
---
Update help information for option `--node-osdisk-size`. The disk size specified by this option is actually in GiB (instead of GB). Fix issue [#27461](https://github.com/Azure/azure-cli/issues/27461)
- az aks create
- az aks nodepool add
=> {AKS} Fix #27461 `az aks create`: Update help information for option `--node-osdisk-size`

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py, src/aks-preview/azext_aks_preview/azurecontainerstorage/acstor_ops.py, src/aks-preview/setup.py
=> AKS: Rearrange a few helm values for Azure container storage

src/webpubsub/HISTORY.rst, src/webpubsub/azext_webpubsub/_client_factory.py, src/webpubsub/azext_webpubsub/_help.py, src/webpubsub/azext_webpubsub/_params.py, src/webpubsub/azext_webpubsub/commands.py, src/webpubsub/azext_webpubsub/replica.py, src/webpubsub/azext_webpubsub/tests/latest/recordings/test_webpubsub_replica.yaml, src/webpubsub/azext_webpubsub/tests/latest/test_webpubsub_replica.py, src/webpubsub/setup.py
=> Support replica command in az webpubsub

src/aosm/HISTORY.rst, src/aosm/azext_aosm/_configuration.py, src/aosm/setup.py
Python 3.11 dataclasses require hashable defaults to use a default_factory.
This PR implements that for the az aosm extension.
Fixes https://github.com/Azure/azure-cli-extensions/pull/6426#discussion_r1371209404
Testing that this resolves all instance of the `mutable default is not allowed` error **to be completed by @yanzhudd**, as agreed offline. 
Function testing of the extension has been completed using the test suite with live tests.
---
az aosm nfd generate-config --definition-type cnf
Once your pull request is merged into main branch, a new pull request will be created to update …
=> Use default_factory when dataclass defaults are hashable

src/spring/HISTORY.md, src/spring/azext_spring/_params.py, src/spring/azext_spring/_validators_enterprise.py, src/spring/azext_spring/gateway.py, src/spring/azext_spring/tests/latest/recordings/test_gateway.yaml, src/spring/azext_spring/tests/latest/recordings/test_persistent_storage.yaml, src/spring/azext_spring/tests/latest/test_asa_gateway.py, src/spring/setup.py
=> Add apms parameter for Spring Cloud Gateway

src/index.json, src/service_name.json
=> [mariner-baremetal] Add mariner-baremetal extension to index.json

src/load/HISTORY.rst, src/load/azext_load/data_plane/load_test/custom.py, src/load/azext_load/data_plane/utils/utils.py, src/load/azext_load/data_plane/utils/validators.py, src/load/azext_load/tests/latest/constants.py, src/load/azext_load/tests/latest/recordings/test_load_app_component.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_app_component.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_create.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_create_with_args.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_delete.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_download_files.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_file.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_list.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_run_create.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_run_delete.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_run_download_files.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_run_list.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_run_metrics.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_run_server_metric.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_run_show.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_run_stop.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_run_update.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_server_metric.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_show.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_update.yaml, src/load/azext_load/tests/latest/recordings/test_load_test_update_with_config.yaml, src/load/azext_load/tests/latest/test_load_test.py, src/load/setup.py
---
This PR is for bug fixes in our existing extension for Azure Load Testing service under "load" extension. 
Changes in this PR:
1. Changed logical implementation of a two commands.
> - Added null support for argument --certificate and --subnet in commands "az load update" and "az load create" to remove those properties from test.
> - Added support to remove certificate, subnet from config file when provided in commands "az load update" and "az load create".
> - Logical implementation changed when using config file using argument --load-test-config-file in commands "az load test update" and "az load test create".  
> 
2. Added a new test case to cover new cases.
Changes will be reflected for …
=> [Azure Load Testing] Bug fix for two commands. Changing logical implementation.

src/index.json, src/service_name.json
Reverts Azure/azure-cli-extensions#6917 because extension is not ready for public preview.
=> Revert "[mariner-baremetal] Add mariner-baremetal extension to index.json"

scripts/ci/test_source.py
Modify the extension's azdev test to use the azext_xxx directory to avoid the issue of being unable to detect the test when it has the same name as the main module.
The containerapp module exists in both the main repo and the extension repo.
After installing the extension, running `azdev test containerapp` will not run any tests. The log is as follows:
To avoid this problem, modify the `azdev test $extension` command to the `azdev test azext_$extension` command.
---
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` …
=> {CI} Modify the extension's azdev test to use the `azext_xxx` directory

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_cni_overlay_migration_from_kubenet.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
`az aks update --network-plugin azure`
=> {AKS} `az aks update`: Add `--network-plugin` to support updating cluster networking settings

src/aks-preview/HISTORY.rst, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/agentpool_decorator.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/linter_exclusions.yml
---
- {AKS} `az aks nodepool add/update`: Add option `--enable-artifact-streaming` to support artifact streaming.
- PR forked from #6950.
- `az aks nodepool add`
- `az aks nodepool update`
=> {AKS} `az aks nodepool add/update`: Add option `--enable-artifact-streaming` to support artifact streaming

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_client_factory.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_approuting_enable_disable.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_approuting_enable_with_keyvault_secrets_provider_addon.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_approuting_update.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_approuting_zone_add_delete_list.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_approuting_zone_update.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_app_routing_enabled.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
`az aks approuting enable --enable-kv`
This command enables App Routing addon in given cluster. The optional flag enables the keyvault-secrets-provider addon in given cluster.
`az aks approuting disable`
This command disables App Routing in given cluster.
`az aks approuting update --attach-kv <keyvault-id>`
This command is used to update `keyvault id` in App Routing addon. Attach a `keyvault id` to the cluster to access secrets and certificates.
`az aks approuting zone add/delete --ids <dns-zone-resource-id> --attach-zones`
This command adds/deletes multiple DNS zone resource IDs in App Routing. It takes comma-separated list of DNS zone resource IDs. `--attach-zones` flag grants DNS zone …
=> [AKS] Approuting cli simplification

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_utils.py, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py
=> {connectedk8s} log debug if 'arcConfigEndpoint' doesn't exist

src/authV2/HISTORY.rst, src/authV2/azext_authV2/_help.py, src/authV2/azext_authV2/custom.py, src/authV2/azext_authV2/tests/latest/recordings/test_authV2_authclassic.yaml, src/authV2/azext_authV2/tests/latest/test_authV2_scenario.py, src/authV2/setup.py
---
Necessary to remove/redact output for auth-classic update command because secrets are getting unintentionally leaked in CI runs where users with higher privilege run update commands. Users should use "show" to get values of secrets instead of the returned output from update command. This change removes output from the command and fixes tests so that they're no longer reliant on the problematic behavior. 
az webapp auth-classic update 
You only need to update the version information in …
=> [AuthV2] BREAKING CHANGE: `az webapp auth-classic update`: Remove json output for auth-classic update

src/index.json
Introducing a new 2.0.0 version of the bare metal infrastructure extension. This update includes a powerful new force power management command specifically designed for SuperDome Flex Servers.
---
`az extension add --name baremetal-infrastructure` should install the new 2.0.0 version instead of old 1.0.0 version.
=> Update baremetalinstance version

src/confcom/HISTORY.rst, src/confcom/azext_confcom/data/internal_config.json, src/confcom/azext_confcom/kata_proxy.py, src/confcom/setup.py
Had an extra print statement that needs to be taken out.
---
az confcom
=> [confcom] taking out print statement

src/fleet/HISTORY.rst, src/fleet/azext_fleet/_help.py, src/fleet/azext_fleet/custom.py, src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubful.yaml, src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubless.yaml, src/fleet/setup.py
---
Updated help text examples for `az fleet`
=> [az fleet] updated help examples

src/elastic/azext_elastic/aaz/latest/elastic/monitor/_create.py, src/elastic/azext_elastic/aaz/latest/elastic/monitor/_list.py, src/elastic/azext_elastic/aaz/latest/elastic/monitor/_list_resource.py, src/elastic/azext_elastic/aaz/latest/elastic/monitor/_list_vm_host.py, src/elastic/azext_elastic/aaz/latest/elastic/monitor/tag_rule/_list.py, src/elastic/azext_elastic/azext_metadata.json, src/elastic/setup.py
=> Updating examples and SKU description for Elastic

src/bastion/HISTORY.rst, src/bastion/azext_bastion/_params.py, src/bastion/azext_bastion/custom.py, src/bastion/azext_bastion/developer_sku_helper.py, src/bastion/azext_bastion/tunnel.py, src/bastion/setup.py
=> [Bastion] adding rdp file to temp location and adding auth-type for rdp

azure-pipelines.yml
Update pipeline to use Python 3.11 as https://github.com/Azure/azure-cli/pull/26749 is merged
=> {CI} Update pipeline to use Python 3.11

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py
=> {AKS} `az aks update`: Remove outbound limit in update description

src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
Recent versions of the aks-preview Azure CLI extension use an AKS preview API (2023-08-02preview) that introduced networkPolicy=none. This causes the command to upgrade to Cilium dataplane to fail with a validation error when --network-policy isn't set explicitly to "cilium".
1. Azure CLI retrieves the current cluster, which defaults to networkPolicy=none.
2. Azure CLI modifies the cluster object, leaving networkPolicy=none if not explicitly overridden by a CLI flag.
3. Azure CLI sends the modified cluster object to AKS, which fails on validation that networkPolicy=cilium when networkDataplane=cilium.
Update Azure Preview CLI to force `--network-policy=cilium` when it is not specified and when `--network-dataplane=cilium` allows the validation to succeed. 
---
This checklist is used to …
=> {AKS} `az aks update`: force `--network-policy=cilium` whenever `--network-dataplane=cilium`

src/bastion/HISTORY.rst, src/bastion/azext_bastion/custom.py, src/bastion/setup.py
=> [Bastion] add auth type password for rdp and fix line formatting issue

src/bastion/HISTORY.rst, src/bastion/azext_bastion/azext_metadata.json, src/bastion/azext_bastion/custom.py, src/bastion/setup.py
=> [Bastion] Addressing issue wtih aad and removing preview flag 

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_constants.py, src/connectedk8s/azext_connectedk8s/_help.py, src/connectedk8s/azext_connectedk8s/_params.py, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py, src/connectedk8s/setup.py
Reverts Azure/azure-cli-extensions#6675
https://portal.microsofticm.com/imp/v3/incidents/incident/446192209/summary
Relevant PR: https://github.com/Azure/azure-cli-extensions/pull/6834
=> Revert "Connectedk8s - RBAC: Add "arc "mode in Guard for using OBO service and deprecate --app-id & --app-secret params"

src/vmware/HISTORY.md, src/vmware/azext_vmware/aaz/latest/vmware/private_cloud/_list_admin_credentials.py, src/vmware/azext_vmware/tests/latest/recordings/test_vmware.yaml, src/vmware/azext_vmware/tests/latest/test_vmware_scenario.py, src/vmware/setup.py
Fix az vmware private-cloud list-admin-credentials not returning nsxtPassword and vcenterPassword
---
=> `az vmware private-cloud list-admin-credentials` bugfix

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py
Fixes an interaction that was previously looking-up an identity object using a weak filter that could be exploited to return multiple entities. The code would just take the first one in the results and grant it access. This change modifies that lookup to use a stronger filter that cannot have multiple objects returned, plugging the security hole.
=> fix lookup for custom locations rp sp to use appId instead of displayName

scripts/ci/breaking_change_test.py
=> {CI} Regenerating breaking change report with only_break=True to control length within 65535.

azure-pipelines.yml, scripts/ci/azdev_linter_style.py, src/containerapp/azext_containerapp/__init__.py
=> {CI} Add statement for azdev style

.github/policies/resourceManagement.yml, .github/workflows/AddIssueComment.yml, .github/workflows/BlockPRMerge.yml
---
1. Add qwuae1 as a vm-repair reviewer 
2. Prevent Merge on "do-not-merge" Label
Add "do-not-merge" label
Remove "do-not-merge" label
=> {CI} Update bot workflow

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/models/_models_py3.py, src/connectedk8s/setup.py
Introduce additional bugfixes, bump CLI extension version
---
- [ x ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
=> Introduce additional bugfixes, bump CLI extension version

src/aks-preview/azext_aks_preview/tests/latest/recording_processors.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_helpers.py, src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py, src/aks-preview/azext_aks_preview/tests/latest/test_maintenanceconfiguration.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
---
- {AKS} Fix azdev style issues for tests (may refer to PR #7112)
- Update recording file for test case `test test_aks_create_and_update_with_http_proxy_config` as vnet/subnet bumped the API version from 2023-05-01 to 2023-09-01
=> {AKS} Fix azdev style issues for tests

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
```bash
az aks create --subscription $SUB_ID \
-n $CLUSTER_NAME \
-g $RG_NAME \
--enable-workload-identity
az aks update --subscription $SUB_ID \
-n $CLUSTER_NAME \
-g $RG_NAME \
--disable-workload-identity
```
=> {AKS} Replace Workload Identity related functions in aks-preview with azure-cli

src/logic/HISTORY.rst, src/logic/azext_logic/aaz/latest/logic/integration_account/_list.py, src/logic/azext_logic/aaz/latest/logic/workflow/_create.py, src/logic/azext_logic/aaz/latest/logic/workflow/_list.py, src/logic/azext_logic/aaz/latest/logic/workflow/_show.py, src/logic/azext_logic/aaz/latest/logic/workflow/_update.py, src/logic/azext_logic/aaz/latest/logic/workflow/identity/_assign.py, src/logic/azext_logic/aaz/latest/logic/workflow/identity/_remove.py, src/logic/azext_logic/custom.py, src/logic/azext_logic/tests/latest/recordings/test_workflow_parameters.yaml, src/logic/azext_logic/tests/latest/test_logic_scenario.py, src/logic/azext_logic/tests/latest/workflow_connection.json, src/logic/azext_logic/tests/latest/workflow_connection_update.json, src/logic/setup.py
---
Fix the issue with `parameters` in `--definition` not working
close https://github.com/Azure/azure-cli/issues/27982
aaz model https://github.com/Azure/aaz/pull/379
`az logic workflow`
=> [Logic] `az logic workflow`: Fix the issue with `parameters` in `--definition` not working

scripts/ci/azdev_linter_style.py, src/monitor-control-service/setup.py
---
The name in setup.py should be the same as the extension dir name.
Otherwise the test case test_index will report an error:
At the same time, we should restrict setup.py to not allow the use of underscores, otherwise the version information of the build package cannot be obtained after user install the extension.
Only if the name contains an underscore, the version information cannot be displayed. This problem only appeared recently, and only packages built on the ci environment have problems, which cannot be reproduced in the local environment. The root cause has not yet been found.
Add build wheel check and extension name check to avoid the same error:
There is a pipeline …
=> {CI} Add build wheel check and extension name check

src/aks-preview/azext_aks_preview/azuremonitormetrics/addonput.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/amg/link.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/amw/create.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/amw/defaults.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/amw/helper.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/constants.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/dce_api.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/dcr_api.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/dcra_api.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/defaults.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/delete.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/helper.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/recordingrules/create.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/recordingrules/delete.py, src/aks-preview/azext_aks_preview/azuremonitormetrics/responseparsers/amwlocationresponseparser.py
---
- Fix azdev style issues for azuremonitormetrics (may refer to PR #7112).
=> {AKS} Fix azdev style issues for azuremonitormetrics

src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py, src/aks-preview/azext_aks_preview/azurecontainerstorage/_validators.py, src/aks-preview/azext_aks_preview/azurecontainerstorage/acstor_ops.py
---
- Fix azdev style issues for azurecontainerstorage (may refer to PR #7112).
=> {AKS} Fix azdev style issues for azurecontainerstorage

src/aks-preview/azext_aks_preview/aks_diagnostics.py, src/aks-preview/azext_aks_preview/aks_draft/commands.py
---
- Fix azdev style issues for diagnostics & draft (may refer to PR #7112).
=> {AKS} Fix azdev style issues for diagnostics & draft

src/aks-preview/azext_aks_preview/addonconfiguration.py, src/aks-preview/azext_aks_preview/agentpool_decorator.py, src/aks-preview/azext_aks_preview/maintenanceconfiguration.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
- Fix azdev style issues for decorators (may refer to PR #7112).
=> {AKS} Fix azdev style issues for decorators

src/quantum/tests.live/Run.ps1
HOTFIX FOR E2E TESTS - RELEASE OF "AZ QUANTUM" EXTENSION IS NOT NEEDED
---
Fixing an issue with e2e tests for `quantum` extension where test recording obfuscation fails in PowerShell 7
N/A
=> fix: quantum extension - obfuscating E2E test recordings

scripts/ci/azdev_linter_style.py
---
https://pypi.org/project/setuptools/69.0.3/ released on Dec 23, 2023 changed the behavior of default replacement of _ with -.
Please check this issue for details: https://github.com/pypa/setuptools/issues/2522
Since the previous extension names all used horizontal lines, we need to add extension name detection to ensure that the extension name does not contain any underscores `_`, otherwise the extension name will change and the new extension cannot be recognized.
Please note:
- The extension name comes from the wheel package name and not the directory name of the extension.
- The extension root dir name and extension name are not required to be consistent, but we recommend them to be …
=> {CI} Fix check extension name issue

src/network-manager/HISTORY.rst, src/network-manager/azext_network_manager/__init__.py, src/network-manager/azext_network_manager/_params.py, src/network-manager/azext_network_manager/action.py, src/network-manager/azext_network_manager/commands.py, src/network-manager/azext_network_manager/custom.py, src/network-manager/azext_network_manager/tests/latest/test_network_scenario.py, src/network-manager/setup.py
Fix #7143 to allow cross tenant resource id for `--hub`
---
=> [Network-Manager] Fix #7143: `az network manager connect-config create/update`: Fix to allow cross tenant resource id for `--hub`

src/quantum/azext_quantum/__init__.py, src/quantum/azext_quantum/_params.py, src/quantum/azext_quantum/_storage.py, src/quantum/azext_quantum/commands.py, src/quantum/azext_quantum/operations/job.py, src/quantum/azext_quantum/operations/workspace.py, src/quantum/azext_quantum/tests/latest/test_quantum_jobs.py, src/quantum/azext_quantum/tests/latest/test_quantum_targets.py, src/quantum/azext_quantum/tests/latest/test_quantum_workspace.py, src/quantum/azext_quantum/tests/latest/utils.py
=> Fix quantum lint

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
`az aks update --ip-families ipv4,ipv6`
=> {AKS} `az aks update`: Add `--ip-families` to support updating cluster networking settings

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_utils.py, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py
Skip checking operation version support for non-stable release trains.
---
az connectedk8s upgrade -g <rg_name> -n <cluster_name>
(should work for any version for dev/private/other-non-stable release trains, but only for v>1.1.14 for stable release train, the same applies for az connectedk8s update/enable-features/disable-features) …
=> Whitelist Version Check for Non-Stable Release Trains for connectedk8s

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_constants.py, src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/commands.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
=> [containerapp] az containerapp add-on create: Support for milvus add-on

src/connectedvmware/HISTORY.rst, src/connectedvmware/azext_connectedvmware/_actions.py, src/connectedvmware/azext_connectedvmware/_help.py, src/connectedvmware/azext_connectedvmware/_params.py, src/connectedvmware/azext_connectedvmware/_validators.py, src/connectedvmware/azext_connectedvmware/custom.py, src/connectedvmware/azext_connectedvmware/tests/latest/test_connectedvmware_scenario.py, src/connectedvmware/setup.py
---
Link HCRP machine to vCenter.
The `location`, `custom-location` properties can be figured out from the vCenter and `inventory-item` can be figured out by searching for the BiosId in the `Machine` properties (called `VMUUID`) from the `vCenter/inventoryItems`. So, making all three properties as optional.
Have added some examples in the help section for this experience.
`az connectedvmware`
=> Link HCRP (Arc for servers) machine  to vCenter

src/datafactory/HISTORY.rst, src/datafactory/azext_datafactory/manual/custom.py, src/datafactory/setup.py
`az datafactory data-flow update` is broken and cannot be used. There is a bug where `data_flow_data["properties"]["typeProperties"]` is not initialized to an empty dictionary and so every time the command is run, the following will appear at the end of the error trace:
```
in datafactory_data_flow_update
data_flow_data["properties"]["typeProperties"]["sinks"] = properties[
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'typeProperties'
```
To fix this issue (and prevent it from happening again) I've performed some refactoring to:
* [DRY the code](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
* Eliminate some [magic strings](https://en.wikipedia.org/wiki/Magic_string)
* Increase readability by constructing inner dictionaries before nesting them
I based the expected …
=> fix: datafactory data-flow update does not work

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
all `az aks mesh` commands.
=> Refactor azure service mesh update function for better readability

.github/workflows/VersionCalPRComment.yml, src/offazure/azext_offazure/__init__.py
=> {CI} Auto-version-calculation fix

src/fleet/HISTORY.rst, src/fleet/azext_fleet/_help.py, src/fleet/azext_fleet/_params.py, src/fleet/azext_fleet/commands.py, src/fleet/azext_fleet/custom.py, src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubful.yaml, src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubless.yaml, src/fleet/azext_fleet/tests/latest/test_fleet_hubless_scenario.py, src/fleet/setup.py
=> [az fleet] Hubless-Hubful PUT and reconcile commands.

src/aks-preview/HISTORY.rst, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_abort.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_addon_disable_confcom_addon.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_addon_disable_openservicemesh.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_approuting_zone_update.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_availability_zones.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_dualstack_with_default_network.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_none_private_dns_zone.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_or_update_with_load_balancer_backend_pool_type.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_private_cluster_public_fqdn.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_enable_ai_toolchain_operator.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_enable_cilium_dataplane.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_enable_network_observability.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ephemeral_disk.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_fips.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_enable_ai_toolchain_operator.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/linter_exclusions.yml, src/aks-preview/setup.py
=> [AKS] Add Kaito preview CLI flags

src/index.json
Revert connectedk8s 1.6.4 which has broken the `az connectedk8s proxy` command. The fix is in this PR:
https://github.com/Azure/azure-cli-extensions/pull/7250
=> revert connectedk8s 1.6.4

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_clientproxyutils.py, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py
Try to merge the below PR first before this PR:
https://github.com/Azure/azure-cli-extensions/pull/7251
It seems the connectedk8s live test doesn't work properly, probably because the command is being run as a subprocess, since it passed when it should have failed: https://github.com/Azure/azure-cli-extensions/blob/06ad14fbbdd9328077170a1f2371c687847b95c2/src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py#L584
So, I did not catch the issue. Ideally, we have a fully automated test pipeline for connectedk8s, but currently we have to run a bunch of manual tests. Other teams seem to have better tests for connectedk8s than connectedk8s has for itself.
Once your pull …
=> fix tenant ID retrieval

scripts/ci/sync_extensions.py, scripts/ci/update_ext_cmd_tree.py
---
1. Change the command tree file encoding to `utf-8`.
2. Add `--overwrite` to support Idempotent operations.
=> {CI} Merge CLI extension release scripts from release-scripts branch to main branch

src/index.json
=> Arc Appliance CLI 1.0.3 February Release

.github/workflows/VersionCalPRComment.yml
=> {CI} Use ref to checkout base branch

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py, src/connectedk8s/setup.py
This PR does the following:
* Fix proxy live test.
* Fix unused variable and parameter.
* Use makedirs instead of mkdir for installing kubectl.
=> fix connectedk8s proxy test

azure-pipelines.yml
Temporarily disable Credential Scanner
https://dev.azure.com/azclitools/public/_build/results?buildId=133760&view=logs&j=9a50307c-53e6-51fa-ddad-d8767a4a0ece&t=854f603a-ce91-59a3-a3f0-bfbaa050f0db
```
Attempting to gather dependency information for package 'Microsoft.Security.CredScan.2.1.17' with respect to project 'D:\a\_work\_sdt', targeting 'Any,Version=v0.0'
MSBuild auto-detection: using msbuild version '16.11.2.50704' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'.
Using credentials from config. UserName: VssSessionToken
WARNING: The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or …
```
=> {CI} Disable Credential Scanner

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_max_inactive_revisions.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py, src/containerapp/setup.py
=> [Container app] Bump version 0.3.48

src/spring/HISTORY.md, src/spring/azext_spring/_tanzu_component.py, src/spring/azext_spring/tests/latest/test_asa_create.py, src/spring/setup.py
---
Change the ACS generation to Gen2 when enabling ACS, `spring create enable_application_configuration_service`
=> Change default ACS generation to Gen2

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_loadbalancer.py, src/aks-preview/azext_aks_preview/_natgateway.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_outbound_ips.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py, src/aks-preview/azext_aks_preview/tests/latest/test_natgateway.py
---
`az aks update --load-balancer-outbound-ports 0`
related: #27071
=> {AKS} Support reset default value for loadbalancer profile and natgateway profile

src/index.json
az aksarc
https://learn.microsoft.com/en-us/cli/azure/aksarc?view=azure-cli-latest
**Note**: `azdev style <YOUR_EXT>` is not enforced currently for our extension in our private repository.
**Note that we are releasing an extension from a private repository and need to manually update the `src/index.json`!**
=> aksarc 1.0.0b1 VMware support release

.github/workflows/TriggerExtensionRelease.yml
=> {CI} Use GitHub Actions to trigger the ADO OneBranch Extension Release Pipeline

.github/workflows/TriggerExtensionRelease.yml
---
There can be at most one running and one pending job in a concurrency group at any time.
https://github.com/orgs/community/discussions/41518
https://github.com/orgs/community/discussions/12835
If extension A and extension B are released at the same time, B's pengding release workflow will be canceled because of extension A's automatically update index.json commit.
So we still keep concurrent release for CLI extensions.
But after each release, we will ensure that pull the latest index.json from main branch and overwrite the index.json in blob.(The last task in OneBranch extension release pipeline)
There is a pipeline to automatically build, upload and publish extension …
=> {CI} Cancel serial release

src/aks-preview/HISTORY.rst, src/aks-preview/README.rst, src/aks-preview/azext_aks_preview/azext_metadata.json, src/aks-preview/setup.py
---
In the new SDK used in aks-preview since 2.0.0b7, it starts using `SensitiveHeaderCleanupPolicy` provided by `azure.core`. aks-preview does not separately declare its dependency on the version of `azure.core`, but inherits from the declaration in azure-cli. In azure-cli PR [#27783](https://github.com/Azure/azure-cli/pull/27783), the dependency on `azure.core` is bumped to `1.28.0` (in which `SensitiveHeaderCleanupPolicy` was [introduced](https://github.com/Azure/azure-sdk-for-python/issues/34091#issuecomment-1921758823)). Changes in \#27783 were released in [2.56.0](https://github.com/Azure/azure-cli/milestone/137). So changing the minimum required cli core version to `2.56.0`.
For users who …
=> {AKS} Bump the minimum required cli core version to `2.56.0`

src/rdbms-connect/HISTORY.rst, src/rdbms-connect/azext_rdbms_connect/_params.py, src/rdbms-connect/azext_rdbms_connect/custom.py, src/rdbms-connect/setup.py
Update compatible release version for setproctitle to support Python 3.11
---
- [X ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
=> Update compatible release version for setproctitle to support Python 3.11

src/spring/azext_spring/azext_metadata.json
Description
After this PR merged: https://github.com/Azure/azure-cli-extensions/pull/7462
We find there are error with latest code against Azure CLI Core <= 2.55.0
After testing, we find it need at least `2.56.0`, so bump version here.
We don't need to update CLI extension version here, since above PRs didn't update the CLI extension version
---
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but …
=> Bump minCliCoreVersion to 2.56.0 for Spring

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py
This PR addresses https://github.com/Azure/azure-cli-extensions/issues/6366
For our use case, it would be very helpful for the connectedk8s proxy to support multiple instances running on the same machine. This enables interactions/ control over multiple Arc connected Kubernetes clusters from the same machine by simply switching your kube context. 
I've tested the change locally and been able to run multiple proxies on different ports and use kubectl to target multiple clusters by switching kube context.
---
az connectedk8s proxy
Once your pull request is merged into main branch, a new pull request will be created to …
=> [ConnectedK8s] Add support for multiple proxy instances running on the same machine using different ports

src/spring/azext_spring/log_stream/log_stream_operations.py, src/spring/azext_spring/managed_components/managed_component_operations.py
=> Refactor for log streaming query params

src/scheduled-query/HISTORY.rst, src/scheduled-query/azext_scheduled_query/_help.py, src/scheduled-query/azext_scheduled_query/custom.py, src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query.yaml, src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query_condition_operator.yaml, src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query_update_action_group.yaml, src/scheduled-query/azext_scheduled_query/tests/latest/test_scheduled_query_scenario.py, src/scheduled-query/setup.py
---
closed https://github.com/Azure/azure-cli/issues/28582
=> {Scheduled-query} Fix help message and update failure

.github/workflows/TriggerExtensionRelease.yml
---
If we continue to use ADO PAT, we have to replace the PAT token every seven days.
So I must migrate to OIDC to login to Azure and trigger onebranch pipeline.
=> {CI} Use OIDC to trigger extension release pipeline

src/quantum/HISTORY.rst, src/quantum/azext_quantum/__init__.py, src/quantum/azext_quantum/operations/templates/create-workspace-and-assign-role.json, src/quantum/setup.py
Previously, we assigned a contributor role to the storage account for the workspace. This PR changes it to the "storage account contributor" role. This is done in order to be compatible with the new "Quantum Workspace Owner" built-in role that allows constrained role assignment of storage account contributor.
---
=> [quantum] Assign "Storage account contributor" role to workspace for linked StorageAccount

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/agentpool_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
---
```
aks nodepool add --name winnp --os-type Windows --disable-windows-outbound-nat
```
**Description**
- Correct the property `disable_outbound_nat` in `windows_profile`. Since customers cannot directly invoke the logic, there is no external impact.
- Why wasn't the error caught earlier? - Because `self.agentpool` is always `None` in customer usage, the code reads from `self.raw_param.get("disable_windows_outbound_nat")` directly, which means the code was not triggered.
- Add UT to validate the `get_disable_windows_outbound_nat` function when the property had been assigned a value.
Once your …
=> {AKS} Correct the property `disable_outbound_nat` in `windows_profile` and add UT

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/tests/latest/test_validators.py, src/aks-preview/setup.py
---
ignore invalid ip error in validator since we would support service tag input with the same api.
We would rely on AKS RP validator.
az aks create/update --api-server-authorized-ip-ranges
=> {AKS} az aks create/update: ignore invalid ip error in ip_ranges validator

src/containerapp/azext_containerapp/_utils.py
---
Currently the `"azext.minCliCoreVersion": "2.53.0"`, but azure-cli version is 2.53.0, with a upcoming PR: https://github.com/Azure/azure-cli-extensions/pull/7551, it will throw: Unable to load extension 'containerapp: cannot import name 'CloudNameEnum' from 'azure.cli.core.cloud'
=> {Containerapp} Fix cannot import name 'CloudNameEnum'

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_add_with_disable_windows_outbound_nat.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
{AKS} Improve Windows OutboundNat test case by removing Windows OSSKU limitation
---
```
az aks nodepool add --name npwin --os-type Windows --disable-windows-outbound-nat
```
=> {AKS} Improve Windows OutboundNat test case by removing Windows OSSKU limitation

scripts/ci/release_version_cal.py
---
https://github.com/Azure/azure-cli-extensions/pull/7587
=> {CI} Fix script re for version extract

src/dataprotection/HISTORY.rst, src/dataprotection/azext_dataprotection/manual/Manifests/AzureKubernetesService.py, src/dataprotection/azext_dataprotection/manual/_params.py, src/dataprotection/azext_dataprotection/manual/custom.py, src/dataprotection/azext_dataprotection/tests/latest/test_dataprotection_configs.py, src/dataprotection/setup.py
---
* Support for vaulted backup for AKS
* `az dataprotection backup-policy get-default-policy-template`: For AzureKubernetesService, default policy now adds vaulted backup rules.
* `az dataprotection backup-vault initialize-restoreconfig:` Three new parameters - `staging_resource_group_id`, `staging_storage_account_id`, `resource_modifier_reference`.
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your …
=> [dataprotection] Support for AKS Vaulted Backups

src/spring/HISTORY.md, src/spring/azext_spring/_clierror.py, src/spring/azext_spring/_utils.py, src/spring/azext_spring/jobs/job.py, src/spring/setup.py
Refine Refine the error message when user failed to get job log streaming in command az spring job logs.
---
=> Refine the error message when user failed to get job log streaming

src/amg/HISTORY.rst, src/amg/azext_amg/sync.py, src/amg/setup.py
=> Use case-insensitive comparison in dashboard sync logic

azure-pipelines.yml, scripts/ci/credscan/CredScanSuppressions.json
---
Last Saturday, this task `ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-credscan.CredScan@2` began failing unexpectedly with the following error message: 
We have sent an email and created an ICM.
But progress is very slow, and many users' PRs have been blocked by this CI task.
And I found out that these two tasks have been deprecated.
- ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-credscan.CredScan@2
- ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-postanalysis.PostAnalysis@1
So we decided to switch to the `securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3` and `securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@2`
Related …
=> {CI} Switch CredScan task

src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_get_upgrades.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2024_04_02_preview/models/__init__.py, src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2024_04_02_preview/models/_models_py3.py
---
az aks get-upgrades -g <> -n <>
az aks nodepool get-upgrades -g <> --cluster-name <> -n <>
=> {AKS} fix componentbyrelease in v20240402preview

.github/workflows/ProcessCodeReview.yml, scripts/ci/codegen_cal.py
=> {CI} Add codegen survey bot

src/index.json
This PR updates the path to the stack-hci-vm cli v1.1.11 as part of wave 1 to block anonymous access on storage accounts.
Original PR adding v1.1.11 - https://github.com/Azure/azure-cli-extensions/pull/7700
---
=> [Wave 1] [stack-hci-vm] Updated v1.1.11 path in index

src/bastion/HISTORY.rst, src/bastion/azext_bastion/tunnel.py, src/bastion/setup.py
---
az network bastion tunnel
The current behaviour is to block once there is a connection and this doesn't work if you are forwarding a web server as the browser will start multiple connections.
There has been an issue open for some time on the main azure-cli repository for this issue:  https://github.com/Azure/azure-cli/issues/24600
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not …
=> Support for concurrent connections with tunnels

.azure-pipelines/templates/azdev_setup.yml
---
Setuptools 70.1.0 was released on Jun 19.
The latest setuptools adds a vendored wheel 0.4.3 to generate wheel and it does not generate metadata.json.
Related PR:
[Adopted the bdist_wheel command from "wheel" by agronholm · Pull Request #4369 · pypa/setuptools (github.com)](https://github.com/pypa/setuptools/pull/4369)
Installing setuptools with a version higher than 70.0.0 will not generate metadata.json.
Pin setuptools version to 70.0.0 to unblock extension release.
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically. …
=> {CI} Pin setuptools version to 70.0.0.

src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh, src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml, src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml
=> {AKS} Fix AKS live test pipeline

src/db-up/HISTORY.rst, src/db-up/azext_db_up/_help.py, src/db-up/setup.py
---
`az mysql|postgres|sql up --help`
=> [db-up] Fix repeated typo in help strings

src/k8s-runtime/HISTORY.rst, src/k8s-runtime/azext_k8s_runtime/custom_commands/storage_class.py, src/k8s-runtime/setup.py
---
`az k8s-runtime storage-class enable`.
Use `preview` release train to install storage class extension when enabling storage class service
=> [k8s-runtime] Use `preview` release train to install storage class extension when enabling storage class service

src/connectedvmware/HISTORY.rst, src/connectedvmware/azext_connectedvmware/custom.py, src/connectedvmware/setup.py
`az connectedvmware create-from-machines` : Check for BIOS UUIDs in both Big Endian and Middle Endian format.
---
`az connectedvmware`
=> [connectedvmware] Search for BIOS IDs with both Big Endian and Middle Endian

src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
the cli should not set network_plugin defaults. it should let the AKS RP handle defaulting.
=> chore: do not use network_plugin default from sdk

src/bastion/HISTORY.rst, src/bastion/azext_bastion/_help.py, src/bastion/azext_bastion/tests/latest/recordings/test_bastion_host_crud.yaml, src/bastion/setup.py
=> Remove redundant aad login commands from example section

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
---
Remove support for 'az aks get-os-options' command. 
The API required by this command was removed from AKS API 2024-05-01, 2024-05-02-preview or later. So remove this command before aks-preview extension starts to use 2024-05-02-preview API.
=> [AKS] Remove support for az aks get-os-options command

src/connectedk8s/MANIFEST.in
A pedantic packaging fix: probably not making a meaningful difference today but likely saving trouble in the future
packaging `connectedk8s` using the tooling recommended in current python packaging reveals that `HISTORY.rst` is not included in the sdist, and therefore not available for use by `setup.py` when building the wheel.
```
$ pip install build ; python -m build
<snipped output>
* Getting build dependencies for wheel...
Wheel is not available, disabling bdist_wheel hook
File "/home/dch/.virtualenvs/foo/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
main()
File "/home/dch/.virtualenvs/foo/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main …
```
=> package HISTORY.rst

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_client_factory.py, src/containerapp/azext_containerapp/_clients.py, src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/_transformers.py, src/containerapp/azext_containerapp/azext_metadata.json, src/containerapp/azext_containerapp/commands.py, src/containerapp/azext_containerapp/containerapp_auth_decorator.py, src/containerapp/azext_containerapp/containerapp_env_decorator.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_auth_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_msi_custom_domains.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_mtls.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_p2p_traffic_encryption.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_usages.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_get_customdomainverificationid_e2e.yaml, src/containerapp/setup.py
=> [Containerapp] Remove GA commands which exist in azure-cli version 2.62.0 and release 0.3.54

src/scvmm/HISTORY.rst, src/scvmm/azext_scvmm/custom.py, src/scvmm/setup.py
---
az scvmm vmmserver connect - There is a fix needed in passing the vmmServerProperties correctly in the body. All calls are facing due to this properties API validation failure.
=> [SCVMM] Fix VMM Server Connect command 1.1.1 release

src/confcom/HISTORY.rst, src/confcom/azext_confcom/_help.py, src/confcom/azext_confcom/_params.py, src/confcom/azext_confcom/custom.py, src/confcom/azext_confcom/data/internal_config.json, src/confcom/azext_confcom/init_checks.py, src/confcom/azext_confcom/kata_proxy.py, src/confcom/azext_confcom/security_policy.py, src/confcom/azext_confcom/template_util.py, src/confcom/azext_confcom/tests/latest/README.md, src/confcom/azext_confcom/tests/latest/test_confcom_arm.py, src/confcom/azext_confcom/tests/latest/test_confcom_image.py, src/confcom/azext_confcom/tests/latest/test_confcom_kata.py, src/confcom/azext_confcom/tests/latest/test_confcom_scenario.py, src/confcom/azext_confcom/tests/latest/test_confcom_tar.py, src/confcom/azext_confcom/tests/latest/test_confcom_template_util.py, src/confcom/setup.py
Also updating tests to use images hosted on MCR instead of Docker Hub
---
az confcom
=> [confcom] Updating katapolicygen to support new node image

.github/workflows/ProcessCodeReview.yml, .github/workflows/VersionCalPRComment.yml
=> {CI} Adjust workflow vars

src/dataprotection/HISTORY.rst, src/dataprotection/azext_dataprotection/manual/custom.py, src/dataprotection/setup.py
`az dataprotection backup-instance restore initialize-for-data-recovery`
=> [dataprotection] Bug fix - missing parameter when calling `initialize-for-data-recovery`

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_precheckutils.py, src/connectedk8s/setup.py
=> [connectedk8s] fix connect cmd issue of namespace delete

src/aks-preview/HISTORY.rst
---
{AKS} Correct release history. Recently, some changes were merged in a close time, there are some issues in the history note due to improper resolution of merge conflicts.
=> {AKS} Correct release history

src/webpubsub/HISTORY.rst, src/webpubsub/azext_webpubsub/azext_metadata.json, src/webpubsub/setup.py
Upgrade minimum core version to 2.56.0 to fix missing attrute 'SensitiveHeaderCleanupPolicy' issue
---
=> [webpubsub] Upgrade minimum core version for webpubsub

src/aks-preview/azext_aks_preview/_client_factory.py, src/aks-preview/azext_aks_preview/custom.py
---
Remove dependency on `azure.graphrbac`. The removed code is mainly used to help users create a service principal/enterprise application, but it has long been abandoned and is not referenced by any command. In summary, the change will not be noticeable to any user.
Related to [#22649](https://github.com/Azure/azure-cli/pull/22649), [#22174](https://github.com/Azure/azure-cli/issues/22174). …
=> {AKS} Remove dependency on `azure.graphrbac`

src/containerapp/azext_containerapp/_archive_utils.py, src/containerapp/azext_containerapp/_up_utils.py, src/containerapp/azext_containerapp/_utils.py, src/containerapp/azext_containerapp/_validators.py, src/containerapp/azext_containerapp/commands.py, src/containerapp/azext_containerapp/containerapp_decorator.py, src/containerapp/azext_containerapp/containerapp_env_certificate_decorator.py, src/containerapp/azext_containerapp/containerapp_job_decorator.py, src/containerapp/azext_containerapp/containerapp_job_registry_decorator.py, src/containerapp/azext_containerapp/containerapp_sessionpool_decorator.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/java_component_decorator.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_create_update_with_yaml.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_ingress_sticky_session.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_preview_scenario.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py, src/containerapp/azext_containerapp/tests/latest/test_containerappjob_crud.py, src/containerapp/azext_containerapp/tests/latest/test_containerappjob_event_triggered_crud.py, src/containerapp/azext_containerapp/tests/latest/test_containerappjob_executions.py, src/containerapp/azext_containerapp/tests/latest/test_containerappjob_preview_scenario.py, src/containerapp/azext_containerapp/tests/latest/test_containerappjob_with_identity.py, src/containerapp/azext_containerapp/tests/latest/test_containerappjob_with_secrets.py, src/containerapp/azext_containerapp/tests/latest/test_containerappjob_with_yaml.py, src/containerapp/azext_containerapp/tests/latest/utils.py
=> [Containerapp] Handle drop msrestazure dependency, migrate `parse_resource_id`, `is_valid_resource_id`, `resource_id`

pylintrc
---
Disable too-many-positional-arguments ([R0917](https://pylint.readthedocs.io/en/latest/user_guide/checkers/features.html)):
Too many positional arguments (%s/%s) Used when a function has too many positional arguments.
https://github.com/Azure/azure-cli/pull/29952#issuecomment-2367160707
It's added in Pylint 3.3 on 2024-09-20
> Added too-many-positional-arguments to allow distinguishing the configuration for too many total arguments (with keyword-only params specified after *) from the configuration for too many positional-or-keyword or positional-only arguments.
Ref: https://pylint.readthedocs.io/en/latest/whatsnew/3/3.3/index.html
There is a pipeline to automatically build, …
=> {CI} Disable too-many-positional-arguments R0917

src/bastion/HISTORY.rst, src/bastion/azext_bastion/aaz/latest/network/bastion/_create.py, src/bastion/azext_bastion/aaz/latest/network/bastion/_delete.py, src/bastion/azext_bastion/aaz/latest/network/bastion/_show.py, src/bastion/azext_bastion/aaz/latest/network/bastion/_update.py, src/bastion/azext_bastion/aaz/latest/network/bastion/_wait.py, src/bastion/setup.py
---
aaz auto generated variable that clashed with existing variable in params causing missing argument exception. fixed by changing aaz variable name.
=> {AzureBastion] Bug fixes for connect introduced in 1.20 

src/db-up/HISTORY.rst, src/db-up/azext_db_up/azext_metadata.json, src/db-up/azext_db_up/commands.py, src/db-up/setup.py
=> Deprecate db-up extension

src/vm-repair/HISTORY.rst, src/vm-repair/azext_vm_repair/custom.py, src/vm-repair/setup.py
---
This change is to bring our default image to Win2022 instead of 2016. This will bring our default image up to date with useful security updates. 
=> Default windows image change breaking change warning, Win2016 to Win2022

src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
private keyvault + konnectivity is blocked now, so vnet integration should be used.
---
az aks create/update --enable-azure-keyvault-kms
=> {AKS} Update tests to use vnet integration

src/networkcloud/HISTORY.rst, src/networkcloud/azext_networkcloud/operations/custom_properties.py, src/networkcloud/azext_networkcloud/tests/unit/test_custom_properties.py, src/networkcloud/setup.py
NeworkCloud 2024-07-01 API version update to include BYOSA for baremetalmachine commands(run/runread/rundataextract command)
---
=> NeworkCloud 2024-07-01 API version update to include BYOSA for baremetalmachine commands(run/runread/rundataextract command)

src/spring/HISTORY.md, src/spring/azext_spring/_params.py, src/spring/azext_spring/commands.py, src/spring/azext_spring/jobs/job.py, src/spring/setup.py
=> Remove preview tag for config server features in Enterprise tier

src/quantum/azext_quantum/operations/workspace.py
Removed all msrestazure dependencies from the quantum CLI extension.
Changes in workspace.py:
- Deleted the CloudError import from msrestazure.azure_exceptions
- Deleted an orphaned function containing the only reference to CloudError
---
=> [Quantum] Remove msrestazure dependency

src/multicloud-connector/azext_multicloud_connector/_utils.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/__cmd_group.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/_generate_aws_template.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/__cmd_group.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_create.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_delete.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_list.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_show.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_test_permission.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_update.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/__cmd_group.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_create.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_delete.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_list.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_show.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_sync_now.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_update.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_type/__cmd_group.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_type/_list.py, src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_type/_show.py, src/multicloud-connector/azext_multicloud_connector/custom.py
aaz PR link: https://github.com/Azure/aaz/pull/590
---
1. Help guide message update
2. Add comments in code
=> [arc-multicloud] Update help guide

src/rdbms-connect/HISTORY.rst, src/rdbms-connect/azext_rdbms_connect/_validators.py, src/rdbms-connect/setup.py
=> Remove dependency on msrestazure: rdbms-connect

src/interactive/HISTORY.rst, src/interactive/azext_interactive/azclishell/__init__.py, src/interactive/azext_interactive/azclishell/configuration.py
---
close #8171 
`az interactive`
=> {Interactive} Compliant with Python 3.12

azure-pipelines.yml
Use 3.12 in CI as https://github.com/Azure/azure-cli/pull/29887 is merged
=> {CI} Update pipeline to use Python 3.12

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/setup.py
---
az aks trustedaccess rolebinding create
=> [AKS] BREAKING CHANGE: `az aks trustedaccess rolebinding create`: Remove deprecated `-r` and `-s` options

src/image-copy/HISTORY.rst, src/image-copy/azext_imagecopy/azext_metadata.json, src/image-copy/azext_imagecopy/cli_utils.py, src/image-copy/setup.py
=> {Image-copy} Remove direct call to msrestazure

src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
{AKS} Fix test case `test_aks_create_with_monitoring_aad_auth_msi_with_datacollectionsettings_and_otheraddon`. Forked from #8226.
N/A
=> {AKS} Fix test case `test_aks_create_with_monitoring_aad_auth_msi_with_datacollectionsettings_and_otheraddon`

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_utils.py, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/azext_connectedk8s/tests/latest/README.md, src/connectedk8s/azext_connectedk8s/tests/latest/config.json.dist, src/connectedk8s/setup.py
This change is to support disconnected on-premises environments.
The connectedk8s team is working on fixing the style errors. I am just contributing to the extension.
**NOTE**: there are pre-existing style errors. The connectedk8s team is working on fixing the style errors. I am just contributing to the extension.
=> update to support disconnected environment

src/amg/HISTORY.rst, src/amg/azext_amg/custom.py, src/amg/setup.py
`az grafana service-account token create`
Fixes #8155
=> AMG: Set service-account token default TTL to 1 day

.github/CODEOWNERS, .github/policies/resourceManagement.yml
=> Add the new owner for the acat extension

.github/workflows/CCOA.yml
=> {CI} Add ccoa announcement

src/alertsmanagement/azext_alertsmanagement/_help.py, src/alertsmanagement/azext_alertsmanagement/_params.py
=> {alertsmanagement} Fix disawllowed html tag

src/front-door/azext_front_door/_params.py
=> {front-door} Fix disallowed html tag

src/spring/azext_spring/_help.py, src/spring/azext_spring/_params.py
=> {spring} Fix disallowed html tag

src/mcc/azext_mcc/aaz/latest/mcc/__cmd_group.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/__cmd_group.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/node/__cmd_group.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/node/_create.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/node/_delete.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/node/_get_provisioning_details.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/node/_list.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/node/_show.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/node/_update.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/node/_wait.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/resource/__cmd_group.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/resource/_create.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/resource/_delete.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/resource/_list.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/resource/_show.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/resource/_update.py, src/mcc/azext_mcc/aaz/latest/mcc/ent/resource/_wait.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/node/_create.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/node/_delete.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/node/_get_provisioning_details.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/node/_list.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/node/_show.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/node/_update.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/resource/_create.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/resource/_delete.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/resource/_list.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/resource/_show.py, src/mcc/azext_mcc/aaz/latest/mcc/isp/resource/_update.py, src/mcc/azext_mcc/azext_metadata.json, src/mcc/setup.py
Change is_preview flags on all commands to true and increment mcc version to v1.0.0b2 from v1.0.0b1.
We are in public preview and we did not want the auto generated docs to say we were in GA and this is what was recommended we do in the teams channel.
 
---
=> [Microsoft Connected Cache] Change is_preview flags on all commands to true and increment mcc version to v1.0.0b2 from v1.0.0b1

src/connectedvmware/HISTORY.rst, src/connectedvmware/azext_connectedvmware/custom.py, src/connectedvmware/azext_connectedvmware/pwinput.py, src/connectedvmware/setup.py
Pwinput : When terminal / tty is not available, read from stdin
---
=> Handle no tty pwinput

src/spring/HISTORY.md, src/spring/azext_spring/app.py, src/spring/setup.py
Update App operation may fail due to quota usage. So I'm adding a few lines to detect such a failure during polling.
=> [Spring] Detect failed Update App operation during polling

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_client_factory.py, src/containerapp/azext_containerapp/_utils.py, src/containerapp/azext_containerapp/containerapp_decorator.py
---
`az containerapp create/updtae`: Fix --bind/--unbind for java component when cloud is not AzureCloud
Currently when customer is using AzureChinaCloud, the command throw error due to it always list service connector, but service connector is not supported on AzureChinaCloud.
cli.azure.cli.core.azclierror: (pii). Status: Response_Status.Status_IncorrectConfiguration, Error code: 3399614475, Tag: 508634112
Tested by change the location to chinaeast3:
You only need to …
=> [Containerapp] `az containerapp create/update`: Fix --bind/--unbind when cloud is not AzureCloud

src/datamigration/HISTORY.rst, src/datamigration/azext_datamigration/manual/helper.py, src/datamigration/setup.py
---
- The URL for downloading the SQL Assessment Zip has been updated to https://aka.ms/sqlassessmentpackage.
- The URL https://aka.ms/sqlassessmentpackage now redirects to the actual download URL: https://sqlassess.z13.web.core.windows.net/SqlAssessment.zip.
- This change ensures that the PowerShell module will not require any code modifications in the future, even if the actual download URL changes. …
=> [DataMigration]: Update SQL Assessment Console App Package Download URL.

src/load/HISTORY.rst, src/load/azext_load/azext_metadata.json, src/load/azext_load/data_plane/utils/utils.py, src/load/setup.py
=> [load] limit the scope of run_az_cmd import

src/load/HISTORY.rst, src/load/azext_load/azext_metadata.json, src/load/setup.py
=> [load] update min required cli core version

src/k8s-extension/HISTORY.rst, src/k8s-extension/azext_k8s_extension/partner_extensions/EntraWorkloadIAM.py, src/k8s-extension/azext_k8s_extension/partner_extensions/azuremonitormetrics/helper.py, src/k8s-extension/setup.py
Fix issue #8293 
Note: This is my first contribution to this repo. Please check that I made all necessary changes :)
---
=> az k8s-extension create | Attempt to register a Resource Provider that is already registered

.github/template/git-hooks-note.md, .github/workflows/GitHookNotice.yml
=> {CI} Add git hook notice

src/durabletask/azext_durabletask/aaz/latest/durabletask/scheduler/_create.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/scheduler/_delete.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/scheduler/_list.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/scheduler/_show.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/scheduler/_update.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/scheduler/_wait.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_create.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_delete.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_list.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_show.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_update.py, src/durabletask/azext_durabletask/aaz/latest/durabletask/taskhub/_wait.py
---
Associated aaz PR: https://github.com/Azure/aaz/pull/672
=> Durabletask shorthand fixes and readme fixes

src/bastion/HISTORY.rst, src/bastion/azext_bastion/aaz/latest/network/bastion/_create.py, src/bastion/azext_bastion/custom.py, src/bastion/azext_bastion/tests/latest/recordings/test_bastion_host_crud.yaml, src/bastion/azext_bastion/tests/latest/test_bastion.py, src/bastion/setup.py
---
`az network bastion create --name MyBastion --resource-group MyResourceGroup --sku Developer --vnet-name MyVnet`
`az network bastion create --name MyBastion --resource-group MyResourceGroup --sku Developer --vnet-name MyVnet --network-acls-ips '[{"addressPrefix":"1.1.1.1/16"},{"addressPrefix":"100.64.0.0/10"}]'` …
=> add support for bastion developer create

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/tests/latest/test_validators.py, src/aks-preview/setup.py
---
- `az aks create`
- `az aks nodepool add`
refer: https://github.com/Azure/azure-cli/pull/30768
=> [AKS] `az aks create/az aks nodepool add`: Emit error message when using `--asg-ids` alone without `--allowed-host-ports`

scripts/ci/avail-ext-doc/list-template.md
According to the allowed values for `ms.topic` as now showing in the Contributor's Guide (https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies/mstopic?branch=main), the ms.topic for autogenerated reference content should be `language-reference`. By making this update, the available extensions report will also be removed from MSFT's broken link report. We'll still be able to monitor broken links from the azure-docs-cli repo's daily build report.
Second, the ms.devlang, ms.tool and keyword metadata has been deprecated.
**This PR fixes the following build error:**
=> Update list-template.md | fix metadata to conform to new guidelines

src/image-copy/HISTORY.rst, src/image-copy/azext_imagecopy/azext_metadata.json, src/image-copy/azext_imagecopy/custom.py, src/image-copy/setup.py
---
Changes related to breaking changes in azure-cli v2.68.0
https://github.com/Azure/azure-cli/pull/30430
Changes for API 2024-12-01-preview
apiVersion has been changed in azCli, keeping it working for older versions of azure-cli too as fallback
az image copy --source-resource-group production --target-location eastus2 --source-type image --source-object-name ubuntu-2004-20250124 --target-resource-group production --target-name test-image-eus2 --tags current=true
You only need to update the version information in file setup.py and historical information in …
=> [ImageCopy] Fixing accessSAS according to latest CodeGen migration

src/datamigration/HISTORY.rst, src/datamigration/azext_datamigration/manual/helper.py, src/datamigration/setup.py
---
**Description**
1. The URL for downloading the SQL Schema migration Zip has been updated to https://aka.ms/sqlschemamigrationpackage.
2. The URL https://aka.ms/sqlschemamigrationpackage now redirects to the actual download URL: https://sqlassess.z13.web.core.windows.net/SqlSchemaMigration/SqlSchemaMigration.zip.
3. This change ensures that the PowerShell module will not require any code modifications in the future, even if the actual download URL changes.
You only …
=> Changing the schema migration package download link

src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
---
During an Azure Container Storage uninstall failure, we observed that there was an unhandled `ExtensionNotInstalledException`. 
This PR addresses this and adds better exception handling and logs a much concise error message to the user.
=> fix: catch and surface a concise err for acstor extension import error

src/application-insights/HISTORY.rst, src/application-insights/azext_applicationinsights/_client_factory.py, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_function.yaml, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_function_cross_resource_groups.yaml, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_webapp.yaml, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_webapp_cross_resource_group.yaml, src/application-insights/azext_applicationinsights/tests/latest/test_applicationinsights_mgmt.py, src/application-insights/azext_applicationinsights/util.py, src/application-insights/setup.py
---
az monitor app-insights events/metrics/query
=> {Application-insights} Add auth adaptor for track 1 sdk

src/quantum/HISTORY.rst, src/quantum/azext_quantum/__init__.py, src/quantum/setup.py
Incremented version number and added release notes
---
=> [Quantum] Quantum CLI Extension Release, Version 1.0.0b5

scripts/ci/find_extension_upgraded.py
=> {CI} Move find_extension_upgraded.py to azure-cli-extensions repo

src/quantum/azext_quantum/__init__.py, src/quantum/setup.py
Rolling back the quantum extension version number to 1.0.0b4 to avoid auto release.
This is part of retracting the 1.0.0b5 release: See https://github.com/Azure/azure-cli-extensions/pull/8561
=> [Quantum] Roll back the quantum extension version number to 1.0.0b4

src/quantum/HISTORY.rst, src/quantum/azext_quantum/__init__.py, src/quantum/setup.py
Incremented version number and revised release notes
---
=> [Quantum] Quantum CLI Extension Release, Version 1.0.0b6

src/confcom/HISTORY.rst, src/confcom/azext_confcom/README.md, src/confcom/azext_confcom/cose_proxy.py, src/confcom/azext_confcom/custom.py, src/confcom/azext_confcom/data/internal_config.json, src/confcom/azext_confcom/oras_proxy.py, src/confcom/azext_confcom/os_util.py, src/confcom/azext_confcom/rootfs_proxy.py, src/confcom/azext_confcom/security_policy.py, src/confcom/azext_confcom/template_util.py, src/confcom/azext_confcom/tests/latest/README.md, src/confcom/azext_confcom/tests/latest/test_confcom_fragment.py, src/confcom/azext_confcom/tests/latest/test_confcom_scenario.py, src/confcom/azext_confcom/tests/latest/test_confcom_tar.py, src/confcom/samples/certs/README.md, src/confcom/samples/certs/create_certchain.sh, src/confcom/setup.py
Supporting OCI images and adding tests.
---
Previously, fully OCI-formatted images would fail out if downloaded from tools like Skopeo or Oras. Now they can be processed and dmverity hashed in the same way as docker-generated images. This change also corresponds to a release in [dmverity-vhd](https://github.com/microsoft/integrity-vhd/releases/tag/v1.5) that fixes a bug where some image layers would return blank.
This PR also adds testing for signed image fragments.
az confcom
You only …
=> [confcom] supporting OCI images and adding tests

src/vm-repair/HISTORY.rst, src/vm-repair/README.md, src/vm-repair/setup.py
---
Adds some more context and important tools for using VM Repair.
=> Improve the public docs for VM Repair

src/spring/HISTORY.md, src/spring/azext_spring/migration/converter/app_converter.py, src/spring/azext_spring/migration/converter/base_converter.py, src/spring/azext_spring/migration/converter/cert_converter.py, src/spring/azext_spring/migration/converter/environment_converter.py, src/spring/azext_spring/migration/converter/main_converter.py, src/spring/azext_spring/migration/converter/param_converter.py, src/spring/azext_spring/migration/converter/readme_converter.py, src/spring/azext_spring/migration/converter/templates/app.bicep.j2, src/spring/azext_spring/migration/converter/templates/config_server.bicep.j2, src/spring/azext_spring/migration/converter/templates/environment.bicep.j2, src/spring/azext_spring/migration/converter/templates/main.bicep.j2, src/spring/azext_spring/migration/converter/templates/param.bicepparam.j2, src/spring/azext_spring/migration/converter/templates/readme.md.j2, src/spring/setup.py
=> [Spring] Support BYOC in migration command

.github/workflows/VersionCalPRComment.yml, scripts/ci/release_version_cal.py
---
This pr is to use extension installed from `whl` of last released package to generate base metadata and to solve issues following
1. https://github.com/Azure/azure-cli-dev-tools/issues/504
2. https://github.com/Azure/azure-cli-dev-tools/issues/472
3. https://github.com/Azure/azure-cli-dev-tools/issues/464
Its released and related pr is:
1. https://github.com/Azure/azure-cli-dev-tools/pull/501
2. https://github.com/Azure/azure-cli-dev-tools/pull/517
There is an edge case that when module folder name is different from its package name, `azdev extension remove` actually didn't remove its source code path in `sys.path`. For simplicity of version cal procedure, just remove the source code after …
=> {CI} Adjust version calculation to use `whl` for base metadata

.github/actions/env-setup/action.yml, .github/workflows/AzdevLinter.yml, .github/workflows/AzdevStyle.yml
---
This pr executed `azdev linter & style` using github workflow, to avoid using any token and ensure security in scripting running.
In the future, we can deploy the other CI tasks into github workflow.
=> {CI} Add `azdev style&linter` into github workflow

.github/workflows/AzdevLinter.yml, .github/workflows/AzdevStyle.yml
=> {CI} Reset workflow for no changed module prs

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_arc_utils.py, src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/containerapp_auth_decorator.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_blob_storage_token_store_msi.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_auth_commands.py
=> Support blob storage token store authenticate with MSI

scripts/ci/release_version_cal.py
---
When `isPreview: false` or not exists, and there is no last version, always return with current meta parsed.
=> {CI} Fix issue when `isPreview: false` 

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/setup.py
---
`az aks mesh disable-egress-gateway`. 
=> Fix ASM egress disable help message

src/standbypool/HISTORY.rst, src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/__cmd_group.py, src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_create.py, src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_delete.py, src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_list.py, src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_show.py, src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_status.py, src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_update.py, src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_wait.py, src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/__cmd_group.py, src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_create.py, src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_delete.py, src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_list.py, src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_show.py, src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_status.py, src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_update.py, src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_wait.py, src/standbypool/azext_standbypool/azext_metadata.json, src/standbypool/azext_standbypool/tests/latest/recordings/test_standby_container_group_pool_scenarios.yaml, src/standbypool/azext_standbypool/tests/latest/recordings/test_standby_virtual_machine_pool_scenarios.yaml, src/standbypool/azext_standbypool/tests/latest/test_standbypool.py, src/standbypool/setup.py
---
`az standby-vm-pool create`
`az standby-vm-pool update`
`az standby-vm-pool show`
`az standby-vm-pool list`
`az standby-vm-pool delete`
`az standby-container-group-pool create`
`az standby-container-group-pool update`
`az standby-container-group-pool show`
`az standby-container-group-pool list`
`az standby-container-group-pool delete`
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not …
=> Add StandbyPool API Version 2025-03-01

src/spring/HISTORY.md, src/spring/azext_spring/_breaking_change.py, src/spring/azext_spring/commands.py, src/spring/setup.py
=> Add spring retirement info

src/confcom/HISTORY.rst, src/confcom/azext_confcom/data/internal_config.json, src/confcom/azext_confcom/kata_proxy.py, src/confcom/azext_confcom/tests/latest/test_confcom_scenario.py, src/confcom/setup.py
Picked up the wrong version of genpolicy in the last release.
---
Reverting and adding a check to make sure we don't pick up prerelease or drafts in the future.
az confcom
=> [confcom] Rollback genpolicy version to Azure Linux V2

scripts/ci/avail-ext-doc/update_extension_list.py, src/managednetworkfabric/HISTORY.rst, src/networkcloud/HISTORY.rst
=> {CI} Update paths in update_extension_list.py and HISTORY.rst for Latest-version

src/datamigration/HISTORY.rst, src/datamigration/azext_datamigration/generated/_help.py, src/datamigration/azext_datamigration/manual/_help.py, src/datamigration/azext_datamigration/manual/helper.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/models/_models.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/models/_models_py3.py, src/datamigration/setup.py
Add support for managed identity based Azure Blob to SQL MI migrations.
---
az datamigration sql-managed-instance create
=> [datamigration]: Add support for blob to Sql MI identity migrations

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_vms_agentpool_type.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
---
aks update --migrate-vmas-to-vms
=> Reset vm_size and count to None under agent pool profile for VMAS migration

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_basiclb_and_update_to_standardlb.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
=> {aks}: Add support for basic lb migration

src/zones/HISTORY.rst, src/zones/README.md, src/zones/azext_zones/_argHelper.py, src/zones/azext_zones/resource_type_validators/microsoft_app.py, src/zones/azext_zones/resource_type_validators/microsoft_network.py, src/zones/setup.py
1.0.0b4
++++++
* Force resource group input to lowercase for comparison with ARG results
* Added support for the following resource types:
- NAT Gateways
- Public IP Prefixes
- Container Apps Jobs
---
az zones validate
- [ X ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ X ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ X ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)
Once your pull request is merged …
=> {zones} new resource types & bugfix - version 1.0.0b4

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/_validators.py
---
`az containerapp session code-interpreter execute`
=> [Session Code Execute] Extend maximum supported value of `--timeout-in-seconds` from 60 to 180

src/amg/HISTORY.rst, src/amg/azext_amg/_validators.py, src/amg/setup.py
To support https://github.com/Azure/azure-cli/pull/31066
---
=> {amg} Remove msrestazure for amg extension

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/_validators.py
---
`az containerapp session code-interpreter execute`
=> [Session Code Execute] Extend maximum supported value of --timeout-in-seconds from 180 to 220

src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
```
az aks create/update
```
=> {AKS} Update test for network isolated cluster

src/managednetworkfabric/HISTORY.rst, src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/fabric/_validate_configuration.py, src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/taprule/_create.py, src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/taprule/_list.py, src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/taprule/_show.py, src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/taprule/_update.py, src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/taprule/_wait.py, src/managednetworkfabric/azext_managednetworkfabric/azext_metadata.json, src/managednetworkfabric/setup.py
networkfabric - cli and sdk updates to fix issues found in the netwokfabric api that caused failures - swagger discrepancies.
---
=> networkfabric - cli and sdk updates to fix issues found in the netwokfabric api that caused failures - swagger discrepancies.

src/service_name.json
Removing Sap-hana cli extension as there are no more customers on this RP .  We did not run any tests as there are no resources available and this is complete removal of extension.
---
=> Remove hana on azure extension as we no longer support customers on Azure CLI

src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ingress_appgw_addon.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
When Ingress Appgateway Addon is enabled in Azure CNI Overlay cluster and `--uppgw-subnet-cidr` is specified on cluster create, the cidr should be shorter than /24.
`az aks create`
=> {AKS} fix test case when AGIC with Azure CNI Overlay

src/vme/HISTORY.rst, src/vme/azext_vme/_params.py, src/vme/azext_vme/custom.py, src/vme/azext_vme/tests/latest/test_vme_scenario.py, src/vme/setup.py
=> Add param force to az vme uninstall

src/qumulo/HISTORY.rst, src/qumulo/azext_qumulo/aaz/latest/qumulo/__cmd_group.py, src/qumulo/azext_qumulo/aaz/latest/qumulo/storage/file_system/__cmd_group.py, src/qumulo/azext_qumulo/aaz/latest/qumulo/storage/file_system/_create.py, src/qumulo/azext_qumulo/aaz/latest/qumulo/storage/file_system/_delete.py, src/qumulo/azext_qumulo/aaz/latest/qumulo/storage/file_system/_list.py, src/qumulo/azext_qumulo/aaz/latest/qumulo/storage/file_system/_show.py, src/qumulo/azext_qumulo/aaz/latest/qumulo/storage/file_system/_wait.py, src/qumulo/azext_qumulo/azext_metadata.json, src/qumulo/setup.py
=> CLI Description Update for Qumulo

src/confcom/HISTORY.rst, src/confcom/azext_confcom/data/internal_config.json, src/confcom/azext_confcom/template_util.py, src/confcom/azext_confcom/tests/latest/test_confcom_policy_conversion.py, src/confcom/azext_confcom/tests/latest/test_confcom_scenario.py, src/confcom/setup.py
Fixing case sensitivity for fields in json
---
Fields are typically case-insensitive in confcom. In #8835 a bug was introduced where the input.json format was no longer case-insensitive. This PR fixes that.
az confcom
=> [confcom] bugfix for json input being case-insensitive

src/storage-actions/HISTORY.rst, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/__cmd_group.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/__cmd_group.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/_create.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/_delete.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/_list.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/_list_assignment.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/_list_report.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/_preview_action.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/_show.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/_update.py, src/storage-actions/azext_storage_actions/aaz/latest/storage_actions/task/_wait.py, src/storage-actions/azext_storage_actions/azext_metadata.json, src/storage-actions/azext_storage_actions/tests/latest/recordings/test_storage_actions_task_preview_action_scenarios.yaml, src/storage-actions/azext_storage_actions/tests/latest/recordings/test_storage_actions_task_scenarios.yaml, src/storage-actions/azext_storage_actions/tests/latest/test_storage_actions.py, src/storage-actions/setup.py
---
https://github.com/Azure/aaz/pull/796
=> [Storage-Actions] GA 2023-01-01

src/aks-preview/azext_aks_preview/_help.py
=> {AKS} udpate description for --pod-cidr and --pod-cidrs

src/amg/HISTORY.rst, src/amg/azext_amg/_help.py, src/amg/azext_amg/commands.py, src/amg/setup.py
=> [AMG]: Deprecate api-key command group

src/cloudhsm/README.md
=> Fix Readme file - Cloudhsm

src/vme/HISTORY.rst, src/vme/README.rst, src/vme/azext_vme/custom.py, src/vme/azext_vme/utils.py, src/vme/setup.py
=> [vme] Skip the animation for powershell ide

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/setup.py
---
{AKS} `az aks update`: Fix the bug affecting VMAS to VMS migration. The code recently added to official azure-cli is updating the value of nodepool type earlier than the code in aks-preview,  leading to the following error. The fix is to slightly relax the check conditions in aks-preview.
> >               raise CLIError('This is not a valid VMAS cluster, we cannot proceed with the migration.')
> E               knack.util.CLIError: This is not a valid VMAS cluster, we cannot proceed with the migration.
- https://github.com/Azure/azure-cli/pull/31831
- https://dev.azure.com/azclitools/public/_build/results?buildId=262770&view=logs&j=155127ab-52f1-52e7-0e45-625d9d7884a4&t=4bb67950-ef03-52d4-44f5- …
=> {AKS} `az aks update`: Fix the bug affecting VMAS to VMS migration

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Due to a design change these two parameters are no longer needed. Ingress will instead scale to one large instance per workload profile node.
Contributes to https://msazure.visualstudio.com/Antares/_workitems/edit/33117299
---
az containerapp env premium-ingress add/update
=> Remove ingress min-replicas, max-replicas parameters

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/bastion/bastion.py, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
---
Introduce a new command: `az aks bastion`. This command utilizes the Bastion CLI extension to streamline secure access to AKS clusters. It performs the following actions:
- Establishes a local Bastion tunnel.
- Downloads the kubeconfig for the specified AKS cluster.
- Updates the kubeconfig to route traffic through the local tunnel port.
- Launches a new sub-shell with the modified kubeconfig, enabling seamless cluster access—especially useful when public access is restricted due to specific cluster features.
Limitations:
- The Bastion host must be provisioned separately by the user within the same virtual network (VNet) as the AKS cluster and passed to the command.
- On Windows, the sub-shell …
=> {AKS} `az aks bastion`: Add command to enable connections to managed Kubernetes clusters via Azure Bastion.

src/quantum/HISTORY.rst, src/quantum/azext_quantum/azext_metadata.json, src/quantum/azext_quantum/operations/workspace.py, src/quantum/setup.py
=> {Quantum} Fix resource SDK import error

src/acrcssc/HISTORY.rst, src/acrcssc/azext_acrcssc/azext_metadata.json, src/acrcssc/azext_acrcssc/helper/_deployment.py, src/acrcssc/setup.py
=> {Acrcssc} Fix resource SDK import error 

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_format.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_machine_cmds.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
---
aks machine show
aks machine list
=> [AKS] `az aks machine show/list`: Show more details

src/fleet/HISTORY.rst, src/fleet/azext_fleet/_help.py, src/fleet/setup.py
---
Updates 'az fleet member` help text for newly supported member cluster type.
=> [fleet] Update `az fleet memeber` help text

azure-pipelines.yml
Similar to https://github.com/Azure/azure-cli-extensions/pull/8116
Use Python 3.13 in pipeline.
Azure CLI will bump to 3.13 in https://github.com/Azure/azure-cli/pull/3192
=> {CI} Update pipeline to use Python 3.13

azure-pipelines.yml, scripts/ci/test_source.py
---
This PR uploads all candidate wheels to Azure DevOps pipeline artifacts for testing.
=> {CI} Add artifact publishing for built wheels in CI pipeline

src/machinelearningservices/CHANGELOG.rst, src/machinelearningservices/azext_mlv2/manual/requirements.txt, src/machinelearningservices/setup.py
=> CLI v2 2.39.0 (Version/changelog changes)

src/containerapp/azext_containerapp/_params.py
This is the range allowed by the underlying azure load balancer.
---
az containerapp env premium-ingress add/update
=> Update request idle timeout range

src/datamigration/HISTORY.rst, src/datamigration/azext_datamigration/tests/latest/recordings/test_datamigration_Scenario.yaml, src/datamigration/azext_datamigration/vendored_sdks/datamigration/_configuration.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/_configuration.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_database_migrations_sql_db_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_database_migrations_sql_mi_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_database_migrations_sql_vm_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_files_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_projects_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_resource_skus_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_service_tasks_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_services_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_sql_migration_services_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_tasks_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/aio/operations/_usages_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_database_migrations_sql_db_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_database_migrations_sql_mi_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_database_migrations_sql_vm_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_files_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_projects_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_resource_skus_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_service_tasks_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_services_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_sql_migration_services_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_tasks_operations.py, src/datamigration/azext_datamigration/vendored_sdks/datamigration/operations/_usages_operations.py, src/datamigration/setup.py
---
Publishing the stable version of the Data Migration APIs.
- az datamigration get-assessment
- az datamigration performance-data-collection
- az datamigration get-sku-recommendation
- az datamigration tde-migration
=> [DataMigration] - [CLI] - Publish stable API version - 2025-06-30

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/setup.py
Remove the sku preview flag from help command for AKS automatic
`az aks create -g -n --sku`
`az aks update -g -n --sku`
=> {AKS} Remove the sku preview flag from help command for AKS automatic

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_kms_infrastructure_encryption.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/linter_exclusions.yml, src/aks-preview/setup.py
=> [AKS] `az aks create`: Add new parameter `--kms-infrastructure-encryption` to enable KMS infrastructure encryption

src/fleet/HISTORY.rst, src/fleet/azext_fleet/_help.py
=> Fix help text for `fleet list` command

src/datadog/HISTORY.rst, src/datadog/azext_datadog/aaz/latest/datadog/monitor/_create.py, src/datadog/azext_datadog/aaz/latest/datadog/monitor/_delete.py, src/datadog/azext_datadog/aaz/latest/datadog/monitor/_show.py, src/datadog/azext_datadog/aaz/latest/datadog/monitor/_update.py, src/datadog/azext_datadog/aaz/latest/datadog/monitor/_wait.py, src/datadog/setup.py
=> Fix resource creation in datadog

src/machinelearningservices/HISTORY.rst, src/machinelearningservices/azext_mlv2/manual/custom/compute.py
=> Pylint fix + History update

src/machinelearningservices/CHANGELOG.rst, src/machinelearningservices/HISTORY.rst, src/machinelearningservices/azext_mlv2/manual/custom/_ssh_command.py, src/machinelearningservices/azext_mlv2/manual/custom/_ssh_connector.py, src/machinelearningservices/azext_mlv2/manual/custom/compute.py, src/machinelearningservices/azext_mlv2/manual/requirements.txt, src/machinelearningservices/setup.py
=> CLI v2 release - 2.39.0

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_consts.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/agentpool_decorator.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_blue_green_upgrade_nodepool.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_run_blue_green_upgrade.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_update_agentpool_profile_preview.py, src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
---
```
az aks nodepool add  --upgrade-strategy BlueGreen --drain-batch-size 10% --drain-timeout-bg 5 --batch-soak-duration 2 --final-soak-duration 2
az aks nodepool update --upgrade-strategy BlueGreen --drain-batch-size 10% --drain-timeout-bg 5 --batch-soak-duration 2 --final-soak-duration 2
az aks nodepool upgrade --upgrade-strategy BlueGreen --drain-batch-size 10% --drain-timeout-bg 5 --batch-soak-duration 2 --final-soak-duration 2
```
You only need to update the …
=> Add blue green upgrade support for aks-preview

src/confcom/azext_confcom/tests/latest/test_confcom_scenario.py
There is a test for the confcom extension which pulls a docker image by tag, and then asserts layer hashes match, this breaks regularly because the image changes between invocations.
This PR fixes that test
---
az confcom
=> [confcom] Fix test which pulls image and tests layers

src/aks-agent/HISTORY.rst, src/aks-agent/azext_aks_agent/_params.py
Without this change, the following error would happen:
```sh
az aks agent: 'true' is not a valid value for '--aks-mcp'. Allowed values: Enable AKS MCP integration, Disable AKS MCP integration.
```
Hence, this PR simplified the aks-mcp parameter by removing custom positive/negative labels and using the default three_state_flag behavior to properly handle true/false values.
---
You only need to update the version information in file setup.py and historical information in …
=> [AKS] Fix --aks-mcp flag to accept true/false values

src/azure-firewall/HISTORY.rst, src/azure-firewall/azext_firewall/_params.py, src/azure-firewall/azext_firewall/custom.py, src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_with_additional_log.yaml, src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py, src/azure-firewall/setup.py
=> Add new parameter to enable Dnstap logging in Azure Firewall
