Azure/azure-cli-extensions

.flake8, .github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, .gitignore, .travis.yml, CONTRIBUTING.rst, pylintrc, scripts/ci/test_static.sh, scripts/ci/util.py, scripts/ci/verify_codeowners.py, scripts/ci/verify_license.py, src/image-copy/azext_imagecopy/__init__.py, src/image-copy/azext_imagecopy/cli_utils.py, src/image-copy/azext_imagecopy/create_target.py, src/image-copy/azext_imagecopy/custom.py
- Fix style of image-copy
- Add PR template
- Add license and codeowner checks
- pylint/pep8
=> Static CI checks

.flake8, .github/PULL_REQUEST_TEMPLATE.md, .travis.yml, scripts/ci/test_index.py, src/index.json
=> CI: Index verification

.gitignore, .travis.yml, scripts/ci/test_integration.py, scripts/ci/test_source.sh, scripts/ci/verify_license.py
- License check: Handle \r\n and \n
- Index check: Reject https://pypi.python.org urls
- Source tests: Install extension in its own dir before running test for extension
=> CI Improvements

scripts/ci/test_integration.py, src/index.json
=> Extension names use dash instead of underscore

scripts/ci/test_integration.py, scripts/ci/test_source.sh, scripts/ci/test_static.sh, src/image-copy/azext_imagecopy/cli_utils.py, src/image-copy/azext_imagecopy/create_target.py, src/image-copy/azext_imagecopy/custom.py
=> Ignore SDK models/operations and KnackConversion testsdk

src/index.json
=> image copy: add version 0.0.4 back to index

pylintrc, scripts/ci/test_integration.py, scripts/ci/test_source.sh, scripts/ci/test_static.sh, src/image-copy/azext_imagecopy/__init__.py, src/image-copy/azext_imagecopy/_help.py, src/image-copy/azext_imagecopy/azext_metadata.json, src/image-copy/azext_imagecopy/cli_utils.py, src/image-copy/azext_imagecopy/create_target.py, src/image-copy/azext_imagecopy/custom.py, src/image-copy/readme.md, src/image-copy/setup.py, src/index.json
Since azure-cli 2.0.24 has been released, the index should be updated for the knack-based extensions.
---
=> Merge Knack-based branch

src/servicebus/azext_servicebus/_help.py, src/servicebus/azext_servicebus/_params.py, src/servicebus/azext_servicebus/commands.py, src/servicebus/azext_servicebus/custom.py, src/servicebus/azext_servicebus/tests/recordings/test_sb_alias.yaml, src/servicebus/azext_servicebus/tests/recordings/test_sb_namespace.yaml, src/servicebus/azext_servicebus/tests/recordings/test_sb_queue.yaml, src/servicebus/azext_servicebus/tests/recordings/test_sb_rules.yaml, src/servicebus/azext_servicebus/tests/recordings/test_sb_subscription.yaml, src/servicebus/azext_servicebus/tests/recordings/test_sb_topic.yaml
=> ServiceBus - cli extension 

.github/CODEOWNERS, src/webapps/azext_webapps/__init__.py, src/webapps/azext_webapps/_help.py, src/webapps/azext_webapps/azext_metadata.json, src/webapps/azext_webapps/create_util.py, src/webapps/azext_webapps/custom.py, src/webapps/setup.cfg, src/webapps/setup.py
=> Adding webapp extension for quickstart command

src/index.json, src/webapp/azext_webapp/create_util.py, src/webapp/azext_webapp/custom.py, src/webapp/setup.py
=> Adding a work around  for calling kudu to warm up 

src/aem/azext_aem/custom.py
Also, the extension response payload appears have a breaking change which I have to adjust the code
=> aem: fix a bug on detecting linux os type

scripts/refdoc/azhelpgen/azhelpgen.py
- Format user directory as ~ and use forward slashes
- Preserve backslash in example text
=> Ref doc gen formatting improvements

src/index.json
=> Az Cli IoT extension v0.4.3

src/index.json, src/webapp/azext_webapp/azext_metadata.json, src/webapp/setup.py
=> Websites: Adding metadata to support the isPreview feature

src/index.json, src/webapp/azext_webapp/_constants.py, src/webapp/azext_webapp/create_util.py, src/webapp/azext_webapp/custom.py, src/webapp/setup.py
=> Webapps: Support for asp.net, Java & static html

src/index.json, src/webapp/azext_webapp/_help.py
=> Websites: Updating Help for az webapp up

src/index.json, src/signalr/azext_signalr/_constants.py, src/signalr/azext_signalr/custom.py
=> Update SKU for SignalR CLI extension

src/index.json, src/webapp/azext_webapp/__init__.py, src/webapp/azext_webapp/custom.py, src/webapp/azext_webapp/tunnel.py, src/webapp/setup.py
This PR has the following improvements:
Implemented:
- State clearer message to connect on which port
- Show username and password when server-side ssh port is detected
- Increase ssh timeout from 30 seconds to 30 minutes
- (--port) argument is now optional, if not supplied, will pick a random available port
- ping scm site before creating tunnel
- Have CTRL-C terminate local server
Note: Will update index.json in subsequent commits
---
=> Tunneling improvements

src/botservice/azext_bot/_exception_handler.py, src/botservice/azext_bot/_params.py, src/botservice/azext_bot/custom.py
=> correct pylint errors in botservice

src/webapp/azext_webapp/__init__.py, src/webapp/azext_webapp/create_util.py, src/webapp/azext_webapp/custom.py, src/webapp/azext_webapp/tunnel.py
=> Pylint fixes for webapp extension

src/dev-spaces-preview/azext_dev_spaces_preview/__init__.py, src/dev-spaces-preview/azext_dev_spaces_preview/_help.py, src/dev-spaces-preview/azext_dev_spaces_preview/azext_metadata.json, src/dev-spaces-preview/azext_dev_spaces_preview/custom.py, src/index.json
=> Updating the dev-spaces command from aks group to ads group

src/dev-spaces-preview/azext_dev_spaces_preview/__init__.py, src/dev-spaces-preview/azext_dev_spaces_preview/_help.py, src/dev-spaces-preview/azext_dev_spaces_preview/custom.py, src/dev-spaces-preview/setup.py, src/index.json
=> Updating dev-spaces-preview extension to honor azds commands update

src/dev-spaces-preview/azext_dev_spaces_preview/custom.py, src/dev-spaces-preview/setup.py, src/index.json
=> Updating output messages to be printed in default mode

src/storage-preview/README.md
=> added examples and new features

src/webapp/azext_webapp/custom.py
I can not connect when using slot option and I got following errors.
```
urllib3.connectionpool : Starting new HTTPS connection (1): appname.scm.azurewebsites.net:443
urllib3.connectionpool : https://appname.scm.azurewebsites.net:443 "GET /api/settings HTTP/1.1" 200 757
urllib3.connectionpool : Starting new HTTPS connection (1): appname.scm.azurewebsites.net:443
urllib3.connectionpool : https://appname.scm.azurewebsites.net:443 "GET /AppServiceTunnel/Tunnel.ashx?GetStatus HTTP/1.1" 403 2399
Exception in thread Thread-1:
File "~/.pyenv/versions/2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "~/.pyenv/versions/2.7.15/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File …
```
=> Fixed: can not connect when using slot option.

src/storage-preview/README.md
=> Minor storage readme changes

.flake8, .travis.yml, scripts/ci/test_static.sh
---
Pinning pylint to 1.9.2 for CI and speed up flake8 to unbottle new PRs
=> Automationstatic

scripts/refdoc/azhelpgen/azhelpgen.py, scripts/refdoc/cligroup/cligroup.py
---
-Ref doc gen was broken by: https://github.com/Azure/azure-cli/pull/6472
-extension script uses latest released version of CLI, hence why this wasn't picked up until now.
=> ref doc gen broken due to deprecation work

scripts/ci/test_source.py
This was causing the test: `test_shource_wheels` to run forever.
=> check_call will block child_process if enough output is sent to PIPE

.travis.yml, scripts/ci/test_source.py
-Automation checks travis-commit-range and does a git diff to find files with changes.
-If not in travis, all tests will run.
=> removed static check for py2 and only run tests for edited extensions

.travis.yml, scripts/ci/index_changes.py, scripts/ci/verify_linter.sh
---
Closes: https://github.com/Azure/azure-cli-extensions/issues/205
-Linter verification occurs whenever index for a extension is modified, therefore publishing a new version of the extension.
-Teams will be expected to address linter problems with their extension when they next publish.
=> [Automation] Adding command linting for extensions to ensure consistency.

src/index.json, src/webapp/azext_webapp/tunnel.py, src/webapp/setup.py
fixes #268 
I tested it and was able to open the port
---
=> Fix webapp remote-connection create fails if specifying --port

src/express-route/azext_express_route/_validators.py
---
Found further issues with the validation that fails `express-route update` if not updating bandwidth.
-Tests need to be added to this extension so that bugs like can be caught from day 1, I'll open an issue for that.
=> [Express-Route] if no bandwidth is given, stop validation

scripts/ci/index_ref_doc.py
Changes in botservice CLI module are blocking the CI for extensions.
Suppressing this for now.
@swagatmishra2007 can you update the botservice extension to specify a max-cli-version of 2.0.51?
=> suppress gen ref docs for botservice for now

src/image-copy/azext_imagecopy/create_target.py, src/image-copy/setup.py, src/index.json
This PR updates the published version of the extension to include a timeout parameter to handle large images that fail to copy in 60 minutes.
Actual change is on #426, this closes #423
FYI @afengli
---
=> [Image-Copy] Update to version 0.0.9

src/index.json
---
@stevengum v0.4.1 does not specify a max cli version, while v0.4.3 is only valid for CLI version 2.0.52. 
This means that for CLI v2.0.53, users would see v0.4.1 of the botservice extension, which I dont believe you want.
Removing the older extension from the index in this PR to unblock CI and reference document generation.
Closes: https://github.com/Azure/azure-cli-extensions/issues/449
=> [botservice] remove old version of botservice extension

src/index.json
---
- Blob url for botservice gives 404, blob might have been deleted from storage account. 
- To bypass CI failures and prevent users from getting 404 errors upon trying to add the extension, I am removing the extension from our index.
=> remove botservice

src/storage-preview/HISTORY.rst, src/storage-preview/azext_storage_preview/__init__.py, src/storage-preview/azext_storage_preview/_client_factory.py, src/storage-preview/setup.py
=> [Storage] fix bug with --auth-mode

src/storage-preview/azext_storage_preview/operations/account.py, src/storage-preview/azext_storage_preview/vendored_sdks/azure_mgmt_storage/v2018_07_01/models/custom_domain.py, src/storage-preview/azext_storage_preview/vendored_sdks/azure_mgmt_storage/v2018_07_01/models/custom_domain_py3.py, src/storage-preview/setup.py
There's a mistake in the 2018-07-01 arm schema, and there is a bug in the account.py overwriting the wrong parameter, the later is fixed in azure-cli. 
---
=> Fix for --use-subdomain in azure storage extensions

.travis.yml
Not critical to merge (302 redirect should be handled correctly) but still necessary.
=> Docs repo renamed; changing ref in travis config

scripts/refdoc/azhelpgen/azhelpgen.py
Update azhelpgen.py in preparation for:
https://github.com/Azure/azure-cli/pull/8325
---
=> azhelpgen.py can now handle new help objects.

src/db-up/azext_db_up/_help.py, src/db-up/azext_db_up/_params.py, src/db-up/azext_db_up/commands.py, src/db-up/azext_db_up/custom.py
=> [db-up] add connection string commands

src/index.json
=> updating azure devops extension to 0.3.0

src/azure-firewall/azext_firewall/__init__.py, src/azure-firewall/azext_firewall/_params.py, src/azure-firewall/azext_firewall/_util.py, src/azure-firewall/azext_firewall/_validators.py, src/azure-firewall/azext_firewall/custom.py, src/azure-firewall/azext_firewall/tests/latest/__init__.py, src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall.yaml, src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py, src/azure-firewall/setup.py, src/index.json
Some minor fixes to AzureFirewall to test the `azdev build` and `azdev publish` commands.
---
=> Testing azdev publish with AzureFirewall

src/aks-preview/azext_aks_preview/custom.py
Two small bug fixes:
1. The service principal client Id is not passed to the role assignment method correctly
2. Need to use the same network profile parameter validation as in the base az aks command.
---
=> bug fixes: missing service principal and network profile parameter validation

src/index.json, src/interactive/azext_interactive/azext_metadata.json
The interactive extension is not compatible with Azure CLI 2.0.62's core. This PR pins the existing release, which will work with <2.0.61. A subsequent PR will have a release compatible with 2.0.62.
=> [Interactive] Pin max CLI core version

src/interactive/HISTORY.rst, src/interactive/azext_interactive/azclishell/__init__.py, src/interactive/azext_interactive/azclishell/_dump_commands.py, src/interactive/azext_interactive/azclishell/app.py, src/interactive/azext_interactive/azclishell/argfinder.py, src/interactive/azext_interactive/azclishell/key_bindings.py, src/interactive/azext_interactive/azclishell/layout.py, src/interactive/azext_interactive/azclishell/util.py, src/interactive/azext_interactive/azext_metadata.json, src/interactive/setup.py
=> Update interactive extension for CLI core 2.0.62.

src/aks-preview/azext_aks_preview/__init__.py
Restores the old, Python2-compatible syntax for calling `super()`.
Fixes Azure/AKS#908
cc: @zqingqing1 @xizhamsft
---
=> [aks-preview]: fix python3-only super() syntax

src/application-insights/azext_applicationinsights/_client_factory.py, src/application-insights/azext_applicationinsights/_help.py, src/application-insights/azext_applicationinsights/_params.py, src/application-insights/azext_applicationinsights/commands.py, src/application-insights/azext_applicationinsights/custom.py, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_api_key.yaml, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component.yaml, src/application-insights/azext_applicationinsights/tests/latest/test_applicationinsights_mgmt.py, src/application-insights/azext_applicationinsights/util.py, src/application-insights/setup.py, src/index.json
---
Introduces commands for managing App Insights components and API keys belonging to those resources. See https://github.com/Azure/azure-cli/issues/5543
=> App Insights control plane

src/aks-preview/azext_aks_preview/custom.py
=> setting default vm size for windows

src/db-up/azext_db_up/_help.py, src/db-up/azext_db_up/_params.py, src/db-up/azext_db_up/commands.py, src/db-up/azext_db_up/custom.py, src/db-up/azext_db_up/tests/latest/test_db_up_scenarios.py, src/db-up/setup.py, src/index.json
1. Use `pymssql` as data plane for 2 reasons
a. It doesn't need ODBC, which requires non trivial manual configuration in the machine, not cool
b. The Linux and Windows package bundles freetds so install is smooth; for OSX, db-up extension will 
handle the brew update to update  "freetds", so the install is smooth as well
2. Finish up the firewall rule and default db provision
=> SQL: make "up" command work end to end

src/index.json
Removing the botservice extension because all features of the extension are already in the main [botservice command module](https://github.com/Azure/azure-cli/tree/dev/src/command_modules/azure-cli-botservice) in the Azure-CLI repo or are outdated. 
@williexu, @tjprescott, @yugangw-msft 
---
- ~[ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)~
- ~[ ] Have you run `python scripts/ci/test_index.py -q` locally?~
- ~[ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).~
=> remove botservice from index.json

src/subscription/azext_subscription/azext_metadata.json, src/subscription/setup.py
=> [subscription] Set the max CLI core version as 2.0.66

src/index.json
=> Remove azure-cli-iot-ext and sap-hana from index.json

scripts/ci/test_index.py, src/index.json
It was removed in commit 43ed33d13552edc7d6b41ee141d9fd361234c28b due to using a feature not supported in CLI core version 2.0.67. The sap-hana extension was updated in https://github.com/Azure/azure-hanaonazure-cli-extension/pull/22 to cap the max CLI core version at 2.0.66 to avoid the breaking change. A follow-up change will be made once 2.0.67 is released to properly support it.
---
=> Re-add sap-hana to index.json

src/aks-preview/azext_aks_preview/custom.py
https://github.com/Azure/azure-cli/pull/7336 introduced support for `az aks browse` in cloud shell using a  special localhost endpoint to manage opening and closing ports for the underlying port-forward. However, the close was not wrapped in a check of whether the user was actually in cloud shell, causing an ugly (albeit innocuous) error message when users terminated the browse command. 
---
=> Check for cloud shell before calling localhost endpoint to close port

src/index.json, src/webapp/azext_webapp/_help.py, src/webapp/azext_webapp/acr_util.py, src/webapp/azext_webapp/custom.py, src/webapp/setup.py
Description
---
This is a small fix to the new 'az webapp container up' extension. Azure Container Registry recently updated their API version in the latest Azure CLI release, which broke some of our code.
=> Fix az webapp container up - use new ACR API version

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_client_factory.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
This PR adds support for ACR role assignment during AKS creation. To support this, two new command-line options are added: `--enable-acr` and `--acr-name`.
Usage: `az aks create ... --enable-acr --acr-name <acr-name>`.
=> Add support for ACR role assignment during AKS creation

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_client_factory.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
This PR adds support for ACR role assignment during AKS creation and update. 
Usage: 
* az aks create –n <name> -g <resource-group> --enable-acr --acr <name-or-id>
* az aks update –n <name> -g <resource-group> --enable-acr --acr <name-or-id>
=> Add support for ACR role assignment for AKS update

src/index.json
There are a couple factors to this index PR related to the IoT extension.
- First the v0.8.0 extension metadata had to be updated with azext.minCliCoreVersion set to 2.0.70. Package was recreated (thus the new hash).
- Second the existing extension version (v0.7.1) remains in the collection for users who are unable to upgrade their Azure CLI installations.
=> Update for IoT extension.

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_client_factory.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py
Rename ACR integration options:
* Rename `--attach-acr <acr-name-or-resource-id>` in `az aks create` command, which allows for attach the ACR to AKS cluster.
* Rename `--attach-acr <acr-name-or-resource-id>` and `--detach-acr <acr-name-or-resource-id>` in `az aks update` command, which allows to attach or detach the ACR from AKS cluster.
This PR actually backports https://github.com/Azure/azure-cli/pull/10379 to extension, so that they're aligned.
---
=> [AKS] Rename ACR integration options

src/aks-preview/azext_aks_preview/_client_factory.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py
Initial implementation of the `az aks kollect` command. This command will deploy a daemon set to customer 's aks cluster and collect logs and diag information. The logs and information will be saved to a storage account the user specified or the storage account specified in the diag settings of the cluster.
---
=> AKS kollect command implementation

src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/custom.py
With the new 0801 api version, we now supports control plane only cluster upgrade. Added the control-plane-only argument for this purpose and change the default to upgrade all (by setting kubernetes version of all agentpool profiles explicitly).
---
=> add support for ccp only upgrade and default to upgrade all

src/index.json, src/vm-repair/azext_vm_repair/repair_utils.py, src/vm-repair/setup.py
This is a urgent hotfix for an error that is happening for all Linux VMs. 
One line check has been added for null usernames. 
Clear to merge when reviewed.
=> vm-repair: hotfix for None replacement error for all linux VMs

src/aks-preview/HISTORY.md, src/aks-preview/setup.py, src/index.json
=> aks-preview extension release v0.4.19

src/index.json, src/internet-analyzer/HISTORY.rst, src/internet-analyzer/azext_internet_analyzer/vendored_sdks/frontdoor/operations/_preconfigured_endpoints_operations.py, src/internet-analyzer/setup.py
removed hack as it's no longer necesssary
=> internet-analyzer rc2

src/index.json, src/ip-group/azext_ip_group/_client_factory.py, src/ip-group/azext_ip_group/commands.py
Updating index for extension ip-group for azure-cli feature requested in [10726](https://github.com/Azure/azure-cli/issues/10726)
---
=> Update index for extension ip-group

src/aks-preview/HISTORY.md, src/aks-preview/README.md, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/setup.py
This change is for being compatible with the Azure-cli,
currently we have --zones for azure cli, however --node-zones for azure-cli-extensions so this is the first step to make them compatible, in second step we will remove the --node-zones command
=> add --zones and -z commands to aks-preview to make it compatible with azure-cli

.travis.yml, scripts/ci/verify_modified_index.sh, src/index.json
* Hotfix: bug introcuded by azure-cli commit [155b6bc Rewrite az in Python](https://github.com/Azure/azure-cli/commit/155b6bc1f9e358757c629cddd69bc3f0862f50cc)
* Update wrong sha256Digest of storage_preview
* Disallow failures on Travis CI
**WARNING**: This hotfix comments out  `azdev verify load-all` and `azdev cli-linter` (from azure-cli) , which opens the Pandora box that leave extension commands without some correctness verification. Will migrate those function into the public [azure-cli-dev-tools](https://github.com/Azure/azure-cli-dev-tools) ASAP.
---
=> Hotfix az rewrite and storage_preview

src/azure-firewall/azext_firewall/_validators.py, src/azure-firewall/azext_firewall/azext_metadata.json, src/azure-firewall/azext_firewall/commands.py, src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall.yaml, src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_rules.yaml, src/azure-firewall/setup.py, src/index.json
=> [Network]fix application rule bug

src/aks-preview/setup.py, src/index.json
The last version aks-preview extension published (0.4.21) did not use the latest wheel package and missed the newly added kanalyze command. So I am publishing a new version with ALL the latest changes.
---
- [x ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ x] Have you run `python scripts/ci/test_index.py -q` locally?
=> publishing new version of cli extension

src/dev-spaces/azext_dev_spaces/custom.py
Our Mac/Linux scripts need to know if `-y` was passed, so they can perform unattended installs.
=> DevSpaces: Passing do_not_prompt option to Mac/Linux install scripts

azure-pipelines.yml, scripts/ci/test_source.py
This is the 2nd and 3rd move for CI to migrate from Travis to ADO which [move job SourceTests to ADO](https://github.com/Azure/azure-cli-extensions/issues/1140) 
- Move 2: SourceTests for integration test (incremental testing)
- Move 3: LintOnModifiedExtensions
Respect #867
---
=> [CI] Move 2, 3: Copy job SourceTests, LintModifiedExtensions from Travis to ADO

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2019_10_01/operations/_managed_clusters_operations.py, src/aks-preview/setup.py, src/index.json
---
Manual test:
```
➜  azure-container-networking git:(master) az aks get-credentials -g <resource-group-name> -n <cluster-name>
The behavior of this command has been altered by the following extension: aks-preview
Merged "<cluster-name>" as current context in /Users/<user>/.kube/config
➜  azure-container-networking git:(master) az aks get-credentials -g <resource-group-name> -n <cluster-name> --admin
The behavior of this command has been altered by the following extension: aks-preview
Merged "<cluster-name>-admin" as current context in /Users/<user>/.kube/config
➜  azure-container-networking git:(master) az aks get-credentials -g <resource-group-name> -n <cluster-name> …
```
=> List credentials for different users via parameter `--user`

src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_01_01/operations/_managed_clusters_operations.py
=> Add the func list_cluster_monitoring_user_credentials in the vendored sdk for the version v2020_01_01

azure-pipelines.yml
Disable temporary until CredScan task of **Microsoft Security Code Analysis (Preview)** installed.
---
=> Chore: Disable job CredScan for ADO sceurity concern

scripts/ci/test_source.py
Build will fail in master branch as ADO envrionment variable `$(System.PullRequest.SourceCommitId)` and `$(System.PullRequest.TargetBranch)` is missing in BatchCI run (BatchCI is the reason to build after PR merge).
Job SouceTest runs `scripts/ci/test_source.py` require those 2 environment variables to make incremental test.
Test Plan:
1. Create a PR https://github.com/Azure/azure-cli-extensions/pull/1199
2. PR from hotfix-ci-test-source-src to hotfix-ci-test-in-master, job `Integration Test` succeed. ( [build ](https://dev.azure.com/azure-sdk/public/_build/results?buildId=233379&view=results))
3. PR merged, job `integration Test` succeed also. ( [build ](https://dev.azure.com/azure-sdk/public/_build/results?buildId=233381&view=results))
---
This checklist is used to make sure that common …
=> fix: CI job "SourceTests" will fail in non PR trigger build

src/connection-monitor-preview/azext_connection_monitor_preview/_help.py, src/connection-monitor-preview/azext_connection_monitor_preview/_params.py, src/connection-monitor-preview/azext_connection_monitor_preview/_validators.py, src/connection-monitor-preview/azext_connection_monitor_preview/tests/latest/recordings/test_nw_connection_monitor_v2_creation.yaml, src/connection-monitor-preview/azext_connection_monitor_preview/tests/latest/test_connection_monitor_preview.py, src/connection-monitor-preview/setup.py, src/index.json
https://github.com/Azure/azure-cli-extensions/pull/1238 's follow up.
---
=> {Network} Update index.json for connection-monitor-preview

src/index.json
The download URL seems to be invalid.
```
▶ dig anfclipython.blob.core.windows.net
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> anfclipython.blob.core.windows.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 21311
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;anfclipython.blob.core.windows.net. IN A
;; Query time: 66 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sat Feb 22 02:33:33 UTC 2020
;; MSG SIZE  rcvd: 63
```
it blocks PR by failed a CI check "IndexVerify":
1.  https://github.com/Azure/azure-cli-extensions/pull/1304
2.  https://github.com/Azure/azure-cli-extensions/pull/1241
Also, will fail CI of Azure/azure-cli
---
This …
=> [hotfix] netappfiles download url 404

src/index.json
#1367 was version 0.5.4. This updates the extension to [version 0.5.5](https://github.com/virtustream/azure-vmware-virtustream-cli-extension/releases/tag/0.5.5) which fixes a bug.
=> update vmware extension to 0.5.5

src/interactive/HISTORY.rst, src/interactive/azext_interactive/azclishell/__init__.py, src/interactive/azext_interactive/azclishell/app.py
Fix #1480: `az interactive` crashes with "cannot import name 'ENV_ADDITIONAL_USER_AGENT'"
This issue is introduced by https://github.com/Azure/azure-cli/pull/12734 which removed the redundant logic of `ENV_ADDITIONAL_USER_AGENT`, because it is already taken care of by msrest. 
This PR removes the dependency of `AZURE_HTTP_USER_AGENT` and hard-codes it because msrest doesn't expose it:
https://github.com/Azure/msrest-for-python/blob/4cc8bc84e96036f03b34716466230fb257e27b36/msrest/pipeline/universal.py#L70
```py
class UserAgentPolicy(SansIOHTTPPolicy):
_USERAGENT = "User-Agent"
_ENV_ADDITIONAL_USER_AGENT = 'AZURE_HTTP_USER_AGENT'
```
---
There is a pipeline to automatically build, …
=> [Interactive] Remove dependency of ENV_ADDITIONAL_USER_AGENT

azure-pipelines.yml, src/index.json
It's caused by ADO would install a global Azure CLI in /opt/az and pre-install azure-devops extension in /opt/az/azcliextenions. Besides, it will overwrite a environment variables  AZURE_EXTENSION_DIR.
The value of overwritten `AZURE_EXTENSION_DIR` is /opt/az/azcliextensions, so when tring to install the same extension azure-devops but with different version like this https://github.com/Azure/azure-cli-extensions/pull/1482 does, CLI will complain about there is already an existing extension installed, so, CI will fail.
Have to overwrite the AZURE_EXTENSION_DIR back to normal to fix that.
Test Result in previous one commit:
---
There is a pipeline to automatically build, upload …
=> [CI] Overwrite AZURE_EXTENSION_DIR to fix bug that CI will fail if installing azure-devops extension

src/support/HISTORY.md, src/support/azext_support/_client_factory.py, src/support/azext_support/_validators.py, src/support/setup.py
=> Removed resource id existence check and cleaned up associated logic

src/alertsmanagement/azext_alertsmanagement/vendored_sdks/__init__.py
{Alertsmanagement} Add __init__.py
Try to fix import error in CI checks when publishing the extension.
---
=> {Alertsmanagement} Add __init__.py

src/aks-preview/azext_aks_preview/custom.py
---
Description for Change:
Before any `aks update` command that doesn't specify the autoscaler profile would lead to clearing it because `if cluster_autoscaler_profile` is truthful. This changes that to only clear the profile when an empty string is passed as the autoscaler profile `--cluster-autoscaler-profile ""`, else it would preserve it.
=> [AKS] fix: avoid clearing the autoscaler profile when its not specified

src/databricks/HISTORY.rst, src/databricks/azext_databricks/_help.py, src/databricks/azext_databricks/_params.py, src/databricks/azext_databricks/_validators.py, src/databricks/azext_databricks/custom.py, src/databricks/azext_databricks/tests/latest/recordings/test_databricks.yaml, src/databricks/azext_databricks/tests/latest/test_databricks_scenario.py, src/databricks/setup.py
=> [Databricks] Remove some custom options

swagger_to_sdk_config.json
=> swagger-to-cli-automation-config

src/spring-cloud/azext_spring_cloud/_help.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/commands.py, src/spring-cloud/azext_spring_cloud/custom.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/__init__.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/_app_platform_management_client_enums.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/_models.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/_models_py3.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/operations/_apps_operations.py
=> spring-cloud: add support to enable/disable MSI

src/eventgrid/azext_eventgrid/tests/latest/recordings/test_private_link.yaml, src/eventgrid/azext_eventgrid/tests/latest/test_eventgrid_commands.py
=> fix tests due to network api version's change

src/spring-cloud/azext_spring_cloud/_transformers.py
---
Update table output for command, to align with portal display.
`az spring-cloud app list`
`az spring-cloud app show`
`az spring-cloud app deployment list`
`az spring-cloud app deployment show`
The new output should be look like 
and 
While the portal looks like
> N/A
> Should be shipped with other feature together, no need to update version this time.
=> Update spring cloud deployment and app table output to align with Azure portal

src/portal/README.md, src/portal/setup.py
=> Change portal README file from rst to markdown

src/vm-repair/azext_vm_repair/custom.py, src/vm-repair/setup.py
Quick few liner bug fix when the HyperV-version variable is none
=> vm-repair: Bug Fix when HyperV-version Variable is None

src/spring-cloud/azext_spring_cloud/_help.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/commands.py, src/spring-cloud/azext_spring_cloud/custom.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/__init__.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/_app_platform_management_client_enums.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/_models.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/_models_py3.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/operations/_apps_operations.py
This reverts commit 666bab74e6a748f0ceb83dab8c8d4ba01adcce95.
---
=> Revert "spring-cloud: add support to enable/disable MSI (#1523)"

azure-pipelines.yml, src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml, src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_management_ip_config.yaml, src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_firewall_policy.yaml
Azure CLI no long depends on wheel https://github.com/Azure/azure-cli/pull/13230, have to add it explicitly on CI.
Otherwise, the job would fail https://dev.azure.com/azure-sdk/public/_build/results?buildId=375020&view=results
---
=> [CI] Add wheel preinstallation for job IndexRefDocVerify and fix azure-firewall test recordings

azure-pipelines.yml, scripts/ci/util.py
remove wheel usage since Docs team might use this script and we don't have wheel preinstalled
---
=> [CI] Remove wheel usage

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
The latest azure-mgmt-resource version bump in https://github.com/Azure/azure-cli/pull/12928 to 9.0.0 seems to have broken the extension.
This causes the `aks-monitoring` deployment to fail.
This PR updates the invoke_deployment logic to match the CLI core  based on https://github.com/Azure/azure-cli/pull/10210
Tested with `az aks create --enable-addons monitoring` which is the only codepath that uses this call and `az aks update` commands.
Closes #13121
---
The precondition is to put …
=> [AKS] fix incorrect usage of ARM without going through the multi-api layer to fix broken monitoring deployment

src/aks-preview/azext_aks_preview/custom.py
---
Thanks @JunSun17 for discussion and please eyeball this PR.
* This PR will fix the exisitng issue folks are facing with respect to the broken functionality of periscope for any `aks cluster` above 1.14. The fix was checkin for `periscope` repo in march, but the issue was the wrong reference in the cli-extension to a release tag which is old.
* Discussed this and since we now have `latest` tag no more individual release of version update will be needed.
The precondition is to put your …
=> Fix the persicope version to always point to latest tag.

src/timeseriesinsights/HISTORY.rst, src/timeseriesinsights/azext_timeseriesinsights/_help.py, src/timeseriesinsights/azext_timeseriesinsights/custom.py, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_environment_longterm.yaml, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/test_timeseriesinsights_scenario.py, src/timeseriesinsights/setup.py
* Fix #1657: ``timeSeriesIdPropertyName`` is not parsed properly
* Fix #1658: When creating a new Standard Environment, ``--data-retention-time`` is not properly documented
=> [TimeSeriesInsights] Fix timeSeriesIdPropertyName is not parsed properly

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
---
Test result
- `az aks nodepool add ... CustomizedUbuntu=aks-ubuntu-1804`
```
The behavior of this command has been altered by the following extension: aks-preview
{
"agentPoolType": "VirtualMachineScaleSets",
"availabilityZones": null,
"count": 1,
"enableAutoScaling": null,
"enableNodePublicIp": false,
"id": …
```
=> AKS: add aks-custom-headers for nodepool and update

src/timeseriesinsights/HISTORY.rst, src/timeseriesinsights/README.md, src/timeseriesinsights/azext_timeseriesinsights/custom.py, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_access_policy.yaml, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_environment_longterm.yaml, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_environment_standard.yaml, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_event_source_eventhub.yaml, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_event_source_iothub.yaml, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_reference_data_set.yaml, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/test_timeseriesinsights_scenario.py, src/timeseriesinsights/azext_timeseriesinsights/vendored_sdks/timeseriesinsights/models/_models_py3.py
- Fix https://github.com/Azure/azure-cli-extensions/issues/1712: `--timestamp-property-name` should be made optional
- Due to service change corresponding to https://github.com/Azure/azure-rest-api-specs/pull/8758, change all `creation_time`'s type to `iso-8601`
- Change `IotHub` to `IoTHub` corresponding to https://github.com/Azure/azure-rest-api-specs/pull/8758, so that `IoTHubEventSourceResource` can be deserialized correctly
- Add instructions for installing and uninstalling the extension
=> [TimeSeriesInsights] Fix #1712: --timestamp-property-name should be made optional

azure-pipelines.yml, scripts/ci/credscan/CredScanSuppressions.json
=> {CI} Re-enable credscan

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_helpers.py, src/aks-preview/azext_aks_preview/tests/latest/test_helpers.py, src/aks-preview/setup.py
Refer https://github.com/Azure/aks-periscope/pull/21: trailing dash "-" is not allowed in storage name, hence this PR removes the trailing dash and aligned the logic with https://github.com/Azure/aks-periscope/pull/21.
---
=> Fix issues of storage account name for az aks kollect

src/subscription/setup.py
As it's going to on board #1842, we should fix the extension that miss azext_metadata.json
---
=> [subscription] Add azext_metadata.json

scripts/ci/test_index.py, scripts/ci/util.py
Fix https://github.com/Azure/azure-cli-extensions/issues/1052 via adding non-forgiveness assertion in CI to ensure azext_metadata.json must be existing.
1. This can detect error like **ip-group** successfully:
But with this PR https://github.com/Azure/azure-cli-extensions/pull/1843 merged, the error of ip-group would disappear.
2. With https://github.com/Azure/azure-cli-extensions/pull/1845 merged, error like **vm-repair** raise could be fixed.
3. Fix mixed-reality https://github.com/Azure/azure-cli-extensions/pull/1847
4. Fix subscription https://github.com/Azure/azure-cli-extensions/pull/1848
5. Fix managementpartner https://github.com/Azure/azure-cli-extensions/pull/1851
6. Fix log-analytics https://github.com/Azure/azure-cli-extensions/pull/1857
---
This checklist is used to make sure …
=> [CI] Add check that azext_metadata.json must exist

src/image-copy/HISTORY.rst, src/image-copy/azext_imagecopy/cli_utils.py, src/image-copy/setup.py
This bug is reported from Boeing on IcM. When a user tries to specify tags, it will fail.
It is a dict instead of a list.
This PR fixed this bug.
---
=> [Imagecopy] Fix a bug of tags

README.md, docs/README.md
Peer of https://github.com/Azure/azure-cli/pull/13960
---
=> {Doc} Refine extension release notes

src/storage-preview/HISTORY.rst, src/storage-preview/azext_storage_preview/operations/blob.py, src/storage-preview/azext_storage_preview/tests/latest/test_storage_adls_scenarios.py
=> [Storage] az storage blob directory move: Fix the problem that the directory fails to move when the source path contains spaces (#1277)

src/aks-preview/azext_aks_preview/custom.py, src/index.json, src/ip-group/setup.py
=> Adding new CLI parameters to support for proxy config

src/codespaces/HISTORY.rst, src/codespaces/azext_codespaces/_params.py, src/codespaces/azext_codespaces/version.py
Update the Codespaces extension to add the option to specify a 60-minute auto-suspend delay. Tested locally and the option is available when creating a codespace through the CLI extension.
---
=> [Codespaces] Add 60 minute auto-suspend timeout

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_byo_appgw_with_ingress_appgw_addon.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_byo_subnet_with_ingress_appgw_addon.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_managed_aad_enable_azure_rbac.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ingress_appgw_addon.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/container_service_client.py, src/aks-preview/setup.py
=> Added --enable-azure-rbac flag in ManagedClusterAadProfile (#2)

src/index.json
Remove https://appinsightscli.blob.core.windows.net/controlplane-cli/application_insights-0.1.1-py2.py3-none-any.whl from index.json
---
=> {Index} Remove useless AI extension version from index.json

scripts/ci/test_source.py
CI in extension use `pip` to install `whl` package and command index cannot detect such changes. Disable command index first. We need to refine CI later.
=> {CI} Temporarily disable command index in CI

src/log-analytics-solution/HISTORY.rst, src/log-analytics-solution/README.md, src/log-analytics-solution/azext_log_analytics_solution/_help.py, src/log-analytics-solution/azext_log_analytics_solution/_params.py, src/log-analytics-solution/azext_log_analytics_solution/_validators.py, src/log-analytics-solution/azext_log_analytics_solution/custom.py, src/log-analytics-solution/azext_log_analytics_solution/tests/latest/recordings/test_log_analytics_solution.yaml, src/log-analytics-solution/azext_log_analytics_solution/tests/latest/test_log_analytics_solution_scenario.py, src/log-analytics-solution/setup.py
Issue: #1677
Because log analytics solution does not support third party solutions,  so annotate `--plan-publisher`, `--name` and` --plan-product` with `deprecate_info`, add a new parameter `--solution-type` and remove any mention to Microsoft or 3rd party solutions.
Since the solution does not modify the logic of any old parameters, they are only declared to be deleted temporarily and will be deleted when the customers no longer uses them, so there will be no breaking change.
---
The …
=> [Log Analytics Solution] deprecate `--plan-publisher`, `--name`, `--plan-product` and add `--solution-type` for create

src/ai-examples/HISTORY.rst, src/ai-examples/azext_ai_examples/custom.py, src/ai-examples/setup.py
The Aladdin service expects to receive a GUID for both the correlationId and subscriptionId if they are sent. If users were not logged in or had disabled their telemetry, this service would return a 400, since the values passed in were considered strings, not GUIDs.
I believe https://github.com/Azure/azure-cli/issues/14094 was caused by this issue in `az find`, though the user was unable to reproduce it, so there could be other factors at play. The PR to fix `az find` is https://github.com/Azure/azure-cli/pull/14243.
---
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` …
=> [ai-examples] Fix missing subscription or disabled telemetry bug

src/ai-did-you-mean-this/azext_ai_did_you_mean_this/_const.py, src/ai-did-you-mean-this/azext_ai_did_you_mean_this/custom.py, src/ai-did-you-mean-this/setup.py
Allow users who've not opted into telemetry to still receive recommendations. If the user opted out of telemetry, no user identifying data will be sent.
Related: #1975 
---
=> [ai-did-you-mean-this] Allow users to receive recommendations if they've opted out of telemetry.

src/spring-cloud/azext_spring_cloud/_help.py
Our documentation treats the summary as markdown. If it has <xxx> it could be rendered as an html tag.
For the page: https://docs.microsoft.com/en-us/cli/azure/ext/spring-cloud/spring-cloud/app/deployment?view=azure-cli-latest#ext-spring-cloud-az-spring-cloud-app-deployment-create
Common solution is wrap <xxx> in backticks, as the PR shows.
=> wrap <xxx> in backticks for better documentation

src/aks-preview/HISTORY.md, src/aks-preview/README.md, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_validators.py, src/aks-preview/setup.py
=> [AKS]Support associating an existing user assigned identity for MSI cluster

src/vm-repair/azext_vm_repair/_help.py, src/vm-repair/azext_vm_repair/_validators.py, src/vm-repair/setup.py
- Minor fixes to address bug reports. 
- Minor fixes to help text
The default name value for newly created repair vms will now have a '_' at the end.
=> vm-repair: Fix vm name bug when 8th character in a VM name is a hyphen

src/aks-preview/azext_aks_preview/_format.py
`agentPoolProfiles` is always nil in the upgrade so this fixes the `-o table` option to also match the core CLI one.
Closes #1866
=> fix format table for upgrade profile because agentPoolProfiles is nil

src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py
This check is somewhat updated and no longer relevant. It also doesn't play nicely with with 0 nodes nodepool. Remove this and let pre-flight validation handle it.
---
=> remove max-pods validation from CLI and let pre-flight handle it

.github/CODEOWNERS, src/hpc-cache/HISTORY.rst, src/hpc-cache/azext_hpc_cache/_help.py, src/hpc-cache/azext_hpc_cache/tests/latest/test_hpc_cache_scenario.py, src/hpc-cache/setup.py
Fix #1946: Copied example has extra spaces
This is because in YAML, `|` stands for [Literal Style](https://yaml.org/spec/1.2/spec.html#id2795688), thus causing line breaks to be preserved.
Therefore, the example for [az hpc-cache create](https://docs.microsoft.com/en-us/cli/azure/ext/hpc-cache/hpc-cache?view=azure-cli-latest#ext-hpc-cache-az-hpc-cache-create-examples) breaks `resource_group` and `subnets` as
```
... re
source_group
... sub
nets
```
=> [hpc-cache] Remove line breaks from examples

src/aks-preview/azext_aks_preview/custom.py
---
PR: https://github.com/Azure/azure-cli/pull/14344 introduced a breaking change to azure-mgmt-resource which broke compatibility of  the AKS CLI-extension with the latest CLI core.
This is based off the changes to preserve backwards compatibility in PR: ttps://github.com/Azure/azure-cli/pull/14344
=> [AKS] fix regression from ARM mgmt sdk change

src/index.json
This update is to explicitly add deprecation information to command groups, commands and package description to make it obvious for users this extension should not be used anymore and to use 'azure-iot' instead.
---
=> Explicit legacy iot extension deprecation.

src/aks-preview/azext_aks_preview/_help.py
=> Fix AGIC typo and remove preview label from VN

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_constants.py, src/connectedk8s/azext_connectedk8s/_help.py, src/connectedk8s/azext_connectedk8s/_params.py, src/connectedk8s/azext_connectedk8s/_utils.py, src/connectedk8s/azext_connectedk8s/commands.py, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py
=> [ConnectedK8s] Added update command (#3)

src/aks-preview/azext_aks_preview/custom.py
=> [AKS] Set network profile when using basic load balancer.

src/db-up/HISTORY.rst, src/db-up/azext_db_up/_params.py, src/db-up/azext_db_up/_validators.py, src/db-up/azext_db_up/util.py, src/db-up/setup.py
=> {db-up} Fix issue 942: Add more arguments for `down`

.github/CODEOWNERS, src/webapp/azext_webapp/__init__.py, src/webapp/azext_webapp/_help.py, src/webapp/azext_webapp/custom.py
- Allows users to deploy various types of artifacts such as app.war, app.jar, static files, and zip files
- Supports asynchronous deployments, and deployments to a custom path.
- Deployment type is inferred from the extension of the file being deployed. This can be overridden using the --type parameter.
---
=> webapp: add support for using new OneDeploy API for deployments  in CLI

src/spring-cloud/azext_spring_cloud/_validators.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_validator.py
---
Disable role assignment check for vnet for Azure Spring Cloud. As checking role assignments for target VNet needs permissions to call AAD, this may block some customers in extreme circumstance when their az account does not have such permissions. 
=> Disable role assignment check for vnet for Azure Spring Cloud

src/image-copy/azext_imagecopy/custom.py
In `create_snapshot` function, there is a line
>location = location or _get_resource_group_location(cmd.cli_ctx, resource_group_name)
However service will use this location to retrieve the disk information. If the disk location differs with resource group location, service will throw "Resource disk_xxxxxxxx not found" error.
This makes the `az image copy` command fails.
This is a workaround solution from `image-copy` side for this case. The `snapshot` issue [az image copy failed create snapshot ](https://github.com/Azure/azure-cli/issues/14560)is recorded in azure-cli repo.
---
Once your PR is …
=> [ImageCopy] fix image copy failure when resource group location and disk location differ

src/application-insights/HISTORY.rst, src/application-insights/azext_applicationinsights/commands.py, src/application-insights/azext_applicationinsights/custom.py, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_workspace.yaml, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_public_network_access.yaml, src/application-insights/setup.py
This is to ask users to consent during APM migration which is described in https://github.com/Azure/azure-cli/issues/14787.
---
=> [Monitor] Ask users to consent during APM migration

src/ai-did-you-mean-this/azext_ai_did_you_mean_this/tests/latest/data/scenarios.py
After adding `--query-examples` option in core, one test failed in option prefix match:
`ambiguous option: --que could match --query, --query-examples`
Use the full matched `--query` to fix it.
---
=> [ai-did-you-mean-this] Fix ambiguous --que in test

src/ai-examples/HISTORY.rst, src/ai-examples/azext_ai_examples/custom.py, src/ai-examples/setup.py
In order to better handle the increased traffic, the Aladdin service is adding hashed User IDs to the request header in order to accurately rate limit clients. These should not interfere with normal usage, just prevent bad actors (most likely run-a-way scripts) from slowing down or breaking the service for other users.
The hashed ID is only used for the rate limiting and is only stored in memory for a temporary amount of time. It is not stored in telemetry.
---
The precondition is to put …
=> [ai-examples] Send User ID hash for rate limiting

src/timeseriesinsights/HISTORY.rst, src/timeseriesinsights/README.md, src/timeseriesinsights/azext_timeseriesinsights/custom.py, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/recordings/test_timeseriesinsights_environment_standard.yaml, src/timeseriesinsights/azext_timeseriesinsights/tests/latest/test_timeseriesinsights_scenario.py, src/timeseriesinsights/setup.py
Fix #2003: `--partition-key-properties` should be optional
**Testing Guide**
```powershell
$env = 'env1'
$rg = 'rg1'
az timeseriesinsights environment standard create -g $rg --name $env --location westus --sku-name S1 --sku-capacity 1 --data-retention-time 31 --storage-limit-exceeded-behavior PauseIngress
az timeseriesinsights environment standard create -g $rg --name $env --location westus --sku-name S1 --sku-capacity 1 --data-retention-time 31 --partition-key-properties DeviceId1 --storage-limit-exceeded-behavior PauseIngress
```
=> [TimeSeriesInsights] Fix #2003: --partition-key-properties should be optional

src/application-insights/azext_applicationinsights/_help.py
I changed api-keys from plural to singular. I ran in to this "problem" because I tried to run 'api-keys show' and it suggested 'api-key show' since the plural version doesn't exist.
---
- [no] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [no] Have you run `python scripts/ci/test_index.py -q` locally?
- [n/a] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).
Once your PR is merged into master branch, a new PR will be created to update …
=> [ApplicationInsights] Help shows api-keys in plural, should be singular

src/index.json
This is a new extension I've written to automate some of the tasks I find most repetitive with azure CLI: specifying my resource group, location, and subscription. It provides four new commands:
* `az fzf group` - select your default resource group
* `az fzf location` - select your default location
* `az fzf subscription` - select your current subscription
* `az fzf install` - download a copy of fzf if you don't have it
These commands make use of [FZF](https://github.com/junegunn/fzf), a command line fuzzy finder. When you install the extension and run them, they pop up a nice text interface that allows for searching and selecting from a list of objects via keyboard or mouse.
While I am a Microsoft employee, this is something I created on my off time and not something I did as a job duty. …
=> Include the fzf extension in the index

src/azure-firewall/HISTORY.rst, src/azure-firewall/azext_firewall/_params.py, src/azure-firewall/setup.py
If you specify `--priority` or `--action` in `az network firewall [network-rule|application-rule] create`, and the collection already exists, the operation will fail because it tries to recreate the collection. Make it more explicit in the documentation.
=> Improve collection arguments documentation for network rules

scripts/ci/update_ext_cmd_tree.py
Now the log will show messages like this in case of conflicts:
> Processing storage-blob-preview
> ...
> Exception: Key: show already exists in storage-preview. 2 extensions cannot have the same command!
Now we know that `storage-blob-preview` and `storage-preview` have the same command ending with `show`. By searching the log message, we are able to find the duplicate command is `az storage account management-policy show`.
---
The precondition is to put your code inside this repo and …
=> Add information in command conflict exception message when building extension command tree

scripts/ci/update_ext_cmd_tree.py
We do not want users to use hidden deprecated command and should exclude them when building the extension command tree for dynamic install.
---
=> Do not include hidden deprecated command when building extension command tree

src/account/HISTORY.rst, src/account/azext_account/generated/_params.py, src/account/azext_account/generated/custom.py, src/account/azext_account/tests/latest/recordings/test_account.yaml, src/account/azext_account/tests/latest/test_account_scenario.py, src/account/azext_account/vendored_sdks/subscription/models/_models.py, src/account/azext_account/vendored_sdks/subscription/models/_models_py3.py, src/account/setup.cfg, src/account/setup.py
Resolve https://github.com/Azure/azure-cli/issues/15436
---
=> [Account] account alias create: Add --reseller-id

src/index.json
See https://github.com/Azure/az-vmware-cli/releases
=> update index.json to vmware 0.7.2

src/azure-firewall/azext_firewall/_completers.py
Fix the top 1 non-actionable bug (https://github.com/Azure/azure-cli/issues/14984) that completer throwing AttributeError while creating a firewall network-rule
1. set export _ARC_DEBUG=1
2. type `az network firewall network-rule create -g harold -f fw-1 --name` and hit tap
3. print out the `namespace` properties show there is no `resource_name` property (the desired property is collection_name)
```
{'_argument_validators': [],
'_cmd': <azure.cli.core.commands.AzCliCommand object at 0x7f9e0d975b50>,
'_command_package': 'network',
'_command_validator': <function validate_af_network_rule at 0x7f9e0d96d290>,
'_jmespath_query': None,
'_log_verbosity_debug': False,
'_log_verbosity_only_show_errors': False,
'_log_verbosity_verbose': False,
'_output_format': 'json',
'_parser': …
```
=> [Firewall] Fix AttributeError while hitting tap to automatically complete the name of network rule of a firewall

src/index.json
=> update iot hub index to version 0.10.6

src/aks-preview/azext_aks_preview/custom.py
“az aks browse” command point to Azure Portal if Kubernetes version >= 1.19.0 or kube-dashboard addon is not enabled.
---
=> [AKS] az aks browse: point to Azure Portal Kubernetes resources view if k8s >=1.19 or kube-dashboard not enabled

linter_exclusions.yml, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_to_msi_cluster.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
=> [AKS] Support updating from SPN cluster to MSI cluster

src/blueprint/HISTORY.rst, src/blueprint/azext_blueprint/_params.py, src/blueprint/azext_blueprint/custom.py, src/blueprint/setup.py
Resolve #2594
To remove depends_on relationships between artifacts, you can use `--depends-on`, `--depends-on=` or `--depends-on ""` in artifact update commands.
---
=> [Blueprint] Support removing depends_on in update

scripts/ci/credscan/CredScanSuppressions.json
One of the suppression comes from:
The definition is 
```Python
class AzureMlLinkedService(LinkedService):
"""Azure ML Studio Web Service linked service.
All required parameters must be populated in order to send to Azure.
:param additional_properties: Unmatched properties from the message are deserialized to this
collection.
:type additional_properties: dict[str, object]
:param type: Required. Type of linked service.Constant filled by server.
:type type: str
:param connect_via: The integration runtime reference.
:type connect_via: ~data_factory_management_client.models.IntegrationRuntimeReference
:param description: Linked service description.
:type description: str
:param parameters: Parameters for linked service.
:type parameters: dict[str, …
```
=> {CI} Deal with CredScan upgrade

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/setup.py
The new error types require azure-cli versions >= 2.15.0. In order to make the extension compatible with older versions of azure-cli, this PR reverts the error type to be CLIError.
---
=> [aks-preview] Revert to use CLIError

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_constants.py, src/connectedk8s/azext_connectedk8s/_help.py, src/connectedk8s/azext_connectedk8s/_params.py, src/connectedk8s/azext_connectedk8s/custom.py
---
Version increase in setup.py will be taken up in another PR
Added --disable-proxy to go from a proxy scenario to a non proxy scenario
=> Added --disable-proxy

.github/CODEOWNERS, src/logic/HISTORY.rst, src/logic/azext_logic/azext_metadata.json, src/logic/azext_logic/manual/custom.py, src/logic/azext_logic/tests/latest/recordings/test_logic.yaml, src/logic/azext_logic/tests/latest/test_logic_scenario.py, src/logic/setup.py
Fix https://github.com/Azure/azure-cli-extensions/issues/2123
---
=> [Logic] logic workflow update: --definition is not to be mandatory while updating

scripts/ci/avail-ext-doc/list-template.md, src/blockchain/README.md, src/vmware/README.md
No extension changes. Part of an effort to remove unnecessary versioning link syntax.
See user story [1797650](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1797650) for more information.
=> 1797650: Remove '?view=' syntax

src/webapp/azext_webapp/__init__.py, src/webapp/azext_webapp/_help.py, src/webapp/azext_webapp/custom.py, src/webapp/setup.py
- The previous onedeploy CLI implementation did not surface all functionality of the onedeploy API via the CLI. Example: restart, clean, etc
- This commit surfaces all functionality supported by the API via the CLI
- Additionally, refactored the enable_onedeploy function to make it readable (and also to address the Python function complexity limit)
- Also - bumping up the extension minor version as this is the first time we are introducing the onedeploy functionality in this extension
---
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically. …
=> OneDeploy enhancements

src/webapp/azext_webapp/__init__.py, src/webapp/azext_webapp/acr_util.py, src/webapp/azext_webapp/custom.py, src/webapp/azext_webapp/tunnel.py
- This commit primarily fixes the style warnings (azdev style webapp)
- upload_source_code parameter list was missing the command param. This commit fixes that.
- Another change to functionality is that OneDeploy async deployments don't poll for the operation completion now. This behavior can be toggled for development purposes using the poll_async_deployment_for_debugging flag in code
---
The precondition is to put your code inside this repo and upgrade the version in the PR but do not …
=> Fix style warnings in the webapp extension

src/webapp/HISTORY.rst, src/webapp/setup.py
- The 0.3.0 release didn't happen because of "azdev style webapp" errors
- Incrementing 0.3.0->0.3.1 to kick-off another release
---
=> Increment webapp version from 0.3.0 -> 0.3.1

src/spring-cloud/azext_spring_cloud/_help.py, src/spring-cloud/azext_spring_cloud/commands.py, src/spring-cloud/azext_spring_cloud/custom.py, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_bind_cert_to_domain.yaml
=> Add warning message and unset active deployment operation

src/ssh/HISTORY.md, src/ssh/azext_ssh/custom.py, src/ssh/azext_ssh/ssh_utils.py, src/ssh/azext_ssh/tests/latest/test_custom.py, src/ssh/setup.py
* Change to use the first in the list of validprincipals as the default username
* Remove old paramiko dependency
This is an ugly hack with a real fix to come as part of a client and server side combined fix.  This will fix guest users who are using their mail (e.g. first.last@contso.com) but logged into az cli using a different UPN (e.g. flast@contso.com)
---
=> [SSH] Add support for getting the username from the certificate

src/ssh/azext_ssh/custom.py
Change the scope so it can be used by both user account and service principal when getting ssh cert.
---
=> [SSH] Change scope so it can be used by both user account and service principal

src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_validator.py
---
For Python, we need assert raised exceptions out of `self.assertRaises()`, referring to [here](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises) for details. Currently lots of UT in Azure Spring Cloud misuses it, and this will lead regression someday since all these UT do not work as excepted today.
=> Fix UT for azure spring cloud

src/cosmosdb-preview/HISTORY.rst, src/cosmosdb-preview/README.md, src/cosmosdb-preview/azext_cosmosdb_preview/_client_factory.py, src/cosmosdb-preview/azext_cosmosdb_preview/_help.py, src/cosmosdb-preview/azext_cosmosdb_preview/_params.py, src/cosmosdb-preview/azext_cosmosdb_preview/_validators.py, src/cosmosdb-preview/azext_cosmosdb_preview/commands.py, src/cosmosdb-preview/azext_cosmosdb_preview/custom.py, src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_mongodb_restorable_commands.yaml, src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_restore_command.yaml, src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_restore_using_create.yaml, src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_sql_restorable_commands.yaml, src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_cosmosdb_sql_role.yaml, src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_update_backup_policy_database_account.yaml, src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/test_cosmosdb-rbac_scenario.py, src/cosmosdb-preview/setup.py
Adding commands that allow public preview customers to create and manage Role Definitions and Role Assignments for enforcing data plane RBAC on Cosmos DB SQL accounts. The following commands are introduced:
- cosmosdb sql role definition create
- cosmosdb sql role definition delete
- cosmosdb sql role definition list
- cosmosdb sql role definition show
- cosmosdb sql role definition update
- cosmosdb sql role definition exists
- cosmosdb sql role assignment create
- cosmosdb sql role assignment delete
- cosmosdb sql role assignment list
- cosmosdb sql role assignment show
- cosmosdb sql role assignment update
- cosmosdb sql role assignment exists
---
There is a pipeline to …
=> Cosmosdb Add Role Definition and Role Assignment commands for Data Plane RBAC

azure-pipelines.yml, scripts/ci/test_index.py, scripts/ci/util.py
To mitigate the increasing failures in `Verify Extensions Index` CI task recently.
---
=> {Script} Add retry in get_whl_from_url and only verify latest version of an extension

src/index.json
Now that 2.0.1 is published with a higher minimum version, 2.0.0 needs to be removed to fix #3045. Older clients need to fall back to 1.0.0.
=> remove vmware 2.0.0 from index

src/next/HISTORY.rst, src/next/azext_next/__init__.py, src/next/setup.py
Because `NextCommandsLoader` is a singleton, the `_has_reload_command_table` is True when executing the recommended nested command for `az next`, then the execution history of the nested command will not be recorded
---
=> [next] Fix the bug that the nested command history could not be logged

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_consts.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_addon_with_azurekeyvaultsecretsprovider_with_secret_rotation.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_azurekeyvaultsecretsprovider_addon.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_enable_addon_with_azurekeyvaultsecretsprovider.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_azurekeyvaultsecretsprovider_with_secret_rotation.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/linter_exclusions.yml, src/aks-preview/setup.py
This change extends the az aks cli commands to allow enabling/disabling the `azure-keyvault-secrets-provider` AKS addon as a part of `az aks create`, `az aks enable-addons` and `az aks disable-addons` commands.
Currently an optional `enableSecretRotation` can be specified with the feature.
---
=> aks-preview: add azure-keyvault-secrets-provider as an aks addon

src/databox/HISTORY.rst, src/databox/azext_databox/azext_metadata.json, src/databox/azext_databox/commands.py, src/databox/setup.py
=> [Databox] GA databox

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_client_factory.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
Currently, the MSI client is created using current context's subscription, which is incorrect when the identity is in another subscription. This PR fix the error.
---
=> [AKS] Fix error that msi client always get managed identity in ctx's sub

scripts/ci/test_index.py, scripts/ci/test_source.py, scripts/ci/util.py
With the work of [PEP420](https://github.com/Azure/azure-cli/pull/14372) and [Enable CLI extensions to include packages in the 'azure' namespace](https://github.com/Azure/azure-cli/pull/13163), we can remove the check in CI that the dependencies of extension cannot start with `azure-`. It's blocking https://github.com/Azure/azure-cli-extensions/pull/3047.
---
=> Remove the limitation of using azure packages in dependency

src/vm-repair/azext_vm_repair/custom.py, src/vm-repair/azext_vm_repair/repair_utils.py, src/vm-repair/azext_vm_repair/scripts/linux-build_setup-cloud-init.txt
This PR is required for PR "https://github.com/Azure/repair-script-library/pull/13" as the current vm-repair extension needs to be modified to add the build tools at deployment time with the help of a cloud-init script.
=> Alar2 modifications

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
The addon profile is null when there is no addon added before. Here need to check it in the update scenario. 
Ref: #3248 
---
=> [AKS] Check addon profile if it exists

azure-pipelines.yml
=> {pipeline} ping azdev to 0.1.31

src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_addon_with_azurekeyvaultsecretsprovider_with_secret_rotation.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_none_private_dns_zone.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_using_azurecni_with_pod_identity_enabled.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ahub.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_auto_upgrade_channel.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_azurekeyvaultsecretsprovider_addon.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_fips.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_pod_identity_enabled.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_windows.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_enable_addon_with_azurekeyvaultsecretsprovider.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_get_upgrades.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_azurekeyvaultsecretsprovider_with_secret_rotation.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Fix the issued caused by a recent [PR #18031](https://github.com/Azure/azure-cli/pull/18031) in azure-cli. In that PR, the sdk version is updated to 11.2.0 in cli and the integration test in extension repo is performed with latest cli from dev branch. As a result, the api version of some operations in the test recordings for some test cases do not match. The most common mismatch is, the api version of the delete operation is changed from 2021-02-01 to 2021-03-01.
The following test cases are affected and need to be modified: 
The two unconfirmed test cases have some problems and need the help of the coder owner to provide new recording files.
Once your PR is merged into master branch, a …
=> [AKS] Update recording files to fix integration test error

scripts/ci/avail-ext-doc/list-template.md
=> [docs]Update list-template.md

scripts/ci/build_ext_cmd_tree.sh
New `ml` extension will be released in #3341.
It has overlapping commands with the old `azure-cli-ml`. Both extensions will coexist for a while. Block the `azure-cli-ml` first to avoid trouble when building extension command tree which requires that 2 extensions cannot have the same command.
---
=> Block azure-cli-ml in extension command tree

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py, src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/custom.py, src/connectedk8s/setup.py, src/db-up/HISTORY.rst, src/db-up/azext_db_up/custom.py, src/db-up/setup.py, src/k8s-extension/HISTORY.rst, src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py, src/k8s-extension/setup.py, src/mesh/HISTORY.rst, src/mesh/azext_mesh/custom.py, src/mesh/setup.py, src/service_name.json
Because Python SDK used by resource module needs to be migrated to track 2 recently, there are a lot of breaking changes in track 2, while the Python SDK of `azure-mgmt-resource` used by `azure-cli-extension` is the same as `azure-cli`. Therefore, the modules that use Python SDK of `azure-mgmt-resource` in `azure-cli-extension` should be added with the compatible logic of track 2.
Please refer to the PR description https://github.com/Azure/azure-cli/pull/17783 for specific compatibility logic to be added
---
Once your PR is merged into master branch, a new PR will be created to update …
=> Add compatible logic for the track 2 migration of resource

src/quantum/azext_quantum/__init__.py, src/quantum/azext_quantum/_client_factory.py, src/quantum/azext_quantum/azext_metadata.json, src/quantum/azext_quantum/operations/job.py, src/quantum/setup.py
As part of this change we are:
- Defining a user-agent-like string to represent the client used to submit jobs via the CLI.
- Append this to the user agent of the Control Plane and Data Plane clients.
- Set this as an environment variable for child processes to read it, as in the case of invoked standalone executables.
=> Add support for user agent string in calls to AQ via CLI

src/aks-preview/azcli_aks_live_test/clone_repo.sh, src/aks-preview/azcli_aks_live_test/prepare_image.sh, src/aks-preview/azcli_aks_live_test/setup_venv.sh, src/aks-preview/azcli_aks_live_test/start_container.sh, src/aks-preview/azcli_aks_live_test/test_cli_live.sh, src/aks-preview/azcli_aks_live_test/test_cli_unit.sh, src/aks-preview/azcli_aks_live_test/test_ext_live.sh, src/aks-preview/azcli_aks_live_test/test_ext_unit.sh, src/aks-preview/azcli_aks_live_test/transcribe_env.sh, src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml, src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml, src/aks-preview/azext_aks_preview/tests/latest/custom_preparers.py
This PR aims to polish the shell scripts used in aks pr check-in pipeline. The main changes are as follows；
* Update all shell scripts, add required variable checks, set bash options in a clearer way
* Update the way to forcibly update the azure-cli command index to ensure that the aks-preview command has been loaded before performing tests
* Define the trigger method in the pipeline yaml file
* Modify the implementation of AKSCustomResourceGroupPreparer to inherit (same as azure-cli)
The precondition is to put your code inside this repo and upgrade the version in the PR but do …
=> [AKS] Polish scripts used in aks pr check-in test pipeline

src/aks-preview/az_aks_tool/main.py, src/aks-preview/az_aks_tool/utils.py, src/aks-preview/azcli_aks_live_test/ext_matrix_default.json, src/aks-preview/azcli_aks_live_test/test_ext_live.sh, src/aks-preview/azcli_aks_live_test/transcribe_env.sh, src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml, src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Base on [PR#3415](https://github.com/Azure/azure-cli-extensions/pull/3415), this PR further fix some other known issues of the AKS PR check-in test pipeline. The main changes are as follows:
* Update az_aks_tool, add path check to avoid unexpected errors caused by invalid path
* Fix the problem that the variable passed to az_aks_tool in the extensions test script is lost
* Add two new test cases excluded by default (test_aks_disable_local_accounts, test_aks_update_to_msi_cluster_with_addons)
* Add a new pipeline variable *EXT_TEST_MATRIX* to override the default filtering rules
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically. …
=> [AKS] fix aks pr check-in test pipeline

src/virtual-wan/HISTORY.rst, src/virtual-wan/azext_vwan/_format.py, src/virtual-wan/azext_vwan/commands.py, src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vhub_connection_basic_scenario.yaml, src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vhub_get_effective_routes.yaml, src/virtual-wan/azext_vwan/tests/latest/test_azure_vwan_vhub_commands.py, src/virtual-wan/setup.py
---
closed https://github.com/Azure/azure-cli/issues/18105
=> [Virtual-wan] support `-o table` output for `az network vhub get-effective-routes`

src/aks-preview/azcli_aks_live_test/ext_matrix_default.json, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ingress_appgw_addon.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_ingress_appgw_addon_with_deprecated_subet_prefix.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
This PR aims to fix several live test cases in aks-preview by removing redundant "--service-principal xxxx" and add necessary "--yes" option in test file. Fixed test cases are listed below:
* azext_aks_preview.test_aks_create_with_virtual_node_addon
* azext_aks_preview.test_aks_create_with_ingress_appgw_addon_with_deprecated_subet_prefix
* azext_aks_preview.test_aks_enable_addon_with_openservicemesh
* azext_aks_preview.test_aks_disable_addon_openservicemesh
* azext_aks_preview.test_aks_byo_appgw_with_ingress_appgw_addon
* azext_aks_preview.test_aks_byo_subnet_with_ingress_appgw_addon
* azext_aks_preview.test_aks_create_with_ingress_appgw_addon
Once your PR is merged into master branch, a …
=> [AKS] Fix several live test cases in aks-preview

src/index.json
chore(arcdata): Welcome arcdata v0.0.1 preview
Introduce arcdata  v0.0.1 preview. The source is housed in an external repository and not here.
---
```
→ python scripts/ci/test_index.py -q
----------------------------------------------------------------------
Ran 9 tests in 103.891s
OK (skipped=2)
```
```
→  azdev linter --include-whl-extensions arcdata
Results 
=========
-  pass: faulty_help_example_parameters_rule 
-  pass: faulty_help_example_rule 
-  pass: faulty_help_type_rule 
-  pass: unrecognized_help_entry_rule 
-  pass: unrecognized_help_parameter_rule 
-  pass: expired_command_group 
-  pass: missing_group_help 
-  pass: expired_command 
-  pass: missing_command_help 
-  pass: no_ids_for_list_commands 
-  pass: bad_short_option 
-  pass: expired_option 
-  pass: …
```
=> chore(arcdata): Welcome arcdata v0.0.1 preview

src/vmware/azext_vmware/_help.py, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_addon.yaml, src/vmware/azext_vmware/tests/latest/test_addon_scenario.py
=> [vmware] add SRM recorded tests

src/vmware/CHANGELOG.md, src/vmware/setup.py
Now that the 2021-06-01 API has rolled out, it is time to publish the vmware extension version 3.0.0.
---
=> publish vmware 3.0.0

src/dnc/HISTORY.rst, src/dnc/azext_dnc/azext_metadata.json, src/dnc/azext_dnc/generated/commands.py, src/dnc/setup.py
Change dnc extension mode from experimental to preview
---
=> Change dnc extension mode

src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
=> fix issue in dcr template

src/index.json
Triggered by Azure CLI Extensions Release Pipeline - ADO_BUILD_ID=990645
Last commit: https://github.com/Azure/azure-cli-extensions/commit/cb184be8a165200bde068142c7b5f88db30c0fd1
Co-authored-by: Xing Zhou <Zhou.Xing@microsoft.com>
---
=> [k8s-extension] Fix index.json of k8s_extension

src/k8s-extension/HISTORY.rst, src/k8s-extension/setup.py
---
The modification #3605 has been added in this PR #3610
Therefore, there is no need to upgrade the version to `0.5.2` (release pipeline failed before, so this package version has not been released yet)
So revert this PR #3608
=> Revert unnecessary version upgrade for aks_extension

src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Remove some test cases that can be executed normally now which are filtered by default previously in the live test check-in pipeline ([AZCLI AKS LIVE TEST V2](https://dev.azure.com/msazure/CloudNativeCompute/_build?definitionId=219428&_a=summary)) .
Removed filtered test cases:
* test_aks_create_and_update_with_managed_aad_enable_azure_rbac
* test_aks_update_to_msi_cluster_with_addons
* test_aks_nodepool_get_upgrades
=> {AKS} Remove some previously filtered test cases in aks live test pipeline

src/quantum/azext_quantum/operations/job.py
This PR is a minor bug fixed related to job ids being retrieved incorrectly from standard output of a caller process.
The fix strips additional information from the output so only the job-id is used.
=> Fix issue during submission of jobs where status is reported incorrectly.

src/quantum/azext_quantum/operations/job.py
Because of a syntax difference between commands `dotnet build` and `dotnet run`, one of them expects the project location to be specified as a positional parameter and another as a named parameter. Because of this, we had a bug in which the user could not specify the location of a project outside of the current folder.
---
=> Fix to allow users to specify a location for a project to run in Azure Quantum

src/quantum/azext_quantum/_client_factory.py
With this change, we're adding the quantum extension version information to the user agent header as it was done in track 1.
---
=> Include CLI extension version info in user agent header in Azure Quantum requests

src/quantum/azext_quantum/_help.py, src/quantum/azext_quantum/commands.py, src/quantum/azext_quantum/operations/job.py
This change adds a new command to the `az quantum` CLI extension to request a job to be cancelled.
---
=> Add `az quantum job cancel` command to CLI extension

src/index.json, src/service_name.json
---
chore(arcdata): version bump to 0.0.2 preview
```
Results 
=========
-  pass: faulty_help_example_parameters_rule 
-  pass: faulty_help_example_rule 
-  pass: faulty_help_type_rule 
-  pass: unrecognized_help_entry_rule 
-  pass: unrecognized_help_parameter_rule 
-  pass: expired_command_group 
-  pass: missing_group_help 
-  pass: expired_command 
-  pass: missing_command_help 
-  pass: no_ids_for_list_commands 
-  pass: bad_short_option 
-  pass: expired_option 
-  pass: expired_parameter 
-  pass: missing_parameter_help 
-  pass: no_parameter_defaults_for_update_commands 
-  pass: no_positional_parameters 
-  pass: option_length_too_long 
-  pass: option_should_not_contain_under_score 
```
```
python scripts/ci/test_index.py -q …
```
=> chore(arcdata): version bump to 0.0.2 preview

src/interactive/HISTORY.rst, src/interactive/azext_interactive/azclishell/__init__.py, src/interactive/azext_interactive/azclishell/app.py
---
Fix https://github.com/Azure/azure-cli/issues/17740
As progress_patch() will raise exception when specifying det=xx, we change progress_patch() to accept key-value pairs.
=> [interactive] Fix #17740: `az interactive` fails with `progress_patch() got an unexpected keyword argument 'det'`

src/vmware/CHANGELOG.md, src/vmware/azext_vmware/_help.py, src/vmware/azext_vmware/_params.py, src/vmware/azext_vmware/commands.py, src/vmware/azext_vmware/custom.py, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_cloud_link.yaml, src/vmware/azext_vmware/tests/latest/test_cloud_link_scenario.py
=> Add `az vmware cloud-link` command group

src/aks-preview/HISTORY.md
Update missing history information aks-preview.
=> [AKS] Update missing history information in aks-preview

src/quantum/HISTORY.rst, src/quantum/azext_quantum/__init__.py, src/quantum/azext_quantum/_client_factory.py, src/quantum/setup.py
Job submissions are limited in the length of the ApplicationID string used.
In order to support this limitation, and keep the user agent consistent, this change is shortening the string to include only `az-cli-ext` instead of `azure-cli-extension` as prefix.
---
=> Hotfix 0.6.1 : Using a shorter version of the user agent string

src/aks-preview/azcli_aks_live_test/scripts/test_cli_live.sh, src/aks-preview/azcli_aks_live_test/scripts/test_ext_live.sh
Set up `az login` before running recording test to avoid the newly added test case does not include a corresponding
recording file and fall back to live mode, otherwise it will prompt `az login`.
=> {AKS} Update aks check-in pipeline

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_upgrade_nodepool.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
---
Test:
`az aks nodepool upgrade --resource-group $rg --cluster-name k8s --name dr2 --kubernetes-version 1.21.1 --aks-custom-headers WindowsContainerRuntime=containerd --debug`
returns successfully and the header value can ben seen below:
```
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': …
```
=> [AKS][aks-preview] `az aks nodepool upgrade`: Add new parameter `--aks-custom-headers`

scripts/ci/build_ext_cmd_tree.sh
`azure-batch-cli-extension` is not compatible with the latest batch SDK
---
=> [Pipeline] add `azure-batch-cli-extension` in blocklist to avoid command tree generate failure

src/application-insights/HISTORY.rst, src/application-insights/azext_applicationinsights/_params.py, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_storage.yaml, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_workspace.yaml, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_public_network_access.yaml, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_function.yaml, src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_webapp.yaml, src/application-insights/setup.py
Closed https://github.com/Azure/azure-cli-extensions/issues/796
---
=> [Application Insights] `az monitor app-insights events show`: Add enum values for `--type`

src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json, src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
Update matrix & Fix venv setup for AKS pipeline.
=> {AKS} Update matrix & Fix venv setup for AKS pipeline

scripts/ci/test_source.py, src/ai-examples/azext_ai_examples/tests/latest/test_ai_examples_scenario.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/alias/azext_alias/tests/test_alias.py, src/alias/azext_alias/tests/test_alias_commands.py, src/alias/azext_alias/tests/test_custom.py, src/alias/azext_alias/tests/test_util.py, src/alias/azext_alias/tests/test_validators.py, src/automation/azext_automation/tests/latest/test_automation_scenario_manual.py, src/blueprint/azext_blueprint/tests/latest/test_blueprint_scenario.py, src/confluent/azext_confluent/tests/latest/test_confluent_scenario.py, src/confluent/azext_confluent/tests/latest/test_confluent_term_accept_flow.py, src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/test_cosmosdb-cassandrami_scenario.py, src/datadog/azext_datadog/tests/latest/test_datadog_scenario.py, src/db-up/azext_db_up/tests/latest/test_db_up_scenarios.py, src/diskpool/azext_diskpool/tests/latest/test_disk_scenario_manual.py, src/hpc-cache/azext_hpc_cache/tests/latest/test_hpc_cache_scenario.py, src/interactive/azext_interactive/tests/latest/test_completion.py, src/interactive/azext_interactive/tests/latest/test_query_injection.py, src/interactive/azext_interactive/tests/latest/test_tree.py, src/scheduled-query/azext_scheduled_query/tests/latest/recordings/test_scheduled_query.yaml, src/scheduled-query/azext_scheduled_query/tests/latest/test_scheduled_query_scenario.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_validator.py, src/ssh/azext_ssh/tests/latest/test_custom.py, src/ssh/azext_ssh/tests/latest/test_rsa_parser.py, src/ssh/azext_ssh/tests/latest/test_ssh_utils.py, src/storage-blob-preview/azext_storage_blob_preview/tests/latest/test_storage_blob_live_scenarios.py
Related with https://github.com/Azure/azure-cli/pull/19024
---
=> {Packaging} Drop mock library

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/data/kubeletconfig.json, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
aks-preview CLI read use input kubelet config and try to read, before this change, wrongly containerLogMaxSizeMb as containerLogMaxSizeMB, fix this by use the correct one.
reference: https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?tabs=json
---
=> Fix wrongly used containerLogMaxSizeMB in customized kubelet config

src/quantum/azext_quantum/operations/job.py
Fixing bug on location used to show job output in synchronous submissions.
Due to this bug, if a default workspace is not set, then location is ignored when waiting for the output of a submitted job, so it will fail to be displayed even when the job has completed.
---
=> [Quantum] Bug fix: Wrong location is used when waiting for 'az quantum execute'

src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh, src/aks-preview/azcli_aks_live_test/scripts/transcribe_env.sh, src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-live-test.yaml, src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-unit-test.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Create ssh-key in advance to avoid the race condition that is prone to occur when key creation is handled by azure-cli when performing test cases concurrently.
For more details, please refer to issue [#18854](https://github.com/Azure/azure-cli/issues/18854).
=> {AKS} create ssh-key in advance when perform concurrent tests

src/quantum/azext_quantum/operations/job.py
It is valid for an Azure Quantum job to produce an empty file as a response. This change extends the logic to allow this condition, and also detect early mismatched quotes in the output.
---
=> Extend handling of job output to consider empty responses

src/quantum/azext_quantum/operations/job.py
As part of this change we're making the user output more informative with the following changes:
- If the program fails during compilation, we'll show the full Q# compiler output so the user understands the error better.
- If the stand alone executable fails to submit, we'll show the corresponding error message so the user can fix issues with parameters.
- We'll also verify if 'dotnet' is available, and error out early if not.
---
=> Improve user output during error handling

src/alertsmanagement/HISTORY.rst, src/alertsmanagement/azext_alertsmanagement/_help.py, src/alertsmanagement/azext_alertsmanagement/custom.py, src/alertsmanagement/azext_alertsmanagement/tests/latest/recordings/test_alertsmanagement_action_rule.yaml, src/alertsmanagement/azext_alertsmanagement/tests/latest/test_alertsmanagement_scenario.py, src/alertsmanagement/setup.py
closed https://github.com/Azure/azure-cli-extensions/issues/3072
---
- Add an example were the recurrence type is set to once.
- Fix error: when the recurrence type is set to once, 'Action Rule property 'properties.suppressionConfig.schedule' cannot be null.'
=> [alertsmanagement] Add an example were the recurrence type is set to once

src/aks-preview/azext_aks_preview/custom.py
Fix the failure of `aks update` sub-command caused by accidentally passing an empty profile object.
=> [AKS] Fix the failure of `aks update` sub-command caused by accidentally passing an empty profile object 

src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
Update default test matrix.
Remove the following exclusions from aks-preview, since they can now be tested normally 
* test_aks_create_with_ossku
* test_aks_nodepool_add_with_ossku
* test_aks_create_with_node_config
* test_aks_create_private_cluster_public_fqdn
* test_aks_custom_kubelet_identity
Add the following exclusion for acs, since they cannot be tested normally
* test_aks_create_with_auto_upgrade_channel
=> {AKS} Update default test matrix

src/authV2/azext_authV2/_params.py, src/authV2/azext_authV2/custom.py, src/authV2/azext_authV2/tests/latest/recordings/test_authV2_auth.yaml, src/authV2/azext_authV2/tests/latest/recordings/test_authV2_authclassic.yaml, src/authV2/setup.py
=> [AuthV2] Address Bug Bash feedback

src/quantum/HISTORY.rst, src/quantum/azext_quantum/__init__.py, src/quantum/azext_quantum/operations/job.py, src/quantum/setup.py
This is a release PR only to start the deployment of the 'az quantum' extension version 0.7.0
---
=> Update version and history info for 'az quantum' extension 0.7.0

src/aks-preview/azext_aks_preview/custom.py
In previous `pod identity add`'s implementation, we check for role assignment with full scope match, which is an incorrect assumption to the [Azure RBAC assignments](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-steps#step-3-identify-the-needed-scope). 
This pull request fixed the pod identity role assignment check as follows:
1. updated the role assignments list filter to `atScope() and assignedTo('{cluster_identity_id}')`. This could give us all role assignments targeted for the cluster identity
2. fixed scope check logic: we check with prefixed resource id
Fix #3679
---
There is a pipeline to automatically build, upload and publish …
=> fix(aks): check parent scopes role assignments in pod identity assignment

src/quantum/azext_quantum/operations/job.py
This is a change from @cesarzc that fixes an output processing issue for some Azure Quantum results that are not strings.
---
=> Quantum: Trim result for microsoft.simulator job only when it is a string.

src/quantum/azext_quantum/__init__.py, src/quantum/azext_quantum/_version_check_helper.py, src/quantum/azext_quantum/tests/latest/recordings/test_version_check.yaml, src/quantum/azext_quantum/tests/latest/test_quantum_workspace.py
Once per day, the Azure CLI quantum extension will perform a version check as part of any command.  If the latest available version of the extension is greater than the one installed, the user will see a yellow warning message in the following format:
```
Version 0.7.0 of the quantum extension is installed locally, but version 0.8.0 is now available.
You can use 'az extension update -n quantum' to upgrade.
```
If the latest available version number cannot be retrieved, or it matches the installed version, no message is shown. We won’t fail the command if we can’t get the most recent version, we’ll just proceed.  We won’t check again until the date changes or the context gets cleared.
This implementation will not cover commands that our extension does not handle directly, like “--help” …
=> Add quantum version check

src/quantum/azext_quantum/_help.py, src/quantum/azext_quantum/_params.py, src/quantum/azext_quantum/operations/job.py, src/quantum/azext_quantum/tests/latest/test_quantum_jobs.py
This PR adds an optional parameter `--job-params` to the following commands.
+ `az quantum job submit`
+ `az quantum execute`
+ `az quantum run`
This parameter contains a ist of `key=value` pairs that will be passed to the Quantum execution target as part of the job submission. The support for those parameters is specific to each target.
---
=> Add support for target specific job parameters

src/aks-preview/azcli_aks_live_test/scripts/test_ext_live.sh, src/aks-preview/azcli_aks_live_test/scripts/transcribe_env.sh
---
Update live test pipeline to support backward compatibility tests.
=> {AKS} Update live test pipeline to support backward compatibility tests

src/aks-preview/azext_aks_preview/_helpers.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/decorator.py
---
* Remove `aks browse`.
* Add support for option `--edge-zone`.
* Align api server access profile validation with cli.
* Backward compatibility with old api version.
=> {AKS} Add backward compatibility to cli

src/index.json
chore(arcdata): arcdata version bump to 1.1.0
---
=> chore(arcdata): arcdata version bump to 1.1.0

src/aks-preview/azext_aks_preview/decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
Reuse azure-keyvault-secrets-provider addon implementation from cli.
=> {AKS} Reuse azure-keyvault-secrets-provider addon implementation from cli

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
In previous version, we accidentally allowed user to specify empty pod labels for pod identity exception, which will be converted to `None` in response. As a result, this behavior will break the exception when using 2021-09-01 model. This is because we marked the `podLabels` as required while updating it with `None` value.
To unblock customer, this pull request added support for backfilling the null `podLabels` before sending to the server side. In the meanwhile, AKS will apply change to fix the response value.
---
Once your PR is merged into master branch, a new PR will be created to update …
=> aks: fix wrong behavior when applying default value for pod identity exception pod labels.

src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
* Fix the getter for outbound_type in decorator pattern.
- "covered_lines": 474,
- "num_statements": 480,
- "percent_covered": 98.75,
- "missing_lines": 6,
- "excluded_lines": 0
=> {AKS} Fix the getter for outbound_type in decorator pattern

src/aks-preview/azext_aks_preview/decorator.py
---
Fix the getter for workspace_id in decorator pattern.
=> {AKS} Fix the getter for workspace_id in decorator pattern

src/quantum/azext_quantum/_version_check_helper.py, src/quantum/azext_quantum/tests/latest/test_quantum_workspace.py
Added logic to suppress the update message if either version number is not available, and modified the unit tests accordingly. 
This bug fix primarily affects the presentation of the update message during testing, and as such will not change the user experience.  However, in the rare event of a transient connectivity glitch during version detection, this bug fix has the added benefit of preventing the user from ever seeing a spurious "None" in place of a valid version number in the message.
---
=> [Quantum] Do not display update message if version numbers are not available

linter_exclusions.yml, src/virtual-wan/HISTORY.rst, src/virtual-wan/azext_vwan/_help.py, src/virtual-wan/azext_vwan/_params.py, src/virtual-wan/azext_vwan/commands.py, src/virtual-wan/azext_vwan/custom.py, src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_gateway_connection_vpn_site_link.yaml, src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_gateway_connection_vpn_site_link_conn.yaml, src/virtual-wan/azext_vwan/tests/latest/recordings/test_azure_vwan_vpn_site_link_conn_ipsec_policy.yaml, src/virtual-wan/azext_vwan/tests/latest/test_azure_vwan_vhub_commands.py, src/virtual-wan/setup.py
closed https://github.com/Azure/azure-cli/issues/19233
closed https://github.com/Azure/azure-cli-extensions/issues/4074
---
=> [Network] Virtual-wan support multi link

src/network-manager/HISTORY.rst, src/network-manager/azext_network_manager/_help.py, src/network-manager/azext_network_manager/_params.py, src/network-manager/azext_network_manager/custom.py, src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_list_queries.yaml, src/network-manager/azext_network_manager/tests/latest/test_network_scenario.py, src/network-manager/setup.py
closed https://github.com/Azure/azure-cli/issues/20208
---
=> [Network Manager] Fix multi issues on network-manager

src/index.json, src/quantum/azext_quantum/commands.py, src/quantum/azext_quantum/tests/latest/test_quantum_jobs.py
The left-align string-formatting option "<" was applied to histogram rows in the job-results console output.
---
=> [Quantum] Left align histogram

src/spring-cloud/azext_spring_cloud/_app_validator.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/commands.py, src/spring-cloud/azext_spring_cloud/custom.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app_validator.py
In most secenarios under `az spring-cloud app`, it can accept a
parameter deployment. If the deployment is set, the command will update apps/deployments resource. Otherwise, it will look for one deployment under the app meets deployment.properties.active = true to be operated.
In today's code, each command handle such logic to fetch or use default value. This PR abstract this logic to validator, and make custom command can be focus on the operation logic
---
The precondition is to put …
=> refactor: 💡 Use validator to validate or default deployment

src/spring-cloud/azext_spring_cloud/_app_validator.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/_transformers.py, src/spring-cloud/azext_spring_cloud/custom.py, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_bind_cert_to_domain.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app_validator.py
There are some commands request there is an active Deployment under the App. This PR moves the logic from every commands to a validator
**It doesn't increase the CLI extension version on purpose**
---
=> refactor: 💡 Move ensure_active_deployment_exist to validator

src/aks-preview/azcli_aks_live_test/scripts/clean_up.sh, src/aks-preview/azcli_aks_live_test/vsts-azcli-aks-clean-up.yaml
=> {AKS} Add clean up pipeline

src/aks-preview/azext_aks_preview/decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
- Refactor updating windows profile.
- Sort out [dual stack related changes](https://github.com/Azure/azure-cli-extensions/pull/4174).
> "covered_lines": 552,
> "num_statements": 554,
> "percent_covered": 99.63898916967509,
> "missing_lines": 2,
> "excluded_lines": 21
=> {AKS} Refactor 2nd part of the update sub-command in aks-preview module

src/spring-cloud/azext_spring_cloud/_app_validator.py, src/spring-cloud/azext_spring_cloud/_client_factory.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/_transformers.py, src/spring-cloud/azext_spring_cloud/_validators.py, src/spring-cloud/azext_spring_cloud/commands.py, src/spring-cloud/azext_spring_cloud/custom.py, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_app_deploy_container.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_asc_update.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_bind_cert_to_domain.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_blue_green_deployment.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_create_asc_heavy_cases.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_create_asc_with_ai_basic_case.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_create_asc_without_ai_cases.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_load_public_cert_to_app.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_persistent_storage.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_stop_and_start_service.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_scenario.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/v2022_01_01_preview/models/_models.py, src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/v2022_01_01_preview/models/_models_py3.py
---
This PR upgrades the commands who use "preview" API version to switch to the latest preview API version. Because the 2022-01-01-preview is the only API version to support the Enterprise sku. As 2022-01-01-preview API version introduces some breaking changes since last preview API version. This PR also address these breaking changes in API level, and keep consistency on command/arguments/response 
The precondition is to put your code inside this repo and upgrade the version in the PR …
=> [Spring-Cloud] Update API version to 2022-01-01-preview

src/spring-cloud/azext_spring_cloud/_enterprise.py, src/spring-cloud/azext_spring_cloud/_help.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/_util_enterprise.py, src/spring-cloud/azext_spring_cloud/_utils.py, src/spring-cloud/azext_spring_cloud/_validators.py, src/spring-cloud/azext_spring_cloud/commands.py, src/spring-cloud/azext_spring_cloud/custom.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_validator.py, src/spring-cloud/azext_spring_cloud/tier_routing_spring_cloud.py
---
This PR adds `az spring-cloud create --sku Enterprise` choice. Since when `sku=Enterprise`, the creation steps are very different with others (later PR will introduce some other parameters which can be used in Enterprise only), this PR adds a router before `custom.py` for create command, routing the command whose `sku==Enterprise` to another impl file. In the new impl file, there will be some steps like creating the top level resource, later creation nested resource for enterprise only. All tiers shares the same step to create top level resource, the new impl file invokes the top level resource creation impl from `custom.py` as well.
There is a pipeline to automatically …
=> {spring-cloud} Add `spring-cloud create --sku Enterprise`

src/spring-cloud/azext_spring_cloud/_app_validator.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app_validator.py
---
This PR add validator on given arguments for `az spring-cloud app deploy` and `az spring-cloud app deployment create`. 
- `--source-path`, `--artifact-path` and `--container-image` must be provided one and only one.
- `--cpu` and `--memory` must be provided in accepted type, here put the normalize to the parameter parsing
This PR doesn't prompt version on purpose, will do it together with other PRs
The precondition is to put your code inside this repo and upgrade the version in the …
=> [spring-cloud] Add validator for app deploy and app deployment create

src/spring-cloud/azext_spring_cloud/gateway.py
---
Add implementation of gateway update, show, clear, gateway custom-domain show, list, update, unbind, gateway route-config show, list, create, update and remove.
=> [Spring Cloud] Add gateway related methods

src/spring-cloud/azext_spring_cloud/application_configuration_service.py
---
Add implementation of Application Configuration Service show, clear, git add, git update, git remove, git list, bind and unbind.
=> [Spring Cloud] Add application configuration service related implementation

src/spring-cloud/azext_spring_cloud/_help.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/_transformers.py, src/spring-cloud/azext_spring_cloud/_validators_enterprise.py, src/spring-cloud/azext_spring_cloud/commands.py, src/spring-cloud/azext_spring_cloud/service_registry.py
---
This PR adds "az spring-cloud service-registry" command groups, including three commands:
`az spring-cloud service-registry show -s xx -g xx`
Show the properties of service registry,
`az spring-cloud service-registry bind -s xx -g xx --app`
Bind an app to service registry
`az spring-cloud service-registry unbind -s xx -g xx --app`
Unind an app to service registry
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` …
=> [Spring Cloud] Add service registry related commands for Enterprise

src/aks-preview/HISTORY.md, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_oidc_issuer_enabled.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_oidc_issuer_enabled.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py, src/aks-preview/setup.py
=> [AKS] Implement `--enable-oidc-issuer`

src/spring-cloud/azext_spring_cloud/_help.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/_transformers.py, src/spring-cloud/azext_spring_cloud/_validators_enterprise.py, src/spring-cloud/azext_spring_cloud/application_configuration_service.py, src/spring-cloud/azext_spring_cloud/commands.py, src/spring-cloud/azext_spring_cloud/gateway.py, src/spring-cloud/azext_spring_cloud/tests/latest/files/gateway_routes.json, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_api_portal.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_application_configuration_service.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_gateway.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_service_registry.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_api_portal.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_application_configuration_service.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_gateway.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_service_registry.py
---
Add end to end logics for 4 Tanzu components: ACS, Service Registry, Gateway and API portal. Including commands, params, help, transformers and validator.
=> Add end to end logics for ACS, Service Registry, Gateway and API portal

src/aks-preview/azext_aks_preview/decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py
---
- Update error handling when creating cluster.
- Catch both `CloudError` and `HttpResponseError`, which would be raised since we have adopted track 2 SDK.
- Add unit test.
=> {AKS} Update error handling when creating cluster

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_format.py, src/aks-preview/setup.py
This will add a new column "currentKubernetesVersion" for az aks show --output table.
---
=> make the aks show table output contain currentKubernetesVersion column

src/spring-cloud/azext_spring_cloud/_params.py
=> add java 17 support

src/spring-cloud/azext_spring_cloud/_deployment_factory.py, src/spring-cloud/azext_spring_cloud/_help.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/_tanzu_component.py, src/spring-cloud/azext_spring_cloud/_transformers.py, src/spring-cloud/azext_spring_cloud/_validators.py, src/spring-cloud/azext_spring_cloud/_validators_enterprise.py, src/spring-cloud/azext_spring_cloud/api_portal.py, src/spring-cloud/azext_spring_cloud/app.py, src/spring-cloud/azext_spring_cloud/application_configuration_service.py, src/spring-cloud/azext_spring_cloud/commands.py, src/spring-cloud/azext_spring_cloud/gateway.py, src/spring-cloud/azext_spring_cloud/spring_cloud_instance.py, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_enterprise_service_create.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_gateway.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_scenario.py
---
- Integrate Tanzu components creation with `service create` commands.
- Add --config-file-pattern parameter to `app deploy/update/deployment create`
=> [Spring Cloud] Integrate tanzu components with service and app

src/spring-cloud/azext_spring_cloud/_app_validator.py, src/spring-cloud/azext_spring_cloud/_deployment_factory.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/_utils.py, src/spring-cloud/azext_spring_cloud/app.py, src/spring-cloud/azext_spring_cloud/custom.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app_validator.py
---
Previously wrongly fatal the `az spring-cloud app update` when there is no active deployment under it. It should just set a warning if user just want to update the app properties
Will upgrade version in #4294 
=> fix(spring-cloud): 🐛 App update warns when  active deployment not found

src/cosmosdb-preview/azext_cosmosdb_preview/_params.py, src/cosmosdb-preview/setup.py
=> Update workaround information in parameter helptext

src/enterprise-edge/HISTORY.rst, src/enterprise-edge/azext_enterprise_edge/_help.py, src/enterprise-edge/azext_enterprise_edge/_params.py, src/enterprise-edge/azext_enterprise_edge/custom.py, src/enterprise-edge/setup.py
=> [Enterprise-Edge] : `az staticwebapp enterprise-edge enable` : register Microsoft.CDN provider automatically upon running enable command 

src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/app.py, src/spring-cloud/azext_spring_cloud/custom.py, src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_app_i2a_tls.yaml, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app_scenario.py
=> Update Terminology end-to-end TLS to ingress-to-app TLS

src/spring-cloud/azext_spring_cloud/_deployment_source_factory.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring-cloud/azext_spring_cloud/_validators.py, src/spring-cloud/azext_spring_cloud/app.py, src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app.py
---
`az spring-cloud app create --enable-persistent-storage` should sent to backend with PATCH.
Will upgrade version in  #4294 
=> fix: 🐛 Validate deployment parameters with source type

linter_exclusions.yml, src/index.json
Also removes older version `v0.10.14` from the index.
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.13.0
---
=> [IoT] IoT Extension Release v0.13.0

src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Update several location configs in test cases.
=> {AKS} Update several location configs in test cases

src/quantum/eng/Generate-DataPlane-Client.ps1
Simple PR to update Data-Plane client generation script to delete previous output folder contents.
No changes in the actual extension.
---
=> Quantum: Update Data-Plane client generate script to delete previous output folder contents

azure-pipelines.yml
Same as https://github.com/Azure/azure-cli/pull/21230
Because package `Microsoft.Security.CredScan` in task `Run Credential Scanner` was upgraded from version `2.1.17` to the new version `2.2.7.8`, a large number of issues were scanned, resulting in CI blocking [pipeline link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1354072&view=logs&j=90b26e6a-5461-58d0-82ac-76aa6c69f0af&t=cb13b626-29b0-5981-0cad-2f2519bb3c97)
Therefore, pin the version of `Microsoft.Security.CredScan` to the last successfully version `2.1.17` to avoid blocking CI
=> {ADO} Pin version `2.1.17` for cred scan

src/aks-preview/azext_aks_preview/addonconfiguration.py
---
Sync PR [#21173](https://github.com/Azure/azure-cli/pull/21173) from azure-cli.
Container Insights Solution being added (if it doesnt exist already) by the AKS RP as part of the monitoring addon enablement. This PR removes this unnecessary ContainerInsights solution addition.
=> {AKS} Remove Container Insights Solution Deployment

src/appservice-kube/HISTORY.rst, src/appservice-kube/azext_appservice_kube/_constants.py, src/appservice-kube/azext_appservice_kube/azext_metadata.json, src/appservice-kube/azext_appservice_kube/commands.py, src/appservice-kube/azext_appservice_kube/custom.py, src/appservice-kube/azext_appservice_kube/resources/LinuxFunctionsStacks.json, src/appservice-kube/azext_appservice_kube/resources/WindowsFunctionsStacks.json, src/appservice-kube/setup.py
=> [appservice-kube] Fix #4357, #4358 : support functions v4 and powershell functions

src/aks-preview/azext_aks_preview/custom.py
---
- Fix `aks kollect` command cannot read storage account from diagnostic settings. Issue [#4448](https://github.com/Azure/azure-cli-extensions/issues/4448).
- The reason for the error is that in the latest api version (2021-05-01-preview) of the monitor management client, the result returned by the list operation for diagnostic settings becomes an [iterator](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2021_05_01_preview/operations/_diagnostic_settings_operations.py#L242), which used to be an object of type [DiagnosticSettingsResourceCollection](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-mgmt-monitor/azur …
=> [AKS] Fix `aks kollect` command cannot read storage account from diagnostic settings

src/index.json
chore(arcdata): arcdata version bump to 1.2.1
=> chore(arcdata): arcdata version bump to 1.2.1

src/quantum/azext_quantum/operations/job.py, src/quantum/azext_quantum/operations/workspace.py
When running the`az quantum execute`command, there is a delay of several seconds between entering the command and anything happening on the screen. This also occurs with the`az quantum job submit`and`az quantum workspace create`commands.
The changes in this PR cause progress messages (or dots) to appear immediately, to address feedback that "something should happen on the screen as soon as the command is entered."
---
=> [Quantum] Show progress messages and dots before executing commands

src/index.json
---
chore(arcdata): arcdata version bump to 1.2.3
=> chore(arcdata): arcdata version bump to 1.2.3

src/vm-repair/HISTORY.rst, src/vm-repair/azext_vm_repair/custom.py, src/vm-repair/setup.py
PR only
This PR fixes an UUID issue which may happen if the same Ubuntu 18 image, by both the recover VM created and the os-image, is in use.
With this PR the recover-vm boots from its own os-disk and not , which can happen by chance, from the disk to be recovered
Below lsblk output makes it clear how the double UUID issue may look like with this fix
repair-AZC-020:~$ lsblk -f
NAME    FSTYPE LABEL           UUID                                 MOUNTPOINT
sda
├─sda1  ext4   cloudimg-rootfs 5b1ab5d4-8b76-46c5-928f-8db42fbe3af6 /
├─sda14
└─sda15 vfat   UEFI            91B6-4BB7                            /boot/efi
sdb
└─sdb1  ext4                   644dfbda-f823-4427-9f08-4ca90bb189c5 /mnt
sdc
├─sdc1  ext4   cloudimg-rootfs 5b1ab5d4-8b76-46c5-928f-8db42fbe3af6
├─sdc14
└─sdc15 vfat   UEFI …
=> Fix UUID issue for data disk

src/index.json
azurestackhci
Moving cli contents to a production subscription, more suitable for release.
cc @JocelynBerrendonner
=> Move cli contents to production subscription

src/functionapp/HISTORY.rst, src/functionapp/azext_functionapp/azure_devops_build_interactive.py, src/functionapp/azext_functionapp/tests/latest/test_devops_build_commands_thru_mock.py, src/functionapp/setup.py
A customer reached about an error when trying to run `az functionapp devops-pipeline create` and this PR address it.
While working on this PR, looks like the dependency, [`azure-functions-devops-build`](https://github.com/Azure/azure-functions-devops-build), also requires a fix (not related to this error as such). I worked up [the PR](https://github.com/Azure/azure-functions-devops-build/pull/55) for that as well.
PS: There were a few `pylint` errors, mostly for considering using `f-strings` but with a 9+ score. I suppose I could fix them and push them in this PR itself. Would that be OK?
resolves #4497
---
=> Fix functionapp devops-pipeline create

scripts/ci/test_index_ref_doc.sh
Same as https://github.com/Azure/azure-cli/pull/21798
CI failed:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1459023&view=logs&j=a49103b8-20d1-5a8c-534b-bda9ab69fa51&t=f07883fb-9b2e-5ef1-366a-e8e57e798ca5&l=1338
```
Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jinja2/__init__.py))
```
=> {CI} Pin `Jinja2` to 3.0.3

src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
self.not_exists('securityProfile.azureKeyVaultKms') can check:
* securityProfile does not exist
* if securityProfile exists, azureKeyVaultKms does not exist
=> [aks-preview] make sure securityProfile.azureKeyVaultKms doesn't exist in kms test case

src/containerapp/azext_containerapp/_utils.py
- Small low hanging fruit I noticed: fix error msg since secrets and env vars are space delimited now, instead of comma delimited
---
=> Fix error msg since secrets and env vars are space delimited 

src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
---
Filter out monitor related cases for cli runner.
=> {AKS} Filter out monitor related cases for cli runner

src/spring-cloud/HISTORY.md, src/spring-cloud/azext_spring_cloud/azext_metadata.json, src/spring-cloud/setup.py
---
1. We released spring-cloud CLI extension `3.1.0` with below PRs:
- [Vendor AppPlatform 2022-03-01-preview SDK](https://github.com/Azure/azure-cli-extensions/pull/4552)
- [Add support for AppMSI](https://github.com/Azure/azure-cli-extensions/pull/4598)
2. Later we find this CLI extension is not compatible with Azure CLI version 2.26.0, the error is "No module named 'azure.core.rest'", see below screenshot.
- <img width="1284" alt="image" src="https://user-images.githubusercontent.com/22190245/161374384-6c980002-46dc-4bf7-bc9d-daef53cd7984.png">
3. Impact: all customers use old version of CLI and spring-cloud cli extension `3.1.0` will be failed to execute any `spring-cloud` commands.
4. Based on that most of the testing spring-cloud extension `3.1.0` is carried out with CLI `2.34.1`, …
=> [Spring-cloud] Upgrade min version requirement of azure cli for spring-cloud

src/index.json
---
remove `3.1.0` of spring-cloud extension from index.json
See #4621 
Delete from history of spring-cloud extension with next release
---
=> [Spring-cloud] Remove 3.1.0 of Spring-Cloud extension from index.json

src/spring-cloud/HISTORY.md, src/spring-cloud/azext_spring_cloud/azext_metadata.json, src/spring-cloud/setup.py
---
1. We released spring-cloud CLI extension `3.1.0` with below PRs:
- [Vendor AppPlatform 2022-03-01-preview SDK](https://github.com/Azure/azure-cli-extensions/pull/4552)
- [Add support for AppMSI](https://github.com/Azure/azure-cli-extensions/pull/4598)
2. We find spring-cloud extension `3.1.0` is not compatible with Azure CLI `2.26.0`. It's caused by SDK introduced in earlier PR.
3. We release spring-cloud `3.1.1` to add min Azure CLI version from `2.25.0` to latest `2.34.1` with below PR
- [Upgrade min version requirement of azure cli for spring-cloud](https://github.com/Azure/azure-cli-extensions/pull/4621)
4. We also deleted spring-cloud `3.1.0` from `index.json` manually with below PR, so that customer will not be able to install it.
- [Remove 3.1.0 of Spring-Cloud extension from …
=> [Spring-cloud] Find min version requirement of Azure CLI

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_client_factory.py, src/aks-preview/azext_aks_preview/_format.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_snapshot.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_snapshot.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
=> add mc snapshot command and change nodepool snapshot

azure-pipelines.yml, scripts/ci/test_source.py
According to #4565, we should use HEAD as the ADO_PULL_REQUEST_LATEST_COMMIT.
This problem happens again at #4486.
See [Error log](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1475781&view=logs&j=d7b07fa6-1884-5260-cab7-367baa6ff6f2&t=2a8d4b0b-b34e-5683-c586-83d0d6277b9a).
In azext_vm_repair's PR our CI run appservice-kube test.
=> {CI} Fix tests not belonging to the changed extension are running 

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_constants.py, src/connectedk8s/setup.py
=> [connectedk8s] Update CSP to latest version

azure-pipelines.yml
Update pipeline to use Python 3.10
=> {CI} Update pipeline to use Python 3.10

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/addonconfiguration.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
---
BugFix: Keep aad profile in PUT request of ManagedCluster. Modified commands are
* `az aks scale`
* `az aks upgrade`
* `az aks enable-addons`
* `az aks disable-addons`
* `az aks addon enable`
* `az aks addon disable`
* `az aks addon update`
=> {AKS} Keep aad profile in PUT request of ManagedCluster

src/k8s-configuration/HISTORY.rst, src/k8s-configuration/setup.py
Fix https://github.com/Azure/azure-cli/issues/21964
MSI's bundled Python has been updated to 3.10 (https://github.com/Azure/azure-cli/pull/21746). `k8s-configuration` and `connectedk8s` depend on `pycryptodome==3.9.8` which doesn't release wheels for Python 3.10:
https://pypi.org/project/pycryptodome/3.9.8/#files
The latest `pycryptodome` 3.14.1 works with Python 3.10 using ABIs:
https://pypi.org/project/pycryptodome/#files
=> [k8s-configuration] Bump `pycryptodome` to support Python 3.10

src/aks-preview/azext_aks_preview/deploymentyaml/aks-periscope.yaml
Description of the fix, this PR updates the old tag within the `aks-periscope deployment file` which will cause failures, please see below for the old broken change, + new change which fixes the issue.
Thanks, 
**New version working**
**Old version causes this error**
---
=> Update periscope deployemnt file.

src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_help.py, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/_utils.py, src/containerapp/azext_containerapp/_validators.py, src/containerapp/azext_containerapp/commands.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/setup.py
=> Containerapps 4/11 Release [ Supporting MSI for ACA & some bug fixes]

src/quantum/azext_quantum/operations/job.py, src/quantum/azext_quantum/tests/latest/test_quantum_workspace.py
The job submission progress messages added for [PR 4480](https://github.com/Azure/azure-cli-extensions/pull/4480) broke the CLI integration tests in the E2E validation pipeline.  Only JSON output is expected in stdout during the tests.  By using the Knack logger and displaying the messages as warnings, the progress messages are output to stderr instead of stdout in a way that PowerShell will not treat them as errors. 
Also updated test_version_check in test_quantum_workspace.py to remediate another E2E validation pipeline test failure.
---
=> [Quantum] Output job progress messages with Knack logger

src/index.json
chore(arcdata): arcdata version bump to 1.3.1
=> chore(arcdata): arcdata version bump to 1.3.1

src/quantum/azext_quantum/_help.py, src/quantum/azext_quantum/_params.py, src/quantum/azext_quantum/commands.py, src/quantum/azext_quantum/operations/workspace.py
Description of changes:
- Expanded the error message that’s issued when the `-r` parameter is missing in `az quantum create workspace` 
- Added an example of how to find Provider IDs and SKUs in workspace.py and help.py
- Added more details to the `--provider-sku-list -r` parameter help in params.py
- Modified `transform_offerings` in commands.py for consistency of column headings
---
=> [Quantum] Expand help and error messages about Provider/SKU format

src/quantum/azext_quantum/operations/workspace.py, src/quantum/azext_quantum/tests/latest/test_quantum_workspace.py, src/quantum/azext_quantum/tests/latest/utils.py
To follow our telemetry naming convention and standardize queries, the ARM deployment name should begin with “Microsoft.AzureQuantum-“ when creating a quantum workspace.
---
=> [Quantum] Add "Microsoft.AzureQuantum-" prefix to deployment name

src/quantum/azext_quantum/tests/latest/test_quantum_workspace.py
Updated test_version_check in test_quantum_workspace.py to undo a fix applied in [PR 4632](https://github.com/Azure/azure-cli-extensions/pull/4632)
---
=> [Quantum] Accommodate changed version check behavior

src/rdbms-connect/HISTORY.rst, src/rdbms-connect/setup.py
Similar to #4643
Windows MSI package's bundled Python has been updated to 3.10 (https://github.com/Azure/azure-cli/pull/21746). `rdbms-connect` depends on `setproctitle==1.2.2` which doesn't release wheels for Python 3.10.
`setproctitle` starts to support Python 3.10 in 1.2.3. We use [compatible release](https://peps.python.org/pep-0440/#compatible-release) for `setproctitle` so that 1.2.3 can be installed.
Note: It is not a good practice to use a pinned version in `setup.py`.
=> [rdbms-connect] Use compatible release for `setproctitle` to support Python 3.10

src/quantum/HISTORY.rst
This pull request only corrects an entry in the az quantum extension history page on a reference version number.
=> Correcting QDK version referenced by quantum extension

src/aks-preview/HISTORY.md, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py, src/aks-preview/setup.py, src/index.json
---
This is an alternateive to https://github.com/Azure/azure-cli-extensions/pull/4719 aks is  debating. 
=> Aks [nodepool] update without args prompts to reconcile. 

src/scvmm/setup.md
All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/
---
=> chore: remove git.io

src/index.json
Related PR: #4778
Since the `index.json` PR #4753 of the previous version `0.5.65` is merged later than the PR #4759 that changed the version to `0.5.66` from `setup.py`, so the code in `index.json` from PR #4759 does not contain the contents of version `0.5.65`, then the generated index.json for version `0.5.66` from this PR conflicts with the index.json for version `0.5.65`
---
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify …
=> Fix conflicts for aks_preview index.json

src/logic/HISTORY.rst, src/logic/README.md, src/logic/azext_logic/generated/_params.py, src/logic/setup.py
=> {Logic}Fix ReadMe missing issue

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_apiserver_vnet_integration.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py, src/aks-preview/linter_exclusions.yml, src/aks-preview/setup.py
=> aks-preview: feature support for apiserver vnet integration

scripts/ci/test_source.sh
---
Because 1.24.0 has breaking change with 1.21.1.
So we bump azure-core version to 1.21.1 to fix CI error:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1561389&view=logs&j=9c80867e-ccda-50f1-65bc-e11447f3cda9&t=8e28b004-aba6-5a56-67c2-9d40a66e3ed9
Test screenshot：
=> {CI} Bump azure-core version to 1.21.1

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_completers.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/setup.py
---
[AKS] Fix: Raise error when user provides invalid value for `--os-sku`.
=> [AKS] Fix: Raise error when user provides invalid value for `--os-sku`

src/subscription/azext_subscription/_params.py, src/subscription/azext_subscription/subscription/models/subscription_client_enums.py
Fix: https://github.com/Azure/azure-cli-extensions/issues/4766
Update supported argument value for `--offer-types` of command `az account create`
---
`az account create`
=> {Subscription} Update supported  `--offer-types` of `az account create`

scripts/ci/test_source.sh
---
CI raise error：
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1569165&view=logs&j=9c80867e-ccda-50f1-65bc-e11447f3cda9&t=8e28b004-aba6-5a56-67c2-9d40a66e3ed9
- Fix: Install testsdk with requirements.
CI raise error:
- Fix: pip Install azure-cli with `--editable` to include tests directory.
=> {CI} pip Install testsdk remove the `--no-deps` parameter

src/containerapp/azext_containerapp/_help.py
Fixes https://github.com/Azure/azure-cli/issues/22443
---
=> {azext_containerapp} | Fixing a typo

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/azext_metadata.json
---
Update the minimum required cli core version for aks-preview.
=> {AKS} Update the minimum required cli core version for aks-preview

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/setup.py
---
Fix the validators for options `--min-count` and `--max-count`. Sync the changes from [PR #22442](https://github.com/Azure/azure-cli/pull/22442).
=> {AKS} Fix the validators for options `--min-count` and `--max-count`

src/datamigration/HISTORY.rst, src/datamigration/README.md, src/datamigration/azext_datamigration/manual/_help.py, src/datamigration/azext_datamigration/manual/_params.py, src/datamigration/azext_datamigration/manual/action.py, src/datamigration/azext_datamigration/manual/custom.py, src/datamigration/azext_datamigration/manual/helper.py, src/datamigration/setup.py
=> DataMigration: Adding time based collection and support for installed-ir-path

src/spring/HISTORY.md, src/spring/azext_spring/_client_factory.py, src/spring/azext_spring/_params.py, src/spring/azext_spring/_validators.py, src/spring/azext_spring/commands.py, src/spring/azext_spring/custom.py, src/spring/azext_spring/spring_instance.py, src/spring/azext_spring/tests/latest/recordings/test_asc_update.yaml, src/spring/azext_spring/tests/latest/recordings/test_az_asc_create.yaml, src/spring/azext_spring/tests/latest/recordings/test_create_asc_heavy_cases.yaml, src/spring/azext_spring/tests/latest/recordings/test_create_asc_with_ai_basic_case.yaml, src/spring/azext_spring/tests/latest/recordings/test_create_asc_without_ai_cases.yaml, src/spring/azext_spring/tests/latest/recordings/test_persistent_storage.yaml, src/spring/azext_spring/tests/latest/recordings/test_stop_and_start_service.yaml, src/spring/azext_spring/tests/latest/test_asa_create.py, src/spring/azext_spring/tests/latest/test_asa_scenario.py
---
We will release a new version in #4844
Version and setup.py will be updated in #4844
=> support ingress read timeout for azure spring app

src/spring/azext_spring/_params.py, src/spring/azext_spring/commands.py
=> remove preview tags for enterprise tier GA

src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Fix aks byo appgw test case `test_aks_byo_appgw_with_ingress_appgw_addon`. See sibling PR [#22608](https://github.com/Azure/azure-cli/pull/22608) in azure-cli.
`network application-gateway create`
=> {AKS} Fix aks byo appgw test case

src/aks-preview/azext_aks_preview/_help.py
Fixes https://github.com/Azure/azure-cli/issues/22673
---
=> {aks-preview} | Fixes typo Github to GitHub

src/webpubsub/setup.py
resolves #4910
---
az webpubsub
=> [Web PubSub] Allow newer versions of websockets

src/aks-preview/HISTORY.rst, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/_consts.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_csi_driver_to_v2.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_csi_drivers_extensibility.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_standard_csi_drivers.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
Fix test cases
- test_aks_create_and_update_with_csi_drivers_extensibility
- test_aks_create_with_standard_csi_drivers
- test_aks_create_with_csi_driver_v2
- test_aks_create_and_update_csi_driver_to_v2
Temporally disable test cases
- test_aks_create_with_azurekeyvaultkms
- test_aks_update_with_azurekeyvaultkms
- `az aks addon list-available`
- `az aks addon list`
- `az aks addon show`
Some of the addon commands are broken by the newly added addon `web application routing` by PR [#4872](https://github.com/Azure/azure-cli-extensions/pull/4872). cc @yizhang4321
Once your pull request is merged …
=> {AKS} Fix several tests

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_keda.yaml, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_keda.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_decorator.py, src/aks-preview/setup.py
```
az aks create
az aks update
```
=> {AKS} Add support for KEDA workload auto-scaler

src/scvmm/HISTORY.rst, src/scvmm/azext_scvmm/custom.py, src/scvmm/setup.py
=> [ Microsoft.SCVMM ] Requesting vmmserver credentials until non-empty

scripts/ci/update_ext_cmd_tree.py
---
Support to load aaz commands.
=> {UpdateExtCommandTree} Support aaz commands

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/custom.py
---
In this PR, it will additionally check if the storage path is a symlink, and if so, skip the permission check. For more details, please see PR [#22800](https://github.com/Azure/azure-cli/pull/22800).
`az aks get-credentials`
=> {AKS} `az aks get-credentials`: Fix permission prompt when saving config file to symlink

src/communication/HISTORY.rst, src/communication/README.md, src/communication/azext_communication/manual/_help.py, src/communication/azext_communication/manual/_params.py, src/communication/azext_communication/manual/custom.py, src/communication/azext_communication/tests/latest/recordings/test_send_sms_n_recipients.yaml, src/communication/azext_communication/tests/latest/test_communication_sms_scenarios.py, src/communication/setup.py
=> [communication] add support for multiple sms recipients

src/aks-preview/azext_aks_preview/agentpool_decorator.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
- Sync web app routing, PR #4872
- Sync custom ca trust, PR #4782
=> {AKS} Update v2 managed cluster decorator - part 1

src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_availability_zones.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
- Sync storage profile, PR #4865 and #4868
- Sync KEDA, PR #4905
- Fix test case `test_aks_availability_zones` to location eastus
=> {AKS} Update v2 managed cluster decorator - part 2

src/automation/README.md
Link is broken, url returns 404 for AzureAutomationTutorial.ps1 in README.md
Old Link: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-automation/scripts/AzureAutomationTutorial.ps1
New Link: https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.automation/101-automation/scripts/AzureAutomationTutorial.ps1
Fixes Azure/azure-cli-extensions#4947
---
The precondition is to put your code inside this repository …
=> {AzureAutomation} fixes Azure/azure-cli-extensions#4947

linter_exclusions.yml, src/index.json
chore(arcdata): version bump to 1.4.2
=> chore(arcdata): version bump to 1.4.2

.github/fabricbot.json
---
Why migrate fabric bot from portal to config-as-code:
- As fabric bot team are preparing to move permanently to "Config As Code", they have [hidden the save button](https://1esdocs.azurewebsites.net/datainsights/merlinbot/extensions/Fabricbot_Overview.html#what-happened-to-the-save-button) to disable the capability to update the configuration in portal.
- We need to update milestone every month, so we need migrate before 2022-07-05.
What will happen after migration?
- The fabricbot.json file in our repo that will always take precedence than config in portal.
- All update need to commit in .github/fabricbot.json.
=> {CI} Migrate fabric bot from portal to config-as-code

src/vmware/README.md
Bulk update: Edit incorrect Azure CLI reference links by removing /ext.
This work is in accordance with [User Story 1948095](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1948095).
---
=> Fix incorrect Azure CLI reference links

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/aks_diagnostics.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_diagnostics.py
This fixes a bug in which the storage container used to retrieve Periscope logs is not the same as the one they are uploaded to.
The change is to put all the logic for determining the container name into one function, rather than spreading it throughout the kollect function.
---
=> Fix kollect bug with inconsistent container name for private clusters

src/containerapp-compose/azext_containerapp_compose/custom.py
```sh
az containerapp compose create 
```
docker-compose.yaml
```yaml
services:
helloworld:
image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
ports: 
- 8080:80
deploy:
resources:
reservations:
cpus: '0.25'
memory: 0.5GB
```
https://github.com/smurawski/docker-compose-examples/issues/1
=> fix no attribute 'gigabytes' error

src/quantum/azext_quantum/tests/latest/utils.py
One of the live tests generates a maximum-length managed application name that includes the provider's name.  When "quantinuum" was automatically added (instead of "honeywell") the name became one character too long.  This PR shortens the name used in the test to a valid length.
---
=> [Quantum] Shorten long workspace name in test

src/quantum/azext_quantum/tests/latest/source_for_build_test/NuGet.config, src/quantum/azext_quantum/tests/latest/source_for_build_test/QuantumRNG.csproj, src/quantum/azext_quantum/tests/latest/test_quantum_jobs.py
A NuGet.config file used for an automated test of the quantum CLI extension has caused the “Secure Supply Chain Analysis” task to fail in an Azure CLI pipeline.  This PR removes that NuGet.config file.
To test the Q# compiler’s validation of the new TargetCapability feature added in [PR 4736](https://github.com/Azure/azure-cli-extensions/pull/4736), one of the extension’s tests used a .csproj file containing the following line:
`<Project Sdk="Microsoft.Quantum.Sdk/0.24.215967-alpha">`
This required a NuGet.config file to access that “alpha” Microsoft.Quantum.Sdk version.  This PR substitutes the last released Microsoft.Quantum.Sdk version number, 0.24.210930, so the NuGet.config file can be deleted. 
Consequently, the test case that verified TargetCapability validation has been …
=> [Quantum] Delete NuGet.config

src/spring-cloud/azext_spring_cloud/_deployment_source_factory.py, src/spring-cloud/azext_spring_cloud/_params.py, src/spring/HISTORY.md, src/spring/azext_spring/_deployment_source_factory.py, src/spring/azext_spring/_params.py, src/spring/azext_spring/tests/latest/recordings/test_app_deploy_container.yaml, src/spring/azext_spring/tests/latest/test_asa_scenario.py, src/spring/setup.py
---
Fixed a regression bug introduced in the previous refactoring that the commands and arguments aren't split correctly.
=> [Spring] Fix the incorrect split of byoc commands and args.

src/spring/HISTORY.md, src/spring/azext_spring/_deployment_factory.py, src/spring/azext_spring/_params.py, src/spring/azext_spring/app.py, src/spring/azext_spring/tests/latest/test_asa_app.py, src/spring/setup.py
=> add support for termination grace period seconds

src/containerapp-compose/HISTORY.rst, src/containerapp-compose/azext_containerapp_compose/_monkey_patch.py, src/containerapp-compose/azext_containerapp_compose/custom.py, src/containerapp-compose/azext_containerapp_compose/tests/latest/common.py, src/containerapp-compose/setup.py
This PR adds basic build support (context and dockerfile) via Azure Container Registry (ACR) build tasks. If a service in the Compose file has the build key defined, either the provided ACR (or a new ACR which will be automatically provisioned) will be used to build the source container image.  The container registry will be mapped the container app to finish the deployment scenario.
---
az containerapp compose
The precondition is to put your code inside this repository and upgrade the …
=> Extending basic build support 

src/ssh/HISTORY.md, src/ssh/setup.py
Az Cli Core has dependency to crytography, so we can remove it from our extension.
---
=> [SSH] Remove cryptography dependency

src/spring/HISTORY.md, src/spring/azext_spring/buildpack_binding.py, src/spring/setup.py
When customer create Azure Spring Apps service instance with CLI, if customer didn't specify anything for application insights, we'll by default create an Application Insights, and associate it to the service instance. But create application insights can fail, we don't want to block customer's flow to create service instance, so log warning rather than throw exception and fail the command, just as was done in Basic and Standard tiers.
[Bug 13041269](https://msazure.visualstudio.com/AzureDMSS/_workitems/edit/13041269): [CLI][All tiers][Pilot]:Create service instance successfully，but application insights create failed
---
```
az spring create xxxxxxx
```
There is a pipeline to …
=> [Fix] Log warning rather than throw exception when we by default create app insights

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/__init__.py, src/aks-preview/azext_aks_preview/_client_factory.py, src/aks-preview/azext_aks_preview/_completers.py, src/aks-preview/azext_aks_preview/_helpers.py, src/aks-preview/azext_aks_preview/_resourcegroup.py, src/aks-preview/azext_aks_preview/addonconfiguration.py, src/aks-preview/azext_aks_preview/aks_diagnostics.py, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_helpers.py, src/aks-preview/setup.py
---
Fix the issue where snapshot is not resolved according to the subscriptions field in the `--snapshot-id` option. Otherwise, when the subscription specified by `--snapshot-id` is inconsistent with the currently logged in subscription, an attempt will be made to obtain the corresponding snapshot through the currently logged in subscription, resulting in an error that the resource cannot be found. See sibling PR [#23077](https://github.com/Azure/azure-cli/pull/23077).
- `az aks create`
- `az aks nodepool add`
Once your pull request is merged into main branch, a new pull request will be created to …
=> {AKS} Fix snapshot not resolved according to the subscriptions field in the `--snapshot-id` option

src/spring/HISTORY.md, src/spring/azext_spring/_clierror.py, src/spring/azext_spring/_params.py, src/spring/azext_spring/_validators.py, src/spring/azext_spring/commands.py, src/spring/azext_spring/tests/latest/recordings/test_asc_app_insights_update.yaml, src/spring/azext_spring/tests/latest/recordings/test_asc_update.yaml, src/spring/azext_spring/tests/latest/recordings/test_create_asc_heavy_cases.yaml, src/spring/azext_spring/tests/latest/recordings/test_create_asc_with_ai_basic_case.yaml, src/spring/azext_spring/tests/latest/recordings/test_create_asc_without_ai_cases.yaml, src/spring/azext_spring/tests/latest/test_asa_app_insights_scenario.py, src/spring/azext_spring/tests/latest/test_asa_app_insights_validator.py, src/spring/setup.py
Commands `az spring app-insights update/show` only support Basic/Standard tier, not support Enterprise tier. To avoid confusing error message customer may get when use these commands against enterprise tier, add tier validator to throw customer error.
- `az spring app-insights update xxx`
- `az spring app-insights show xxx`
https://msazure.visualstudio.com/AzureDMSS/_build/results?buildId=57323066&view=results
---
The precondition is to put your code inside this …
=> [Spring] Add pricing tier validator for command group az spring app-insights 

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/setup.py
fixes Azure/azure-cli-extensions#5098
az aks addon list command always returns "enable:false" for virtual-node addon. REST API returns "enable:true", but CLI displays result as "enable:false"
```
az aks addon list -g TestRG -n TestCluster --debug
"addonProfiles": {
"aciConnectorLinux": {
"enabled": true,            <<<<<<<
"config": {
"SubnetName": "VirtualNodeSubnet"
},
#However, CLI displays "enabled:false". It appears to be matching with "aciConnector" instead of "aciConnectorLinux".
{
"api_key": "aciConnector",
"enabled": false,           <<<<<<<<<
"name": "virtual-node"
},
```
As per [this](https://github.com/Azure/azure-cli-extensions/blob/b02803b4bd7aee2ae9e707af1be8b6a9860559a7/src/aks-preview/azext_aks_preview/addonconfiguration.py#L107) and …
=> {AKS} Fix enabled virtual node addon showing wrong status in `aks addon list`

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/data/defenderconfig.json, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/setup.py
---
Fixed the model compatibility issue caused by the recent [rebranding](https://github.com/Azure/azure-rest-api-specs/pull/19172) of Microsoft Defender when updating defender-related configurations through `aks create/update` commands in aks-preview. Would release a new version (TBD) of aks-preview.
**Notice**
The breaking change on this model is in effect in the **preview API** (corresponding to aks-preview) since [2022-05-02-preview](https://github.com/Azure/azure-rest-api-specs/pull/19172). 
In **stable API** (corresponding to azure-cli, without the extension aks-preview), the breaking change on this model will take effect from [2022-06-01](https://github.com/Azure/azure-rest-api-specs/pull/196 …
=> {AKS} Fix compatibility issue when enabling Microsoft Defender via aks-preview

src/storage-preview/azext_storage_preview/_params.py
Fixes https://github.com/Azure/azure-cli/issues/22699
---
=> [Storage Preview] Fix #22699: fixing typo

src/connectedk8s/HISTORY.rst, src/connectedk8s/azext_connectedk8s/_troubleshootutils.py, src/connectedk8s/setup.py
=> Increase the timeout of diagnoser job completion to 180 sec

linter_exclusions.yml, src/index.json
Minor version release to fix doc string generation in v0.16.0.
Notes for this release:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.16.1
And the previous release:
https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.16.0
---
=> [IoT] IoT Extension Release v0.16.1

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py, src/aks-preview/linter_exclusions.yml
* Add a new parameter `--disable-azure-keyvault-kms` for `az aks update`.
* Add tests for disabling KMS.
=> {AKS} support disabling Azure KeyVault KMS

scripts/ci/credscan/CredScanSuppressions.json, src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_constants.py, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/_up_utils.py, src/containerapp/azext_containerapp/_utils.py, src/containerapp/azext_containerapp/_validators.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_container_acr.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_ingress_traffic_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_update.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_update_containers.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py, src/containerapp/setup.py
=> Containerapp 0.3.8 Release

src/webpubsub/azext_webpubsub/_params.py, src/webpubsub/azext_webpubsub/custom.py
=> [Web PubSub] Add premium tier in help and fix a bug

src/aks-preview/HISTORY.rst, src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json, src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json, src/aks-preview/azext_aks_preview/tests/latest/recordings/test_list_trustedaccess_roles.yaml, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
---
- Sort out test matrix.
- Add test_aks_create_with_defender, test_aks_update_with_defender back in CLI matrix.
- Add new tag for monitoring test cases.
- Add new tag for kms test cases.
- Fix test case test_list_trustedaccess_roles.
- Update history & release new version.
=> {AKS} Filter tests

src/vmware/HISTORY.md, src/vmware/azext_vmware/_help.py, src/vmware/azext_vmware/_params.py, src/vmware/azext_vmware/commands.py, src/vmware/azext_vmware/custom.py, src/vmware/azext_vmware/tests/latest/recordings/test_vmware.yaml, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_addon.yaml, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_cloud_link.yaml, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_datastores.yaml, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_global_reach_connection.yaml, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_hcx.yaml, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_placement_policy.yaml, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_script.yaml, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_virtual_machines.yaml, src/vmware/azext_vmware/tests/latest/recordings/test_vmware_workload_network.yaml, src/vmware/azext_vmware/tests/latest/test_vmware_scenario.py, src/vmware/setup.py
=> private-cloud cmk-encryption commands, identity commands, and test cases

src/front-door/azext_front_door/_help.py
fixes Azure/azure-cli-extensions#5170
For managing Azure Front Door Standard/Premium, please refer https://docs.microsoft.com/en-us/cli/azure/afd?view=azure-cli-latest.
For classical Azure Front Door, please refer https://docs.microsoft.com/en-us/cli/azure/network/front-door?view=azure-cli-latest.
---
=> {AzureFrontDoor} Fix #5170: Update documents

scripts/ci/avail-ext-doc/requirements.txt
The pipeline (Azure CLI Extensions Sync to MicrosoftDocs）didn't work since July 5th.
Here is the error message:
~~Since MarkupSafe remove soft_unicode in version 2.1.0~~
~~So we use MarkupSafe == 2.0.1 to fix this error.~~
And we use jinja2 == 3.0.3 in azure-cli which already drops the soft_unicode.
https://github.com/Azure/azure-cli/blob/75f7048672cf8198bb8f073262caa9e706b68699/scripts/ci/test_ref_doc.sh#L17
So we also upgrade jinja2 to 3.0.3 in azure-cli-extensions.
Test result:
=> {CI} Fix Azure CLI Extensions Sync to MicrosoftDocs error

SECURITY.md
Migrate from https://github.com/Azure/azure-cli-extensions-pr/pull/51
Not sure why this repo isn't scanned. This file was added to `azure-cli` repo in https://github.com/Azure/azure-cli/pull/22513, https://github.com/Azure/azure-cli/pull/22477
=> Adding Microsoft SECURITY.MD

src/serial-console/HISTORY.rst, src/serial-console/azext_serialconsole/_help.py, src/serial-console/azext_serialconsole/custom.py, src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VM.yaml, src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VMSS.yaml, src/serial-console/azext_serialconsole/tests/latest/recordings/test_enable_disable.yaml, src/serial-console/azext_serialconsole/tests/latest/test_serialconsole_scenario.py, src/serial-console/setup.py
=> [serial-console] Add support for managed boot diagnostics storage account

src/azure-firewall/azext_firewall/_help.py
---
Fixes: https://github.com/Azure/azure-cli/issues/23306
az network firewall policy rule-collection-group collection add-filter-collection
=> [AzureFirewall] Update help message

azure-pipelines.yml
---
By default, the end-of-life is scheduled 5 years after the first release.
And the python SDK has already dropped python 3.6.
But we still use python 3.6 in our test enviroment, that will cause some error like these:
The root cause is that azure-mgmt-monitor no longer supports python3.6, so the latest azure-mgmt-monitor cannot be installed in the python3.6 test environment.
This pull request will drop python 3.6 in our pipeline.
And I will bump pylint to 2.11.1 in this [PR](https://github.com/Azure/azure-cli-extensions/pull/4645) when I have time.
=> {CI} drop python 3.6

src/index.json
chore(arcdata): version bump to 1.4.5
=> chore(arcdata): version bump to 1.4.5

src/azure-firewall/HISTORY.rst, src/azure-firewall/azext_firewall/_params.py, src/azure-firewall/azext_firewall/custom.py, src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_v2.yaml, src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py, src/azure-firewall/setup.py
---
Closed: https://github.com/Azure/azure-cli/issues/23325
=> [AzureFirewall]  `az network firewall`: Add parameter `--fat-flow-logging`

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/_validators.py, src/aks-preview/azext_aks_preview/tests/latest/test_validators.py, src/aks-preview/setup.py
---
The implementation of the `az aks nodepool wait` command directly calls the operation provided by the SDK, and the parameter name used to identify the nodepool name is `agent_pool_name`, which is different from the parameter name `nodepool_name` in the custom implemented nodepool commands.
The fix is to add a new dedicated validator for the command. Also added some unit tests. See sibling PR [#23489](https://github.com/Azure/azure-cli/pull/23489).
Fix issue [#23468](https://github.com/Azure/azure-cli/issues/23468).
`az aks nodepool wait`
Once your pull request is merged into main branch, a new …
=> {AKS} Fix #23468: `az aks nodepool wait` crashes with error "'Namespace' object has no attribute 'nodepool_name'"

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/commands.py, src/aks-preview/azext_aks_preview/custom.py
=> [AKS][TA] remove source_resource_id of rolebinding update command

src/aks-preview/HISTORY.rst, src/aks-preview/README.rst
=> {AKS} Update readme to add dependency description

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/_params.py, src/aks-preview/azext_aks_preview/custom.py
=> [TA] change rolebinding create command parameter roles to comma-seperated

src/communication/HISTORY.rst, src/communication/azext_communication/__init__.py, src/communication/azext_communication/manual/_help.py, src/communication/azext_communication/manual/commands.py, src/communication/setup.py
=> [Communication] update help and fix chat command group preview info

src/automation/HISTORY.rst, src/automation/README.md, src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_move.py, src/automation/linter_exclusions.yml
---
az automation hrwg hrw move
=> fixed hybid worker move command

src/automation/HISTORY.rst, src/automation/README.md, src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_move.py, src/automation/setup.py
---
updated the extension version
=> updated automation extension version

scripts/ci/credscan/CredScanSuppressions.json, src/containerapp/HISTORY.rst, src/containerapp/azext_containerapp/_params.py, src/containerapp/azext_containerapp/_up_utils.py, src/containerapp/azext_containerapp/_utils.py, src/containerapp/azext_containerapp/custom.py, src/containerapp/azext_containerapp/tests/latest/recordings/test_container_acr.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_anonymous_registry.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dapr_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_dapr_components.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_storage.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_identity_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_identity_system.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_identity_user.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_ingress_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_ingress_traffic_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_logstream.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_identity_user.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_msi.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_revision_label_e2e.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_update.yaml, src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_update_containers.yaml, src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py, src/containerapp/azext_containerapp/tests/latest/utils.py, src/containerapp/setup.py
=> Containerapp 0.3.10 Release

src/automation/HISTORY.rst, src/automation/azext_automation/aaz/latest/automation/hrwg/_create.py, src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_create.py, src/automation/azext_automation/tests/latest/recordings/test_automation.yaml, src/automation/azext_automation/tests/latest/test_automation_scenario_manual.py, src/automation/setup.py
---
added support for handling success responses on create resources
az automation hrwg create
az automation hrwg hrw create
=> added support for handling success responses on create resources

src/network-manager/HISTORY.rst, src/network-manager/azext_network_manager/custom.py, src/network-manager/setup.py
---
Fixed: https://github.com/Azure/azure-cli/issues/23707
=> [NetworkManager] Fix az network manager resources delete behavior

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/_consts.py, src/aks-preview/azext_aks_preview/_help.py, src/aks-preview/azext_aks_preview/aks_draft/commands.py, src/aks-preview/azext_aks_preview/custom.py, src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py, src/aks-preview/setup.py
---
Following changes is for fixing failing test and the `1:n` release issue which needs to be fixed with `1:1` release  because currently there was a function auto downloading the latest version and `DRAFT CLI` had a breaking change in `v0.0.23` from `v0.0.22` and even if `AZ CLI` was in old version this auto download code would have broken the existing user.
This PR fixes:
* `1:n` to `1:1` release issue for az cli and draft.
* Fix test by removing `--host and --certificate` which was removed under this PR: https://github.com/Azure/draft/pull/136
* **Question**: I see that 2 new parameters are added in the new `draft` PR, will those parameter required parameters fr update command to work?
* Also, …
=> Fix for Draft CLI 1:n release issue and failing tests. ☕️🙏🚀

src/aks-preview/HISTORY.rst, src/aks-preview/azext_aks_preview/aks_draft/commands.py, src/aks-preview/setup.py
---
{AKS} Fix `az aks draft` command crashed on windows during binary check. 
When the binary file of aks-draft does not exist, it will be downloaded from GitHub release. Since the file corresponding to the Windows platform ends with `.exe`, and the url used for downloading does not contain the suffix, an error occurs.
Fix issues [#5336](https://github.com/Azure/azure-cli-extensions/issues/5336), [#5310](https://github.com/Azure/azure-cli-extensions/issues/5310).
`az aks draft`
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` …
=> {AKS} Fix `az aks draft` command crashed on windows during binary check

src/index.json
Hide spring 1.1.6 from customers since not compatible with old CLI core
spring 1.1.6 has minCliCoreVersion at 2.30, but it's not compatible with CLI core < 2.38.
---
az spring
=> Hide spring 1.1.6 from customers since not compatible with old CLI core

src/spring/HISTORY.md, src/spring/azext_spring/azext_metadata.json, src/spring/setup.py
update min cli core version from 2.30.0 to 2.38.0 to fix the compatibility issue
---
az spring
=> Update min cli core version from 2.30.0 to 2.38.0 to fix the compatibility issue

src/k8s-extension/HISTORY.rst, src/k8s-extension/azext_k8s_extension/_client_factory.py, src/k8s-extension/setup.py
CLI Command: az k8s-extension extension-types list -g {} --cluster-name {} --cluster-type {}
Results in below error:
File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
results.append(self._run_job(expanded_arg, cmd_copy))
File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
result = cmd_copy(params)
File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
return self.handler(*args, **kwargs)
File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line …
=> {k8s-extension} fixes Azure/azure-cli-extensions#5356

src/spring/HISTORY.md, src/spring/azext_spring/custom.py, src/spring/setup.py
=> [Spring] Fix the crash in windows.

src/aks-preview/azext_aks_preview/managed_cluster_decorator.py, src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
---
az aks update --enable-apiserver-vnet-integration
=> AKS: bug fix about not report error when existing cluster is already vnet integrated
